In [1]:
from __future__ import annotations
import numpy as np
import pandas as pd
from scipy.stats import nbinom, norm

from deconveil.utils_fit import *
from deconveil.utils_processing import *

import rpy2.robjects as ro
from rpy2.robjects import pandas2ri, conversion, Formula
import rpy2.robjects.packages as rpackages
from rpy2.robjects.packages import importr

import matplotlib.pyplot as plt
import seaborn as sns

import pickle
import os
import re
from itertools import product
from glob import glob

In [3]:
import pydeseq2
from pydeseq2.dds import DeseqDataSet
from pydeseq2.default_inference import DefaultInference
from pydeseq2.ds import DeseqStats

from deconveil.dds import deconveil_fit
from deconveil.inference import Inference
from deconveil.default_inference import DefInference
from deconveil.utils_fit import *
from deconveil.utils_processing import *
from deconveil.utils_plot import *
from deconveil import deconveil_fit
from deconveil.ds import deconveil_stats
from deconveil.simulate_gene_dosage import *

#### Load data

In [5]:
rna_counts = load_test_data(
    modality="rna",
    dataset="tcga_brca",
    debug=False,
)
rna_counts = rna_counts.T

metadata = load_test_data(
    modality="metadata",
    dataset="tcga_brca",
    debug=False,
)

cnv = load_test_data(
    modality="cnv",
    dataset="tcga_brca",
    debug=False,
)
cnv = cnv.T

#### QC & filtering

In [7]:
print("Before filtering:", rna_counts.shape, cnv.shape, metadata.shape)
# Reorder cnv to match rna_counts
cnv = cnv.loc[rna_counts.index]
assert (rna_counts.index == metadata.index).all(), "Sample order mismatch between rna_counts and metadata"
assert (cnv.index == rna_counts.index).all(), "Sample order mismatch between cnv and rna_counts"

Before filtering: (400, 17387) (400, 17387) (400, 1)

In [9]:
all_zero_mask = (rna_counts.sum(axis=0) == 0)
print("All-zero genes:", all_zero_mask.sum())
rna_counts = rna_counts.loc[:, ~all_zero_mask]
cnv = cnv.loc[:, ~all_zero_mask]

All-zero genes: 0

In [11]:
res = filter_low_count_genes(rna_counts, other_dfs=[cnv], min_count=300, min_samples=50)
rna_counts = res["filtered_df"]
cnv = res["other_filtered"][0]
print("After low-count filtering:", rna_counts.shape, cnv.shape)

After low-count filtering: (400, 16252) (400, 16252)

#### Configuration setup

In [43]:
out_dir = "sim_results/sim_data/sim2/"
os.makedirs(out_dir, exist_ok=True)


n_genes = 5000
sample_sizes = [10, 20, 40, 60]

CN_SIGNAL_REGIMES = {
    "CNweak": {
        "dsg_strength": (1.2, 1.6),
        "dcg_strength": (1.2, 2.0),
    },
    "CNstrong": {
        "dsg_strength": (2.0, 3.4),
        "dcg_strength": (2.0, 3.2),
    },
}

# number of replicates per configuration
n_reps = 20
base_seed = 13

In [13]:
cnv = cnv.T
cn_tumor = cnv.iloc[:, 200:400]
cn_tumor = cn_tumor.clip(lower=0, upper=6)
cn_tumor.head()

,TCGA-D8-A1Y1-01A,TCGA-AO-A124-01A,TCGA-AO-A1KS-01A,TCGA-EW-A6SB-01A,TCGA-A8-A08J-01A,TCGA-BH-A0GY-01A,TCGA-AC-A2QJ-01A,TCGA-B6-A401-01A,TCGA-Z7-A8R5-01A,TCGA-A8-A093-01A,...,TCGA-BH-A208-01A,TCGA-A2-A0CL-01A,TCGA-LL-A6FR-01A,TCGA-E9-A1N6-01A,TCGA-AR-A251-01A,TCGA-A2-A4S1-01A,TCGA-E2-A2P5-01A,TCGA-A2-A0EV-01A,TCGA-LL-A6FQ-01A,TCGA-A2-A04T-01A
A2M,3,5,4,6,4,4,2,3,3,3,...,3,4,2,3,2,2,4,2,4,6
A2M-AS1,3,5,4,6,4,4,2,3,3,3,...,3,4,2,3,2,2,4,2,4,6
A2ML1,3,4,4,6,4,4,2,3,3,3,...,3,4,2,5,2,2,4,2,4,6
A2ML1-AS1,3,4,4,6,4,4,2,3,3,3,...,3,4,2,5,2,2,4,2,4,6
A2MP1,3,5,4,6,4,4,2,3,3,3,...,3,4,2,3,2,2,4,2,4,6

In [15]:
cn_normal = cnv.iloc[:, 0:200]
cn_normal = cn_normal.clip(lower=2, upper=2)
cn_normal.head()

,GTEX-13PVQ-1026-SM-5KM3M.1,GTEX-18QFQ-0826-SM-718AX.1,GTEX-1JN6P-2426-SM-ARL99.1,GTEX-13S86-1226-SM-5S2OA.1,GTEX-132NY-0826-SM-5K7Y7.1,GTEX-ZTX8-1226-SM-4YCE9.1,GTEX-UJHI-1426-SM-3DB9C.1,GTEX-15RJE-2626-SM-7KFT1.1,GTEX-ZEX8-2226-SM-57WC6.1,GTEX-1KANA-2026-SM-DIPFB.1,...,GTEX-17F96-2426-SM-7IGLN.1,GTEX-S7SE-0826-SM-4AT4D.1,GTEX-1IDJF-2326-SM-ARL86.1,GTEX-ZF3C-2326-SM-5S2MZ.1,GTEX-1J8EW-2626-SM-CL53E.1,GTEX-R3RS-0626-SM-48FE1.1,GTEX-13O61-1826-SM-5KM4I.1,GTEX-1J8QM-2026-SM-ARZMW.1,GTEX-183FY-1126-SM-7DHLJ.1,GTEX-1B98T-0726-SM-7939J.1
A2M,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
A2M-AS1,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
A2ML1,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
A2ML1-AS1,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
A2MP1,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2

In [17]:
rna_counts = rna_counts.T
rna_counts.head()

,GTEX-13PVQ-1026-SM-5KM3M.1,GTEX-18QFQ-0826-SM-718AX.1,GTEX-1JN6P-2426-SM-ARL99.1,GTEX-13S86-1226-SM-5S2OA.1,GTEX-132NY-0826-SM-5K7Y7.1,GTEX-ZTX8-1226-SM-4YCE9.1,GTEX-UJHI-1426-SM-3DB9C.1,GTEX-15RJE-2626-SM-7KFT1.1,GTEX-ZEX8-2226-SM-57WC6.1,GTEX-1KANA-2026-SM-DIPFB.1,...,TCGA-BH-A208-01A,TCGA-A2-A0CL-01A,TCGA-LL-A6FR-01A,TCGA-E9-A1N6-01A,TCGA-AR-A251-01A,TCGA-A2-A4S1-01A,TCGA-E2-A2P5-01A,TCGA-A2-A0EV-01A,TCGA-LL-A6FQ-01A,TCGA-A2-A04T-01A
A2M,3502210.0,5394960.0,7136304.0,5710693.0,4020951.0,4662838.0,2417958.0,11106464.0,2393132.0,5335893.0,...,11194647.0,6703305.0,4730868.0,1644905.0,5994136.0,1402228.0,2872243.0,2919369.0,1323810.0,3827589.0
A2M-AS1,83739.0,155914.0,219925.0,236061.0,155161.0,135397.0,62922.0,358297.0,107984.0,130254.0,...,195693.0,115080.0,680762.0,40599.0,104901.0,99105.0,79866.0,58999.0,119745.0,123720.0
A2ML1,1592.0,14511.0,2254.0,932.0,6312.0,2020.0,1644.0,2209.0,1404.0,2513.0,...,558914.0,13736.0,37602.0,9311.0,1361008.0,111.0,2167.0,681.0,198.0,4399482.0
A2ML1-AS1,17369.0,10089.0,12267.0,4446.0,5744.0,4094.0,2319.0,28098.0,8396.0,7131.0,...,2120.0,1285.0,326.0,2331.0,6109.0,351.0,1166.0,1631.0,293.0,3528.0
A2MP1,9842.0,11023.0,5955.0,12644.0,5015.0,7609.0,2149.0,45583.0,7827.0,10049.0,...,5414.0,8559.0,818.0,902.0,2792.0,755.0,3489.0,1801.0,426.0,4632.0

#### Run simulation set up

In [51]:
for S in sample_sizes:
    for cn_label, cn_cfg in CN_SIGNAL_REGIMES.items():
        for R in range(1, n_reps + 1):

            seed = base_seed + R

            print(
                f"Running S={S}, G={n_genes}, "
                f"CN={cn_label}, R={R}"
            )

            sim = cn_aware_rna_simulator(
                counts=rna_counts,
                metadata=metadata,
                cn_tumor=cn_tumor,
                cn_normal=cn_normal,
                n_genes=n_genes,
                design="~ 1",
                seed=seed,
                inject_del=True,
                del_frac_dcg=0.15,
                del_frac_dsg=0.2,
                frac_cn0=0.3,
                max_log2fc=3.0,
                n_normal_sim=S,
                n_tumor_sim=S,
                bootstrap_cn=True,
                # CN signal regime
                dsg_strength=cn_cfg["dsg_strength"],
                dcg_strength=cn_cfg["dcg_strength"],
                cn_heterogeneity_sd=0.40,
                disp_scale_norm=1.0, 
                disp_scale_tum=1.5,
                diff_disp_range=(0.5, 1.5),
                
            )

            fname = (
                f"sim_S{S}_G{n_genes}_"
                f"{cn_label}_R{R}.pkl"
            )

            with open(os.path.join(out_dir, fname), "wb") as f:
                pickle.dump(sim, f)

Running S=10, G=5000, CN=CNweak, R=1

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 605 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=10, G=5000, CN=CNweak, R=2

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 549 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=10, G=5000, CN=CNweak, R=3

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 567 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.
Running S=10, G=5000, CN=CNweak, R=4

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 532 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4994 genes.
Running S=10, G=5000, CN=CNweak, R=5

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 562 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.
Running S=10, G=5000, CN=CNweak, R=6

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 553 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=10, G=5000, CN=CNweak, R=7

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 615 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4987 genes.
Running S=10, G=5000, CN=CNweak, R=8

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 597 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=10, G=5000, CN=CNweak, R=9

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 550 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.
Running S=10, G=5000, CN=CNweak, R=10

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 572 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4997 genes.
Running S=10, G=5000, CN=CNweak, R=11

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 578 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=10, G=5000, CN=CNweak, R=12

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 595 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=10, G=5000, CN=CNweak, R=13

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 585 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4983 genes.
Running S=10, G=5000, CN=CNweak, R=14

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 568 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.
Running S=10, G=5000, CN=CNweak, R=15

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 574 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=10, G=5000, CN=CNweak, R=16

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 576 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=10, G=5000, CN=CNweak, R=17

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 552 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.
Running S=10, G=5000, CN=CNweak, R=18

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 588 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=10, G=5000, CN=CNweak, R=19

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 584 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.
Running S=10, G=5000, CN=CNweak, R=20

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 600 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=10, G=5000, CN=CNstrong, R=1

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 605 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=10, G=5000, CN=CNstrong, R=2

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 549 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=10, G=5000, CN=CNstrong, R=3

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 567 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.
Running S=10, G=5000, CN=CNstrong, R=4

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 532 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4994 genes.
Running S=10, G=5000, CN=CNstrong, R=5

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 562 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.
Running S=10, G=5000, CN=CNstrong, R=6

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 553 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=10, G=5000, CN=CNstrong, R=7

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 615 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4987 genes.
Running S=10, G=5000, CN=CNstrong, R=8

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 597 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=10, G=5000, CN=CNstrong, R=9

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 550 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.
Running S=10, G=5000, CN=CNstrong, R=10

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 572 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4997 genes.
Running S=10, G=5000, CN=CNstrong, R=11

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 578 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=10, G=5000, CN=CNstrong, R=12

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 595 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=10, G=5000, CN=CNstrong, R=13

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 585 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4983 genes.
Running S=10, G=5000, CN=CNstrong, R=14

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 568 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.
Running S=10, G=5000, CN=CNstrong, R=15

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 574 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=10, G=5000, CN=CNstrong, R=16

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 576 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=10, G=5000, CN=CNstrong, R=17

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 552 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.
Running S=10, G=5000, CN=CNstrong, R=18

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 588 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=10, G=5000, CN=CNstrong, R=19

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 584 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.
Running S=10, G=5000, CN=CNstrong, R=20

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 600 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=20, G=5000, CN=CNweak, R=1

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 605 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=20, G=5000, CN=CNweak, R=2

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 549 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=20, G=5000, CN=CNweak, R=3

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 567 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.
Running S=20, G=5000, CN=CNweak, R=4

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 532 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4994 genes.
Running S=20, G=5000, CN=CNweak, R=5

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 562 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.
Running S=20, G=5000, CN=CNweak, R=6

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 553 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=20, G=5000, CN=CNweak, R=7

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 615 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4987 genes.
Running S=20, G=5000, CN=CNweak, R=8

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 597 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=20, G=5000, CN=CNweak, R=9

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 550 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.
Running S=20, G=5000, CN=CNweak, R=10

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 572 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4997 genes.
Running S=20, G=5000, CN=CNweak, R=11

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 578 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=20, G=5000, CN=CNweak, R=12

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 595 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=20, G=5000, CN=CNweak, R=13

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 585 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4983 genes.
Running S=20, G=5000, CN=CNweak, R=14

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 568 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.
Running S=20, G=5000, CN=CNweak, R=15

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 574 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=20, G=5000, CN=CNweak, R=16

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 576 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=20, G=5000, CN=CNweak, R=17

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 552 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.
Running S=20, G=5000, CN=CNweak, R=18

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 588 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=20, G=5000, CN=CNweak, R=19

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 584 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.
Running S=20, G=5000, CN=CNweak, R=20

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 600 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=20, G=5000, CN=CNstrong, R=1

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 605 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=20, G=5000, CN=CNstrong, R=2

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 549 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=20, G=5000, CN=CNstrong, R=3

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 567 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.
Running S=20, G=5000, CN=CNstrong, R=4

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 532 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4994 genes.
Running S=20, G=5000, CN=CNstrong, R=5

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 562 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.
Running S=20, G=5000, CN=CNstrong, R=6

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 553 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=20, G=5000, CN=CNstrong, R=7

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 615 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4987 genes.
Running S=20, G=5000, CN=CNstrong, R=8

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 597 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=20, G=5000, CN=CNstrong, R=9

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 550 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.
Running S=20, G=5000, CN=CNstrong, R=10

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 572 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4997 genes.
Running S=20, G=5000, CN=CNstrong, R=11

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 578 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=20, G=5000, CN=CNstrong, R=12

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 595 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=20, G=5000, CN=CNstrong, R=13

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 585 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4983 genes.
Running S=20, G=5000, CN=CNstrong, R=14

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 568 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.
Running S=20, G=5000, CN=CNstrong, R=15

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 574 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=20, G=5000, CN=CNstrong, R=16

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 576 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=20, G=5000, CN=CNstrong, R=17

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 552 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.
Running S=20, G=5000, CN=CNstrong, R=18

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 588 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=20, G=5000, CN=CNstrong, R=19

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 584 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.
Running S=20, G=5000, CN=CNstrong, R=20

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 600 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=40, G=5000, CN=CNweak, R=1

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 605 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=40, G=5000, CN=CNweak, R=2

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 549 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=40, G=5000, CN=CNweak, R=3

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 567 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.
Running S=40, G=5000, CN=CNweak, R=4

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 532 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4994 genes.
Running S=40, G=5000, CN=CNweak, R=5

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 562 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.
Running S=40, G=5000, CN=CNweak, R=6

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 553 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=40, G=5000, CN=CNweak, R=7

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 615 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4987 genes.
Running S=40, G=5000, CN=CNweak, R=8

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 597 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=40, G=5000, CN=CNweak, R=9

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 550 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.
Running S=40, G=5000, CN=CNweak, R=10

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 572 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4997 genes.
Running S=40, G=5000, CN=CNweak, R=11

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 578 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=40, G=5000, CN=CNweak, R=12

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 595 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=40, G=5000, CN=CNweak, R=13

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 585 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4983 genes.
Running S=40, G=5000, CN=CNweak, R=14

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 568 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.
Running S=40, G=5000, CN=CNweak, R=15

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 574 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=40, G=5000, CN=CNweak, R=16

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 576 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=40, G=5000, CN=CNweak, R=17

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 552 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.
Running S=40, G=5000, CN=CNweak, R=18

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 588 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=40, G=5000, CN=CNweak, R=19

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 584 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.
Running S=40, G=5000, CN=CNweak, R=20

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 600 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=40, G=5000, CN=CNstrong, R=1

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 605 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=40, G=5000, CN=CNstrong, R=2

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 549 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=40, G=5000, CN=CNstrong, R=3

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 567 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.
Running S=40, G=5000, CN=CNstrong, R=4

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 532 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4994 genes.
Running S=40, G=5000, CN=CNstrong, R=5

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 562 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.
Running S=40, G=5000, CN=CNstrong, R=6

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 553 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=40, G=5000, CN=CNstrong, R=7

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 615 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4987 genes.
Running S=40, G=5000, CN=CNstrong, R=8

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 597 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=40, G=5000, CN=CNstrong, R=9

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 550 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.
Running S=40, G=5000, CN=CNstrong, R=10

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 572 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4997 genes.
Running S=40, G=5000, CN=CNstrong, R=11

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 578 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=40, G=5000, CN=CNstrong, R=12

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 595 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=40, G=5000, CN=CNstrong, R=13

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 585 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4983 genes.
Running S=40, G=5000, CN=CNstrong, R=14

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 568 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.
Running S=40, G=5000, CN=CNstrong, R=15

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 574 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=40, G=5000, CN=CNstrong, R=16

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 576 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=40, G=5000, CN=CNstrong, R=17

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 552 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.
Running S=40, G=5000, CN=CNstrong, R=18

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 588 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=40, G=5000, CN=CNstrong, R=19

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 584 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.
Running S=40, G=5000, CN=CNstrong, R=20

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 600 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=60, G=5000, CN=CNweak, R=1

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 605 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=60, G=5000, CN=CNweak, R=2

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 549 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=60, G=5000, CN=CNweak, R=3

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 567 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.
Running S=60, G=5000, CN=CNweak, R=4

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 532 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4994 genes.
Running S=60, G=5000, CN=CNweak, R=5

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 562 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.
Running S=60, G=5000, CN=CNweak, R=6

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 553 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=60, G=5000, CN=CNweak, R=7

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 615 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4987 genes.
Running S=60, G=5000, CN=CNweak, R=8

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 597 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=60, G=5000, CN=CNweak, R=9

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 550 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.
Running S=60, G=5000, CN=CNweak, R=10

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 572 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4997 genes.
Running S=60, G=5000, CN=CNweak, R=11

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 578 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=60, G=5000, CN=CNweak, R=12

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 595 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=60, G=5000, CN=CNweak, R=13

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 585 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4983 genes.
Running S=60, G=5000, CN=CNweak, R=14

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 568 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.
Running S=60, G=5000, CN=CNweak, R=15

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 574 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=60, G=5000, CN=CNweak, R=16

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 576 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=60, G=5000, CN=CNweak, R=17

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 552 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.
Running S=60, G=5000, CN=CNweak, R=18

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 588 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=60, G=5000, CN=CNweak, R=19

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 584 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.
Running S=60, G=5000, CN=CNweak, R=20

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 600 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=60, G=5000, CN=CNstrong, R=1

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 605 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=60, G=5000, CN=CNstrong, R=2

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 549 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=60, G=5000, CN=CNstrong, R=3

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 567 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.
Running S=60, G=5000, CN=CNstrong, R=4

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 532 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4994 genes.
Running S=60, G=5000, CN=CNstrong, R=5

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 562 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.
Running S=60, G=5000, CN=CNstrong, R=6

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 553 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=60, G=5000, CN=CNstrong, R=7

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 615 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4987 genes.
Running S=60, G=5000, CN=CNstrong, R=8

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 597 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=60, G=5000, CN=CNstrong, R=9

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 550 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.
Running S=60, G=5000, CN=CNstrong, R=10

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 572 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4997 genes.
Running S=60, G=5000, CN=CNstrong, R=11

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 578 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=60, G=5000, CN=CNstrong, R=12

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 595 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=60, G=5000, CN=CNstrong, R=13

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 585 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4983 genes.
Running S=60, G=5000, CN=CNstrong, R=14

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 568 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.
Running S=60, G=5000, CN=CNstrong, R=15

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 574 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=60, G=5000, CN=CNstrong, R=16

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 576 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.
Running S=60, G=5000, CN=CNstrong, R=17

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 552 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.
Running S=60, G=5000, CN=CNstrong, R=18

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 588 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.
Running S=60, G=5000, CN=CNstrong, R=19

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 584 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.
Running S=60, G=5000, CN=CNstrong, R=20

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 600 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.

#### Load and extract simulation data

In [53]:
def load_sim(path):
    with open(path, "rb") as f:
        sim = pickle.load(f)
    return sim

def extract_sim_components(sim):

    counts_df = sim["counts"]        # NB-sampled counts (G × N)
    cn_df     = sim["CN"]            # integer CN matrix (G × N)
    truth_df  = sim["truth"]         # truth LFC + class labels
    meta      = sim["metadata"].copy()  # sample annotation

    # Ensure condition labels match A/B format
    meta["condition"] = meta["condition"].replace({
        "normal": "A",
        "tumor": "B"
    })

    return counts_df, cn_df, truth_df, meta

#### Run PyDESeq2 and DeConveil

Helper functions

In [19]:
def run_pydeseq2(rna_counts, metadata, design="~condition", alpha=0.05):
    """
    Runs PyDESeq2 analysis and saves the results.

    Parameters:
        rna_counts (pd.DataFrame): Count matrix with genes as rows and samples as columns.
        metadata (pd.DataFrame): Metadata for the samples with design factors.
        output_path (str): Directory to save the results.
        design_factors (str): Column in metadata to use for design.
        alpha (float): Significance level for statistical tests.
    """
    #os.makedirs(output_path, exist_ok=True)
    
    # Initialize DESeq2 analysis
    inference = DefaultInference(n_cpus=8)
    dds = DeseqDataSet(
        counts=rna_counts,
        metadata=metadata,
        design_factors=None,  # compare samples based on condition
        refit_cooks=True,
        inference=inference,
    )

    # Fit DESeq2 model
    dds.fit_size_factors()
    dds.fit_genewise_dispersions()
    dds.fit_dispersion_trend()
    dds.fit_dispersion_prior()
    dds.fit_MAP_dispersions()
    dds.fit_LFC()
    dds.calculate_cooks()
    
    if dds.refit_cooks:
        dds.refit()

    # Perform statistical analysis
    stat_res_pydeseq = DeseqStats(dds, 
                                  alpha=alpha, 
                                  cooks_filter=True, 
                                  independent_filter=True, 
                                  contrast=["condition", "B", "A"])
    stat_res_pydeseq.run_wald_test()

    if stat_res_pydeseq.cooks_filter:
        stat_res_pydeseq._cooks_filtering()
    stat_res_pydeseq.p_values

    if stat_res_pydeseq.independent_filter:
        stat_res_pydeseq._independent_filtering()
    else:
        stat_res_pydeseq._p_value_adjustment()

    # Log-fold change shrinkage
    stat_res_pydeseq.lfc_shrink(coeff="condition[T.B]")
    stat_res_pydeseq.summary()

    # Save results
    #results_path = os.path.join(output_path, "res_CNnaive.csv")
    #stat_res_pydeseq.results_df.to_csv(results_path)
    return(stat_res_pydeseq.results_df)


def run_deconveil(rna_counts, metadata, cnv, design="~condition", alpha=0.05):
    """
    Runs DeConveil analysis and saves the results.

    Parameters:
        rna_counts (pd.DataFrame): Count matrix with genes as rows and samples as columns.
        metadata (pd.DataFrame): Metadata for the samples with design factors.
        cnv (pd.DataFrame): Copy number variation (CNV) data matrix  with genes as rows and samples as columns.
        output_path (str): Directory to save the results.
        design_factors (str): Column in metadata to use for design.
        alpha (float): Significance level for statistical tests.
    """
    #os.makedirs(output_path, exist_ok=True)
    
    # Initialize DeConveil inference
    inference = DefInference(n_cpus=8)

    # Fit DeConveil model
    dds = deconveil_fit(
        counts=rna_counts,
        metadata=metadata,
        cnv=cnv,
        design_factors="condition",
        inference=inference,
        refit_cooks=True
    )
    dds.fit_size_factors()
    dds.fit_genewise_dispersions()
    dds.fit_dispersion_trend()
    dds.fit_dispersion_prior()
    dds.fit_MAP_dispersions()
    dds.fit_LFC()
    dds.calculate_cooks()

    if dds.refit_cooks:
        dds.refit()  # Replace outlier counts

    # Statistical analysis
    stat_res_deconveil = deconveil_stats(
        dds, 
        alpha=alpha, 
        contrast=["condition", "B", "A"],
        independent_filter=True, 
        cooks_filter=True
    )
    stat_res_deconveil.run_wald_test()

    if stat_res_deconveil.independent_filter:
        stat_res_deconveil._independent_filtering()
    else:
        stat_res_deconveil._p_value_adjustment()

    # Log-fold change shrinkage
    stat_res_deconveil.lfc_shrink(coeff="condition[T.B]")
    stat_res_deconveil.summary()

    # Save results
    #results_path = os.path.join(output_path, "res_CNaware.csv")
    #stat_res_deconveil.results_df.to_csv(results_path)
    return(stat_res_deconveil.results_df)

In [57]:
def parse_sim_filename(path):
    """
    Parse sim_S40_G5000_CNstrong_R3.pkl
    """
    fname = os.path.basename(path)

    m = re.match(
        r"sim_S(\d+)_G(\d+)_CN([A-Za-z0-9]+)_R(\d+)\.pkl",
        fname
    )

    if m is None:
        raise ValueError(f"Could not parse filename: {fname}")

    S  = int(m.group(1))
    G  = int(m.group(2))
    CN = m.group(3)
    R  = int(m.group(4))

    return S, G, CN, R


def analyse_one_sim(path, outdir="sim_results/sim_res_fit/sim2"):

    os.makedirs(outdir, exist_ok=True)
    S, G, CN, R = parse_sim_filename(path)

    sim = load_sim(path)
    counts_df, cn_df, truth_df, meta = extract_sim_components(sim)

    counts_df = counts_df.T
    cn_df = cn_df.T

    print(f"[INFO] Running analysis for S={S}, G={G}, CN={CN}, R={R}")

    print("[INFO] Running PyDESeq2 (CN-naive)")
    res_naive = run_pydeseq2(counts_df, meta)

    print("[INFO] Running DeConveil (CN-aware)")
    res_aware = run_deconveil(counts_df, meta, cn_df)

    print("[INFO] Applying stageR")
    _, _, res_naive, res_aware = run_stageR(res_naive, res_aware)

    # File paths
    out_naive = os.path.join(outdir, f"res_CNnaive_S{S}_G{G}_CN{CN}_R{R}.csv")
    out_aware = os.path.join(outdir, f"res_CNaware_S{S}_G{G}_CN{CN}_R{R}.csv")
    out_truth = os.path.join(outdir, f"truth_S{S}_G{G}_CN{CN}_R{R}.csv")

    # Save
    res_naive.to_csv(out_naive, index=True)
    res_aware.to_csv(out_aware, index=True)
    truth_df.to_csv(out_truth, index=True)

    print(f"[SAVED] {out_naive}")
    print(f"[SAVED] {out_aware}")
    print(f"[SAVED] {out_truth}")

    return truth_df, res_naive, res_aware

def analyse_all_sims(
    sim_dir="sim_data",
    outdir="sim_results/sim_res_fit/sim2/",
):

    os.makedirs(outdir, exist_ok=True)

    sim_files = sorted(
        glob(os.path.join(sim_dir, "sim_S*_G*_CN*_R*.pkl"))
    )

    if not sim_files:
        raise RuntimeError("No simulation files found")

    print(f"[INFO] Found {len(sim_files)} simulations")

    for i, path in enumerate(sim_files, 1):
        print("=" * 60)
        print(f"[INFO] ({i}/{len(sim_files)}) {os.path.basename(path)}")

        try:
            analyse_one_sim(path, outdir=outdir)
        except Exception as e:
            print(f"[ERROR] Failed on {path}")
            print(e)

    print("[DONE] All simulations processed")

In [59]:
results = analyse_all_sims(
    sim_dir="sim_results/sim_data/sim2",
    outdir="sim_results/sim_res_fit/sim2/"
)

[INFO] Found 160 simulations
============================================================
[INFO] (1/160) sim_S10_G5000_CNstrong_R1.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=1
[INFO] Running PyDESeq2 (CN-naive)
Using None as control genes, passed at DeseqDataSet initialization

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.25 seconds.

Fitting LFCs...
... done in 0.71 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 323 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.12 seconds.

Running Wald tests...
... done in 0.25 seconds.

Fitting MAP LFCs...
... done in 1.27 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
JMJD6       3.026211e+05        0.771798  0.256397  3.144974  1.661016e-03
PLA2G12AP1  4.142646e+03       -0.114618  0.332653 -0.397677  6.908685e-01
VEGFA       3.434603e+06        3.433408  1.042302  3.503401  4.593572e-04
RHO         2.638783e+02        0.504632  1.128042 -0.326236  7.442458e-01
TK1         2.143792e+05       -0.657534  0.915289 -1.541141  1.232826e-01
...                  ...             ...       ...       ...           ...
SCN9A       1.299745e+04       -0.155733  0.474445 -0.439491  6.603057e-01
BCL2L2      5.901878e+05        0.769813  1.025092  1.164804  2.440985e-01
NADSYN1     5.951822e+05        0.575505  0.332611  2.016585  4.373888e-02
CUL7        1.118385e+06        2.612650  0.333618  8.077930  6.587523e-16
POGK        4.104011e+05       -0.314046  0.625979 -0.788268  4.305400e-01

                    padj
JMJD6       9.892755e-03
PLA2G12AP1  8.850686e-01
VEGFA       3.220016e-03
RHO         9.123759e-01
TK1         3.252131e-01
...                  ...
SCN9A       8.686310e-01
BCL2L2      5.067786e-01
NADSYN1     1.506561e-01
CUL7        4.503880e-14
POGK        6.972177e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.31 seconds.

Fitting LFCs...
... done in 1.02 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 321 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 321)
Number of True values in replace_mask: 540
replacement_counts_trimmed shape: (20, 321)

... done in 0.09 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.19 seconds.

Fitting MAP LFCs...
... done in 1.45 seconds.

R callback write-console:
Caricamento pacchetto: ‘stageR’


R callback write-console: Il seguente oggetto è mascherato da ‘package:methods’:

    getMethod

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
JMJD6       3.026211e+05        1.165958  0.238189  -1.644479  1.000774e-01
PLA2G12AP1  4.142646e+03       -0.105365  0.331922  -0.397661  6.908798e-01
VEGFA       3.434603e+06        3.743219  0.159947   2.820014  4.802156e-03
RHO         1.893211e+02        1.384268  0.047515 -17.355205  1.801547e-67
TK1         2.143792e+05        1.255635  0.857607  -0.710758  4.772341e-01
...                  ...             ...       ...        ...           ...
SCN9A       1.299745e+04       -0.009232  0.477445  -0.439489  6.603074e-01
BCL2L2      3.039122e+05        1.360307  0.002100   0.000028  9.999776e-01
NADSYN1     5.951822e+05        1.360740  0.215697  -1.203723  2.286967e-01
CUL7        1.118385e+06        3.380990  0.143611   6.527366  6.693650e-11
POGK        4.104011e+05        0.904879  0.444404  -2.111984  3.468785e-02

                    padj
JMJD6       2.645583e-01
PLA2G12AP1  8.989128e-01
VEGFA       2.096899e-02
RHO         9.464758e-66
TK1         7.436432e-01
...                  ...
SCN9A       8.816464e-01
BCL2L2      9.999929e-01
NADSYN1     4.775838e-01
CUL7        1.155986e-09
POGK        1.142753e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R1.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R1.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R1.csv
============================================================
[INFO] (2/160) sim_S10_G5000_CNstrong_R10.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=10
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.87 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.60 seconds.

Fitting LFCs...
... done in 0.73 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 274 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
... done in 1.27 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CCL18     40372.742769       -0.227732  0.771559 -0.639463  0.522522  0.767747
TMPRSS3   64505.672745        0.209832  0.853962  0.574397  0.565699  0.796281
NPC2     729420.762398       -0.145721  0.377883 -0.507064  0.612110  0.820674
GZMH      10049.347621       -0.194984  0.641453 -0.516602  0.605434  0.818328
OTOGL      3422.867724       -2.160329  0.850914 -3.296300  0.000980  0.006444
...                ...             ...       ...       ...       ...       ...
CCDC196     171.565273        1.063176  1.645797  0.736655  0.461332  0.722063
PBOV1       198.669849       -0.314701  0.455880 -0.890308  0.373300  0.643679
CDHR2       980.423293        0.689722  2.649156  1.004449  0.315162  0.585669
FAM215A     218.601855        0.829160  0.495455  2.103223  0.035446  0.129288
POLD3     19765.247293       -0.002716  0.931503 -0.039599  0.968412  0.990538

[4997 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.45 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 1.06 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 271 outlier genes.

Fitting dispersions...

replace_mask before filtering: (20, 271)
Number of True values in replace_mask: 435
replacement_counts_trimmed shape: (20, 271)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.41 seconds.

Fitting MAP LFCs...
... done in 4.38 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
CCL18     40372.742769        0.599878  0.854405 -0.639463  5.225220e-01
TMPRSS3   64505.672745        1.669209  0.870742  0.204181  8.382120e-01
NPC2     729420.762398        1.636444  0.279768 -0.507062  6.121110e-01
GZMH      10049.347621       -0.224315  0.644034 -0.516600  6.054352e-01
OTOGL      3422.867724       -2.523730  0.830836 -3.725469  1.949521e-04
...                ...             ...       ...       ...           ...
CCDC196      83.810555        2.916265  0.087599 -8.906484  5.267678e-19
PBOV1       198.669849       -0.723682  0.480838 -1.928003  5.385479e-02
CDHR2       501.956988        3.673336  0.038021 -0.004678  9.962673e-01
FAM215A     218.601855        0.817977  0.496315  2.102369  3.552095e-02
POLD3     19765.247293        0.560693  1.018228 -0.313067  7.542295e-01

                 padj
CCL18    7.692942e-01
TMPRSS3  9.581485e-01
NPC2     8.270537e-01
GZMH     8.240801e-01
OTOGL    1.367816e-03
...               ...
CCDC196  2.481275e-17
PBOV1    1.615967e-01
CDHR2    9.999753e-01
FAM215A  1.168354e-01
POLD3    9.142601e-01

[4997 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: Removing 4 features with NA screening hypothesis p-values.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R10.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R10.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R10.csv
============================================================
[INFO] (3/160) sim_S10_G5000_CNstrong_R11.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=11
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 2.36 seconds.

Fitting dispersion trend curve...
... done in 0.53 seconds.

Fitting MAP dispersions...
... done in 2.41 seconds.

Fitting LFCs...
... done in 1.96 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 307 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.26 seconds.

Fitting MAP dispersions...
... done in 0.26 seconds.

Fitting LFCs...
... done in 0.32 seconds.

Running Wald tests...
... done in 0.58 seconds.

Fitting MAP LFCs...
... done in 1.84 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat    pvalue  \
OSGEPL1-AS1    2045.139034        0.259308  0.282639  1.002441  0.316131
CPLANE1      218046.595124        1.086101  0.420173  2.904231  0.003682
NPEPL1       322801.706192       -0.129592  0.759312 -0.357299  0.720868
ZNF467       322324.500973        2.147073  0.646810  3.851778  0.000117
ABHD17A      369841.031874        0.222911  0.292919  0.785582  0.432112
...                    ...             ...       ...       ...       ...
TGDS          57711.242847       -0.100110  0.355275 -0.331611  0.740183
NPAP1           254.408123       -0.022546  0.707594 -0.065403  0.947853
NOD1         323774.666602        0.443612  0.675089  1.030341  0.302850
NT5C1B         4659.378281        1.409574  0.370076  4.148042  0.000034
NHP2P2          931.958604        0.886148  0.276322  3.432588  0.000598

                 padj
OSGEPL1-AS1  0.577106
CPLANE1      0.019002
NPEPL1       0.889897
ZNF467       0.000950
ABHD17A      0.690183
...               ...
TGDS         0.898322
NPAP1        0.982913
NOD1         0.563581
NT5C1B       0.000300
NHP2P2       0.003984

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.42 seconds.

Fitting dispersion trend curve...
... done in 0.29 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 1.03 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 308 outlier genes.

Fitting dispersions...

replace_mask before filtering: (20, 308)
Number of True values in replace_mask: 548
replacement_counts_trimmed shape: (20, 308)

... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.17 seconds.

Fitting LFCs...
... done in 0.14 seconds.

Running Wald tests...
... done in 0.44 seconds.

Fitting MAP LFCs...
... done in 1.17 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat    pvalue  \
OSGEPL1-AS1    2045.139034        0.277594  0.282349  1.002327  0.316186
CPLANE1      218046.595124        1.609422  0.328600  0.412753  0.679788
NPEPL1       322801.706192        0.954192  0.642043 -1.370062  0.170668
ZNF467       322324.500973        3.026624  0.440618  3.130847  0.001743
ABHD17A      369841.031874        1.993985  0.252349  0.785582  0.432113
...                    ...             ...       ...       ...       ...
TGDS          57711.242847        1.024841  0.391292 -0.331611  0.740183
NPAP1           254.408123       -0.019632  0.686795 -0.065397  0.947858
NOD1         323774.666602        1.341045  0.466179 -0.587914  0.556590
NT5C1B         4659.378281        1.169568  0.369864  3.514400  0.000441
NHP2P2          931.958604       -0.097286  0.268351 -0.399015  0.689882

                 padj
OSGEPL1-AS1  0.576574
CPLANE1      0.881365
NPEPL1       0.384889
ZNF467       0.008438
ABHD17A      0.697791
...               ...
TGDS         0.913876
NPAP1        0.999998
NOD1         0.801021
NT5C1B       0.002444
NHP2P2       0.889372

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R11.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R11.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R11.csv
============================================================
[INFO] (4/160) sim_S10_G5000_CNstrong_R12.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=12
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.09 seconds.

Fitting dispersion trend curve...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 1.24 seconds.

Fitting LFCs...
... done in 0.66 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 281 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 0.14 seconds.

Fitting LFCs...
... done in 0.17 seconds.

Running Wald tests...
... done in 0.41 seconds.

Fitting MAP LFCs...
... done in 1.49 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
PCGF1     76338.839231       -0.753301  0.335139 -2.539349  0.011106  0.049033
NPAS3      9289.254584       -0.416864  0.636753 -1.024362  0.305664  0.565009
USP8     291547.223870       -0.180798  0.189877 -1.010838  0.312094  0.572346
YRDC     112870.452601       -0.146208  0.318373 -0.539665  0.589428  0.804777
OSR2     157743.872818        0.156719  0.546865  0.395909  0.692172  0.864929
...                ...             ...       ...       ...       ...       ...
SLC10A7   46562.421004       -0.038088  0.496283 -0.112407  0.910501  0.965870
MYOM1     91153.689142        0.126418  0.896351  0.360337  0.718595  0.875048
ZNF644   253088.867191       -0.206373  0.260950 -0.883135  0.377163  0.640131
FABP9       530.235177       -0.548642  0.614550 -1.318185  0.187442  0.416918
DCAF1     95251.171367        0.318314  1.160685  0.934296  0.350151  0.611661

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.24 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 0.92 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 281 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 281)
Number of True values in replace_mask: 476
replacement_counts_trimmed shape: (20, 281)

... done in 0.09 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.27 seconds.

Fitting MAP LFCs...
... done in 1.16 seconds.

R callback write-console: Removing 2 features with NA screening hypothesis p-values.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
PCGF1     76338.839231        0.770165  0.351987 -3.306741  0.000944  0.005295
NPAS3      9289.254584       -0.405522  0.630374 -1.069249  0.284957  0.545062
USP8     291547.223870        2.417390  0.217031 -1.010836  0.312095  0.576584
YRDC     112870.452601        1.289920  0.348260 -0.539664  0.589429  0.820626
OSR2     157743.872818        2.411363  0.524168  1.801943  0.071554  0.202982
...                ...             ...       ...       ...       ...       ...
SLC10A7   46562.421004        1.165816  0.564198 -0.112407  0.910501  0.992496
MYOM1     91153.689142        1.759912  1.064880  0.360338  0.718594  0.892747
ZNF644   253088.867191        1.793296  0.250860 -0.883134  0.377164  0.647521
FABP9       530.235177       -1.543124  0.697803 -2.915710  0.003549  0.016743
DCAF1     29462.274915        1.542923  0.004881 -0.001217  0.999029  0.999985

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R12.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R12.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R12.csv
============================================================
[INFO] (5/160) sim_S10_G5000_CNstrong_R13.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=13
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.22 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.34 seconds.

Fitting LFCs...
... done in 0.75 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 277 outlier genes.

Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.12 seconds.

Fitting LFCs...
... done in 0.18 seconds.

Running Wald tests...
... done in 0.26 seconds.

Fitting MAP LFCs...
... done in 1.33 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
EPDR1       74608.433510       -0.750893  0.517796 -1.903261  5.700644e-02
INTS12     141081.506250        0.206382  0.213100  1.022363  3.066092e-01
LINC00943     689.817198        0.056207  0.738742  0.140985  8.878815e-01
PCDH9       25703.785630        0.120299  0.781258  0.309175  7.571883e-01
LRGUK       23957.432957        1.906050  0.765952  3.146817  1.650580e-03
...                  ...             ...       ...       ...           ...
MIR155HG     7119.525481       -0.322723  0.270747 -1.306999  1.912129e-01
TNFAIP3    306142.359962       -0.920810  0.446776 -2.504332  1.226827e-02
CRYBG3     205574.529842       -1.718939  0.325613 -5.636174  1.738693e-08
ATXN3      273568.838559       -0.308417  0.661774 -0.781935  4.342527e-01
NCR1          499.473640       -1.231478  0.249502 -5.172304  2.312245e-07

                   padj
EPDR1      1.822452e-01
INTS12     5.720514e-01
LINC00943  9.545805e-01
PCDH9      8.962158e-01
LRGUK      9.907679e-03
...                 ...
MIR155HG   4.247944e-01
TNFAIP3    5.348451e-02
CRYBG3     3.689349e-07
ATXN3      6.917779e-01
NCR1       3.765333e-06

[4983 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.86 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.14 seconds.

Fitting LFCs...
... done in 0.82 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 276 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 276)
Number of True values in replace_mask: 469
replacement_counts_trimmed shape: (20, 276)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.25 seconds.

Fitting MAP LFCs...
... done in 1.27 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
EPDR1       74608.433510        0.417200  0.493491 -2.668201  7.625858e-03
INTS12     141081.506250        2.168904  0.242586  1.022360  3.066106e-01
LINC00943     689.817198        0.053513  0.725186  0.140981  8.878847e-01
PCDH9       25703.785630        1.084691  1.050682  0.309175  7.571885e-01
LRGUK       23957.432957        2.754093  0.751290  2.908296  3.634047e-03
...                  ...             ...       ...       ...           ...
MIR155HG     7119.525481       -0.660105  0.274284 -2.528556  1.145329e-02
TNFAIP3    306142.359962        0.901308  0.351858 -3.305597  9.477413e-04
CRYBG3     205574.529842        0.196610  0.337698 -6.694776  2.160023e-11
ATXN3      273568.838559        1.273375  0.622990 -0.781935  4.342528e-01
NCR1          499.473640       -1.772925  0.249947 -7.316046  2.553841e-13

                   padj
EPDR1      3.212143e-02
INTS12     5.666198e-01
LINC00943  9.803851e-01
PCDH9      9.120306e-01
LRGUK      1.678263e-02
...                 ...
MIR155HG   4.539406e-02
TNFAIP3    5.116571e-03
CRYBG3     4.271188e-10
ATXN3      6.914881e-01
NCR1       6.059899e-12

[4983 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R13.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R13.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R13.csv
============================================================
[INFO] (6/160) sim_S10_G5000_CNstrong_R14.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=14
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.97 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.19 seconds.

Fitting LFCs...
... done in 0.64 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 311 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.22 seconds.

Fitting MAP LFCs...
... done in 1.09 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
MIA3       5.310071e+05        0.160207  0.400015  0.432976  0.665032
CTNNB1     2.207044e+06       -0.408756  0.350105 -1.374605  0.169254
DDX10      1.612162e+05        0.351543  0.270170  1.402326  0.160818
RNU6-322P  2.751957e+02       -0.455134  0.669539 -1.107038  0.268278
RN7SL130P  1.059755e+03       -0.193683  0.747873 -0.529377  0.596544
...                 ...             ...       ...       ...       ...
GPR137     2.212875e+05       -0.615672  0.501383 -1.611709  0.107025
DDX52      1.309569e+05       -1.362685  0.443971 -3.518834  0.000433
TOR1AIP1   3.064373e+05       -0.563685  0.372342 -1.740751  0.081727
ACTBP11    1.219059e+04       -0.006300  0.245951 -0.029145  0.976749
RPS3AP49   5.260071e+03       -0.620207  0.796902 -1.426567  0.153705

               padj
MIA3       0.861349
CTNNB1     0.405884
DDX10      0.392446
RNU6-322P  0.537232
RN7SL130P  0.821827
...             ...
GPR137     0.295921
DDX52      0.003058
TOR1AIP1   0.242364
ACTBP11    0.991284
RPS3AP49   0.380675

[4988 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.99 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.25 seconds.

Fitting LFCs...
... done in 1.19 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 311 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 311)
Number of True values in replace_mask: 547
replacement_counts_trimmed shape: (20, 311)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 1.29 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
MIA3       5.310071e+05        0.965830  0.263241 -2.454295  0.014116
CTNNB1     2.207044e+06        1.703769  0.133924 -1.374605  0.169254
DDX10      1.612162e+05        2.067374  0.255129  1.402324  0.160819
RNU6-322P  2.751957e+02       -0.795306  0.745077 -1.771010  0.076559
RN7SL130P  1.059755e+03       -0.203263  0.733518 -0.529367  0.596551
...                 ...             ...       ...       ...       ...
GPR137     2.212875e+05        0.948680  0.407545 -2.318375  0.020429
DDX52      1.309569e+05        0.429516  0.421245 -4.226629  0.000024
TOR1AIP1   3.064373e+05        0.473985  0.314201 -4.607586  0.000004
ACTBP11    1.219059e+04       -0.980792  0.246981 -3.932594  0.000084
RPS3AP49   5.260071e+03       -0.478697  0.748627 -1.426559  0.153707

               padj
MIA3       0.051583
CTNNB1     0.381836
DDX10      0.367291
RNU6-322P  0.209133
RN7SL130P  0.827770
...             ...
GPR137     0.070276
DDX52      0.000170
TOR1AIP1   0.000035
ACTBP11    0.000541
RPS3AP49   0.355608

[4988 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R14.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R14.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R14.csv
============================================================
[INFO] (7/160) sim_S10_G5000_CNstrong_R15.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=15
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.14 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.67 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 274 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.23 seconds.

Fitting MAP LFCs...
... done in 1.12 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
BBIP1       238417.329034        0.172260  0.582131  0.398116  0.690545
DMWD        309982.038747        0.849941  0.244957  3.635954  0.000277
TMEM163      24145.324885        0.110325  0.632624  0.277189  0.781635
RPTOR       326225.096269        0.570081  0.413779  1.642667  0.100452
CRYGS        50248.688777        1.461186  0.421114  3.852982  0.000117
...                   ...             ...       ...       ...       ...
VWA8        128949.826778        0.053475  0.459085  0.143729  0.885714
FGB          37500.419510       -0.892955  0.835219 -1.860852  0.062765
THAP6        92786.745135       -0.779234  1.042808 -1.767627  0.077123
HNRNPA3P13     218.534031        0.423156  1.626284  1.541384  0.123223
GUSBP5        5074.201411        0.481966  0.315946  1.711034  0.087075

                padj
BBIP1       0.868885
DMWD        0.002075
TMEM163     0.914346
RPTOR       0.279195
CRYGS       0.000970
...              ...
VWA8        0.956868
FGB         0.196693
THAP6       0.229987
HNRNPA3P13  0.322540
GUSBP5      0.251981

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.90 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.11 seconds.

Fitting LFCs...
... done in 0.79 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 278 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 278)
Number of True values in replace_mask: 463
replacement_counts_trimmed shape: (20, 278)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 0.97 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
BBIP1       238417.329034        1.735239  0.528762  0.398115  0.690545
DMWD        309982.038747        2.028289  0.234986  1.936873  0.052761
TMEM163      24145.324885        1.053942  0.782538  0.277188  0.781636
RPTOR       326225.096269        1.423095  0.299320 -0.583343  0.559662
CRYGS        50248.688777        1.753388  0.394698  1.479639  0.138970
...                   ...             ...       ...       ...       ...
VWA8        128949.826778        1.588980  0.423363  0.143729  0.885715
FGB          37500.419510        0.162099  0.623723 -1.860850  0.062765
THAP6        92786.745135        0.454867  0.749007 -1.832559  0.066868
HNRNPA3P13     218.534031        0.384070  1.585093  1.541286  0.123247
GUSBP5        5074.201411        0.414965  0.311732  1.710969  0.087087

                padj
BBIP1       0.887795
DMWD        0.157431
TMEM163     0.932245
RPTOR       0.800603
CRYGS       0.334613
...              ...
VWA8        0.980861
FGB         0.180171
THAP6       0.189334
HNRNPA3P13  0.304932
GUSBP5      0.233213

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R15.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R15.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R15.csv
============================================================
[INFO] (8/160) sim_S10_G5000_CNstrong_R16.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=16
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.83 seconds.

Fitting dispersion trend curve...
... done in 0.14 seconds.

Fitting MAP dispersions...
... done in 1.18 seconds.

Fitting LFCs...
... done in 1.14 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 329 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.19 seconds.

Fitting MAP LFCs...
... done in 1.08 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
TMEM167A   441210.756997       -0.270663  0.242377 -1.218110  0.223182
LINC02021    3726.127960       -0.078503  0.497773 -0.220675  0.825346
FAAP100    245516.554092       -0.602937  0.329366 -2.106229  0.035184
MYOM2       21190.826560        0.087532  0.709831  0.220051  0.825831
FOXN3-AS1   13133.993464       -0.003880  0.531154 -0.017722  0.985860
...                  ...             ...       ...       ...       ...
IPO8P1      16459.169674        0.313200  0.439594  0.892016  0.372384
ATP6V1B1    44843.855282       -1.320898  0.967051 -2.318259  0.020435
KCNH3        5595.913076       -0.962389  0.296760 -3.514506  0.000441
KRTAP1-5      142.817531       -0.707666  0.455352 -1.917891  0.055125
AGA        101599.567518       -0.294084  0.415238 -0.867714  0.385551

               padj
TMEM167A   0.491158
LINC02021  0.931098
FAAP100    0.129930
MYOM2      0.931098
FOXN3-AS1  0.993917
...             ...
IPO8P1     0.645176
ATP6V1B1   0.083842
KCNH3      0.003186
KRTAP1-5   0.186200
AGA        0.660094

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.97 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.17 seconds.

Fitting LFCs...
... done in 0.82 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 328 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 328)
Number of True values in replace_mask: 544
replacement_counts_trimmed shape: (20, 328)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 1.06 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
TMEM167A   441210.756997        1.938503  0.219466 -1.218109  0.223182
LINC02021    3726.127960       -0.125896  0.492869 -0.371692  0.710122
FAAP100    245516.554092        2.168908  0.335074  0.495227  0.620440
MYOM2       21190.826560        0.913238  0.902823  0.220051  0.825832
FOXN3-AS1   13133.993464       -0.143588  0.525978 -0.017722  0.985860
...                  ...             ...       ...       ...       ...
IPO8P1      16459.169674        1.118568  0.474210  2.753205  0.005901
ATP6V1B1    44843.855282       -0.210555  0.656375 -2.742454  0.006098
KCNH3        5595.913076       -1.274382  0.297952 -4.713884  0.000002
KRTAP1-5      142.817531       -0.844141  0.462527 -2.262512  0.023666
AGA        101599.567518        1.236058  0.428242 -0.867714  0.385551

               padj
TMEM167A   0.470210
LINC02021  0.892168
FAAP100    0.835988
MYOM2      0.960166
FOXN3-AS1  0.999994
...             ...
IPO8P1     0.024659
ATP6V1B1   0.025355
KCNH3      0.000022
KRTAP1-5   0.082027
AGA        0.649397

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R16.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R16.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R16.csv
============================================================
[INFO] (9/160) sim_S10_G5000_CNstrong_R17.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=17
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.82 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.12 seconds.

Fitting LFCs...
... done in 0.57 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 287 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.22 seconds.

Fitting MAP LFCs...
... done in 1.11 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
DNAJB14  2.558891e+05        0.239174  0.246785  1.026518  0.304647  0.570771
GAL3ST3  2.965364e+01       -0.215571  0.821827 -2.652802  0.007983  0.036499
KCTD3    7.554997e+05       -0.462420  0.491482 -1.227539  0.219620  0.461905
SFRP2    1.615177e+06        0.233480  0.652626  0.496895  0.619263  0.829213
WDR1     1.567556e+06        0.014792  0.277595 -0.062871  0.949870  0.978528
...               ...             ...       ...       ...       ...       ...
TDG      1.156467e+05        0.305620  0.731126  0.743709  0.457052  0.716051
DBN1     5.479501e+05       -1.104114  0.311453 -3.790616  0.000150  0.001193
SIGLEC1  1.152769e+05       -0.739725  1.285578 -2.062678  0.039143  0.133135
ENGASE   5.647250e+05        1.454045  0.326967  4.769694  0.000002  0.000023
OR7E2P   3.380960e+02        0.275335  0.495159  0.739026  0.459891  0.716901

[4993 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.92 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.15 seconds.

Fitting LFCs...
... done in 1.26 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 284 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...

replace_mask before filtering: (20, 284)
Number of True values in replace_mask: 476
replacement_counts_trimmed shape: (20, 284)

... done in 0.05 seconds.

Running Wald tests...
... done in 0.17 seconds.

Fitting MAP LFCs...
... done in 0.77 seconds.

R callback write-console: Removing 4 features with NA screening hypothesis p-values.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat        pvalue  \
DNAJB14  2.558891e+05        2.160158  0.238091  1.026517  3.046479e-01
GAL3ST3  0.000000e+00       -0.252593  0.798827  0.000000           NaN
KCTD3    7.554997e+05        0.758641  0.273623 -3.425900  6.127660e-04
SFRP2    1.615177e+06        2.039115  0.256712  0.496895  6.192634e-01
WDR1     1.567556e+06        2.096222  0.156879 -0.062871  9.498696e-01
...               ...             ...       ...       ...           ...
TDG      1.156467e+05        1.807174  0.795734  0.743708  4.570531e-01
DBN1     5.479501e+05        0.911405  0.266896 -4.924556  8.455193e-07
SIGLEC1  1.152769e+05        0.483866  0.831254 -1.477841  1.394502e-01
ENGASE   5.647250e+05        1.921704  0.207762  1.265940  2.055346e-01
OR7E2P   3.380960e+02        0.265399  0.490918  0.738880  4.599801e-01

             padj
DNAJB14  0.572678
GAL3ST3       NaN
KCTD3    0.003389
SFRP2    0.844271
WDR1     0.999999
...           ...
TDG      0.723085
DBN1     0.000009
SIGLEC1  0.339209
ENGASE   0.440848
OR7E2P   0.723696

[4993 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R17.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R17.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R17.csv
============================================================
[INFO] (10/160) sim_S10_G5000_CNstrong_R18.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=18
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.85 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.12 seconds.

Fitting LFCs...
... done in 0.57 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 293 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.22 seconds.

Fitting MAP LFCs...
... done in 1.12 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
LINC02766  7.950072e+02        0.235882  1.054837  0.729889  4.654581e-01
SLC25A48   5.290171e+03       -1.382490  1.578044 -2.323777  2.013745e-02
TYSND1     1.512735e+05        0.594758  0.363533  1.862855  6.248265e-02
RAD51D     9.783350e+04       -0.022651  0.335458 -0.091083  9.274268e-01
SIGLEC5    9.978531e+03        0.117337  0.431874  0.332330  7.396398e-01
...                 ...             ...       ...       ...           ...
ARLNC1     1.947046e+02       -0.102828  0.786688 -0.385845  6.996112e-01
CXCL9      1.254267e+05        0.621160  1.086934  1.456364  1.452921e-01
AP2A1      1.741227e+06        0.575826  0.792976  1.555907  1.197302e-01
RFC2       5.183426e+05        2.247482  0.324730  7.197576  6.129249e-13
QRICH1     3.637488e+05       -0.288402  0.414832 -0.868143  3.853161e-01

                   padj
LINC02766  7.298910e-01
SLC25A48   7.945139e-02
TYSND1     1.986311e-01
RAD51D     9.699194e-01
SIGLEC5    8.908965e-01
...                 ...
ARLNC1     8.692997e-01
CXCL9      3.651324e-01
AP2A1      3.202430e-01
RFC2       2.447287e-11
QRICH1     6.579243e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.88 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.13 seconds.

Fitting LFCs...
... done in 0.77 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 290 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 290)
Number of True values in replace_mask: 485
replacement_counts_trimmed shape: (20, 290)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 0.95 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
LINC02766  7.950072e+02        0.211124  1.021775  0.729880  4.654636e-01
SLC25A48   5.290171e+03       -0.812770  1.256926 -2.323765  2.013811e-02
TYSND1     1.512735e+05        2.045182  0.326163  1.862853  6.248290e-02
RAD51D     9.783350e+04        1.314012  0.359248 -0.091083  9.274269e-01
SIGLEC5    9.978531e+03       -0.357757  0.434931 -0.865687  3.866616e-01
...                 ...             ...       ...       ...           ...
ARLNC1     2.429753e+02       -0.356099  0.036610 -5.095322  3.481494e-07
CXCL9      1.254267e+05        2.466064  0.825157  1.162097  2.451962e-01
AP2A1      1.741227e+06        2.169791  0.212067  0.749995  4.532577e-01
RFC2       5.183426e+05        3.123627  0.192308  5.893684  3.776794e-09
QRICH1     3.637488e+05        1.381893  0.369802 -0.868143  3.853162e-01

                   padj
LINC02766  7.201267e-01
SLC25A48   7.230885e-02
TYSND1     1.848560e-01
RAD51D     9.947349e-01
SIGLEC5    6.459663e-01
...                 ...
ARLNC1     3.777421e-06
CXCL9      4.899016e-01
AP2A1      7.087121e-01
RFC2       5.416660e-08
QRICH1     6.449293e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R18.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R18.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R18.csv
============================================================
[INFO] (11/160) sim_S10_G5000_CNstrong_R19.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=19
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.80 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.13 seconds.

Fitting LFCs...
... done in 0.59 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 281 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.23 seconds.

Fitting MAP LFCs...
... done in 1.51 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
NOTCH1   543089.574216       -0.281734  0.464020 -0.802759  4.221140e-01
TMEM30A  687964.526628       -0.678293  0.333018 -2.309171  2.093409e-02
ZIC4      11953.799287        0.269182  0.950753  0.736397  4.614892e-01
ZBTB24   433528.100081        3.279780  0.358034  9.361905  7.831195e-21
SVIP     400713.633414        1.329566  0.489137  3.133831  1.725399e-03
...                ...             ...       ...       ...           ...
ZHX2     176794.646263        0.688335  0.648735  1.513657  1.301128e-01
HOXD3     40476.608381        0.638827  0.789067  1.430191  1.526622e-01
RARS2    184318.040509       -0.621048  0.514237 -1.588355  1.122062e-01
PRAL     311386.382694        0.168167  0.233329  0.725531  4.681262e-01
GRIK1     16253.870064        1.736487  0.674777  3.164073  1.555777e-03

                 padj
NOTCH1   6.849579e-01
TMEM30A  8.197952e-02
ZIC4     7.158172e-01
ZBTB24   1.396470e-18
SVIP     9.614864e-03
...               ...
ZHX2     3.319639e-01
HOXD3    3.712385e-01
RARS2    3.010583e-01
PRAL     7.209606e-01
GRIK1    8.857462e-03

[4993 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.88 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.15 seconds.

Fitting LFCs...
... done in 0.79 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 285 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 285)
Number of True values in replace_mask: 463
replacement_counts_trimmed shape: (20, 285)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.21 seconds.

Fitting MAP LFCs...
... done in 1.07 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
NOTCH1   543089.574216        1.491297  0.351407 -0.802760  4.221133e-01
TMEM30A  687964.526628        1.056106  0.230304 -3.630079  2.833340e-04
ZIC4      11953.799287        0.854787  1.098867 -0.024028  9.808304e-01
ZBTB24   433528.100081        3.962099  0.206084  8.373547  5.590916e-17
SVIP     400713.633414        2.405541  0.345823  2.347008  1.892485e-02
...                ...             ...       ...       ...           ...
ZHX2     176794.646263        1.605860  0.509157  0.137514  8.906249e-01
HOXD3     40476.608381        2.132736  0.801134  1.430190  1.526625e-01
RARS2    184318.040509        0.940222  0.511179 -1.588358  1.122053e-01
PRAL     311386.382694        2.167666  0.228340  0.725530  4.681267e-01
GRIK1     16253.870064        2.329559  0.666093  2.444515  1.450472e-02

                 padj
NOTCH1   6.937498e-01
TMEM30A  1.690187e-03
ZIC4     9.999843e-01
ZBTB24   1.798323e-15
SVIP     6.892178e-02
...               ...
ZHX2     9.896459e-01
HOXD3    3.593482e-01
RARS2    2.889331e-01
PRAL     7.306962e-01
GRIK1    5.519976e-02

[4993 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R19.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R19.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R19.csv
============================================================
[INFO] (12/160) sim_S10_G5000_CNstrong_R2.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=2
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.87 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.13 seconds.

Fitting LFCs...
... done in 0.69 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 292 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.23 seconds.

Fitting MAP LFCs...
... done in 1.08 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SPHKAP     1.028435e+03       -0.060995  0.911358  0.546815  0.584506
P2RX3      5.571083e+00       -0.731063  1.018686  0.589642  0.555431
SRSF5      2.485602e+06       -0.235563  0.407603 -0.434336  0.664045
MFSD2A     7.987464e+04        0.786149  0.593692  1.810611  0.070201
SMOC2      4.441377e+05       -0.244254  0.563567 -0.647618  0.517232
...                 ...             ...       ...       ...       ...
RNU6-395P  3.436471e+03        0.313034  0.865034  0.816829  0.414026
ZNF33A     6.094603e+05        0.569963  0.850226  1.282957  0.199507
CHTF18     2.836809e+05        0.896313  0.677626  1.862848  0.062484
ZC3H7B     3.892212e+05       -0.095682  0.441064 -0.219672  0.826127
NOX4       5.824643e+04       -0.008426  0.359656 -0.017143  0.986323

               padj
SPHKAP     0.811028
P2RX3      0.792044
SRSF5      0.860708
MFSD2A     0.221196
SMOC2      0.765575
...             ...
RNU6-395P  0.682207
ZNF33A     0.450347
CHTF18     0.202241
ZC3H7B     0.935580
NOX4       0.995932

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.92 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.25 seconds.

Fitting LFCs...
... done in 0.82 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 290 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 290)
Number of True values in replace_mask: 501
replacement_counts_trimmed shape: (20, 290)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 1.58 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SPHKAP     3.381114e+02       -0.623003  0.031754 -0.001226  0.999022
P2RX3      3.779599e+00       -2.189741  0.280254 -0.637009  0.524119
SRSF5      2.485602e+06        1.755042  0.170900 -0.434336  0.664045
MFSD2A     7.987464e+04        2.248480  0.518228  1.810609  0.070201
SMOC2      4.441377e+05        1.483477  0.435717 -0.647618  0.517232
...                 ...             ...       ...       ...       ...
RNU6-395P  3.436471e+03        0.329837  0.860255  0.816825  0.414028
ZNF33A     6.094603e+05        2.223451  0.356938  0.808409  0.418855
CHTF18     2.836809e+05        1.767810  0.431450  0.396403  0.691807
ZC3H7B     3.892212e+05        1.583987  0.366542 -0.219672  0.826127
NOX4       5.824643e+04        1.157440  0.397171 -0.017143  0.986323

               padj
SPHKAP     0.999987
P2RX3      0.784692
SRSF5      0.877275
MFSD2A     0.201249
SMOC2      0.780602
...             ...
RNU6-395P  0.691109
ZNF33A     0.695445
CHTF18     0.893585
ZC3H7B     0.958829
NOX4       0.999987

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R2.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R2.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R2.csv
============================================================
[INFO] (13/160) sim_S10_G5000_CNstrong_R20.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=20
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.72 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.15 seconds.

Fitting LFCs...
... done in 0.59 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 297 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.22 seconds.

Fitting MAP LFCs...
... done in 1.09 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                   baseMean  log2FoldChange     lfcSE      stat        pvalue  \
PRICKLE2-AS2     373.730475        2.498166  1.665793  2.778765  5.456594e-03
HCCAT5           172.638112       -1.043689  1.520010 -2.148540  3.167089e-02
THY1          833677.843604        1.133425  0.919294  2.011430  4.428005e-02
PPARD         187644.631872       -1.576631  0.292013 -5.701278  1.189127e-08
FAM180A        43397.269176        0.599993  0.449984  1.630168  1.030660e-01
...                     ...             ...       ...       ...           ...
MYHAS           2519.099882        0.346097  0.703401  0.843286  3.990688e-01
SYCE1L         17405.604129        0.499700  0.290167  1.862659  6.251023e-02
SAR1B         345339.145601        0.191726  0.334897  0.619470  5.356068e-01
TXNL4B         61290.164360       -0.018394  0.783078 -0.069290  9.447586e-01
HSD17B6        39524.532173        1.531288  0.321344  5.045258  4.529108e-07

                      padj
PRICKLE2-AS2  2.647531e-02
HCCAT5        1.145802e-01
THY1          1.479659e-01
PPARD         2.461641e-07
FAM180A       2.749712e-01
...                    ...
MYHAS         6.583843e-01
SYCE1L        1.933121e-01
SAR1B         7.725188e-01
TXNL4B        9.834160e-01
HSD17B6       6.807918e-06

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.89 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.09 seconds.

Fitting LFCs...
... done in 0.79 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 295 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 295)
Number of True values in replace_mask: 495
replacement_counts_trimmed shape: (20, 295)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 0.93 seconds.

R callback write-console: Removing 2 features with NA screening hypothesis p-values.

Log2 fold change & Wald test p-value: condition B vs A
                   baseMean  log2FoldChange     lfcSE      stat        pvalue  \
PRICKLE2-AS2     373.730475        2.448702  1.687768  2.778441  5.462041e-03
HCCAT5           172.638112       -0.902920  1.432712 -2.148231  3.169542e-02
THY1          833677.843604        2.970531  0.354796  2.011430  4.428005e-02
PPARD         187644.631872        0.511058  0.299233 -6.868623  6.482453e-12
FAM180A        43397.269176        1.483750  0.478800  1.128092  2.592812e-01
...                     ...             ...       ...       ...           ...
MYHAS           2519.099882        0.329553  0.693626  0.843275  3.990746e-01
SYCE1L         17405.604129        0.374563  0.282340  1.862634  6.251371e-02
SAR1B         345339.145601        1.899059  0.261294  0.619470  5.356070e-01
TXNL4B         61290.164360        0.798993  0.983156 -0.069290  9.447585e-01
HSD17B6        39524.532173        2.211935  0.321848  3.831329  1.274528e-04

                      padj
PRICKLE2-AS2  2.348207e-02
HCCAT5        1.039902e-01
THY1          1.368815e-01
PPARD         1.330370e-10
FAM180A       5.050062e-01
...                    ...
MYHAS         6.561770e-01
SYCE1L        1.818548e-01
SAR1B         7.807869e-01
TXNL4B        9.999894e-01
HSD17B6       8.531636e-04

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R20.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R20.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R20.csv
============================================================
[INFO] (14/160) sim_S10_G5000_CNstrong_R3.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=3
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.92 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.24 seconds.

Fitting LFCs...
... done in 0.61 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 282 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.21 seconds.

Fitting MAP LFCs...
... done in 1.31 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SULT2B1   210448.689184        1.914986  1.225936  2.579151  9.904359e-03
MORN2      45359.443101       -1.247385  0.408540 -3.478451  5.043199e-04
PRR7-AS1    1991.094745        0.150042  0.478882  0.409635  6.820735e-01
FMO2      355537.483697        0.136636  0.589892  0.315942  7.520464e-01
NFYC      262087.410440       -0.399594  0.239779 -1.789663  7.350812e-02
...                 ...             ...       ...       ...           ...
GAS2        4669.033403       -1.701290  0.365525 -4.998694  5.771984e-07
AGMAT       5305.509889        0.399894  1.520365  1.399989  1.615166e-01
LIPT1      34985.710514        0.555017  0.269589  2.234956  2.542021e-02
PGPEP1     82021.982185       -2.347787  0.489569 -5.205064  1.939296e-07
ADAMTS15  487445.910909        0.567134  1.399616  1.585493  1.128544e-01

              padj
SULT2B1   0.045181
MORN2     0.003497
PRR7-AS1  0.876324
FMO2      0.909260
NFYC      0.222261
...            ...
GAS2      0.000008
AGMAT     0.392738
LIPT1     0.097091
PGPEP1    0.000003
ADAMTS15  0.307516

[4992 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.39 seconds.

Fitting dispersion trend curve...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 1.06 seconds.

Fitting LFCs...
... done in 1.19 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 281 outlier genes.

Fitting dispersions...

replace_mask before filtering: (20, 281)
Number of True values in replace_mask: 462
replacement_counts_trimmed shape: (20, 281)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.04 seconds.

R callback write-console: Removing 1 features with NA screening hypothesis p-values.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SULT2B1   210448.689184        3.469811  0.607555  2.285232  2.229921e-02
MORN2      45359.443101        0.390406  0.411706 -3.956991  7.589967e-05
PRR7-AS1    1991.094745       -0.030655  0.471302 -0.110881  9.117108e-01
FMO2      355537.483697        1.148235  0.414522 -1.165683  2.437427e-01
NFYC      262087.410440        1.631967  0.253306 -1.789661  7.350848e-02
...                 ...             ...       ...       ...           ...
GAS2        4669.033403       -2.056830  0.365225 -6.077613  1.219850e-09
AGMAT       5305.509889        0.392698  1.526305  1.399982  1.615188e-01
LIPT1      34985.710514        0.686771  0.275661  2.234939  2.542135e-02
PGPEP1     82021.982185       -0.153942  0.489991 -5.792532  6.933293e-09
ADAMTS15  487445.910909        3.353091  0.498171  1.585493  1.128544e-01

                  padj
SULT2B1   7.810201e-02
MORN2     5.175071e-04
PRR7-AS1  9.961359e-01
FMO2      4.962926e-01
NFYC      2.098861e-01
...                ...
GAS2      1.850538e-08
AGMAT     3.767011e-01
LIPT1     8.738151e-02
PGPEP1    9.252424e-08
ADAMTS15  2.910884e-01

[4992 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R3.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R3.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R3.csv
============================================================
[INFO] (15/160) sim_S10_G5000_CNstrong_R4.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=4
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.85 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.19 seconds.

Fitting LFCs...
... done in 0.58 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 294 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.21 seconds.

Fitting MAP LFCs...
... done in 1.11 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
TCP11        2891.352107        0.217789  0.745049  0.557431  0.577233
RNA5SP216   15657.400551        1.373678  0.524394  3.103764  0.001911
EML5        85604.193494        0.256747  0.217570  1.250542  0.211102
TEX19        1241.792341        5.514807  1.822602  2.812566  0.004915
PA2G4P5     34887.783366        0.862622  0.240061  3.745573  0.000180
...                  ...             ...       ...       ...       ...
LINC02345    3701.950551        0.707793  1.504146  1.825372  0.067945
DOCK1      535290.819962       -0.075537  0.266684 -0.388688  0.697507
ANKRD39     40440.389483       -1.245002  0.798048 -2.339147  0.019328
IFT81       85260.892789       -0.123304  0.398452 -0.384108  0.700898
SCN3B       26165.992111       -0.371787  0.393379 -1.137784  0.255211

               padj
TCP11      0.800750
RNA5SP216  0.011070
EML5       0.458167
TEX19      0.025020
PA2G4P5    0.001336
...             ...
LINC02345  0.212506
DOCK1      0.867584
ANKRD39    0.077280
IFT81      0.869314
SCN3B      0.512474

[4994 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.88 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.13 seconds.

Fitting LFCs...
... done in 0.79 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 289 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 289)
Number of True values in replace_mask: 496
replacement_counts_trimmed shape: (20, 289)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.17 seconds.

Fitting MAP LFCs...
... done in 0.99 seconds.

R callback write-console: Removing 1 features with NA screening hypothesis p-values.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
TCP11        2891.352107        0.118657  0.710616  0.300625  7.637001e-01
RNA5SP216   15657.400551        1.330468  0.534971  2.735101  6.236113e-03
EML5        85604.193494        1.990522  0.247814  1.250536  2.111039e-01
TEX19         203.296611        5.108248  0.051942 -6.989085  2.766839e-12
PA2G4P5     34887.783366        0.642801  0.239536  2.812216  4.920138e-03
...                  ...             ...       ...       ...           ...
LINC02345    3701.950551        0.677721  1.507979  1.825359  6.794688e-02
DOCK1      535290.819962        1.854090  0.233618 -0.388688  6.975070e-01
ANKRD39     40440.389483        0.048692  0.593210 -2.339145  1.932795e-02
IFT81       85260.892789        1.244317  0.420965 -0.384108  7.008984e-01
SCN3B       26165.992111        0.178917  0.399912 -1.137779  2.552128e-01

                   padj
TCP11      9.186419e-01
RNA5SP216  2.616074e-02
EML5       4.449311e-01
TEX19      5.417580e-11
PA2G4P5    2.119607e-02
...                 ...
LINC02345  1.940840e-01
DOCK1      8.816842e-01
ANKRD39    6.863760e-02
IFT81      8.840540e-01
SCN3B      4.971819e-01

[4994 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R4.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R4.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R4.csv
============================================================
[INFO] (16/160) sim_S10_G5000_CNstrong_R5.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=5
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.20 seconds.

Fitting dispersion trend curve...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 1.04 seconds.

Fitting LFCs...
... done in 0.59 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 267 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.22 seconds.

Fitting MAP LFCs...
... done in 1.11 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
MLYCD      1.332347e+05        0.060960  0.349913  0.180476  8.567788e-01
RPL26      1.948871e+06        0.076892  0.286674  0.354478  7.229809e-01
FASTKD5    1.359850e+05        0.386293  0.365995  1.221117  2.220418e-01
ADCY10     2.457048e+03       -1.132290  0.822550 -2.164548  3.042232e-02
UPK2       4.688612e+03        0.098859  0.508715  0.259155  7.955160e-01
...                 ...             ...       ...       ...           ...
RPS15AP14  2.771668e+00       -0.210661  0.843626 -1.154403  2.483352e-01
POMT2      1.752632e+05       -0.818923  1.551137 -2.530203  1.139966e-02
NKX2-8     5.695058e+02       -0.557100  0.188880 -3.071128  2.132518e-03
NHLH1      2.029291e+03       -0.005590  0.424886 -0.021195  9.830900e-01
REEP1      1.679645e+05        1.699498  0.232466  7.477705  7.563172e-14

                   padj
MLYCD      9.378612e-01
RPL26      8.732745e-01
FASTKD5    4.699773e-01
ADCY10     1.134584e-01
UPK2       9.113005e-01
...                 ...
RPS15AP14  5.006950e-01
POMT2      4.972405e-02
NKX2-8     1.195647e-02
NHLH1      9.936437e-01
REEP1      3.145019e-12

[4990 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.89 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.15 seconds.

Fitting LFCs...
... done in 0.79 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 267 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...

replace_mask before filtering: (20, 267)
Number of True values in replace_mask: 450
replacement_counts_trimmed shape: (20, 267)

... done in 0.05 seconds.

Running Wald tests...
... done in 0.17 seconds.

Fitting MAP LFCs...
... done in 0.97 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
MLYCD      1.332347e+05        1.619363  0.360641  0.180476  8.567790e-01
RPL26      1.948871e+06        2.205165  0.141909  0.354478  7.229809e-01
FASTKD5    1.359850e+05        0.886259  0.360024 -1.646924  9.957370e-02
ADCY10     2.457048e+03       -2.203309  0.847761 -3.437248  5.876578e-04
UPK2       4.688612e+03        0.076494  0.504150  0.259151  7.955186e-01
...                 ...             ...       ...       ...           ...
RPS15AP14  3.155223e+00       -0.823935  0.261508 -0.136441  8.914728e-01
POMT2      1.752632e+05        0.101236  0.704656 -2.530195  1.139992e-02
NKX2-8     5.695058e+02       -1.007822  0.190277 -5.448450  5.081057e-08
NHLH1      2.029291e+03       -1.096871  0.460904 -2.845600  4.432789e-03
REEP1      1.679645e+05        2.779922  0.224720  5.848988  4.945728e-09

                   padj
MLYCD      9.650627e-01
RPL26      8.976826e-01
FASTKD5    2.617875e-01
ADCY10     3.136270e-03
UPK2       9.351326e-01
...                 ...
RPS15AP14  9.778345e-01
POMT2      4.355711e-02
NKX2-8     6.260364e-07
NHLH1      1.908138e-02
REEP1      7.091720e-08

[4990 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R5.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R5.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R5.csv
============================================================
[INFO] (17/160) sim_S10_G5000_CNstrong_R6.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=6
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.84 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.12 seconds.

Fitting LFCs...
... done in 0.58 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 276 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.23 seconds.

Fitting MAP LFCs...
... done in 1.10 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SYCP2L        4597.220806       -1.824535  0.509611 -4.051516  0.000051
RNA5SP187      229.500143       -0.957700  0.999141 -1.904449  0.056852
PRR13       577766.065966       -0.449061  0.282342 -1.796747  0.072376
SLC44A3      55038.687747       -0.280358  0.538666 -0.743895  0.456940
CCDC92      329136.953596       -0.319005  0.349519 -0.995525  0.319481
...                   ...             ...       ...       ...       ...
MTSS1       313829.350139       -0.096043  0.787794 -1.602227  0.109105
GRHL2       385988.621741       -0.088544  0.386979 -0.317904  0.750558
SHC2        241932.010694        0.104413  0.843886  0.274312  0.783845
ZNF829       63018.606077        3.132214  1.221124  3.366220  0.000762
RNU6-1330P     531.585845       -0.067547  0.502061 -0.188844  0.850215

                padj
SYCP2L      0.000468
RNA5SP187   0.181816
PRR13       0.216606
SLC44A3     0.708400
CCDC92      0.578965
...              ...
MTSS1       0.287547
GRHL2       0.897695
SHC2        0.912507
ZNF829      0.005016
RNU6-1330P  0.943654

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.11 seconds.

Fitting dispersion trend curve...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 1.09 seconds.

Fitting LFCs...
... done in 0.77 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 271 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 271)
Number of True values in replace_mask: 456
replacement_counts_trimmed shape: (20, 271)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 0.95 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SYCP2L        4597.220806       -2.102402  0.509982 -4.773386  0.000002
RNA5SP187      229.500143       -0.895987  0.997388 -1.904200  0.056884
PRR13       577766.065966        1.675869  0.250988 -1.796746  0.072376
SLC44A3      55038.687747        0.986993  0.594022 -0.743894  0.456940
CCDC92      329136.953596        1.574904  0.288427 -0.995524  0.319481
...                   ...             ...       ...       ...       ...
MTSS1       153955.334319       -1.298681  0.002738  0.000277  0.999779
GRHL2       385988.621741        0.766975  0.298340 -3.154884  0.001606
SHC2        241932.010694        1.887614  0.655170  0.274312  0.783845
ZNF829       63018.606077        3.469794  0.888679  2.404636  0.016189
RNU6-1330P     531.585845       -0.064954  0.495462 -0.188822  0.850232

                padj
SYCP2L      0.000018
RNA5SP187   0.170039
PRR13       0.205980
SLC44A3     0.712621
CCDC92      0.577706
...              ...
MTSS1       0.999985
GRHL2       0.008002
SHC2        0.930874
ZNF829      0.059605
RNU6-1330P  0.964047

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R6.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R6.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R6.csv
============================================================
[INFO] (18/160) sim_S10_G5000_CNstrong_R7.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=7
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.80 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.16 seconds.

Fitting LFCs...
... done in 0.61 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 303 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.22 seconds.

Fitting MAP LFCs...
... done in 1.10 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC01908      40.811160        0.403130  1.676815   1.509037  1.312894e-01
PCSK6      151741.022257        0.174052  0.675879   0.422059  6.729821e-01
NRF1       254041.229847        1.709407  0.172388  10.089816  6.128423e-24
EFCAB11     35777.558654       -0.037202  0.383200  -0.126057  8.996871e-01
VANGL1     148738.491218       -1.260442  0.597848  -2.691602  7.110965e-03
...                  ...             ...       ...        ...           ...
RCN1       912403.890146        0.310674  1.649443   2.130055  3.316704e-02
UBE2D1      13403.033462       -0.921501  1.680279  -0.921640  3.567166e-01
ZNF512     198343.862633       -0.033815  0.542226  -0.113071  9.099742e-01
PRR22       17164.879814        0.490561  0.275686   1.917587  5.516341e-02
CACNA1G     34973.927093        1.719717  0.316246   5.707055  1.149478e-08

                   padj
LINC01908  3.316979e-01
PCSK6      8.687251e-01
NRF1       1.273435e-21
EFCAB11    9.613755e-01
VANGL1     3.265413e-02
...                 ...
RCN1       1.176415e-01
UBE2D1     6.257071e-01
ZNF512     9.653910e-01
PRR22      1.758951e-01
CACNA1G    2.107518e-07

[4987 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.88 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.54 seconds.

Fitting LFCs...
... done in 0.92 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 299 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 299)
Number of True values in replace_mask: 514
replacement_counts_trimmed shape: (20, 299)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.25 seconds.

Fitting MAP LFCs...
... done in 1.19 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE        stat        pvalue  \
LINC01908      40.811160        0.346853  1.609865    1.508535  1.314177e-01
PCSK6      151741.022257        1.682109  0.713483    0.422059  6.729822e-01
NRF1       254041.229847        3.374954  0.178805    7.806057  5.900510e-15
EFCAB11     35777.558654        1.237308  0.416227   -0.126056  8.996874e-01
VANGL1     148738.491218        0.435419  0.530787   -2.691599  7.111046e-03
...                  ...             ...       ...         ...           ...
RCN1       135612.247264        2.095881  0.002750 -144.724095  0.000000e+00
UBE2D1       9730.508659       -3.510897  0.008960  -39.913418  0.000000e+00
ZNF512     198343.862633        1.259131  0.453114   -0.892638  3.720513e-01
PRR22       17164.879814        0.375100  0.267972    1.917558  5.516706e-02
CACNA1G     34973.927093        1.487274  0.324682    1.763661  7.778908e-02

                   padj
LINC01908  3.226884e-01
PCSK6      8.854515e-01
NRF1       1.532596e-13
EFCAB11    9.895768e-01
VANGL1     2.987598e-02
...                 ...
RCN1       0.000000e+00
UBE2D1     0.000000e+00
ZNF512     6.429036e-01
PRR22      1.673468e-01
CACNA1G    2.193848e-01

[4987 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R7.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R7.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R7.csv
============================================================
[INFO] (19/160) sim_S10_G5000_CNstrong_R8.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=8
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.42 seconds.

Fitting dispersion trend curve...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 1.00 seconds.

Fitting LFCs...
... done in 0.59 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 289 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.23 seconds.

Fitting MAP LFCs...
... done in 1.11 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
ZNF542P     244067.864624        2.139849  0.409807  5.532642  3.154432e-08
RFX7        146624.373849       -0.090982  0.290414 -0.377524  7.057843e-01
GEMIN7-AS1   14611.656104       -1.645739  0.423418 -4.292367  1.767781e-05
MIR6774        354.744262       -0.274343  0.771919 -0.749509  4.535506e-01
RMDN1       232522.600915       -0.413288  0.319781 -1.472634  1.408497e-01
...                   ...             ...       ...       ...           ...
LCNL1         7716.598696       -0.003101  0.385270 -0.013730  9.890457e-01
ENDOD1      380237.836713       -0.381017  0.924835 -1.517075  1.292477e-01
ZNF335      239513.179368       -0.193499  0.829352 -0.609412  5.422513e-01
PGF          55252.738002        0.045218  0.672994  0.105786  9.157522e-01
PKNOX2       14538.976871       -0.334398  0.636911 -0.850875  3.948390e-01

                    padj
ZNF542P     5.918710e-07
RFX7        8.758874e-01
GEMIN7-AS1  1.789654e-04
MIR6774     7.183977e-01
RMDN1       3.527250e-01
...                  ...
LCNL1       9.968712e-01
ENDOD1      3.321707e-01
ZNF335      7.846006e-01
PGF         9.652628e-01
PKNOX2      6.677877e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.84 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.27 seconds.

Fitting LFCs...
... done in 0.81 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 289 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 289)
Number of True values in replace_mask: 499
replacement_counts_trimmed shape: (20, 289)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 1.10 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
ZNF542P     244067.864624        2.899140  0.292317  4.308563  1.643190e-05
RFX7        146624.373849        1.400486  0.317316 -0.377523  7.057847e-01
GEMIN7-AS1   14611.656104       -2.055926  0.416083 -5.296855  1.178144e-07
MIR6774        354.744262       -0.256926  0.751899 -0.749471  4.535735e-01
RMDN1       232522.600915        7.008748  0.562418  9.025132  1.794786e-19
...                   ...             ...       ...       ...           ...
LCNL1         7716.598696       -0.046578  0.382147 -0.013729  9.890459e-01
ENDOD1      380237.836713        0.601508  0.849065 -1.517053  1.292534e-01
ZNF335      239513.179368        0.864328  0.705034 -1.294724  1.954154e-01
PGF          55252.738002        1.369149  0.804415  0.105786  9.157523e-01
PKNOX2       14538.976871       -0.091686  0.606023 -0.850873  3.948401e-01

                    padj
ZNF542P     1.297652e-04
RFX7        8.867949e-01
GEMIN7-AS1  1.354865e-06
MIR6774     7.125543e-01
RMDN1       5.396251e-18
...                  ...
LCNL1       9.999940e-01
ENDOD1      3.139191e-01
ZNF335      4.251604e-01
PGF         9.884825e-01
PKNOX2      6.592998e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R8.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R8.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R8.csv
============================================================
[INFO] (20/160) sim_S10_G5000_CNstrong_R9.pkl
[INFO] Running analysis for S=10, G=5000, CN=strong, R=9
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.85 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.14 seconds.

Fitting LFCs...
... done in 0.59 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 313 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.22 seconds.

Fitting MAP LFCs...
... done in 1.09 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
VN1R81P      1.795099e+03       -0.299167  0.433397 -0.863568  3.878251e-01
MIR7844      2.561908e+03       -2.169076  0.669840 -3.821298  1.327509e-04
CFAP69       3.845652e+04       -1.514188  0.637574 -2.988300  2.805339e-03
BCAR3        2.085355e+05        0.506959  0.389746  1.522917  1.277796e-01
CEP57        2.149787e+05       -0.300862  0.226794 -1.429279  1.529240e-01
...                   ...             ...       ...       ...           ...
ARPC4-TTLL3  1.284415e+06        1.725238  0.368360  4.986416  6.150975e-07
SRGAP3-AS4   1.331268e+02       -1.298868  0.489798 -3.116231  1.831788e-03
GPR45        3.298975e+02        0.133902  0.833705  0.358855  7.197039e-01
SULT4A1      5.129650e+03       -0.052117  0.714029 -0.148533  8.819225e-01
GTSE1-DT     2.623577e+03        0.071363  0.332827  0.240568  8.098902e-01

                 padj
VN1R81P      0.653244
MIR7844      0.001000
CFAP69       0.014776
BCAR3        0.325448
CEP57        0.369901
...               ...
ARPC4-TTLL3  0.000008
SRGAP3-AS4   0.010152
GPR45        0.882035
SULT4A1      0.955641
GTSE1-DT     0.924424

[4988 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.89 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.18 seconds.

Fitting LFCs...
... done in 1.22 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 309 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 309)
Number of True values in replace_mask: 527
replacement_counts_trimmed shape: (20, 309)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 0.81 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
VN1R81P      1.795099e+03       -0.549567  0.443464 -1.540696  0.123391
MIR7844      2.561908e+03       -2.406730  0.667865 -4.194087  0.000027
CFAP69       3.845652e+04       -0.289268  0.574371 -3.524821  0.000424
BCAR3        2.085355e+05        2.061133  0.309357  1.522916  0.127780
CEP57        2.149787e+05        1.552539  0.254771 -1.429277  0.152925
...                   ...             ...       ...       ...       ...
ARPC4-TTLL3  1.284415e+06        2.826323  0.188631  4.078168  0.000045
SRGAP3-AS4   1.331268e+02       -1.584355  0.492971 -3.687531  0.000226
GPR45        3.298975e+02        0.125600  0.815178  0.358839  0.719716
SULT4A1      5.129650e+03       -0.074437  0.712156 -0.148532  0.881923
GTSE1-DT     2.623577e+03        0.086947  0.331905  0.240553  0.809901

                 padj
VN1R81P      0.298918
MIR7844      0.000191
CFAP69       0.002280
BCAR3        0.306075
CEP57        0.350546
...               ...
ARPC4-TTLL3  0.000303
SRGAP3-AS4   0.001309
GPR45        0.896589
SULT4A1      0.978855
GTSE1-DT     0.943655

[4988 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNstrong_R9.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNstrong_R9.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNstrong_R9.csv
============================================================
[INFO] (21/160) sim_S10_G5000_CNweak_R1.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=1
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.76 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.12 seconds.

Fitting LFCs...
... done in 0.59 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 317 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.23 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.69 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
JMJD6       2.437122e+05   -2.201180e-06  0.001529   1.230191  2.186258e-01
PLA2G12AP1  4.151973e+03   -6.228791e-07  0.001420  -0.271067  7.863392e-01
VEGFA       3.520370e+06    3.470261e+00  1.057006   3.548515  3.874104e-04
RHO         2.612536e+02    5.490404e-07  0.002158  -0.283695  7.766438e-01
TK1         2.125112e+05   -2.307416e-06  0.001181  -1.482618  1.381759e-01
...                  ...             ...       ...        ...           ...
SCN9A       1.031386e+04    2.544111e-06  0.001408  -0.213250  8.311317e-01
BCL2L2      6.496743e+05    4.455284e-06  0.003188   2.673274  7.511498e-03
NADSYN1     5.011078e+05    1.268680e-05  0.001663   2.011754  4.424587e-02
CUL7        1.587945e+06    2.936557e+00  0.265777  11.228492  2.954781e-29
POGK        3.293767e+05    1.909581e-04  0.001356  -0.904955  3.654893e-01

                    padj
JMJD6       4.650224e-01
PLA2G12AP1  9.155908e-01
VEGFA       3.020591e-03
RHO         9.097307e-01
TK1         3.478992e-01
...                  ...
SCN9A       9.346516e-01
BCL2L2      3.801458e-02
NADSYN1     1.545045e-01
CUL7        9.829571e-27
POGK        6.281695e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.87 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.14 seconds.

Fitting LFCs...
... done in 0.79 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 317 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 317)
Number of True values in replace_mask: 539
replacement_counts_trimmed shape: (20, 317)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 0.97 seconds.

R callback write-console: Removing 1 features with NA screening hypothesis p-values.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
JMJD6       2.437122e+05        1.215016  0.258255  -1.466483  1.425168e-01
PLA2G12AP1  4.151973e+03       -0.068324  0.331737  -0.271057  7.863472e-01
VEGFA       3.520370e+06        3.783492  0.158543   2.864169  4.181043e-03
RHO         1.890927e+02        1.454861  0.047119 -10.965300  5.611395e-28
TK1         2.125112e+05        1.290989  0.860122  -0.652312  5.141999e-01
...                  ...             ...       ...        ...           ...
SCN9A       1.031386e+04       -0.043879  0.575568  -0.213249  8.311324e-01
BCL2L2      6.496743e+05        3.652644  0.394714   2.301226  2.137889e-02
NADSYN1     5.011078e+05        1.730695  0.230783   0.095528  9.238952e-01
CUL7        1.587945e+06        3.757239  0.119446   9.551165  1.282465e-21
POGK        3.293767e+05        0.948161  0.517307  -1.915123  5.547676e-02

                    padj
JMJD6       3.398946e-01
PLA2G12AP1  9.380522e-01
VEGFA       1.854525e-02
RHO         2.204792e-26
TK1         7.626852e-01
...                  ...
SCN9A       9.607020e-01
BCL2L2      7.591740e-02
NADSYN1     9.999975e-01
CUL7        4.383219e-20
POGK        1.675720e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R1.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R1.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R1.csv
============================================================
[INFO] (22/160) sim_S10_G5000_CNweak_R10.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=10
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.83 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 0.68 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 295 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.12 seconds.

Running Wald tests...
... done in 0.72 seconds.

Fitting MAP LFCs...
... done in 1.04 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CCL18     39817.919199       -0.192061  0.764818 -0.561870  0.574205  0.809165
TMPRSS3   64779.295300        0.220144  0.853435  0.617558  0.536867  0.783964
NPC2     729736.450199       -0.111967  0.377279 -0.405614  0.685026  0.871012
GZMH      10102.590690       -0.180771  0.637061 -0.491037  0.623400  0.836899
OTOGL      3401.484563       -2.106977  0.854876 -3.241052  0.001191  0.008277
...                ...             ...       ...       ...       ...       ...
CCDC196     173.190090        1.074309  1.675057  0.777714  0.436738  0.710271
PBOV1       197.844741       -0.272483  0.451219 -0.784729  0.432612  0.709473
CDHR2       981.756819        0.659243  2.690693  1.037796  0.299365  0.586638
FAM215A     220.285513        0.871682  0.498071  2.202643  0.027620  0.112117
POLD3     19685.269125        0.001927  0.921183 -0.021758  0.982641  0.992573

[4997 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.99 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.26 seconds.

Fitting LFCs...
... done in 0.84 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 294 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 294)
Number of True values in replace_mask: 499
replacement_counts_trimmed shape: (20, 294)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.17 seconds.

Fitting MAP LFCs...
... done in 1.02 seconds.

R callback write-console: Removing 1 features with NA screening hypothesis p-values.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
CCL18     39817.919199        0.634993  0.872985 -0.574551  5.655948e-01
TMPRSS3   64779.295300        1.703861  0.870301  0.248091  8.040643e-01
NPC2     729736.450199        1.669901  0.279711 -0.405607  6.850314e-01
GZMH      10102.590690       -0.224653  0.640996 -0.491036  6.234011e-01
OTOGL      3401.484563       -2.454377  0.836351 -3.670076  2.424788e-04
...                ...             ...       ...       ...           ...
CCDC196      82.872012        2.975468  0.088143  0.015963  9.872643e-01
PBOV1       197.844741       -0.671138  0.476295 -1.826472  6.777919e-02
CDHR2       503.363029        3.739011  0.038101 -8.945738  3.694722e-19
FAM215A     220.285513        0.859957  0.499209  2.201756  2.768254e-02
POLD3     19685.269125        0.565186  1.022033 -0.295406  7.676837e-01

                 padj
CCL18    8.050460e-01
TMPRSS3  9.416561e-01
NPC2     8.795725e-01
GZMH     8.425993e-01
OTOGL    1.661761e-03
...               ...
CCDC196  9.999949e-01
PBOV1    2.019230e-01
CDHR2    2.006395e-17
FAM215A  9.935487e-02
POLD3    9.241802e-01

[4997 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R10.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R10.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R10.csv
============================================================
[INFO] (23/160) sim_S10_G5000_CNweak_R11.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=11
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.85 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.17 seconds.

Fitting LFCs...
... done in 0.59 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 306 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.23 seconds.

Fitting MAP LFCs...
... done in 1.11 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat    pvalue  \
OSGEPL1-AS1    2050.505180        0.319677  0.283375  1.237347  0.215958
CPLANE1      175277.182006        0.653814  0.397772  1.958582  0.050162
NPEPL1       302337.352761       -0.179263  0.754275 -0.490359  0.623880
ZNF467       328227.828398        2.203084  0.649521  3.927715  0.000086
ABHD17A      370589.812238        0.275783  0.293591  0.985924  0.324171
...                    ...             ...       ...       ...       ...
TGDS          71815.475595        0.257579  0.454014  0.712533  0.476135
NPAP1           292.568387       -0.295470  0.576446 -0.757675  0.448646
NOD1         298928.367433        0.937157  0.692918  1.926025  0.054101
NT5C1B         4689.076261        1.086248  0.417978  2.977139  0.002910
NHP2P2          743.857362        0.628707  0.260898  2.588461  0.009641

                 padj
OSGEPL1-AS1  0.469301
CPLANE1      0.169693
NPEPL1       0.823535
ZNF467       0.000739
ABHD17A      0.595492
...               ...
TGDS         0.721429
NPAP1        0.701501
NOD1         0.179365
NT5C1B       0.016885
NHP2P2       0.045393

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.89 seconds.

Fitting dispersion trend curve...
... done in 0.15 seconds.

Fitting MAP dispersions...
... done in 1.30 seconds.

Fitting LFCs...
... done in 0.80 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 308 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 308)
Number of True values in replace_mask: 545
replacement_counts_trimmed shape: (20, 308)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 1.27 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat    pvalue  \
OSGEPL1-AS1    2050.505180        0.338149  0.283292  1.237207  0.216010
CPLANE1      175277.182006        1.678763  0.336199  0.581395  0.560974
NPEPL1       302337.352761        1.069381  0.637114 -1.166791  0.243295
ZNF467       328227.828398        3.077117  0.439586  3.210502  0.001325
ABHD17A      370589.812238        2.048340  0.252546  0.985923  0.324171
...                    ...             ...       ...       ...       ...
TGDS          71815.475595        1.598374  0.467362  0.712532  0.476135
NPAP1           292.568387       -0.280827  0.567134 -0.757556  0.448717
NOD1         298928.367433        1.992892  0.409409  0.776896  0.437220
NT5C1B         4689.076261        0.794211  0.418371  2.101674  0.035582
NHP2P2          743.857362        0.018860  0.255370  0.083575  0.933395

                 padj
OSGEPL1-AS1  0.454514
CPLANE1      0.802932
NPEPL1       0.492411
ZNF467       0.006776
ABHD17A      0.589842
...               ...
TGDS         0.730523
NPAP1        0.709840
NOD1         0.702791
NT5C1B       0.116375
NHP2P2       0.999988

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R11.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R11.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R11.csv
============================================================
[INFO] (24/160) sim_S10_G5000_CNweak_R12.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=12
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.83 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.10 seconds.

Fitting LFCs...
... done in 0.58 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 315 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.23 seconds.

Fitting MAP LFCs...
... done in 1.09 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
PCGF1     76295.003032       -0.698194  0.334714 -2.375835  0.017509  0.075216
NPAS3      9277.702037       -0.378481  0.627027 -0.964082  0.335005  0.600985
USP8     292949.076028       -0.120163  0.194086 -0.686330  0.492505  0.734327
YRDC     113024.958401       -0.103815  0.314818 -0.387016  0.698744  0.865454
OSR2     158570.232636        0.182343  0.545096  0.470131  0.638262  0.832957
...                ...             ...       ...       ...       ...       ...
SLC10A7   58970.887898       -0.185282  0.457405 -0.540400  0.588921  0.799167
MYOM1     56030.930413        0.353037  1.012723  1.030625  0.302717  0.568406
ZNF644   203789.483924        0.103773  0.334600  0.343347  0.731338  0.882150
FABP9       230.052414       -0.506941  0.450592 -1.424421  0.154325  0.377045
DCAF1    120978.046929       -0.076722  0.818515 -3.650208  0.000262  0.002119

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.87 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.12 seconds.

Fitting LFCs...
... done in 0.81 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 313 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 313)
Number of True values in replace_mask: 531
replacement_counts_trimmed shape: (20, 313)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.20 seconds.

Fitting MAP LFCs...
... done in 0.97 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE        stat    pvalue  \
PCGF1     76295.003032        0.818991  0.353649   -3.143592  0.001669
NPAS3      9277.702037       -0.384719  0.623458   -1.008657  0.313139
USP8     292949.076028        2.495454  0.214825   -0.686329  0.492506
YRDC     113024.958401        1.331815  0.346799   -0.387015  0.698745
OSR2     158570.232636        2.450840  0.523377    1.876787  0.060547
...                ...             ...       ...         ...       ...
SLC10A7   58970.887898        1.120793  0.514193   -0.540399  0.588922
MYOM1     56030.930413        2.249965  1.141728    1.030625  0.302717
ZNF644   203789.483924        1.758200  0.318656    0.343346  0.731338
FABP9       230.052414       -1.231426  0.479759   -3.060663  0.002208
DCAF1     25713.708334       -0.410058  0.005175 -118.125751  0.000000

             padj
PCGF1    0.008584
NPAS3    0.574607
USP8     0.741844
YRDC     0.885816
OSR2     0.174910
...           ...
SLC10A7  0.815468
MYOM1    0.564159
ZNF644   0.901566
FABP9    0.011018
DCAF1    0.000000

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R12.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R12.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R12.csv
============================================================
[INFO] (25/160) sim_S10_G5000_CNweak_R13.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=13
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.94 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.14 seconds.

Fitting LFCs...
... done in 0.81 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 313 outlier genes.

Fitting dispersions...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.11 seconds.

Fitting LFCs...
... done in 0.15 seconds.

Running Wald tests...
... done in 0.26 seconds.

Fitting MAP LFCs...
... done in 1.12 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
EPDR1       74375.883233       -0.686715  0.517911 -1.778077  7.539120e-02
INTS12     141198.449248        0.261059  0.216442  1.249720  2.114019e-01
LINC00943     684.921301        0.064084  0.729353  0.169320  8.655447e-01
PCDH9       25823.930376        0.134954  0.775660  0.368316  7.126375e-01
LRGUK       24367.487290        1.988092  0.767456  3.252184  1.145217e-03
...                  ...             ...       ...       ...           ...
MIR155HG     6607.529467       -0.136908  0.289545 -0.530984  5.954297e-01
TNFAIP3    241834.800162       -0.666564  0.401624 -1.993339  4.622439e-02
CRYBG3     236806.876654       -1.948734  0.388263 -5.445198  5.174769e-08
ATXN3      145929.472379        0.109321  0.592113  0.279113  7.801581e-01
NCR1          571.535113       -0.769155  0.204610 -3.933168  8.383371e-05

                   padj
EPDR1      2.320410e-01
INTS12     4.596054e-01
LINC00943  9.495869e-01
PCDH9      8.783261e-01
LRGUK      7.925858e-03
...                 ...
MIR155HG   8.118290e-01
TNFAIP3    1.628844e-01
CRYBG3     9.841937e-07
ATXN3      9.129938e-01
NCR1       7.779206e-04

[4983 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.77 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.16 seconds.

Fitting LFCs...
... done in 0.80 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 311 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 311)
Number of True values in replace_mask: 538
replacement_counts_trimmed shape: (20, 311)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.20 seconds.

Fitting MAP LFCs...
... done in 1.10 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
EPDR1       74375.883233        0.458663  0.498304 -2.539473  1.110197e-02
INTS12     141198.449248        2.230645  0.243195  1.249717  2.114031e-01
LINC00943     684.921301        0.060624  0.714584  0.169315  8.655485e-01
PCDH9       25823.930376        1.136363  1.076340  0.368316  7.126377e-01
LRGUK       24367.487290        2.831433  0.750139  3.015427  2.566179e-03
...                  ...             ...       ...       ...           ...
MIR155HG     6607.529467       -0.492990  0.294326 -1.822268  6.841426e-02
TNFAIP3    241834.800162        0.949168  0.357517 -2.934213  3.343949e-03
CRYBG3     236806.876654        0.497561  0.389030 -6.169941  6.831565e-10
ATXN3      145929.472379        1.557390  0.633447  0.279112  7.801591e-01
NCR1          571.535113       -1.318078  0.206001 -6.578625  4.748192e-11

                   padj
EPDR1      4.439896e-02
INTS12     4.452332e-01
LINC00943  9.702941e-01
PCDH9      8.953619e-01
LRGUK      1.245109e-02
...                 ...
MIR155HG   1.955871e-01
TNFAIP3    1.563124e-02
CRYBG3     1.119792e-08
ATXN3      9.295870e-01
NCR1       8.730717e-10

[4983 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R13.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R13.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R13.csv
============================================================
[INFO] (26/160) sim_S10_G5000_CNweak_R14.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=14
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.81 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.13 seconds.

Fitting LFCs...
... done in 0.62 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 290 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.26 seconds.

Fitting MAP LFCs...
... done in 1.12 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
MIA3       4.954694e+05        0.050233  0.400556  0.127461  0.898576
CTNNB1     2.202420e+06       -0.349268  0.350255 -1.182901  0.236848
DDX10      1.620485e+05        0.413505  0.273342  1.632284  0.102620
RNU6-322P  2.719473e+02       -0.401049  0.657672 -0.999835  0.317390
RN7SL130P  1.059081e+03       -0.171945  0.742259 -0.479345  0.631693
...                 ...             ...       ...       ...       ...
GPR137     2.207045e+05       -0.558589  0.499378 -1.482391  0.138236
DDX52      1.294412e+05       -1.293371  0.443240 -3.369226  0.000754
TOR1AIP1   2.784691e+05       -0.820893  0.379007 -2.501203  0.012377
ACTBP11    1.075493e+04       -0.298381  0.247932 -1.305775  0.191629
RPS3AP49   5.190343e+03       -0.558145  0.776142 -1.329936  0.183539

               padj
MIA3       0.960789
CTNNB1     0.499112
DDX10      0.290333
RNU6-322P  0.595615
RN7SL130P  0.840012
...             ...
GPR137     0.354693
DDX52      0.005215
TOR1AIP1   0.056536
ACTBP11    0.440076
RPS3AP49   0.425588

[4988 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.88 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.15 seconds.

Fitting LFCs...
... done in 0.81 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 293 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 293)
Number of True values in replace_mask: 505
replacement_counts_trimmed shape: (20, 293)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 0.97 seconds.

R callback write-console: Removing 1 features with NA screening hypothesis p-values.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
MIA3       4.954694e+05        1.139831  0.264703 -1.956232  0.050438
CTNNB1     2.202420e+06        1.723412  0.183558 -1.182901  0.236848
DDX10      1.620485e+05        1.854298  0.288435  1.632281  0.102620
RNU6-322P  2.719473e+02       -0.701224  0.724533 -1.666496  0.095615
RN7SL130P  1.059081e+03       -0.189505  0.725995 -0.479336  0.631699
...                 ...             ...       ...       ...       ...
GPR137     2.207045e+05        0.990148  0.408590 -2.190343  0.028499
DDX52      1.294412e+05        0.474774  0.422803 -4.078705  0.000045
TOR1AIP1   2.784691e+05        0.594682  0.330268 -4.464905  0.000008
ACTBP11    1.075493e+04       -0.782677  0.255802 -3.700538  0.000215
RPS3AP49   5.190343e+03       -0.440297  0.732385 -1.329929  0.183542

               padj
MIA3       0.153375
CTNNB1     0.480641
DDX10      0.264206
RNU6-322P  0.250436
RN7SL130P  0.842998
...             ...
GPR137     0.094923
DDX52      0.000323
TOR1AIP1   0.000065
ACTBP11    0.001290
RPS3AP49   0.403226

[4988 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R14.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R14.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R14.csv
============================================================
[INFO] (27/160) sim_S10_G5000_CNweak_R15.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=15
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.37 seconds.

Fitting dispersion trend curve...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.89 seconds.

Fitting LFCs...
... done in 0.58 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 268 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.22 seconds.

Fitting MAP LFCs...
... done in 1.09 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
BBIP1       237572.377319        0.195234  0.581363  0.459254  0.646052
DMWD        310825.516546        0.896020  0.245151  3.828715  0.000129
TMEM163      24110.054755        0.134355  0.631991  0.344508  0.730464
RPTOR       293324.253903        0.393056  0.401426  1.173837  0.240460
CRYGS        41756.343276        1.118341  0.422108  3.048349  0.002301
...                   ...             ...       ...       ...       ...
VWA8        128494.258750        0.078928  0.438746  0.220344  0.825604
FGB          26872.560034        0.385606  0.765436  0.966893  0.333597
THAP6        87205.818338       -0.450421  0.831225 -1.215189  0.224294
HNRNPA3P13      67.987006        0.734690  1.377861  2.122894  0.033763
GUSBP5        3161.290941        0.040450  0.410079  0.118667  0.905539

                padj
BBIP1       0.838707
DMWD        0.001129
TMEM163     0.883969
RPTOR       0.499025
CRYGS       0.014034
...              ...
VWA8        0.928083
FGB         0.603496
THAP6       0.479025
HNRNPA3P13  0.128976
GUSBP5      0.960994

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.89 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.13 seconds.

Fitting LFCs...
... done in 0.78 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 267 outlier genes.

Fitting dispersions...
... done in 0.04 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...

replace_mask before filtering: (20, 267)
Number of True values in replace_mask: 435
replacement_counts_trimmed shape: (20, 267)

... done in 0.05 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 0.95 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
BBIP1       237572.377319        1.765285  0.527838  0.459254  0.646052
DMWD        310825.516546        2.069138  0.235079  2.128994  0.033255
TMEM163      24110.054755        1.096190  0.790598  0.344507  0.730465
RPTOR       293324.253903        1.487332  0.306440 -0.470445  0.638037
CRYGS        41756.343276        1.514059  0.436881  1.585216  0.112917
...                   ...             ...       ...       ...       ...
VWA8        128494.258750        1.653516  0.417345  0.220343  0.825604
FGB          26872.560034        1.650024  0.935997  0.966892  0.333598
THAP6        87205.818338        0.135408  0.665139 -1.365151  0.172206
HNRNPA3P13      39.877582        2.393646  0.087026 -0.037377  0.970185
GUSBP5        3161.290941        0.040378  0.406793  0.118664  0.905542

                padj
BBIP1       0.857677
DMWD        0.111929
TMEM163     0.910700
RPTOR       0.852253
CRYGS       0.291134
...              ...
VWA8        0.957224
FGB         0.605035
THAP6       0.392657
HNRNPA3P13  0.999986
GUSBP5      0.990269

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R15.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R15.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R15.csv
============================================================
[INFO] (28/160) sim_S10_G5000_CNweak_R16.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=16
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.88 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.13 seconds.

Fitting LFCs...
... done in 0.61 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 331 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.23 seconds.

Fitting MAP LFCs...
... done in 1.09 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
TMEM167A   438516.278135       -0.232197  0.243209 -1.040391  0.298158
LINC02021    3674.736910       -0.066381  0.493236 -0.188652  0.850365
FAAP100    243761.966835       -0.570107  0.329878 -1.998932  0.045616
MYOM2       21209.849752        0.099560  0.710767  0.253964  0.799523
FOXN3-AS1   12982.847951        0.014825  0.528319  0.032821  0.973817
...                  ...             ...       ...       ...       ...
IPO8P1      15037.356272        0.438436  0.374873  1.374779  0.169200
ATP6V1B1   102408.832741        0.171354  0.876636  0.493149  0.621908
KCNH3        6649.783879       -0.996066  0.239827 -4.384897  0.000012
KRTAP1-5      147.815736       -0.444246  0.395180 -1.353309  0.175957
AGA        106119.134457        0.182191  0.326225  0.620841  0.534704

               padj
TMEM167A   0.578573
LINC02021  0.946850
FAAP100    0.165150
MYOM2      0.927384
FOXN3-AS1  0.989369
...             ...
IPO8P1     0.403315
ATP6V1B1   0.837209
KCNH3      0.000136
KRTAP1-5   0.414287
AGA        0.779669

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.88 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.12 seconds.

Fitting LFCs...
... done in 1.12 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 331 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 331)
Number of True values in replace_mask: 555
replacement_counts_trimmed shape: (20, 331)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 0.90 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
TMEM167A   438516.278135        1.976910  0.218699 -1.040390  2.981585e-01
LINC02021    3674.736910       -0.113780  0.487695 -0.341948  7.323897e-01
FAAP100    243761.966835        2.198498  0.334877  0.592947  5.532164e-01
MYOM2       21209.849752        0.939475  0.913988  0.253964  7.995235e-01
FOXN3-AS1   12982.847951       -0.133529  0.522171  0.032821  9.738175e-01
...                  ...             ...       ...       ...           ...
IPO8P1      15037.356272        1.496615  0.403207  3.621669  2.927090e-04
ATP6V1B1   102408.832741        1.662073  0.997109  0.267677  7.889479e-01
KCNH3        6649.783879       -1.274109  0.240622 -5.689373  1.275064e-08
KRTAP1-5      147.815736       -0.648523  0.403210 -1.951960  5.094297e-02
AGA        106119.134457        1.581257  0.349238  0.620840  5.347051e-01

                   padj
TMEM167A   5.668875e-01
LINC02021  9.075739e-01
FAAP100    7.993137e-01
MYOM2      9.454922e-01
FOXN3-AS1  9.999642e-01
...                 ...
IPO8P1     1.785239e-03
ATP6V1B1   9.400671e-01
KCNH3      1.723928e-07
KRTAP1-5   1.568855e-01
AGA        7.836362e-01

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R16.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R16.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R16.csv
============================================================
[INFO] (29/160) sim_S10_G5000_CNweak_R17.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=17
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.81 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.10 seconds.

Fitting LFCs...
... done in 0.60 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 274 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.22 seconds.

Fitting MAP LFCs...
... done in 1.09 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
DNAJB14  2.559034e+05        0.303900  0.247710  1.305437  0.191744  0.432842
GAL3ST3  2.884465e+01       -0.208264  0.806690 -2.446011  0.014445  0.065151
KCTD3    6.852232e+05       -0.669216  0.507917 -1.730834  0.083481  0.246640
SFRP2    1.616304e+06        0.287441  0.658451  0.619857  0.535352  0.778169
WDR1     1.558514e+06        0.077709  0.272810  0.205313  0.837327  0.931825
...               ...             ...       ...       ...       ...       ...
TDG      1.157591e+05        0.337449  0.735723  0.819809  0.412325  0.679676
DBN1     5.417105e+05       -1.035768  0.311621 -3.571240  0.000355  0.002648
SIGLEC1  1.140759e+05       -0.695088  1.223986 -2.023943  0.042976  0.151424
ENGASE   4.666433e+05        1.145765  0.335880  3.675112  0.000238  0.001872
OR7E2P   3.406171e+02        0.332883  0.501255  0.893053  0.371829  0.642464

[4993 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.83 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.13 seconds.

Fitting LFCs...
... done in 0.76 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 271 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...

replace_mask before filtering: (20, 271)
Number of True values in replace_mask: 469
replacement_counts_trimmed shape: (20, 271)

... done in 0.05 seconds.

Running Wald tests...
... done in 0.17 seconds.

Fitting MAP LFCs...
... done in 0.96 seconds.

R callback write-console: Removing 3 features with NA screening hypothesis p-values.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
DNAJB14  2.559034e+05        2.225818  0.238549  1.305436  0.191745  0.423157
GAL3ST3  0.000000e+00       -0.243764  0.781081  0.000000       NaN       NaN
KCTD3    6.852232e+05        0.787895  0.376621 -3.191567  0.001415  0.007536
SFRP2    1.616304e+06        2.104337  0.255030  0.619857  0.535352  0.781799
WDR1     1.558514e+06        2.180630  0.158478  0.205313  0.837327  0.952493
...               ...             ...       ...       ...       ...       ...
TDG      1.157591e+05        1.859779  0.794360  0.819809  0.412325  0.676365
DBN1     5.417105e+05        0.972356  0.266920 -4.704054  0.000003  0.000025
SIGLEC1  1.140759e+05        0.496227  0.834671 -1.439261  0.150077  0.356495
ENGASE   4.666433e+05        2.023416  0.225212  1.449007  0.147336  0.352110
OR7E2P   3.406171e+02        0.320393  0.497233  0.892879  0.371922  0.638861

[4993 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R17.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R17.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R17.csv
============================================================
[INFO] (30/160) sim_S10_G5000_CNweak_R18.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=18
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.83 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.20 seconds.

Fitting LFCs...
... done in 0.59 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 298 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.24 seconds.

Fitting MAP LFCs...
... done in 1.37 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
LINC02766  8.050670e+02        0.241423  1.059866  0.765836  4.437738e-01
SLC25A48   5.244069e+03       -1.295145  1.568140 -2.289330  2.206018e-02
TYSND1     1.523628e+05        0.641092  0.366934  1.995473  4.599129e-02
RAD51D     9.816831e+04        0.033852  0.338150  0.100952  9.195887e-01
SIGLEC5    9.976696e+03        0.181225  0.431033  0.524581  5.998748e-01
...                 ...             ...       ...       ...           ...
ARLNC1     1.893465e+02       -0.003145  0.813502 -0.980891  3.266464e-01
CXCL9      1.275064e+05        0.620734  1.096425  1.502125  1.330647e-01
AP2A1      1.748144e+06        0.587620  0.795066  1.599858  1.096301e-01
RFC2       5.244370e+05        2.306771  0.322624  7.425037  1.127484e-13
QRICH1     3.636989e+05       -0.225852  0.414236 -0.690536  4.898574e-01

                   padj
LINC02766  6.980382e-01
SLC25A48   9.114434e-02
TYSND1     1.618893e-01
RAD51D     9.655227e-01
SIGLEC5    8.140226e-01
...                 ...
ARLNC1     5.956494e-01
CXCL9      3.542006e-01
AP2A1      3.067505e-01
RFC2       4.430924e-12
QRICH1     7.345225e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.87 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.13 seconds.

Fitting LFCs...
... done in 0.79 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 296 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 296)
Number of True values in replace_mask: 507
replacement_counts_trimmed shape: (20, 296)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 0.98 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
LINC02766  8.050670e+02        0.215872  1.029407  0.765827  4.437794e-01
SLC25A48   5.244069e+03       -0.790599  1.232229 -2.289318  2.206091e-02
TYSND1     1.523628e+05        2.092796  0.326906  1.995471  4.599150e-02
RAD51D     9.816831e+04        1.380345  0.361971  0.100952  9.195888e-01
SIGLEC5    9.976696e+03       -0.308434  0.430531 -0.679030  4.971186e-01
...                 ...             ...       ...       ...           ...
ARLNC1     1.606719e+02       -0.009056  0.044120 -9.946722  2.606257e-23
CXCL9      1.275064e+05        2.512205  0.820580  1.207814  2.271188e-01
AP2A1      1.748144e+06        2.195385  0.211329  0.793332  4.275842e-01
RFC2       5.244370e+05        3.176768  0.191746  6.123545  9.151576e-10
QRICH1     3.636989e+05        1.445011  0.370204 -0.690535  4.898575e-01

                   padj
LINC02766  7.009186e-01
SLC25A48   7.815700e-02
TYSND1     1.435545e-01
RAD51D     9.900455e-01
SIGLEC5    7.467893e-01
...                 ...
ARLNC1     9.929642e-22
CXCL9      4.684090e-01
AP2A1      6.875234e-01
RFC2       1.388314e-08
QRICH1     7.403913e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R18.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R18.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R18.csv
============================================================
[INFO] (31/160) sim_S10_G5000_CNweak_R19.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=19
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.83 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.13 seconds.

Fitting LFCs...
... done in 0.59 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 277 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.22 seconds.

Fitting MAP LFCs...
... done in 1.09 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
NOTCH1   542875.206367       -0.261834  0.463448 -0.753767  4.509890e-01
TMEM30A  683487.257534       -0.642442  0.330239 -2.218953  2.648991e-02
ZIC4       9297.596784        0.105746  0.875178  0.301807  7.627990e-01
ZBTB24   437068.456841        3.316912  0.357146  9.487380  2.369130e-21
SVIP     402089.417682        1.380421  0.487003  3.254826  1.134618e-03
...                ...             ...       ...       ...           ...
ZHX2     313929.488339        0.348143  0.804710  0.940115  3.471584e-01
HOXD3     18828.767434       -0.609007  0.770689 -1.409196  1.587772e-01
RARS2    220562.335382        0.095271  0.474444  0.253773  7.996708e-01
PRAL     325373.824243       -0.135273  0.148546 -0.918342  3.584401e-01
GRIK1     10823.199596        0.431210  0.523506  1.108506  2.676432e-01

                 padj
NOTCH1   7.014916e-01
TMEM30A  1.035741e-01
ZIC4     9.022461e-01
ZBTB24   3.379733e-19
SVIP     7.434577e-03
...               ...
ZHX2     6.155405e-01
HOXD3    3.846552e-01
RARS2    9.190071e-01
PRAL     6.238032e-01
GRIK1    5.290351e-01

[4993 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.88 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.14 seconds.

Fitting LFCs...
... done in 0.79 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 279 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 279)
Number of True values in replace_mask: 465
replacement_counts_trimmed shape: (20, 279)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 1.28 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
NOTCH1   542875.206367        1.508062  0.347244 -0.774708  4.385121e-01
TMEM30A  683487.257534        1.085432  0.229973 -3.548720  3.871089e-04
ZIC4       9297.596784       -0.076237  0.803789 -0.112745  9.102325e-01
ZBTB24   437068.456841        3.996567  0.205756  8.503938  1.832651e-17
SVIP     402089.417682        2.443811  0.344025  2.457575  1.398788e-02
...                ...             ...       ...       ...           ...
ZHX2     313929.488339        1.812660  0.524931  0.240371  8.100427e-01
HOXD3     18828.767434        0.298130  0.647741 -1.409194  1.587778e-01
RARS2    220562.335382        1.614594  0.454936  0.253773  7.996708e-01
PRAL     325373.824243        3.194500  0.219469 -0.918339  3.584413e-01
GRIK1     10823.199596        0.240131  0.511894  0.364726  7.153161e-01

                 padj
NOTCH1   6.991338e-01
TMEM30A  2.306486e-03
ZIC4     9.918793e-01
ZBTB24   6.059884e-16
SVIP     5.490428e-02
...               ...
ZHX2     9.456496e-01
HOXD3    3.728127e-01
RARS2    9.393400e-01
PRAL     6.248944e-01
GRIK1    8.955801e-01

[4993 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R19.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R19.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R19.csv
============================================================
[INFO] (32/160) sim_S10_G5000_CNweak_R2.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=2
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.60 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.12 seconds.

Fitting LFCs...
... done in 0.61 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 271 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.23 seconds.

Fitting MAP LFCs...
... done in 1.17 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SPHKAP     1.858776e+03       -0.049863  0.926364 -0.245560  0.806023
P2RX3      5.560215e+00       -0.702365  1.009608  0.628729  0.529527
SRSF5      2.492896e+06       -0.212264  0.409461 -0.338659  0.734867
MFSD2A     8.102578e+04        0.835808  0.600572  1.894072  0.058215
SMOC2      4.419315e+05       -0.220932  0.561300 -0.587449  0.556902
...                 ...             ...       ...       ...       ...
RNU6-395P  2.797807e+03        0.354447  1.069398  1.010731  0.312145
ZNF33A     1.475252e+06        2.071605  0.848153  3.146827  0.001651
CHTF18     1.443339e+05       -0.890116  0.537904 -2.162197  0.030603
ZC3H7B     9.378278e+05       -0.268569  0.686183 -0.648856  0.516431
NOX4       5.637546e+04       -0.036915  0.308903 -0.140866  0.887976

               padj
SPHKAP     0.918306
P2RX3      0.766148
SRSF5      0.882794
MFSD2A     0.191680
SMOC2      0.782517
...             ...
RNU6-395P  0.580662
ZNF33A     0.010467
CHTF18     0.117673
ZC3H7B     0.756755
NOX4       0.955972

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.89 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.14 seconds.

Fitting LFCs...
... done in 0.83 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 269 outlier genes.

Fitting dispersions...
... done in 0.04 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 269)
Number of True values in replace_mask: 467
replacement_counts_trimmed shape: (20, 269)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.20 seconds.

Fitting MAP LFCs...
... done in 1.05 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SPHKAP     1.858776e+03       -0.012839  0.878537 -0.245560  0.806023
P2RX3      3.730951e+00       -2.147402  0.292305  0.077080  0.938560
SRSF5      2.492896e+06        1.786762  0.170789 -0.338659  0.734867
MFSD2A     8.102578e+04        2.298371  0.518267  1.894071  0.058216
SMOC2      4.419315e+05        1.510439  0.434078 -0.587449  0.556902
...                 ...             ...       ...       ...       ...
RNU6-395P  2.797807e+03        0.312042  1.045789  1.010726  0.312147
ZNF33A     1.475252e+06        3.382855  0.192989  2.794215  0.005203
CHTF18     1.443339e+05        0.578687  0.472377 -3.167699  0.001537
ZC3H7B     9.378278e+05        1.461899  0.392182 -0.648856  0.516431
NOX4       5.637546e+04        1.353608  0.336485 -0.140865  0.887976

               padj
SPHKAP     0.937576
P2RX3      0.999563
SRSF5      0.898582
MFSD2A     0.168927
SMOC2      0.789855
...             ...
RNU6-395P  0.572978
ZNF33A     0.023122
CHTF18     0.007947
ZC3H7B     0.764386
NOX4       0.978774

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R2.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R2.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R2.csv
============================================================
[INFO] (33/160) sim_S10_G5000_CNweak_R20.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=20
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.31 seconds.

Fitting LFCs...
... done in 0.65 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 309 outlier genes.

Fitting dispersions...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.12 seconds.

Fitting LFCs...
... done in 0.13 seconds.

Running Wald tests...
... done in 0.25 seconds.

Fitting MAP LFCs...
... done in 1.81 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                   baseMean  log2FoldChange     lfcSE      stat        pvalue  \
PRICKLE2-AS2     373.072936        2.535619  1.662434  2.804662  5.036932e-03
HCCAT5           172.677614       -0.948284  1.445572 -2.118484  3.413409e-02
THY1          841390.274985        1.157977  0.926481  2.058501  3.954208e-02
PPARD         186250.610417       -1.504108  0.295978 -5.416778  6.068264e-08
FAM180A        43811.037688        0.646100  0.454102  1.761004  7.823771e-02
...                     ...             ...       ...       ...           ...
MYHAS           2393.277775       -0.214358  0.626737 -0.563061  5.733934e-01
SYCE1L         19759.189807       -0.332944  0.311959 -1.214340  2.246179e-01
SAR1B         259430.684268       -0.155239  0.305951 -0.610556  5.414933e-01
TXNL4B         50424.056959       -0.726502  0.920699 -1.652682  9.839558e-02
HSD17B6        37239.679078        1.181683  0.260043  4.787741  1.686695e-06

                  padj
PRICKLE2-AS2  0.027344
HCCAT5        0.128622
THY1          0.144102
PPARD         0.000001
FAM180A       0.236562
...                ...
MYHAS         0.798175
SYCE1L        0.484487
SAR1B         0.774352
TXNL4B        0.277970
HSD17B6       0.000023

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.87 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.14 seconds.

Fitting LFCs...
... done in 0.83 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 307 outlier genes.

Fitting dispersions...

replace_mask before filtering: (20, 307)
Number of True values in replace_mask: 544
replacement_counts_trimmed shape: (20, 307)

... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.22 seconds.

Fitting LFCs...
... done in 0.14 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.21 seconds.

R callback write-console: Removing 1 features with NA screening hypothesis p-values.

Log2 fold change & Wald test p-value: condition B vs A
                   baseMean  log2FoldChange     lfcSE      stat        pvalue  \
PRICKLE2-AS2     373.072936        2.492321  1.682391  2.804319  5.042298e-03
HCCAT5           172.677614       -0.810468  1.325656 -2.118173  3.416044e-02
THY1          841390.274985        3.004682  0.353172  2.058500  3.954218e-02
PPARD         186250.610417        0.577616  0.301670 -6.577756  4.776025e-11
FAM180A        43811.037688        1.543594  0.481112  1.257724  2.084915e-01
...                     ...             ...       ...       ...           ...
MYHAS           2393.277775       -0.203676  0.615011 -0.563054  5.733984e-01
SYCE1L         19759.189807       -0.441267  0.309656 -1.214344  2.246164e-01
SAR1B         259430.684268        1.564011  0.294065 -0.610565  5.414875e-01
TXNL4B         50424.056959        0.246126  0.666277 -1.652679  9.839627e-02
HSD17B6        37239.679078        1.200547  0.269882  3.582751  3.399942e-04

                      padj
PRICKLE2-AS2  2.257718e-02
HCCAT5        1.142805e-01
THY1          1.289127e-01
PPARD         9.269577e-10
FAM180A       4.494190e-01
...                    ...
MYHAS         8.086262e-01
SYCE1L        4.743380e-01
SAR1B         7.831692e-01
TXNL4B        2.640132e-01
HSD17B6       2.096280e-03

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R20.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R20.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R20.csv
============================================================
[INFO] (34/160) sim_S10_G5000_CNweak_R3.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=3
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.25 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.17 seconds.

Fitting LFCs...
... done in 0.64 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 279 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
... done in 1.17 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SULT2B1   214113.342984        1.995512  1.225206  2.641426  0.008256
MORN2      44860.835570       -1.178473  0.408077 -3.312370  0.000925
PRR7-AS1    1997.147065        0.195272  0.480928  0.537232  0.591107
FMO2      310661.056459       -0.042945  0.578685 -0.099837  0.920474
NFYC      260898.641354       -0.329054  0.238074 -1.493644  0.135269
...                 ...             ...       ...       ...       ...
GAS2        5753.190852       -1.382721  0.487567 -3.314072  0.000919
AGMAT       1108.241645       -0.180940  0.855548 -0.917665  0.358794
LIPT1      31070.155915       -0.260928  0.268126 -1.088291  0.276467
PGPEP1    135822.107490       -1.398333  0.621817 -2.867905  0.004132
ADAMTS15  646723.596073        0.037317  0.919765  0.078558  0.937384

              padj
SULT2B1   0.042054
MORN2     0.006292
PRR7-AS1  0.808553
FMO2      0.963775
NFYC      0.348612
...            ...
GAS2      0.006262
AGMAT     0.631782
LIPT1     0.543123
PGPEP1    0.023229
ADAMTS15  0.970834

[4992 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.92 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.22 seconds.

Fitting LFCs...
... done in 0.81 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 283 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 283)
Number of True values in replace_mask: 476
replacement_counts_trimmed shape: (20, 283)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.17 seconds.

Fitting MAP LFCs...
... done in 0.99 seconds.

R callback write-console: Removing 1 features with NA screening hypothesis p-values.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SULT2B1   214113.342984        3.525154  0.602773  2.345681  0.018992
MORN2      44860.835570        0.440165  0.413807 -3.794724  0.000148
PRR7-AS1    1997.147065        0.016399  0.470544  0.017462  0.986068
FMO2      310661.056459        1.219431  0.422450 -1.049039  0.294160
NFYC      260898.641354        1.704747  0.254002 -1.493642  0.135269
...                 ...             ...       ...       ...       ...
GAS2        5753.190852       -1.865016  0.487248 -4.343031  0.000014
AGMAT        481.158945       -1.114159  0.027956  0.018528  0.985218
LIPT1      31070.155915       -0.416759  0.264592 -1.088283  0.276470
PGPEP1    135822.107490        0.530788  0.531134 -3.493025  0.000478
ADAMTS15  646723.596073        1.834518  0.581832  0.071312  0.943149

              padj
SULT2B1   0.069495
MORN2     0.000954
PRR7-AS1  0.999993
FMO2      0.558233
NFYC      0.334719
...            ...
GAS2      0.000116
AGMAT     0.999993
LIPT1     0.534935
PGPEP1    0.002759
ADAMTS15  0.999993

[4992 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R3.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R3.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R3.csv
============================================================
[INFO] (35/160) sim_S10_G5000_CNweak_R4.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=4
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.85 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.92 seconds.

Fitting LFCs...
... done in 1.22 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 297 outlier genes.

Fitting dispersions...
... done in 0.28 seconds.

Fitting MAP dispersions...
... done in 0.28 seconds.

Fitting LFCs...
... done in 0.17 seconds.

Running Wald tests...
... done in 0.43 seconds.

Fitting MAP LFCs...
... done in 2.70 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
TCP11        2909.919932        0.247650  0.751637  0.634457  0.525783
RNA5SP216   15841.807171        1.444249  0.523628  3.241938  0.001187
EML5        85871.146703        0.319644  0.216461  1.544080  0.122569
TEX19         227.038906        4.579199  1.728545  1.437601  0.150547
PA2G4P5     35611.102578        0.838891  0.256689  3.503122  0.000460
...                  ...             ...       ...       ...       ...
LINC02345    2745.144470        0.532888  1.337806  1.511473  0.130668
DOCK1      491769.821121        0.163508  0.205982  0.812435  0.416542
ANKRD39     55018.317730        0.432902  0.612729  1.083966  0.278380
IFT81       95350.281892       -0.095407  0.418117 -0.276889  0.781865
SCN3B       27329.581015        0.312116  0.517610  0.821300  0.411475

               padj
TCP11      0.764636
RNA5SP216  0.007842
EML5       0.323525
TEX19      0.371870
PA2G4P5    0.003392
...             ...
LINC02345  0.338328
DOCK1      0.682394
ANKRD39    0.547981
IFT81      0.901950
SCN3B      0.678635

[4994 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 2.20 seconds.

Fitting dispersion trend curve...
... done in 0.66 seconds.

Fitting MAP dispersions...
... done in 1.61 seconds.

Fitting LFCs...
... done in 0.89 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 295 outlier genes.

Fitting dispersions...

replace_mask before filtering: (20, 295)
Number of True values in replace_mask: 494
replacement_counts_trimmed shape: (20, 295)

... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 0.12 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.21 seconds.

Fitting MAP LFCs...
... done in 1.72 seconds.

R callback write-console: Removing 1 features with NA screening hypothesis p-values.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
TCP11        2909.919932        0.151822  0.713117  0.375725  0.707121
RNA5SP216   15841.807171        1.406806  0.535156  2.866262  0.004154
EML5        85871.146703        2.038306  0.247781  1.544072  0.122571
TEX19          82.579074        4.933694  0.064354 -4.587496  0.000004
PA2G4P5     35611.102578        0.799786  0.263837  2.415830  0.015699
...                  ...             ...       ...       ...       ...
LINC02345    2745.144470        0.490103  1.326094  1.511463  0.130670
DOCK1      491769.821121        2.379263  0.221359  0.812435  0.416542
ANKRD39     55018.317730        1.858309  0.634617  1.083966  0.278380
IFT81       95350.281892        1.354513  0.430694 -0.276889  0.781866
SCN3B       27329.581015        1.306498  0.590743  0.821299  0.411476

               padj
TCP11      0.880371
RNA5SP216  0.018500
EML5       0.305235
TEX19      0.000039
PA2G4P5    0.057722
...             ...
LINC02345  0.320134
DOCK1      0.674657
ANKRD39    0.530111
IFT81      0.923179
SCN3B      0.671625

[4994 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R4.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R4.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R4.csv
============================================================
[INFO] (36/160) sim_S10_G5000_CNweak_R5.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=5
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.19 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.29 seconds.

Fitting LFCs...
... done in 0.85 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 294 outlier genes.

Fitting dispersions...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.12 seconds.

Fitting LFCs...
... done in 0.19 seconds.

Running Wald tests...
... done in 0.26 seconds.

Fitting MAP LFCs...
... done in 1.46 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
MLYCD      1.333607e+05        0.105671  0.351907  0.339324  7.343656e-01
RPL26      1.942317e+06        0.140741  0.283522  0.514131  6.071605e-01
FASTKD5    1.133233e+05        0.035825  0.353617  0.108409  9.136711e-01
ADCY10     2.772434e+03       -0.572219  0.680218 -1.356866  1.748238e-01
UPK2       4.425437e+03       -0.006556  0.519092 -0.028785  9.770360e-01
...                 ...             ...       ...       ...           ...
RPS15AP14  4.681685e+02       -0.756971  1.444860 -3.407395  6.558606e-04
POMT2      2.933860e+04        0.278122  0.997517 -2.214904  2.676664e-02
NKX2-8     5.833211e+02       -0.376761  0.179596 -2.184617  2.891692e-02
NHLH1      1.605393e+03       -0.011437  0.476571 -0.037203  9.703229e-01
REEP1      1.638295e+05        1.872222  0.253565  7.607784  2.788357e-14

                   padj
MLYCD      8.914423e-01
RPL26      8.209191e-01
FASTKD5    9.746085e-01
ADCY10     4.124151e-01
UPK2       9.920090e-01
...                 ...
RPS15AP14  4.655398e-03
POMT2      1.048395e-01
NKX2-8     1.111998e-01
NHLH1      9.895389e-01
REEP1      1.300365e-12

[4990 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.05 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.16 seconds.

Fitting LFCs...
... done in 1.34 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 290 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 290)
Number of True values in replace_mask: 492
replacement_counts_trimmed shape: (20, 290)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.26 seconds.

Fitting MAP LFCs...
... done in 1.26 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
MLYCD      1.333607e+05        1.673619  0.362085  0.339324  7.343659e-01
RPL26      1.942317e+06        2.253749  0.142633  0.514131  6.071605e-01
FASTKD5    1.133233e+05        0.955998  0.371621 -1.510249  1.309799e-01
ADCY10     2.772434e+03       -1.132949  0.777165 -2.343196  1.911932e-02
UPK2       4.425437e+03       -0.077707  0.522358 -0.028785  9.770363e-01
...                 ...             ...       ...       ...           ...
RPS15AP14  6.617763e+01       -3.980608  0.085505  0.009448  9.924618e-01
POMT2      1.775484e+04        1.838075  0.002368  0.001116  9.991096e-01
NKX2-8     5.833211e+02       -0.821577  0.181039 -4.693459  2.686243e-06
NHLH1      1.605393e+03       -0.677384  0.513606 -1.787513  7.385460e-02
REEP1      1.638295e+05        2.873663  0.225766  6.069452  1.283478e-09

                   padj
MLYCD      9.120174e-01
RPL26      8.356835e-01
FASTKD5    3.200187e-01
ADCY10     6.835959e-02
UPK2       9.999928e-01
...                 ...
RPS15AP14  9.999928e-01
POMT2      9.999928e-01
NKX2-8     2.597743e-05
NHLH1      2.071582e-01
REEP1      2.113715e-08

[4990 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R5.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R5.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R5.csv
============================================================
[INFO] (37/160) sim_S10_G5000_CNweak_R6.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=6
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.26 seconds.

Fitting LFCs...
... done in 0.84 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 282 outlier genes.

Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.12 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
... done in 1.38 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SYCP2L        4552.945342       -1.763327  0.511927 -3.927482  0.000086
RNA5SP187      227.476347       -0.901675  0.981478 -1.852831  0.063907
PRR13       574976.818119       -0.386719  0.281229 -1.573936  0.115502
SLC44A3      54980.698495       -0.235329  0.535628 -0.634725  0.525608
CCDC92      328405.870379       -0.266675  0.349282 -0.814144  0.415563
...                   ...             ...       ...       ...       ...
MTSS1       511673.505532       -0.566579  1.053689 -1.771300  0.076511
GRHL2       406131.506946        0.115608  0.342205  0.373312  0.708916
SHC2        176391.169910        0.506408  0.908356  1.207280  0.227324
ZNF829       99396.139127        0.535524  1.099044  1.374112  0.169407
RNU6-1330P     485.972292        0.861726  0.394032  2.527581  0.011485

                padj
SYCP2L      0.000781
RNA5SP187   0.201791
PRR13       0.305698
SLC44A3     0.755694
CCDC92      0.668360
...              ...
MTSS1       0.230642
GRHL2       0.869415
SHC2        0.476521
ZNF829      0.394654
RNU6-1330P  0.053726

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.89 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.35 seconds.

Fitting LFCs...
... done in 1.07 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 283 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 283)
Number of True values in replace_mask: 464
replacement_counts_trimmed shape: (20, 283)

... done in 0.08 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.26 seconds.

Fitting MAP LFCs...
... done in 1.26 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SYCP2L        4552.945342       -2.047842  0.511957 -4.649519  0.000003
RNA5SP187      227.476347       -0.838155  0.975416 -1.852588  0.063941
PRR13       574976.818119        1.739547  0.251239 -1.573935  0.115502
SLC44A3      54980.698495        1.037525  0.598850 -0.634724  0.525608
CCDC92      328405.870379        1.630686  0.288468 -0.814143  0.415563
...                   ...             ...       ...       ...       ...
MTSS1       511673.505532        0.419463  0.702655 -2.394808  0.016629
GRHL2       406131.506946        1.193667  0.265031 -1.942124  0.052122
SHC2        176391.169910        2.372879  0.795720  1.207280  0.227324
ZNF829       99396.139127        2.292100  0.762023  0.867075  0.385901
RNU6-1330P     485.972292        0.851625  0.394841  2.526879  0.011508

                padj
SYCP2L      0.000032
RNA5SP187   0.185467
PRR13       0.287315
SLC44A3     0.759814
CCDC92      0.666004
...              ...
MTSS1       0.062237
GRHL2       0.159434
SHC2        0.463096
ZNF829      0.639513
RNU6-1330P  0.045821

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R6.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R6.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R6.csv
============================================================
[INFO] (38/160) sim_S10_G5000_CNweak_R7.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=7
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.97 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.61 seconds.

Fitting LFCs...
... done in 1.49 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 300 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.16 seconds.

Fitting LFCs...
... done in 0.20 seconds.

Running Wald tests...
... done in 0.26 seconds.

Fitting MAP LFCs...
... done in 1.26 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC01908      42.107937        0.389484  1.689734   1.544118  1.225599e-01
PCSK6      152039.458407        0.195480  0.673161   0.497462  6.188634e-01
NRF1       258736.793020        1.779296  0.176904  10.222864  1.566430e-24
EFCAB11     35995.357151        0.016732  0.382834   0.042958  9.657350e-01
VANGL1     148353.840798       -1.202311  0.597852  -2.607409  9.123019e-03
...                  ...             ...       ...        ...           ...
RCN1       944040.917467        0.297697  1.628246   2.165411  3.035625e-02
UBE2D1      13408.209726       -0.723593  1.316425  -0.861003  3.892362e-01
ZNF512     199556.201515        0.004827  0.539602  -0.015473  9.876550e-01
PRR22       17335.741026        0.549444  0.276843   2.146375  3.184308e-02
CACNA1G     26884.167382        1.238991  0.306350   4.314310  1.601022e-05

                   padj
LINC01908  3.198357e-01
PCSK6      8.270469e-01
NRF1       2.893255e-22
EFCAB11    9.897493e-01
VANGL1     4.349569e-02
...                 ...
RCN1       1.127227e-01
UBE2D1     6.602720e-01
ZNF512     9.958589e-01
PRR22      1.169081e-01
CACNA1G    1.695180e-04

[4987 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.09 seconds.

Fitting dispersion trend curve...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 1.47 seconds.

Fitting LFCs...
... done in 1.03 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 300 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 300)
Number of True values in replace_mask: 525
replacement_counts_trimmed shape: (20, 300)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.24 seconds.

Fitting MAP LFCs...
... done in 1.07 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE        stat        pvalue  \
LINC01908      42.107937        0.335274  1.619638    1.543610  1.226829e-01
PCSK6      152039.458407        1.728250  0.711181    0.497461  6.188639e-01
NRF1       258736.793020        3.402558  0.178912    7.973184  1.546376e-15
EFCAB11     35995.357151        1.299905  0.417604    0.042958  9.657351e-01
VANGL1     148353.840798        0.464892  0.533254   -2.607408  9.123055e-03
...                  ...             ...       ...         ...           ...
RCN1       137308.010467        2.158025  0.002698 -127.204863  0.000000e+00
UBE2D1       9844.205397       -3.418423  0.008861  -41.486119  0.000000e+00
ZNF512     199556.201515        1.299884  0.452214   -0.795571  4.262816e-01
PRR22       17335.741026        0.435490  0.269123    2.146343  3.184565e-02
CACNA1G     26884.167382        0.986205  0.318498    2.018645  4.352409e-02

                   padj
LINC01908  3.087406e-01
PCSK6      8.389615e-01
NRF1       4.590344e-14
EFCAB11    9.999950e-01
VANGL1     3.925511e-02
...                 ...
RCN1       0.000000e+00
UBE2D1     0.000000e+00
ZNF512     6.972340e-01
PRR22      1.091507e-01
CACNA1G    1.394953e-01

[4987 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R7.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R7.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R7.csv
============================================================
[INFO] (39/160) sim_S10_G5000_CNweak_R8.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=8
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.25 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.63 seconds.

Fitting LFCs...
... done in 0.95 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 271 outlier genes.

Fitting dispersions...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.11 seconds.

Fitting LFCs...
... done in 0.15 seconds.

Running Wald tests...
... done in 0.27 seconds.

Fitting MAP LFCs...
... done in 1.45 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
ZNF542P     247825.854496        2.198130  0.410151  5.671481  1.415684e-08
RFX7        147011.083725       -0.041290  0.291432 -0.168779  8.659704e-01
GEMIN7-AS1   14436.773311       -1.577946  0.421912 -4.155238  3.249498e-05
MIR6774        350.309983       -0.250334  0.757358 -0.709123  4.782479e-01
RMDN1       231651.560829       -0.357070  0.315860 -1.287568  1.978962e-01
...                   ...             ...       ...       ...           ...
LCNL1         7748.865173        0.038222  0.386073  0.116838  9.069887e-01
ENDOD1      371618.640494       -0.354872  0.893690 -1.476268  1.398720e-01
ZNF335      218444.178819       -0.248865  0.824251 -0.821360  4.114410e-01
PGF          55464.841217        0.073658  0.670141  0.185443  8.528820e-01
PKNOX2       14496.044386       -0.294225  0.627524 -0.770439  4.410396e-01

                    padj
ZNF542P     3.126407e-07
RFX7        9.501117e-01
GEMIN7-AS1  3.450690e-04
MIR6774     7.351482e-01
RMDN1       4.493631e-01
...                  ...
LCNL1       9.639041e-01
ENDOD1      3.609623e-01
ZNF335      6.763018e-01
PGF         9.450041e-01
PKNOX2      7.010283e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.14 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.55 seconds.

Fitting LFCs...
... done in 1.07 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 276 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 276)
Number of True values in replace_mask: 474
replacement_counts_trimmed shape: (20, 276)

... done in 0.09 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.27 seconds.

Fitting MAP LFCs...
... done in 1.39 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
ZNF542P     247825.854496        2.949434  0.291630  4.448402  8.651157e-06
RFX7        147011.083725        1.464221  0.319099 -0.168779  8.659705e-01
GEMIN7-AS1   14436.773311       -1.978956  0.414114 -5.156257  2.519357e-07
MIR6774        350.309983       -0.235206  0.737426 -0.709087  4.782707e-01
RMDN1       231651.560829        7.091958  0.569909  9.302601  1.370510e-20
...                   ...             ...       ...       ...           ...
LCNL1         7748.865173       -0.015804  0.382230  0.116836  9.069901e-01
ENDOD1      371618.640494        0.618173  0.857765 -1.476272  1.398708e-01
ZNF335      218444.178819        0.770301  0.857123 -1.235448  2.166638e-01
PGF          55464.841217        1.421228  0.807118  0.185442  8.528821e-01
PKNOX2       14496.044386       -0.061682  0.599213 -0.770437  4.410409e-01

                    padj
ZNF542P     7.655660e-05
RFX7        9.729984e-01
GEMIN7-AS1  2.993836e-06
MIR6774     7.406296e-01
RMDN1       4.817054e-19
...                  ...
LCNL1       9.884483e-01
ENDOD1      3.378970e-01
ZNF335      4.587847e-01
PGF         9.673548e-01
PKNOX2      7.057504e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R8.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R8.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R8.csv
============================================================
[INFO] (40/160) sim_S10_G5000_CNweak_R9.pkl
[INFO] Running analysis for S=10, G=5000, CN=weak, R=9
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.97 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.21 seconds.

Fitting LFCs...
... done in 0.69 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 314 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.24 seconds.

Fitting MAP LFCs...
... done in 1.19 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
VN1R81P      1.803361e+03       -0.242486  0.433348 -0.707556  0.479221
MIR7844      2.518842e+03       -2.082455  0.669879 -3.706892  0.000210
CFAP69       3.821209e+04       -1.439002  0.639131 -2.877502  0.004008
BCAR3        2.102309e+05        0.563599  0.390996  1.689348  0.091153
CEP57        2.150647e+05       -0.245502  0.224962 -1.150941  0.249756
...                   ...             ...       ...       ...       ...
ARPC4-TTLL3  1.036170e+06        1.282329  0.450266  3.272597  0.001066
SRGAP3-AS4   1.663064e+02       -1.624712  0.605551 -3.260588  0.001112
GPR45        2.066946e+02       -0.003695  0.849154 -0.022901  0.981729
SULT4A1      9.117161e+03        0.049930  0.655798  0.118923  0.905336
GTSE1-DT     2.560878e+03        0.219032  0.327447  0.756626  0.449274

                 padj
VN1R81P      0.738996
MIR7844      0.001630
CFAP69       0.021685
BCAR3        0.258382
CEP57        0.520994
...               ...
ARPC4-TTLL3  0.007059
SRGAP3-AS4   0.007336
GPR45        0.992587
SULT4A1      0.970540
GTSE1-DT     0.714597

[4988 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.03 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.19 seconds.

Fitting LFCs...
... done in 0.86 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 312 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 312)
Number of True values in replace_mask: 542
replacement_counts_trimmed shape: (20, 312)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.23 seconds.

Fitting MAP LFCs...
... done in 1.01 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
VN1R81P      1.803361e+03       -0.488081  0.442853 -1.381677  0.167071
MIR7844      2.518842e+03       -2.325794  0.668007 -4.082401  0.000045
CFAP69       3.821209e+04       -0.258734  0.564557 -3.415103  0.000638
BCAR3        2.102309e+05        2.117755  0.308597  1.689347  0.091153
CEP57        2.150647e+05        1.607499  0.255201 -1.150939  0.249757
...                   ...             ...       ...       ...       ...
ARPC4-TTLL3  1.036170e+06        2.388053  0.228420  2.232604  0.025575
SRGAP3-AS4   1.663064e+02       -1.904616  0.606984 -3.712435  0.000205
GPR45        2.066946e+02       -0.003142  0.821649 -0.022900  0.981730
SULT4A1      9.117161e+03        0.010143  0.655877  0.118923  0.905337
GTSE1-DT     2.560878e+03        0.228033  0.326692  0.756577  0.449303

                 padj
VN1R81P      0.375583
MIR7844      0.000305
CFAP69       0.003442
BCAR3        0.237426
CEP57        0.495935
...               ...
ARPC4-TTLL3  0.087918
SRGAP3-AS4   0.001215
GPR45        0.999998
SULT4A1      0.992729
GTSE1-DT     0.705422

[4988 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S10_G5000_CNweak_R9.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S10_G5000_CNweak_R9.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S10_G5000_CNweak_R9.csv
============================================================
[INFO] (41/160) sim_S20_G5000_CNstrong_R1.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=1
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.97 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.41 seconds.

Fitting LFCs...
... done in 0.88 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 496 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 0.17 seconds.

Fitting LFCs...
... done in 0.18 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.26 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
JMJD6       2.866650e+05        0.845194  0.228093   3.916538  8.982957e-05
PLA2G12AP1  4.043340e+03       -0.173189  0.213699  -0.862429  3.884515e-01
VEGFA       6.260131e+06        2.495645  0.684905   3.104709  1.904664e-03
RHO         1.021977e+03        2.405120  1.034263   3.149162  1.637392e-03
TK1         1.812348e+05       -0.353141  0.591807  -0.904780  3.655820e-01
...                  ...             ...       ...        ...           ...
SCN9A       1.458442e+04       -0.003716  0.373554  -0.017245  9.862412e-01
BCL2L2      4.951732e+05       -0.524249  0.732460  -1.271456  2.035664e-01
NADSYN1     7.098718e+05        1.404708  0.204097   7.082969  1.410979e-12
CUL7        1.246909e+06        2.620398  0.182979  14.387702  6.181551e-47
POGK        5.367068e+05        0.161350  0.542532   0.400160  6.890386e-01

                    padj
JMJD6       4.937659e-04
PLA2G12AP1  6.121760e-01
VEGFA       8.062918e-03
RHO         7.063287e-03
TK1         5.908742e-01
...                  ...
SCN9A       9.930058e-01
BCL2L2      4.120031e-01
NADSYN1     2.035317e-11
CUL7        1.714007e-44
POGK        8.493435e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.41 seconds.

Fitting LFCs...
... done in 0.92 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 497 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 497)
Number of True values in replace_mask: 1135
replacement_counts_trimmed shape: (40, 497)

... done in 0.12 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.35 seconds.

Fitting MAP LFCs...
... done in 1.05 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
JMJD6       2.866650e+05        1.196185  0.191039  -1.727715  8.403941e-02
PLA2G12AP1  4.043340e+03       -0.149374  0.213253  -0.862385  3.884757e-01
VEGFA       6.260131e+06        2.855403  0.077391   2.428930  1.514346e-02
RHO         1.021977e+03        1.836873  1.053530   2.698937  6.956134e-03
TK1         1.812348e+05        1.837410  0.510733   0.388445  6.976869e-01
...                  ...             ...       ...        ...           ...
SCN9A       1.458442e+04       -0.099083  0.370559  -0.017245  9.862413e-01
BCL2L2      4.951732e+05        1.204456  0.390014  -1.433716  1.516533e-01
NADSYN1     7.098718e+05        1.913582  0.126827   1.683056  9.236430e-02
CUL7        1.246909e+06        3.498494  0.093975  12.021206  2.749290e-33
POGK        5.367068e+05        1.257992  0.308821  -1.437055  1.507023e-01

                    padj
JMJD6       2.033563e-01
PLA2G12AP1  6.248412e-01
VEGFA       4.496195e-02
RHO         2.221245e-02
TK1         8.889044e-01
...                  ...
SCN9A       9.999869e-01
BCL2L2      3.227726e-01
NADSYN1     2.198332e-01
CUL7        5.297956e-32
POGK        3.215199e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R1.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R1.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R1.csv
============================================================
[INFO] (42/160) sim_S20_G5000_CNstrong_R10.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=10
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.31 seconds.

Fitting LFCs...
... done in 0.65 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 478 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.11 seconds.

Fitting LFCs...
... done in 0.20 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.23 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CCL18     40619.071931       -0.767560  0.697647 -1.738280  0.082162  0.215498
TMPRSS3  122258.225879       -0.305080  0.722238 -0.812686  0.416398  0.659307
NPC2     865069.718095        0.012983  0.279382  0.109354  0.912921  0.963997
GZMH       6204.678086       -0.122956  0.498502 -0.347969  0.727864  0.872424
OTOGL      3706.901620       -2.165726  0.566747 -4.323955  0.000015  0.000097
...                ...             ...       ...       ...       ...       ...
CCDC196     358.216605       -0.292697  0.707308 -1.348719  0.177427  0.386488
PBOV1       207.520362       -0.780036  0.274251 -3.076752  0.002093  0.009030
CDHR2      4317.765208       -0.300249  0.857654 -0.990898  0.321736  0.566096
FAM215A     298.997481        0.625341  0.264432  2.557432  0.010545  0.038238
POLD3     34400.837127       -0.691012  0.975420 -0.379016  0.704676  0.858602

[4997 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.91 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.28 seconds.

Fitting LFCs...
... done in 1.13 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 472 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 472)
Number of True values in replace_mask: 1055
replacement_counts_trimmed shape: (40, 472)

... done in 0.13 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.03 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE       stat        pvalue  \
CCL18     40619.071931        0.469120  0.622614  -1.738279  8.216169e-02
TMPRSS3  122258.225879        0.813983  0.727546  -1.478662  1.392307e-01
NPC2     865069.718095        1.832010  0.180708   0.109354  9.129214e-01
GZMH       6204.678086       -0.234873  0.500568  -0.347967  7.278650e-01
OTOGL      3706.901620       -2.515735  0.553442  -4.896673  9.747277e-07
...                ...             ...       ...        ...           ...
CCDC196     191.124137       -0.661402  0.024761  -9.599233  8.054174e-22
PBOV1       207.520362       -1.140279  0.276805  -4.398678  1.089124e-05
CDHR2      4317.765208       -0.295442  0.812613  -1.162770  2.449229e-01
FAM215A     298.997481        0.617789  0.264494   2.556208  1.058199e-02
POLD3     10621.273067       -2.000037  0.003637 -75.397512  0.000000e+00

                 padj
CCL18    1.978612e-01
TMPRSS3  3.050136e-01
NPC2     9.999988e-01
GZMH     9.027405e-01
OTOGL    5.436065e-06
...               ...
CCDC196  1.474238e-20
PBOV1    5.314799e-05
CDHR2    4.712667e-01
FAM215A  3.254042e-02
POLD3    0.000000e+00

[4997 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R10.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R10.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R10.csv
============================================================
[INFO] (43/160) sim_S20_G5000_CNstrong_R11.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=11
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.91 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.33 seconds.

Fitting LFCs...
... done in 0.93 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 466 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.14 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.16 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat        pvalue  \
OSGEPL1-AS1    2036.709307        0.026603  0.251050  0.114365  9.089483e-01
CPLANE1      219915.724799        0.988056  0.253574  4.133980  3.565346e-05
NPEPL1       302103.538173       -0.443636  0.485391 -1.173095  2.407576e-01
ZNF467       327903.970298        2.080519  0.437789  5.130635  2.887661e-07
ABHD17A      289845.964315        0.231394  0.226840  1.046776  2.952030e-01
...                    ...             ...       ...       ...           ...
TGDS          65753.099586        0.535891  0.282924  2.044976  4.085725e-02
NPAP1           212.861413       -0.176906  0.566747 -0.460792  6.449480e-01
NOD1         325726.247041        0.035952  0.393987  0.078453  9.374677e-01
NT5C1B         5416.391920        1.922111  0.263239  7.530006  5.073805e-14
NHP2P2          722.440926        1.005624  0.217819  4.806095  1.539067e-06

                     padj
OSGEPL1-AS1  9.587238e-01
CPLANE1      2.017533e-04
NPEPL1       4.602381e-01
ZNF467       2.276460e-06
ABHD17A      5.252613e-01
...                   ...
TGDS         1.182822e-01
NPAP1        8.210564e-01
NOD1         9.724113e-01
NT5C1B       8.413076e-13
NHP2P2       1.060978e-05

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.99 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.29 seconds.

Fitting LFCs...
... done in 0.89 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 468 outlier genes.

Fitting dispersions...

replace_mask before filtering: (40, 468)
Number of True values in replace_mask: 1038
replacement_counts_trimmed shape: (40, 468)

... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.12 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.37 seconds.

Fitting MAP LFCs...
... done in 1.02 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat        pvalue  \
OSGEPL1-AS1    2036.709307        0.026528  0.250205  0.114357  9.089548e-01
CPLANE1      219915.724799        1.470455  0.214078  0.002784  9.977790e-01
NPEPL1       302103.538173        0.774188  0.358299 -3.266851  1.087508e-03
ZNF467       327903.970298        3.103184  0.289385  4.691429  2.713028e-06
ABHD17A      289845.964315        1.909012  0.192653  1.046775  2.952033e-01
...                    ...             ...       ...       ...           ...
TGDS          65753.099586        1.747020  0.288002  2.044972  4.085762e-02
NPAP1           212.861413       -0.166601  0.555800 -0.460743  6.449833e-01
NOD1         325726.247041        1.045837  0.277784 -2.442408  1.458964e-02
NT5C1B         5416.391920        1.540169  0.262980  6.168712  6.884834e-10
NHP2P2          722.440926       -0.042051  0.213530 -0.252405  8.007277e-01

                     padj
OSGEPL1-AS1  9.999958e-01
CPLANE1      9.999958e-01
NPEPL1       3.852201e-03
ZNF467       1.362246e-05
ABHD17A      5.200034e-01
...                   ...
TGDS         1.066529e-01
NPAP1        8.438718e-01
NOD1         4.255809e-02
NT5C1B       5.068172e-09
NHP2P2       9.434040e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R11.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R11.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R11.csv
============================================================
[INFO] (44/160) sim_S20_G5000_CNstrong_R12.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=12
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.94 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.31 seconds.

Fitting LFCs...
... done in 0.85 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 467 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.12 seconds.

Fitting LFCs...
... done in 0.19 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.37 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
PCGF1     63791.059888       -0.314962  0.219813 -1.541437  0.123211  0.291464
NPAS3     13744.384958       -0.947164  0.466867 -2.457268  0.014000  0.047546
USP8     314620.125555       -0.146628  0.163143 -1.049205  0.294084  0.529670
YRDC      95161.783332       -0.060245  0.261801 -0.267426  0.789141  0.910078
OSR2     205712.590618        0.768290  0.438938  2.152331  0.031371  0.096255
...                ...             ...       ...       ...       ...       ...
SLC10A7   49909.034957       -0.297781  0.290062 -1.127567  0.259503  0.490401
MYOM1     44604.095493       -0.633998  0.669737 -2.397993  0.016485  0.054976
ZNF644   248392.569385        0.401726  0.301680  1.405348  0.159918  0.349007
FABP9       387.395162        0.089402  0.465091  0.247493  0.804527  0.918057
DCAF1    304557.748159       -0.842339  1.053324 -1.895752  0.057993  0.161454

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.04 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.36 seconds.

Fitting LFCs...
... done in 1.33 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 467 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 467)
Number of True values in replace_mask: 1045
replacement_counts_trimmed shape: (40, 467)

... done in 0.10 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.39 seconds.

Fitting MAP LFCs...
... done in 1.03 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE       stat    pvalue  \
PCGF1     63791.059888        0.907442  0.232434  -2.838537  0.004532
NPAS3     13744.384958       -0.737123  0.484022  -3.197755  0.001385
USP8     314620.125555        1.894227  0.169361  -1.049203  0.294085
YRDC      95161.783332        1.340211  0.269714  -0.267426  0.789141
OSR2     205712.590618        2.997269  0.323127   4.109641  0.000040
...                ...             ...       ...        ...       ...
SLC10A7   49909.034957        0.891435  0.312570  -1.127565  0.259504
MYOM1     14082.718311       -1.225396  0.003300 -80.583460  0.000000
ZNF644   248392.569385        1.842307  0.273468   1.405347  0.159918
FABP9       387.395162       -0.769789  0.502630  -2.012582  0.044159
DCAF1    304557.748159        0.836577  0.649661  -1.895752  0.057993

             padj
PCGF1    0.014905
NPAS3    0.004993
USP8     0.533523
YRDC     0.943452
OSR2     0.000180
...           ...
SLC10A7  0.488553
MYOM1    0.000000
ZNF644   0.341245
FABP9    0.117310
DCAF1    0.148525

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R12.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R12.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R12.csv
============================================================
[INFO] (45/160) sim_S20_G5000_CNstrong_R13.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=13
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.91 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.43 seconds.

Fitting LFCs...
... done in 0.69 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 461 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.11 seconds.

Fitting LFCs...
... done in 0.21 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.18 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
EPDR1       81072.683093       -0.205242  0.420499  -0.620800  5.347312e-01
INTS12     132671.054651        0.259374  0.158559   1.618627  1.055276e-01
LINC00943     673.288352        0.248102  0.624878   0.634086  5.260250e-01
PCDH9       21114.949908       -0.079799  0.575648  -0.220589  8.254124e-01
LRGUK       22346.348744        2.383010  0.500615   5.153936  2.550757e-07
...                  ...             ...       ...        ...           ...
MIR155HG     5773.869349       -0.423114  0.179351  -2.448664  1.433873e-02
TNFAIP3    210864.347715       -1.054482  0.259194  -4.397250  1.096311e-05
CRYBG3     203104.737206       -2.400373  0.203828 -11.960334  5.733055e-33
ATXN3      237451.136983        0.001370  0.507285   0.041684  9.667506e-01
NCR1          458.520482       -0.993223  0.179315  -5.703221  1.175643e-08

                   padj
EPDR1      7.529998e-01
INTS12     2.621355e-01
LINC00943  7.462776e-01
PCDH9      9.256012e-01
LRGUK      2.187680e-06
...                 ...
MIR155HG   4.944629e-02
TNFAIP3    7.022134e-05
CRYBG3     5.493810e-31
ATXN3      9.853439e-01
NCR1       1.188281e-07

[4983 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.06 seconds.

Fitting dispersion trend curve...
... done in 0.25 seconds.

Fitting MAP dispersions...
... done in 1.46 seconds.

Fitting LFCs...
... done in 0.86 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 461 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 461)
Number of True values in replace_mask: 1033
replacement_counts_trimmed shape: (40, 461)

... done in 0.11 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.06 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
EPDR1       81072.683093        0.952050  0.427729  -1.647391  9.947779e-02
INTS12     132671.054651        2.203058  0.167410   1.618622  1.055285e-01
LINC00943     673.288352        0.230295  0.613906   0.634068  5.260364e-01
PCDH9       21114.949908        0.787041  0.672481  -0.220589  8.254125e-01
LRGUK       22346.348744        2.965149  0.498385   4.746997  2.064590e-06
...                  ...             ...       ...        ...           ...
MIR155HG     5773.869349       -0.856424  0.178803  -4.631938  3.622579e-06
TNFAIP3    210864.347715        0.644924  0.251934  -5.907144  3.480897e-09
CRYBG3     203104.737206        0.287014  0.235092 -13.242640  4.976806e-40
ATXN3      237451.136983        1.622611  0.436454   0.041684  9.667506e-01
NCR1          458.520482       -1.459261  0.179728  -8.306611  9.847421e-17

                   padj
EPDR1      2.335993e-01
INTS12     2.457237e-01
LINC00943  7.619311e-01
PCDH9      9.644424e-01
LRGUK      1.114610e-05
...                 ...
MIR155HG   1.892171e-05
TNFAIP3    2.502931e-08
CRYBG3     1.265277e-38
ATXN3      9.999969e-01
NCR1       1.254979e-15

[4983 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R13.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R13.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R13.csv
============================================================
[INFO] (46/160) sim_S20_G5000_CNstrong_R14.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=14
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 1.19 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 480 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.10 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
MIA3       5.328449e+05       -0.434429  0.280162 -1.609865  0.107427
CTNNB1     2.291353e+06        0.016601  0.255659  0.210563  0.833228
DDX10      1.535152e+05        0.023487  0.198496  0.073921  0.941073
RNU6-322P  4.288059e+02       -0.339740  0.573532 -0.876166  0.380940
RN7SL130P  7.606177e+02       -0.159937  0.533768 -0.433407  0.664719
...                 ...             ...       ...       ...       ...
GPR137     2.213848e+05       -0.407750  0.393443 -1.274566  0.202463
DDX52      1.322983e+05       -1.196051  0.305427 -4.231656  0.000023
TOR1AIP1   4.638067e+05       -0.106770  0.185794 -0.641631  0.521113
ACTBP11    1.220689e+04       -0.278950  0.209229 -1.415022  0.157062
RPS3AP49   6.136711e+03        0.410160  0.514336 -0.531308  0.595205

               padj
MIA3       0.261772
CTNNB1     0.924089
DDX10      0.971255
RNU6-322P  0.613538
RN7SL130P  0.830774
...             ...
GPR137     0.409789
DDX52      0.000138
TOR1AIP1   0.733122
ACTBP11    0.344817
RPS3AP49   0.784216

[4988 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.94 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.36 seconds.

Fitting LFCs...
... done in 0.84 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 480 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 480)
Number of True values in replace_mask: 1043
replacement_counts_trimmed shape: (40, 480)

... done in 0.11 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.01 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
MIA3       5.328449e+05        0.645417  0.191472  -5.697325  1.217021e-08
CTNNB1     2.291353e+06        1.948791  0.118050   0.210563  8.332280e-01
DDX10      1.535152e+05        1.782057  0.190031   0.073921  9.410734e-01
RNU6-322P  4.288059e+02       -0.509437  0.592739  -1.313884  1.888851e-01
RN7SL130P  7.606177e+02       -0.156389  0.527869  -0.433393  6.647296e-01
...                 ...             ...       ...        ...           ...
GPR137     2.213848e+05        1.143629  0.304344  -2.138277  3.249425e-02
DDX52      1.322983e+05        0.446672  0.299959  -5.477437  4.315309e-08
TOR1AIP1   4.638067e+05        0.770079  0.163584  -6.164207  7.083721e-10
ACTBP11    1.220689e+04       -1.191002  0.212638  -6.038018  1.560185e-09
RPS3AP49   4.375280e+03        0.701376  0.006288 -59.543984  0.000000e+00

                   padj
MIA3       7.588128e-08
CTNNB1     9.628588e-01
DDX10      9.999982e-01
RNU6-322P  3.737242e-01
RN7SL130P  8.538942e-01
...                 ...
GPR137     8.612184e-02
DDX52      2.568587e-07
TOR1AIP1   5.083971e-09
ACTBP11    1.076376e-08
RPS3AP49   0.000000e+00

[4988 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R14.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R14.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R14.csv
============================================================
[INFO] (47/160) sim_S20_G5000_CNstrong_R15.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=15
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.92 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.64 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 490 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.21 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.18 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
BBIP1       253292.151030       -0.192236  0.329890 -0.722695  0.469867
DMWD        459763.019487        1.046815  0.246331  4.512872  0.000006
TMEM163      17073.657360       -0.338417  0.407561 -1.022655  0.306471
RPTOR       311368.814083        0.626393  0.261857  2.499805  0.012426
CRYGS        42168.831941        0.913128  0.298221  3.324172  0.000887
...                   ...             ...       ...       ...       ...
VWA8        196703.483944       -0.164441  0.324652 -0.596677  0.550723
FGB          42542.269335        0.126661  0.689920  0.327242  0.743485
THAP6        66313.486561       -0.315783  0.671141 -0.826489  0.408527
HNRNPA3P13     199.943668        0.546204  0.969674 -0.173032  0.862627
GUSBP5        4385.329187       -0.076174  0.261800 -0.327000  0.743668

                padj
BBIP1       0.704811
DMWD        0.000043
TMEM163     0.550192
RPTOR       0.043535
CRYGS       0.004116
...              ...
VWA8        0.767687
FGB         0.883161
THAP6       0.653041
HNRNPA3P13  0.942335
GUSBP5      0.883161

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.09 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.85 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 481 outlier genes.

Fitting dispersions...

replace_mask before filtering: (40, 481)
Number of True values in replace_mask: 1029
replacement_counts_trimmed shape: (40, 481)

... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.13 seconds.

Fitting LFCs...
... done in 0.13 seconds.

Running Wald tests...
... done in 0.39 seconds.

Fitting MAP LFCs...
... done in 1.56 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
BBIP1       253292.151030        1.423739  0.303473 -0.722695  0.469867
DMWD        459763.019487        2.098396  0.157598  2.395406  0.016602
TMEM163      17073.657360       -0.338856  0.409109 -1.022652  0.306472
RPTOR       311368.814083        1.391033  0.197106 -0.889883  0.373529
CRYGS        42168.831941        1.265330  0.292867  0.121609  0.903209
...                   ...             ...       ...       ...       ...
VWA8        196703.483944        1.355692  0.316204 -0.596677  0.550723
FGB          42542.269335        1.461261  0.843804  0.327242  0.743485
THAP6        66313.486561        0.633050  0.689137 -1.493515  0.135302
HNRNPA3P13      92.806428        1.422534  0.034585  0.000599  0.999522
GUSBP5        4385.329187       -0.068381  0.260937 -0.326990  0.743675

                padj
BBIP1       0.714031
DMWD        0.048409
TMEM163     0.544513
RPTOR       0.619733
CRYGS       0.999990
...              ...
VWA8        0.781444
FGB         0.915420
THAP6       0.295545
HNRNPA3P13  0.999990
GUSBP5      0.915420

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R15.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R15.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R15.csv
============================================================
[INFO] (48/160) sim_S20_G5000_CNstrong_R16.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=16
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.06 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.55 seconds.

Fitting LFCs...
... done in 0.76 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 498 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.13 seconds.

Fitting LFCs...
... done in 0.21 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.18 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
TMEM167A   463693.112069        0.055823  0.148461  0.330068  7.413485e-01
LINC02021    3865.105525       -1.295818  0.416597 -3.520214  4.311984e-04
FAAP100    199117.626491       -0.741789  0.266030 -3.036845  2.390683e-03
MYOM2       14423.827824        0.072193  0.498836  0.195491  8.450089e-01
FOXN3-AS1   12218.676072       -0.069492  0.385386 -0.225753  8.213937e-01
...                  ...             ...       ...       ...           ...
IPO8P1      11615.901785       -0.395565  0.244589 -1.753995  7.943135e-02
ATP6V1B1   147727.567021        1.924653  1.002391  0.522703  6.011806e-01
KCNH3        5929.634700       -1.563575  0.237616 -6.809627  9.785206e-12
KRTAP1-5      155.027456       -0.509132  0.242576 -2.252322  2.430193e-02
AGA        127635.939051        0.073033  0.216639  0.332603  7.394337e-01

                   padj
TMEM167A   8.770661e-01
LINC02021  2.058611e-03
FAAP100    9.821666e-03
MYOM2      9.269458e-01
FOXN3-AS1  9.163909e-01
...                 ...
IPO8P1     2.076594e-01
ATP6V1B1   7.974001e-01
KCNH3      1.431624e-10
KRTAP1-5   7.758620e-02
AGA        8.764635e-01

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.97 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.31 seconds.

Fitting LFCs...
... done in 0.86 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 496 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 496)
Number of True values in replace_mask: 1045
replacement_counts_trimmed shape: (40, 496)

... done in 0.11 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.03 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE        stat        pvalue  \
TMEM167A   463693.112069        2.229268  0.159192    0.330068  7.413488e-01
LINC02021    3865.105525       -1.668657  0.417030   -4.537059  5.704412e-06
FAAP100    199117.626491        1.998422  0.255684    0.222906  8.236086e-01
MYOM2       14423.827824        0.066470  0.500231    0.195490  8.450092e-01
FOXN3-AS1   12218.676072       -0.180891  0.380451   -0.225752  8.213942e-01
...                  ...             ...       ...         ...           ...
IPO8P1      11615.901785        0.336834  0.241983    1.755728  7.913494e-02
ATP6V1B1    76090.698217        2.265090  0.001511  470.123166  0.000000e+00
KCNH3        5929.634700       -1.671539  0.239427   -7.665167  1.785988e-14
KRTAP1-5      155.027456       -0.776965  0.244903   -3.393656  6.896617e-04
AGA        127635.939051        1.485962  0.228143    0.332603  7.394341e-01

                   padj
TMEM167A   9.132318e-01
LINC02021  2.744389e-05
FAAP100    9.595247e-01
MYOM2      9.702534e-01
FOXN3-AS1  9.584167e-01
...                 ...
IPO8P1     1.905982e-01
ATP6V1B1   0.000000e+00
KCNH3      1.860186e-13
KRTAP1-5   2.505988e-03
AGA        9.131186e-01

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R16.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R16.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R16.csv
============================================================
[INFO] (49/160) sim_S20_G5000_CNstrong_R17.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=17
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.88 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.64 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 474 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.21 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.42 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat        pvalue  \
DNAJB14  2.371025e+05        0.202597  0.209423  0.992849  3.207838e-01
GAL3ST3  4.389108e+01       -1.095460  1.722606 -1.753519  7.951292e-02
KCTD3    7.178511e+05        0.375872  0.302203  1.443352  1.489214e-01
SFRP2    2.031800e+06       -0.757462  0.563682 -1.841546  6.554162e-02
WDR1     1.536035e+06        0.266900  0.210599  1.376551  1.686510e-01
...               ...             ...       ...       ...           ...
TDG      1.056562e+05       -1.166760  0.489606 -2.894159  3.801760e-03
DBN1     4.735800e+05       -0.407733  0.175972 -2.376264  1.748892e-02
SIGLEC1  3.510793e+04       -0.042910  0.815244  0.178875  8.580357e-01
ENGASE   4.561348e+05        0.969307  0.167838  6.042536  1.517101e-09
OR7E2P   3.489447e+02        0.543748  0.277332  2.136311  3.265410e-02

                 padj
DNAJB14  5.467569e-01
GAL3ST3  2.043620e-01
KCTD3    3.271670e-01
SFRP2    1.740688e-01
WDR1     3.572465e-01
...               ...
TDG      1.450129e-02
DBN1     5.714684e-02
SIGLEC1  9.355997e-01
ENGASE   1.527195e-08
OR7E2P   9.739260e-02

[4993 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.90 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 471 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 471)
Number of True values in replace_mask: 1037
replacement_counts_trimmed shape: (40, 471)

... done in 0.11 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.02 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE       stat    pvalue      padj
DNAJB14  2.371025e+05        1.825343  0.199361   0.992848  0.320784  0.560508
GAL3ST3  9.498441e+00       -3.312387  0.098221  -0.062205  0.950400  0.999993
KCTD3    7.178511e+05        1.287319  0.160656  -1.842070  0.065465  0.163107
SFRP2    2.031800e+06        1.301595  0.200318  -1.841547  0.065541  0.163216
WDR1     1.536035e+06        2.204895  0.101439   1.376551  0.168651  0.351515
...               ...             ...       ...        ...       ...       ...
TDG      1.056562e+05        0.450103  0.466624  -2.894157  0.003802  0.012613
DBN1     4.735800e+05        1.480620  0.142193  -4.001461  0.000063  0.000267
SIGLEC1  1.066066e+04        0.687842  0.003107 -50.390301  0.000000  0.000000
ENGASE   4.561348e+05        1.518198  0.144240  -0.795248  0.426469  0.673687
OR7E2P   3.489447e+02        0.539930  0.277329   2.135521  0.032718  0.089416

[4993 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R17.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R17.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R17.csv
============================================================
[INFO] (50/160) sim_S20_G5000_CNstrong_R18.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=18
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.90 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.64 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 469 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.20 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.20 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC02766  8.046895e+02        0.262342  0.737793   0.652807  5.138806e-01
SLC25A48   1.765722e+04        0.065515  0.626126   0.157769  8.746391e-01
TYSND1     1.901048e+05        0.209149  0.236122   0.894696  3.709499e-01
RAD51D     1.207798e+05       -0.049643  0.318654  -0.191864  8.478489e-01
SIGLEC5    1.217687e+04       -0.430766  0.386003  -1.331031  1.831788e-01
...                 ...             ...       ...        ...           ...
ARLNC1     1.047102e+03       -0.601936  0.879435  -1.407219  1.593626e-01
CXCL9      1.790798e+05       -0.966726  1.172278  -1.978711  4.784860e-02
AP2A1      1.472223e+06        1.561108  0.513987   3.519229  4.328022e-04
RFC2       6.761414e+05        2.842577  0.181898  15.691349  1.733330e-55
QRICH1     4.057777e+05       -0.199390  0.474727  -0.564993  5.720784e-01

                   padj
LINC02766  7.247183e-01
SLC25A48   9.486276e-01
TYSND1     6.059936e-01
RAD51D     9.347501e-01
SIGLEC5    3.812534e-01
...                 ...
ARLNC1     3.439480e-01
CXCL9      1.349222e-01
AP2A1      2.061179e-03
RFC2       5.088854e-53
QRICH1     7.695494e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.33 seconds.

Fitting LFCs...
... done in 0.87 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 466 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 466)
Number of True values in replace_mask: 1021
replacement_counts_trimmed shape: (40, 466)

... done in 0.10 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.57 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC02766  8.046895e+02        0.248037  0.722541   0.652797  5.138871e-01
SLC25A48   1.765722e+04        1.288225  0.745008   0.157769  8.746392e-01
TYSND1     1.901048e+05        1.813748  0.223111   0.894695  3.709503e-01
RAD51D     1.207798e+05        1.530532  0.299579  -0.191864  8.478490e-01
SIGLEC5    1.217687e+04       -0.718817  0.405181  -2.770252  5.601292e-03
...                 ...             ...       ...        ...           ...
ARLNC1     1.047102e+03       -0.483838  0.819582  -1.407204  1.593670e-01
CXCL9      1.790798e+05        0.665324  0.654071  -2.288041  2.213510e-02
AP2A1      1.472223e+06        2.596844  0.187603   2.459692  1.390565e-02
RFC2       6.761414e+05        3.728509  0.123088  13.852256  1.232781e-43
QRICH1     4.057777e+05        1.538911  0.344160  -0.564993  5.720784e-01

                   padj
LINC02766  7.423474e-01
SLC25A48   9.885788e-01
TYSND1     6.115973e-01
RAD51D     9.745772e-01
SIGLEC5    1.779507e-02
...                 ...
ARLNC1     3.314812e-01
CXCL9      6.203049e-02
AP2A1      4.128678e-02
RFC2       2.861771e-42
QRICH1     7.906920e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R18.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R18.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R18.csv
============================================================
[INFO] (51/160) sim_S20_G5000_CNstrong_R19.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=19
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.90 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 0.68 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 452 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.21 seconds.

Fitting LFCs...
... done in 0.26 seconds.

Running Wald tests...
... done in 0.50 seconds.

Fitting MAP LFCs...
... done in 1.29 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE       stat        pvalue  \
NOTCH1   592909.150890        0.194940  0.306573   0.692518  4.886121e-01
TMEM30A  669208.849363       -1.045135  0.210818  -5.191619  2.084733e-07
ZIC4      11566.994118        1.274529  1.018278   2.201668  2.768879e-02
ZBTB24   436107.791325        2.918887  0.273626  10.828906  2.511387e-27
SVIP     432520.339614        1.859331  0.299854   6.441762  1.180942e-10
...                ...             ...       ...        ...           ...
ZHX2     284355.179248        0.047082  0.507478   0.104944  9.164202e-01
HOXD3     35260.780405        0.198971  0.526575   0.517464  6.048323e-01
RARS2    214456.676576        0.015638  0.413038   0.015814  9.873825e-01
PRAL     346023.496818       -0.112395  0.137107  -0.968717  3.326862e-01
GRIK1     14575.953367        1.566550  0.364834   4.620987  3.819186e-06

                 padj
NOTCH1   7.190215e-01
TMEM30A  1.636647e-06
ZIC4     8.502469e-02
ZBTB24   1.441305e-25
SVIP     1.371266e-09
...               ...
ZHX2     9.721024e-01
HOXD3    8.037896e-01
RARS2    9.937514e-01
PRAL     5.759835e-01
GRIK1    2.495968e-05

[4993 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.35 seconds.

Fitting dispersion trend curve...
... done in 0.54 seconds.

Fitting MAP dispersions...
... done in 1.87 seconds.

Fitting LFCs...
... done in 1.19 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 453 outlier genes.

Fitting dispersions...

replace_mask before filtering: (40, 453)
Number of True values in replace_mask: 961
replacement_counts_trimmed shape: (40, 453)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.17 seconds.

Fitting LFCs...
... done in 0.12 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.14 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
NOTCH1   592909.150890        1.866554  0.208758  0.692518  4.886121e-01
TMEM30A  669208.849363        0.953198  0.171066 -6.703673  2.032448e-11
ZIC4      11566.994118        1.873091  0.964310  1.117144  2.639327e-01
ZBTB24   436107.791325        3.570935  0.197627  9.442264  3.648115e-21
SVIP     432520.339614        2.753127  0.210608  5.278601  1.301737e-07
...                ...             ...       ...       ...           ...
ZHX2     284355.179248        1.212156  0.362814 -1.395414  1.628911e-01
HOXD3     35260.780405        1.424418  0.585906  0.517464  6.048326e-01
RARS2    214456.676576        1.552269  0.371175  0.015814  9.873825e-01
PRAL     346023.496818        2.224419  0.156899 -0.968716  3.326869e-01
GRIK1     14575.953367        1.031341  0.364032  3.138541  1.697913e-03

                 padj
NOTCH1   7.239289e-01
TMEM30A  1.740654e-10
ZIC4     4.884417e-01
ZBTB24   5.727999e-20
SVIP     7.878269e-07
...               ...
ZHX2     3.415856e-01
HOXD3    8.187917e-01
RARS2    9.999983e-01
PRAL     5.698085e-01
GRIK1    5.880681e-03

[4993 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R19.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R19.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R19.csv
============================================================
[INFO] (52/160) sim_S20_G5000_CNstrong_R2.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=2
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.31 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.46 seconds.

Fitting LFCs...
... done in 0.76 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 504 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.14 seconds.

Fitting MAP dispersions...
... done in 0.24 seconds.

Fitting LFCs...
... done in 0.23 seconds.

Running Wald tests...
... done in 0.38 seconds.

Fitting MAP LFCs...
... done in 1.48 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SPHKAP     4.700889e+02        1.746136  1.213204  1.753623  0.079495
P2RX3      6.616688e+01        0.456678  0.866150  1.066873  0.286029
SRSF5      2.024832e+06       -0.032633  0.266855 -0.035590  0.971610
MFSD2A     4.946556e+04       -0.038392  0.499155 -0.115857  0.907766
SMOC2      3.473956e+05        0.167505  0.409028  0.447029  0.654854
...                 ...             ...       ...       ...       ...
RNU6-395P  2.247530e+03        0.085863  0.603229  0.220032  0.825847
ZNF33A     8.328743e+05        1.453072  0.648222  2.814966  0.004878
CHTF18     2.513434e+05        0.661542  0.482729  1.687794  0.091451
ZC3H7B     6.089158e+05       -0.174451  0.433667 -0.408623  0.682816
NOX4       5.119254e+04       -0.033495  0.209999 -0.140277  0.888441

               padj
SPHKAP     0.205682
P2RX3      0.525809
SRSF5      0.989856
MFSD2A     0.963560
SMOC2      0.841714
...             ...
RNU6-395P  0.931691
ZNF33A     0.019186
CHTF18     0.230471
ZC3H7B     0.856748
NOX4       0.958127

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.83 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.46 seconds.

Fitting LFCs...
... done in 0.89 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 502 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 502)
Number of True values in replace_mask: 1121
replacement_counts_trimmed shape: (40, 502)

... done in 0.12 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.22 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SPHKAP     2.176422e+02        2.692164  0.018624  0.010307  0.991776
P2RX3      2.418634e+01        0.652752  0.054331 -3.640184  0.000272
SRSF5      2.024832e+06        1.862248  0.125043 -0.035590  0.971610
MFSD2A     4.946556e+04        1.283048  0.541734 -0.115857  0.907766
SMOC2      3.473956e+05        1.785096  0.305452  0.450220  0.652552
...                 ...             ...       ...       ...       ...
RNU6-395P  2.247530e+03        0.090808  0.594318  0.220030  0.825847
ZNF33A     8.328743e+05        2.575914  0.205964  1.983232  0.047342
CHTF18     2.513434e+05        1.407995  0.336231 -0.600666  0.548063
ZC3H7B     6.089158e+05        1.632123  0.270249 -0.408624  0.682816
NOX4       5.119254e+04        1.279765  0.227303 -0.140276  0.888442

               padj
SPHKAP     0.999994
P2RX3      0.001048
SRSF5      0.999994
MFSD2A     0.999994
SMOC2      0.870199
...             ...
RNU6-395P  0.972124
ZNF33A     0.121481
CHTF18     0.785803
ZC3H7B     0.890552
NOX4       0.999994

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R2.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R2.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R2.csv
============================================================
[INFO] (53/160) sim_S20_G5000_CNstrong_R20.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=20
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.21 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.69 seconds.

Fitting LFCs...
... done in 0.74 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 498 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.17 seconds.

Fitting LFCs...
... done in 0.19 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.27 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                   baseMean  log2FoldChange     lfcSE      stat        pvalue  \
PRICKLE2-AS2     126.112332       -0.247285  0.796051 -0.595255  5.516729e-01
HCCAT5            67.868814        0.356222  0.944886 -1.492674  1.355224e-01
THY1          322913.775861        0.279781  0.539823  0.662247  5.078127e-01
PPARD         201890.310002       -1.641404  0.225560 -7.549810  4.358922e-14
FAM180A        51885.769633        0.848375  0.434524  2.326864  1.997251e-02
...                     ...             ...       ...       ...           ...
MYHAS           2228.947847       -0.520117  0.502550 -1.377391  1.683913e-01
SYCE1L         20948.288155       -0.358523  0.252344 -1.544243  1.225296e-01
SAR1B         349612.797238       -0.333949  0.271707 -1.423118  1.547019e-01
TXNL4B         87179.833280        0.373809  0.684783  0.911349  3.621118e-01
HSD17B6        37161.458044        1.365546  0.261923  5.449655  5.046753e-08

                      padj
PRICKLE2-AS2  7.526103e-01
HCCAT5        3.066310e-01
THY1          7.183094e-01
PPARD         8.054319e-13
FAM180A       6.491390e-02
...                    ...
MYHAS         3.577956e-01
SYCE1L        2.824861e-01
SAR1B         3.375274e-01
TXNL4B        5.952462e-01
HSD17B6       4.456328e-07

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.01 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 1.18 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 494 outlier genes.

Fitting dispersions...

replace_mask before filtering: (40, 494)
Number of True values in replace_mask: 1073
replacement_counts_trimmed shape: (40, 494)

... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.17 seconds.

Fitting LFCs...
... done in 0.16 seconds.

Running Wald tests...
... done in 0.43 seconds.

Fitting MAP LFCs...
... done in 2.03 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                   baseMean  log2FoldChange     lfcSE      stat        pvalue  \
PRICKLE2-AS2      36.615005       -0.919523  0.042995  0.000926  9.992612e-01
HCCAT5            23.126181        1.218397  0.055309 -0.058317  9.534964e-01
THY1          322913.775861        1.929485  0.396029  0.662247  5.078127e-01
PPARD         201890.310002        0.229067  0.243782 -9.360382  7.944897e-21
FAM180A        51885.769633        1.702458  0.427506  1.374449  1.693022e-01
...                     ...             ...       ...       ...           ...
MYHAS           2228.947847       -0.500437  0.499960 -1.377369  1.683982e-01
SYCE1L         20948.288155       -0.134937  0.257251 -1.544232  1.225322e-01
SAR1B         349612.797238        1.533614  0.202134 -1.423118  1.547021e-01
TXNL4B         87179.833280        2.013869  0.604384  0.911346  3.621130e-01
HSD17B6        37161.458044        2.105311  0.257720  4.071351  4.674123e-05

                      padj
PRICKLE2-AS2  9.999946e-01
HCCAT5        9.999946e-01
THY1          7.431733e-01
PPARD         1.172695e-19
FAM180A       3.566928e-01
...                    ...
MYHAS         3.550882e-01
SYCE1L        2.742545e-01
SAR1B         3.318794e-01
TXNL4B        6.076558e-01
HSD17B6       2.065474e-04

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R20.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R20.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R20.csv
============================================================
[INFO] (54/160) sim_S20_G5000_CNstrong_R3.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=3
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.31 seconds.

Fitting dispersion trend curve...
... done in 0.48 seconds.

Fitting MAP dispersions...
... done in 1.52 seconds.

Fitting LFCs...
... done in 1.19 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 498 outlier genes.

Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.13 seconds.

Fitting LFCs...
... done in 0.22 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.26 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SULT2B1   129529.376279        1.173021  0.630960  2.443637  1.454005e-02
MORN2      44948.142727       -1.210962  0.359768 -3.719112  1.999243e-04
PRR7-AS1    2644.978257        1.314553  0.414810  3.560007  3.708448e-04
FMO2      566149.066312       -0.397088  0.600094 -1.006987  3.139410e-01
NFYC      308342.689274       -0.018855  0.154659 -0.217442  8.278641e-01
...                 ...             ...       ...       ...           ...
GAS2        6220.513998       -1.685677  0.212008 -8.150757  3.616532e-16
AGMAT       8204.571975       -0.529088  0.903799 -1.353109  1.760207e-01
LIPT1      34131.247506        0.386846  0.198016  2.036831  4.166699e-02
PGPEP1     95049.187905       -1.441702  0.375103 -4.218078  2.463933e-05
ADAMTS15  377418.942109        0.155644  0.808286  0.440184  6.598036e-01

                  padj
SULT2B1   4.951154e-02
MORN2     1.038525e-03
PRR7-AS1  1.818524e-03
FMO2      5.434097e-01
NFYC      9.228610e-01
...                ...
GAS2      7.781780e-15
AGMAT     3.772843e-01
LIPT1     1.222101e-01
PGPEP1    1.471286e-04
ADAMTS15  8.250850e-01

[4992 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.02 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.54 seconds.

Fitting LFCs...
... done in 0.89 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 497 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 497)
Number of True values in replace_mask: 1105
replacement_counts_trimmed shape: (40, 497)

... done in 0.12 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.07 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
SULT2B1   129529.376279        2.306394  0.448417   1.719319  8.555636e-02
MORN2      44948.142727        0.197131  0.363367  -4.077086  4.560368e-05
PRR7-AS1    2644.978257        0.965661  0.413246   2.726715  6.396832e-03
FMO2      566149.066312        0.918400  0.347964  -2.570966  1.014153e-02
NFYC      308342.689274        1.994772  0.169285  -0.217440  8.278655e-01
...                 ...             ...       ...        ...           ...
GAS2        6220.513998       -2.065270  0.212847 -10.335037  4.892232e-25
AGMAT       8204.571975       -0.361462  0.787826  -1.353109  1.760208e-01
LIPT1      34131.247506        0.685483  0.206498   2.036816  4.166845e-02
PGPEP1     95049.187905        0.379598  0.374271  -5.196872  2.026702e-07
ADAMTS15  377418.942109        2.043682  0.466476   0.435056  6.635215e-01

                  padj
SULT2B1   2.073288e-01
MORN2     1.993464e-04
PRR7-AS1  2.023637e-02
FMO2      3.086981e-02
NFYC      9.692084e-01
...                ...
GAS2      8.250682e-24
AGMAT     3.643018e-01
LIPT1     1.113538e-01
PGPEP1    1.179172e-06
ADAMTS15  8.641533e-01

[4992 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R3.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R3.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R3.csv
============================================================
[INFO] (55/160) sim_S20_G5000_CNstrong_R4.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=4
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.32 seconds.

Fitting dispersion trend curve...
... done in 0.24 seconds.

Fitting MAP dispersions...
... done in 2.53 seconds.

Fitting LFCs...
... done in 1.56 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 481 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.39 seconds.

Fitting MAP dispersions...
... done in 0.40 seconds.

Fitting LFCs...
... done in 0.42 seconds.

Running Wald tests...
... done in 0.73 seconds.

Fitting MAP LFCs...
... done in 2.35 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
TCP11        5963.436007        1.022883  0.761440  2.044997  4.085519e-02
RNA5SP216   23994.465692        2.047337  0.237882  8.829771  1.048898e-18
EML5        88304.636563        0.183527  0.164280  1.136248  2.558528e-01
TEX19         892.880490        0.761958  1.182819  1.730385  8.356159e-02
PA2G4P5     33515.072932        1.093244  0.197027  5.719332  1.069435e-08
...                  ...             ...       ...       ...           ...
LINC02345     544.840507        0.075582  0.758626 -1.390739  1.643045e-01
DOCK1      440097.127081        0.213434  0.169989  1.238569  2.155051e-01
ANKRD39     88125.318145        0.252083  0.435294  0.720937  4.709485e-01
IFT81       91795.375468        0.015133  0.282276  0.029645  9.763503e-01
SCN3B       26272.437268       -0.315813  0.275357 -1.274265  2.025696e-01

                   padj
TCP11      1.221976e-01
RNA5SP216  2.645555e-17
EML5       4.847226e-01
TEX19      2.165044e-01
PA2G4P5    9.908647e-08
...                 ...
LINC02345  3.648452e-01
DOCK1      4.331293e-01
ANKRD39    7.003922e-01
IFT81      9.897668e-01
SCN3B      4.146035e-01

[4994 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.03 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.80 seconds.

Fitting dispersion trend curve...
... done in 0.44 seconds.

Fitting MAP dispersions...
... done in 2.29 seconds.

Fitting LFCs...
... done in 3.07 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 479 outlier genes.

replace_mask before filtering: (40, 479)
Number of True values in replace_mask: 1081
replacement_counts_trimmed shape: (40, 479)

Fitting dispersions...
... done in 0.24 seconds.

Fitting MAP dispersions...
... done in 0.32 seconds.

Fitting LFCs...
... done in 0.20 seconds.

Running Wald tests...
... done in 0.58 seconds.

Fitting MAP LFCs...
... done in 1.72 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat         pvalue  \
TCP11        5963.436007        0.631005  0.723009   1.381104   1.672469e-01
RNA5SP216   23994.465692        2.232586  0.247490   7.425279   1.125425e-13
EML5        88304.636563        1.960019  0.180471   1.136244   2.558546e-01
TEX19         301.559479        0.758291  0.017706 -13.281329   2.970753e-40
PA2G4P5     33515.072932        1.129224  0.205413   3.950270   7.806318e-05
...                  ...             ...       ...        ...            ...
LINC02345     217.132684        0.278321  0.018740 -26.305234  1.670759e-152
DOCK1      440097.127081        2.335238  0.152687   1.238568   2.155054e-01
ANKRD39     88125.318145        1.748838  0.398723   0.720936   4.709487e-01
IFT81       91795.375468        1.444697  0.286851   0.029645   9.763504e-01
SCN3B       26272.437268       -0.362134  0.274626  -1.274259   2.025717e-01

                    padj
TCP11       3.525733e-01
RNA5SP216   1.040810e-12
EML5        4.803527e-01
TEX19       6.367356e-39
PA2G4P5     3.264096e-04
...                  ...
LINC02345  4.937143e-151
DOCK1       4.242152e-01
ANKRD39     7.122708e-01
IFT81       9.999982e-01
SCN3B       4.054682e-01

[4994 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R4.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R4.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R4.csv
============================================================
[INFO] (56/160) sim_S20_G5000_CNstrong_R5.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=5
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.92 seconds.

Fitting dispersion trend curve...
... done in 0.19 seconds.

Fitting MAP dispersions...
... done in 2.67 seconds.

Fitting LFCs...
... done in 1.19 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 454 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.26 seconds.

Fitting MAP dispersions...
... done in 0.23 seconds.

Fitting LFCs...
... done in 0.28 seconds.

Running Wald tests...
... done in 0.55 seconds.

Fitting MAP LFCs...
... done in 1.86 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
MLYCD      9.840582e+04       -0.317751  0.362405  -1.055535  2.911809e-01
RPL26      1.972588e+06        0.171687  0.206647   0.986473  3.239008e-01
FASTKD5    1.922792e+05        1.224771  0.271021   4.810117  1.508420e-06
ADCY10     3.286628e+03       -0.039220  0.492084  -0.116256  9.074495e-01
UPK2       4.400744e+03        0.171806  0.394966   0.523141  6.008760e-01
...                 ...             ...       ...        ...           ...
RPS15AP14  4.727782e+01       -0.523127  0.874340   0.282069  7.778902e-01
POMT2      1.379725e+05        0.304258  0.889779   0.816176  4.143992e-01
NKX2-8     5.376214e+02       -0.409670  0.128103  -3.264855  1.095202e-03
NHLH1      1.850757e+03       -0.242597  0.356162  -0.798511  4.245739e-01
REEP1      1.432951e+05        2.070933  0.191225  10.932689  8.042878e-28

                   padj
MLYCD      5.180010e-01
RPL26      5.504990e-01
FASTKD5    1.073754e-05
ADCY10     9.551092e-01
UPK2       7.794051e-01
...                 ...
RPS15AP14  8.931148e-01
POMT2      6.379458e-01
NKX2-8     4.883877e-03
NHLH1      6.460999e-01
REEP1      3.551678e-26

[4990 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.03 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.60 seconds.

Fitting dispersion trend curve...
... done in 0.27 seconds.

Fitting MAP dispersions...
... done in 2.00 seconds.

Fitting LFCs...
... done in 1.39 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 449 outlier genes.

replace_mask before filtering: (40, 449)
Number of True values in replace_mask: 985
replacement_counts_trimmed shape: (40, 449)

Fitting dispersions...
... done in 0.23 seconds.

Fitting MAP dispersions...
... done in 0.31 seconds.

Fitting LFCs...
... done in 0.19 seconds.

Running Wald tests...
... done in 0.62 seconds.

Fitting MAP LFCs...
... done in 1.77 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
MLYCD      9.840582e+04        1.292143  0.349077 -1.055534  2.911812e-01
RPL26      1.972588e+06        2.249918  0.097467  0.986473  3.239009e-01
FASTKD5    1.922792e+05        1.635821  0.227939  0.929594  3.525811e-01
ADCY10     3.286628e+03       -0.786810  0.539523 -2.044436  4.091052e-02
UPK2       4.400744e+03        0.111514  0.389369  0.523135  6.008802e-01
...                 ...             ...       ...       ...           ...
RPS15AP14  2.065917e+01       -1.531767  0.053630 -0.036074  9.712232e-01
POMT2      1.379725e+05        2.223571  0.723717  0.816128  4.144267e-01
NKX2-8     5.376214e+02       -0.865311  0.128657 -6.827341  8.650294e-12
NHLH1      1.850757e+03       -1.398612  0.376597 -4.148187  3.351187e-05
REEP1      1.432951e+05        2.838588  0.188704  9.358897  8.057343e-21

                   padj
MLYCD      5.191120e-01
RPL26      5.559909e-01
FASTKD5    5.868512e-01
ADCY10     1.082989e-01
UPK2       8.105954e-01
...                 ...
RPS15AP14  9.999979e-01
POMT2      6.546342e-01
NKX2-8     7.520029e-11
NHLH1      1.505169e-04
REEP1      1.214687e-19

[4990 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R5.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R5.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R5.csv
============================================================
[INFO] (57/160) sim_S20_G5000_CNstrong_R6.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=6
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.85 seconds.

Fitting dispersion trend curve...
... done in 0.46 seconds.

Fitting MAP dispersions...
... done in 1.98 seconds.

Fitting LFCs...
... done in 0.99 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 488 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.25 seconds.

Fitting MAP dispersions...
... done in 0.24 seconds.

Fitting LFCs...
... done in 0.27 seconds.

Running Wald tests...
... done in 0.47 seconds.

Fitting MAP LFCs...
... done in 2.61 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SYCP2L        5303.932611       -2.161903  0.442048 -5.274630  1.330245e-07
RNA5SP187      171.182484       -1.027210  0.779494 -2.055699  3.981152e-02
PRR13       431287.324681       -0.233099  0.226058 -1.115770  2.645205e-01
SLC44A3      44727.233189       -0.187144  0.392414 -0.586180  5.577544e-01
CCDC92      311925.040572       -0.611822  0.247489 -2.627105  8.611472e-03
...                   ...             ...       ...       ...           ...
MTSS1       167815.147445       -0.412819  0.692145 -3.430190  6.031580e-04
GRHL2       328663.763078       -0.281225  0.220938 -1.383796  1.664210e-01
SHC2        199421.340244       -0.035296  0.597295 -0.119743  9.046868e-01
ZNF829       13890.404790        1.520616  1.191428  1.370692  1.704709e-01
RNU6-1330P     442.782553       -0.204442  0.381654 -0.644354  5.193460e-01

                padj
SYCP2L      0.000001
RNA5SP187   0.116973
PRR13       0.493343
SLC44A3     0.763412
CCDC92      0.031100
...              ...
MTSS1       0.002818
GRHL2       0.358805
SHC2        0.962917
ZNF829      0.365326
RNU6-1330P  0.732961

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.49 seconds.

Fitting dispersion trend curve...
... done in 0.15 seconds.

Fitting MAP dispersions...
... done in 1.90 seconds.

Fitting LFCs...
... done in 1.33 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 484 outlier genes.

replace_mask before filtering: (40, 484)
Number of True values in replace_mask: 1095
replacement_counts_trimmed shape: (40, 484)

Fitting dispersions...
... done in 0.16 seconds.

Fitting MAP dispersions...
... done in 0.27 seconds.

Fitting LFCs...
... done in 0.14 seconds.

Running Wald tests...
... done in 0.49 seconds.

Fitting MAP LFCs...
... done in 1.52 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
SYCP2L        5303.932611       -2.764792  0.434697  -6.420770  1.355869e-10
RNA5SP187      171.182484       -0.978918  0.785640  -2.055432  3.983727e-02
PRR13       431287.324681        1.734164  0.182842  -1.115770  2.645207e-01
SLC44A3      44727.233189        1.089233  0.425020  -0.586180  5.577549e-01
CCDC92      311925.040572        1.405328  0.211678  -2.627104  8.611506e-03
...                   ...             ...       ...        ...           ...
MTSS1        56995.423121       -1.991135  0.001559   0.000279  9.997775e-01
GRHL2       328663.763078        0.575990  0.198148  -6.462615  1.029086e-10
SHC2        199421.340244        1.530035  0.564190  -0.119743  9.046867e-01
ZNF829        4910.659977        1.526684  0.004912 -57.195948  0.000000e+00
RNU6-1330P     442.782553       -0.197342  0.378231  -0.644267  5.194022e-01

                    padj
SYCP2L      1.003624e-09
RNA5SP187   1.041111e-01
PRR13       4.913231e-01
SLC44A3     7.851691e-01
CCDC92      2.648755e-02
...                  ...
MTSS1       9.999896e-01
GRHL2       7.662851e-10
SHC2        9.999896e-01
ZNF829      0.000000e+00
RNU6-1330P  7.511008e-01

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R6.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R6.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R6.csv
============================================================
[INFO] (58/160) sim_S20_G5000_CNstrong_R7.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=7
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.51 seconds.

Fitting dispersion trend curve...
... done in 0.16 seconds.

Fitting MAP dispersions...
... done in 2.06 seconds.

Fitting LFCs...
... done in 1.34 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 477 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.30 seconds.

Fitting MAP dispersions...
... done in 0.28 seconds.

Fitting LFCs...
... done in 0.35 seconds.

Running Wald tests...
... done in 0.59 seconds.

Fitting MAP LFCs...
... done in 2.25 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC01908  9.004229e+00        0.400210  1.093820   1.383916  1.663843e-01
PCSK6      1.688637e+05       -1.216236  0.574321  -2.708615  6.756468e-03
NRF1       2.795190e+05        2.010213  0.116242  17.546875  6.284437e-69
EFCAB11    3.474259e+04       -0.859709  0.299962  -3.144196  1.665441e-03
VANGL1     1.936414e+05        0.307661  0.460962   0.839701  4.010759e-01
...                 ...             ...       ...        ...           ...
RCN1       1.209648e+06        0.620940  1.104845   1.503793  1.326346e-01
UBE2D1     4.915516e+04       -1.004251  0.992934  -1.972502  4.855233e-02
ZNF512     1.729879e+05       -1.053786  0.543507  -2.484925  1.295787e-02
PRR22      1.545997e+04       -0.049338  0.212381  -0.262724  7.927633e-01
CACNA1G    3.258056e+04        1.412188  0.232429   6.295706  3.060037e-10

                   padj
LINC01908  3.629740e-01
PCSK6      2.479360e-02
NRF1       3.917561e-66
EFCAB11    6.944444e-03
VANGL1     6.435540e-01
...                 ...
RCN1       3.073646e-01
UBE2D1     1.401262e-01
ZNF512     4.450474e-02
PRR22      9.106072e-01
CACNA1G    3.391201e-09

[4987 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.59 seconds.

Fitting dispersion trend curve...
... done in 0.19 seconds.

Fitting MAP dispersions...
... done in 2.06 seconds.

Fitting LFCs...
... done in 1.33 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

Replacing 472 outlier genes.

replace_mask before filtering: (40, 472)
Number of True values in replace_mask: 1018
replacement_counts_trimmed shape: (40, 472)

Fitting dispersions...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 0.27 seconds.

Fitting LFCs...
... done in 0.16 seconds.

Running Wald tests...
... done in 0.44 seconds.

Fitting MAP LFCs...
... done in 1.79 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC01908  2.547870e+00        1.649993  0.150936  -0.122898  9.021876e-01
PCSK6      1.688637e+05        0.687172  0.522411  -2.707877  6.771518e-03
NRF1       2.795190e+05        3.546529  0.126421  12.819339  1.277845e-37
EFCAB11    3.474259e+04        0.179932  0.309520  -3.144185  1.665503e-03
VANGL1     1.936414e+05        1.828758  0.403708   0.839701  4.010761e-01
...                 ...             ...       ...        ...           ...
RCN1       1.209648e+06        2.778415  0.279093   1.289960  1.970646e-01
UBE2D1     4.915516e+04        0.234049  0.654156  -1.972471  4.855582e-02
ZNF512     1.729879e+05        0.583968  0.495329  -3.016644  2.555895e-03
PRR22      1.545997e+04       -0.142663  0.208071  -0.262721  7.927660e-01
CACNA1G    3.258056e+04        1.210077  0.240907   1.011757  3.116540e-01

                   padj
LINC01908  9.999991e-01
PCSK6      2.135962e-02
NRF1       2.758707e-36
EFCAB11    5.804236e-03
VANGL1     6.483521e-01
...                 ...
RCN1       3.961337e-01
UBE2D1     1.264480e-01
ZNF512     8.618154e-03
PRR22      9.494377e-01
CACNA1G    5.477988e-01

[4987 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R7.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R7.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R7.csv
============================================================
[INFO] (59/160) sim_S20_G5000_CNstrong_R8.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=8
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.50 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.90 seconds.

Fitting LFCs...
... done in 0.97 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 486 outlier genes.

Fitting dispersions...
... done in 0.15 seconds.

Fitting MAP dispersions...
... done in 0.26 seconds.

Fitting LFCs...
... done in 0.24 seconds.

Running Wald tests...
... done in 0.44 seconds.

Fitting MAP LFCs...
... done in 1.69 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
ZNF542P     207041.354847        1.816422  0.277226   6.764583  1.336940e-11
RFX7        142944.980090       -0.231823  0.200471  -1.216280  2.238783e-01
GEMIN7-AS1   14025.291853       -2.631171  0.234919 -11.380992  5.200502e-30
MIR6774        272.454929        0.345723  0.722568   0.869758  3.844327e-01
RMDN1       183646.830777       -0.494759  0.269467  -2.026333  4.273068e-02
...                   ...             ...       ...        ...           ...
LCNL1         6227.876213        0.041314  0.397879   0.122536  9.024744e-01
ENDOD1      268501.173059       -0.127673  0.817002  -0.426649  6.696346e-01
ZNF335      216631.436792        0.185617  0.676304   0.458724  6.464321e-01
PGF          43873.340883       -0.357274  0.515006  -0.965053  3.345184e-01
PKNOX2       13244.606017        0.147268  0.522035   0.393960  6.936107e-01

                    padj
ZNF542P     1.838200e-10
RFX7        4.441083e-01
GEMIN7-AS1  4.255033e-28
MIR6774     6.247814e-01
RMDN1       1.245002e-01
...                  ...
LCNL1       9.575016e-01
ENDOD1      8.322078e-01
ZNF335      8.199092e-01
PGF         5.717587e-01
PKNOX2      8.474832e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.41 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.82 seconds.

Fitting LFCs...
... done in 1.25 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 482 outlier genes.

Fitting dispersions...

replace_mask before filtering: (40, 482)
Number of True values in replace_mask: 1032
replacement_counts_trimmed shape: (40, 482)

... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.23 seconds.

Fitting LFCs...
... done in 0.14 seconds.

Running Wald tests...
... done in 0.42 seconds.

Fitting MAP LFCs...
... done in 1.48 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
ZNF542P     207041.354847        2.645774  0.210534   5.238634  1.617694e-07
RFX7        142944.980090        1.568213  0.197951  -1.216278  2.238791e-01
GEMIN7-AS1   14025.291853       -3.121150  0.235391 -13.007321  1.111715e-38
MIR6774        272.454929        0.329016  0.712771   0.869712  3.844577e-01
RMDN1       183646.830777        6.122784  0.353925  10.577292  3.797745e-26
...                   ...             ...       ...        ...           ...
LCNL1         6227.876213       -0.070790  0.394467   0.122535  9.024752e-01
ENDOD1      268501.173059        1.379349  0.739969  -0.426641  6.696408e-01
ZNF335      216631.436792        1.354984  0.426214  -0.809096  4.184598e-01
PGF          43873.340883        0.924193  0.556350  -0.965052  3.345188e-01
PKNOX2       13244.606017        0.129644  0.523508   0.393959  6.936113e-01

                    padj
ZNF542P     9.280358e-07
RFX7        4.324228e-01
GEMIN7-AS1  2.381361e-37
MIR6774     6.242122e-01
RMDN1       6.513589e-25
...                  ...
LCNL1       9.999931e-01
ENDOD1      8.584887e-01
ZNF335      6.573915e-01
PGF         5.703922e-01
PKNOX2      8.739594e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R8.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R8.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R8.csv
============================================================
[INFO] (60/160) sim_S20_G5000_CNstrong_R9.pkl
[INFO] Running analysis for S=20, G=5000, CN=strong, R=9
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.46 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.95 seconds.

Fitting LFCs...
... done in 1.02 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 509 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.19 seconds.

Fitting MAP dispersions...
... done in 0.23 seconds.

Fitting LFCs...
... done in 0.27 seconds.

Running Wald tests...
... done in 0.41 seconds.

Fitting MAP LFCs...
... done in 2.26 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
VN1R81P      2.127107e+03       -1.055589  0.414243 -2.930280  0.003387
MIR7844      1.768628e+03       -0.928876  0.452886 -2.452772  0.014176
CFAP69       4.005310e+04       -1.248925  0.422895 -3.364751  0.000766
BCAR3        2.388447e+05        0.122482  0.361734  0.362736  0.716802
CEP57        2.563413e+05        0.344281  0.185888  1.818122  0.069046
...                   ...             ...       ...       ...       ...
ARPC4-TTLL3  1.198529e+06        1.155363  0.251476  4.750717  0.000002
SRGAP3-AS4   9.574134e+01       -1.062549  0.364966 -3.246609  0.001168
GPR45        3.065862e+02        0.379042  0.847154  0.943253  0.345551
SULT4A1      8.930091e+03       -0.468295  0.532228 -1.204435  0.228421
GTSE1-DT     2.800736e+03       -0.171820  0.195689 -0.925124  0.354901

                 padj
VN1R81P      0.012885
MIR7844      0.046125
CFAP69       0.003332
BCAR3        0.861129
CEP57        0.178445
...               ...
ARPC4-TTLL3  0.000013
SRGAP3-AS4   0.004883
GPR45        0.583338
SULT4A1      0.439740
GTSE1-DT     0.591873

[4988 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.44 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.90 seconds.

Fitting LFCs...
... done in 1.27 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 507 outlier genes.

Fitting dispersions...

replace_mask before filtering: (40, 507)
Number of True values in replace_mask: 1129
replacement_counts_trimmed shape: (40, 507)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.25 seconds.

Fitting LFCs...
... done in 0.12 seconds.

Running Wald tests...
... done in 0.49 seconds.

Fitting MAP LFCs...
... done in 1.47 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
VN1R81P      2.127107e+03       -1.335111  0.416381 -3.663921  0.000248
MIR7844      1.768628e+03       -1.298382  0.459152 -3.349741  0.000809
CFAP69       4.005310e+04       -0.197904  0.420411 -4.639988  0.000003
BCAR3        2.388447e+05        1.638421  0.318926  0.362736  0.716802
CEP57        2.563413e+05        1.950168  0.186549  1.818113  0.069047
...                   ...             ...       ...       ...       ...
ARPC4-TTLL3  1.198529e+06        2.346666  0.138556  3.418361  0.000630
SRGAP3-AS4   9.574134e+01       -1.181966  0.366848 -3.588651  0.000332
GPR45        3.065862e+02        0.340993  0.826121  0.943221  0.345568
SULT4A1      8.930091e+03       -0.381481  0.527581 -1.204431  0.228423
GTSE1-DT     2.800736e+03       -0.149557  0.195640 -0.925043  0.354943

                 padj
VN1R81P      0.000918
MIR7844      0.002788
CFAP69       0.000016
BCAR3        0.890957
CEP57        0.164416
...               ...
ARPC4-TTLL3  0.002202
SRGAP3-AS4   0.001208
GPR45        0.579365
SULT4A1      0.430115
GTSE1-DT     0.589171

[4988 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNstrong_R9.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNstrong_R9.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNstrong_R9.csv
============================================================
[INFO] (61/160) sim_S20_G5000_CNweak_R1.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=1
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.58 seconds.

Fitting dispersion trend curve...
... done in 0.20 seconds.

Fitting MAP dispersions...
... done in 2.13 seconds.

Fitting LFCs...
... done in 1.12 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 511 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.26 seconds.

Fitting MAP dispersions...
... done in 0.29 seconds.

Fitting LFCs...
... done in 0.35 seconds.

Running Wald tests...
... done in 0.66 seconds.

Fitting MAP LFCs...
... done in 1.78 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
JMJD6       2.348912e+05        0.460772  0.235063   1.993734  4.618113e-02
PLA2G12AP1  4.040252e+03       -0.112762  0.213016  -0.566737  5.708930e-01
VEGFA       6.364051e+06        2.568976  0.684330   3.210341  1.325777e-03
RHO         1.044427e+03        2.473607  1.034593   3.212609  1.315351e-03
TK1         1.814216e+05       -0.308562  0.584076  -0.815308  4.148962e-01
...                  ...             ...       ...        ...           ...
SCN9A       1.276627e+04        0.143567  0.336155   0.483151  6.289887e-01
BCL2L2      5.062225e+05        0.835128  0.839876   0.022286  9.822200e-01
NADSYN1     5.880083e+05        0.871765  0.216608   4.155398  3.247217e-05
CUL7        1.331017e+06        2.650397  0.190481  13.992993  1.720178e-44
POGK        3.784505e+05       -0.103813  0.506254  -0.310623  7.560874e-01

                    padj
JMJD6       1.359021e-01
PLA2G12AP1  7.624700e-01
VEGFA       6.326251e-03
RHO         6.300303e-03
TK1         6.432888e-01
...                  ...
SCN9A       8.035021e-01
BCL2L2      9.935671e-01
NADSYN1     2.138108e-04
CUL7        3.066218e-42
POGK        8.818800e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 2.02 seconds.

Fitting dispersion trend curve...
... done in 0.23 seconds.

Fitting MAP dispersions...
... done in 2.13 seconds.

Fitting LFCs...
... done in 1.49 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 509 outlier genes.

replace_mask before filtering: (40, 509)
Number of True values in replace_mask: 1104
replacement_counts_trimmed shape: (40, 509)

Fitting dispersions...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.34 seconds.

Fitting LFCs...
... done in 0.13 seconds.

Running Wald tests...
... done in 0.48 seconds.

Fitting MAP LFCs...
... done in 1.68 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE        stat        pvalue  \
JMJD6       2.348912e+05        1.286488  0.206992   -1.407104  1.593964e-01
PLA2G12AP1  4.040252e+03       -0.089456  0.212558   -0.566708  5.709127e-01
VEGFA       6.364051e+06        2.908053  0.076727    2.534486  1.126126e-02
RHO         1.044427e+03        1.905694  1.054765    2.760394  5.773169e-03
TK1         1.814216e+05        1.879888  0.509506    0.476300  6.338607e-01
...                  ...             ...       ...         ...           ...
SCN9A       1.276627e+04        0.037064  0.328642    0.483148  6.289908e-01
BCL2L2      2.243174e+05        1.396893  0.000897 -314.164576  0.000000e+00
NADSYN1     5.880083e+05        1.816022  0.142383    0.694660  4.872686e-01
CUL7        1.331017e+06        3.502767  0.092317   11.949721  6.514392e-33
POGK        3.784505e+05        1.203556  0.330073   -1.712459  8.681202e-02

                    padj
JMJD6       3.352497e-01
PLA2G12AP1  7.926079e-01
VEGFA       3.456638e-02
RHO         1.883261e-02
TK1         8.409353e-01
...                  ...
SCN9A       8.373681e-01
BCL2L2      0.000000e+00
NADSYN1     7.223378e-01
CUL7        1.265110e-31
POGK        2.082437e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R1.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R1.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R1.csv
============================================================
[INFO] (62/160) sim_S20_G5000_CNweak_R10.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=10
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 2.23 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.88 seconds.

Fitting LFCs...
... done in 1.17 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 487 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.19 seconds.

Fitting MAP dispersions...
... done in 0.23 seconds.

Fitting LFCs...
... done in 0.28 seconds.

Running Wald tests...
... done in 0.43 seconds.

Fitting MAP LFCs...
... done in 1.71 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CCL18     40174.649143       -0.739740  0.692416 -1.699477  0.089229  0.229598
TMPRSS3  121323.061852       -0.280052  0.714609 -0.758033  0.448431  0.670105
NPC2     863302.477946        0.052346  0.278581  0.267636  0.788979  0.903835
GZMH       6198.271952       -0.086494  0.496889 -0.249413  0.803041  0.909519
OTOGL      3656.243300       -2.107417  0.567225 -4.225842  0.000024  0.000158
...                ...             ...       ...       ...       ...       ...
CCDC196     335.508582       -0.343319  0.785663 -0.992318  0.321043  0.551612
PBOV1       195.390775       -0.596299  0.258481 -2.495229  0.012588  0.047352
CDHR2      7456.272662        0.153116  0.930964  0.478448  0.632332  0.807503
FAM215A     249.780008        0.426186  0.282275  1.666420  0.095630  0.240736
POLD3     20983.123968       -0.291366  0.824255 -0.325402  0.744877  0.878072

[4997 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.41 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.85 seconds.

Fitting LFCs...
... done in 1.27 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 487 outlier genes.

replace_mask before filtering: (40, 487)
Number of True values in replace_mask: 1041
replacement_counts_trimmed shape: (40, 487)

Fitting dispersions...
... done in 0.20 seconds.

Fitting MAP dispersions...
... done in 0.31 seconds.

Fitting LFCs...
... done in 0.17 seconds.

Running Wald tests...
... done in 0.55 seconds.

Fitting MAP LFCs...
... done in 1.60 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CCL18     40174.649143        0.477579  0.622283 -1.699476  0.089230  0.211719
TMPRSS3  121323.061852        0.832747  0.733265 -1.425461  0.154024  0.329901
NPC2     863302.477946        1.869406  0.180364  0.267636  0.788979  0.944545
GZMH       6198.271952       -0.213985  0.498230 -0.249412  0.803042  0.952707
OTOGL      3656.243300       -2.393277  0.565974 -4.793917  0.000002  0.000009
...                ...             ...       ...       ...       ...       ...
CCDC196     143.622221       -1.039990  0.028694  0.001230  0.999019  0.999999
PBOV1       195.390775       -0.927792  0.261460 -3.807313  0.000140  0.000613
CDHR2      7456.272662        0.807339  1.221734  0.196380  0.844313  0.975499
FAM215A     249.780008        0.419396  0.281795  1.665626  0.095788  0.223984
POLD3      3786.256631       -1.288350  0.005427 -0.002303  0.998162  0.999999

[4997 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R10.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R10.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R10.csv
============================================================
[INFO] (63/160) sim_S20_G5000_CNweak_R11.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=11
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.49 seconds.

Fitting dispersion trend curve...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 1.87 seconds.

Fitting LFCs...
... done in 1.03 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 483 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.19 seconds.

Fitting MAP dispersions...
... done in 0.23 seconds.

Fitting LFCs...
... done in 0.27 seconds.

Running Wald tests...
... done in 0.43 seconds.

Fitting MAP LFCs...
... done in 1.77 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat        pvalue  \
OSGEPL1-AS1    2034.698221        0.067947  0.250497  0.294288  7.685378e-01
CPLANE1      183307.372378        0.640503  0.252577  2.693709  7.066184e-03
NPEPL1       275774.551009       -0.657903  0.495829 -1.728413  8.391416e-02
ZNF467       332718.116066        2.128536  0.437035  5.251496  1.508691e-07
ABHD17A      290356.653217        0.275627  0.227809  1.261899  2.069851e-01
...                    ...             ...       ...       ...           ...
TGDS          70009.662889        0.130759  0.256387  0.538945  5.899247e-01
NPAP1           314.569192       -0.073140  0.550129 -0.201286  8.404752e-01
NOD1         186316.886283        0.226037  0.446207  0.588537  5.561718e-01
NT5C1B         4842.408385        1.808520  0.247303  7.540859  4.668862e-14
NHP2P2          612.530802        0.661764  0.195588  3.526069  4.217765e-04

                     padj
OSGEPL1-AS1  8.903835e-01
CPLANE1      2.731784e-02
NPEPL1       2.207778e-01
ZNF467       1.300497e-06
ABHD17A      4.235599e-01
...                   ...
TGDS         7.887007e-01
NPAP1        9.253979e-01
NOD1         7.687256e-01
NT5C1B       7.953000e-13
NHP2P2       2.132813e-03

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.37 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.86 seconds.

Fitting LFCs...
... done in 1.81 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 480 outlier genes.

Fitting dispersions...

replace_mask before filtering: (40, 480)
Number of True values in replace_mask: 1083
replacement_counts_trimmed shape: (40, 480)

... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.28 seconds.

Fitting LFCs...
... done in 0.12 seconds.

Running Wald tests...
... done in 0.46 seconds.

Fitting MAP LFCs...
... done in 1.51 seconds.

R callback write-console: Removing 1 features with NA screening hypothesis p-values.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat        pvalue  \
OSGEPL1-AS1    2034.698221        0.067305  0.249604  0.294267  7.685539e-01
CPLANE1      183307.372378        1.532313  0.224875  0.188996  8.500957e-01
NPEPL1       275774.551009        0.866787  0.358720 -3.069435  2.144642e-03
ZNF467       332718.116066        3.142290  0.289084  4.775641  1.791359e-06
ABHD17A      290356.653217        1.953299  0.192821  1.261898  2.069854e-01
...                    ...             ...       ...       ...           ...
TGDS          70009.662889        1.382378  0.273473  0.538944  5.899254e-01
NPAP1           314.569192       -0.068760  0.539040 -0.201271  8.404870e-01
NOD1         186316.886283        1.435331  0.351733 -0.684771  4.934887e-01
NT5C1B         4842.408385        1.480284  0.248114  6.184417  6.233230e-10
NHP2P2          612.530802       -0.002798  0.192911 -0.021223  9.830681e-01

                     padj
OSGEPL1-AS1  9.274689e-01
CPLANE1      9.744952e-01
NPEPL1       7.541764e-03
ZNF467       9.469152e-06
ABHD17A      4.148020e-01
...                   ...
TGDS         8.118056e-01
NPAP1        9.690457e-01
NOD1         7.418061e-01
NT5C1B       4.614810e-09
NHP2P2       9.999968e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R11.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R11.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R11.csv
============================================================
[INFO] (64/160) sim_S20_G5000_CNweak_R12.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=12
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.45 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.93 seconds.

Fitting LFCs...
... done in 0.99 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 456 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.21 seconds.

Fitting MAP dispersions...
... done in 0.24 seconds.

Fitting LFCs...
... done in 0.26 seconds.

Running Wald tests...
... done in 0.47 seconds.

Fitting MAP LFCs...
... done in 1.97 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
PCGF1     63598.422262       -0.257031  0.217612 -1.272223  0.203294  0.416352
NPAS3     13616.522838       -0.877911  0.464289 -2.316267  0.020544  0.069865
USP8     315236.484148       -0.104909  0.165070 -0.655049  0.512436  0.740630
YRDC      95199.522014       -0.003814  0.260994 -0.032615  0.973982  0.990806
OSR2     206562.507814        0.824829  0.439176  2.303234  0.021266  0.071637
...                ...             ...       ...       ...       ...       ...
SLC10A7   59580.162758        0.383091  0.298150  1.415305  0.156979  0.347458
MYOM1     83629.957323        0.357430  0.672609  0.887786  0.374656  0.621396
ZNF644   265551.480422       -0.235606  0.273112 -0.963659  0.335217  0.582311
FABP9       365.002607       -0.930040  0.525540 -2.259975  0.023823  0.078710
DCAF1    489964.032822       -0.015455  0.690710 -0.086589  0.930998  0.972749

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.03 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.99 seconds.

Fitting dispersion trend curve...
... done in 0.16 seconds.

Fitting MAP dispersions...
... done in 2.70 seconds.

Fitting LFCs...
... done in 1.56 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 452 outlier genes.

replace_mask before filtering: (40, 452)
Number of True values in replace_mask: 1007
replacement_counts_trimmed shape: (40, 452)

Fitting dispersions...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 0.32 seconds.

Fitting LFCs...
... done in 0.14 seconds.

Running Wald tests...
... done in 0.49 seconds.

Fitting MAP LFCs...
... done in 1.60 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
PCGF1     63598.422262        0.958730  0.231242 -2.571742  0.010119  0.031830
NPAS3     13616.522838       -0.692452  0.479467 -3.054921  0.002251  0.007971
USP8     315236.484148        1.959931  0.169507 -0.655048  0.512437  0.762090
YRDC      95199.522014        1.395118  0.269294 -0.032615  0.973982  0.999999
OSR2     206562.507814        3.051581  0.321768  4.268147  0.000020  0.000096
...                ...             ...       ...       ...       ...       ...
SLC10A7   59580.162758        1.590555  0.308664  1.415302  0.156980  0.339330
MYOM1     83629.957323        1.979789  0.608583  0.887788  0.374655  0.630406
ZNF644   265551.480422        1.542415  0.219347 -0.963658  0.335217  0.587219
FABP9       365.002607       -1.679669  0.540883 -3.673078  0.000240  0.001001
DCAF1    489964.032822        1.735134  0.361719 -0.086590  0.930998  0.999999

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R12.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R12.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R12.csv
============================================================
[INFO] (65/160) sim_S20_G5000_CNweak_R13.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=13
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.58 seconds.

Fitting dispersion trend curve...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 2.05 seconds.

Fitting LFCs...
... done in 1.71 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 493 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.16 seconds.

Fitting MAP dispersions...
... done in 0.34 seconds.

Fitting LFCs...
... done in 0.29 seconds.

Running Wald tests...
... done in 0.46 seconds.

Fitting MAP LFCs...
... done in 1.83 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
EPDR1       81230.276217       -0.168174  0.417847  -0.520003  6.030614e-01
INTS12     133231.823666        0.311770  0.158987   1.953494  5.076113e-02
LINC00943     676.395655        0.278029  0.625131   0.730323  4.651929e-01
PCDH9       21177.535618       -0.057974  0.569481  -0.167796  8.667434e-01
LRGUK       22677.400986        2.426294  0.501428   5.235349  1.646730e-07
...                  ...             ...       ...        ...           ...
MIR155HG     5812.148998       -0.545145  0.168352  -3.359822  7.799273e-04
TNFAIP3    239185.562164       -1.171247  0.248126  -5.013294  5.350611e-07
CRYBG3     179499.297108       -2.163910  0.181409 -12.132388  7.114424e-34
ATXN3      144311.508489       -1.394933  0.520196  -3.220363  1.280286e-03
NCR1          511.259768       -1.014115  0.210211  -5.027155  4.978095e-07

                   padj
EPDR1      7.839209e-01
INTS12     1.494224e-01
LINC00943  6.848024e-01
PCDH9      9.344401e-01
LRGUK      1.631343e-06
...                 ...
MIR155HG   4.122714e-03
TNFAIP3    4.928299e-06
CRYBG3     6.565033e-32
ATXN3      6.386051e-03
NCR1       4.602474e-06

[4983 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.43 seconds.

Fitting dispersion trend curve...
... done in 0.51 seconds.

Fitting MAP dispersions...
... done in 2.05 seconds.

Fitting LFCs...
... done in 1.40 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 491 outlier genes.

replace_mask before filtering: (40, 491)
Number of True values in replace_mask: 1077
replacement_counts_trimmed shape: (40, 491)

Fitting dispersions...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 0.29 seconds.

Fitting LFCs...
... done in 0.12 seconds.

Running Wald tests...
... done in 0.46 seconds.

Fitting MAP LFCs...
... done in 1.54 seconds.

R callback write-console: Removing 1 features with NA screening hypothesis p-values.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
EPDR1       81230.276217        0.984368  0.429034  -1.544764  1.224033e-01
INTS12     133231.823666        2.253953  0.168048   1.953488  5.076178e-02
LINC00943     676.395655        0.258163  0.614341   0.730303  4.652052e-01
PCDH9       21177.535618        0.813781  0.679885  -0.167796  8.667435e-01
LRGUK       22677.400986        3.009020  0.498409   4.832379  1.349113e-06
...                  ...             ...       ...        ...           ...
MIR155HG     5812.148998       -0.906800  0.169464  -5.640723  1.693378e-08
TNFAIP3    239185.562164        0.655925  0.242335  -6.565646  5.180779e-11
CRYBG3     179499.297108        0.213217  0.220657 -13.317438  1.832900e-40
ATXN3      144311.508489        0.570745  0.491467  -3.220347  1.280355e-03
NCR1          511.259768       -1.496728  0.210869  -7.344477  2.065654e-13

                   padj
EPDR1      2.793465e-01
INTS12     1.340197e-01
LINC00943  7.004086e-01
PCDH9      9.810408e-01
LRGUK      7.725610e-06
...                 ...
MIR155HG   1.181570e-07
TNFAIP3    4.552141e-10
CRYBG3     4.611872e-39
ATXN3      4.778073e-03
NCR1       2.166545e-12

[4983 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R13.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R13.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R13.csv
============================================================
[INFO] (66/160) sim_S20_G5000_CNweak_R14.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=14
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.61 seconds.

Fitting dispersion trend curve...
... done in 0.15 seconds.

Fitting MAP dispersions...
... done in 2.38 seconds.

Fitting LFCs...
... done in 1.11 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 488 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 0.20 seconds.

Fitting LFCs...
... done in 0.25 seconds.

Running Wald tests...
... done in 0.38 seconds.

Fitting MAP LFCs...
... done in 1.62 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
MIA3       4.880297e+05       -0.653033  0.280944 -2.530344  0.011395
CTNNB1     2.289031e+06        0.059856  0.256455  0.412435  0.680021
DDX10      1.530128e+05        0.064254  0.198335  0.290841  0.771173
RNU6-322P  4.257441e+02       -0.306189  0.567707 -0.808484  0.418812
RN7SL130P  7.547578e+02       -0.128244  0.529435 -0.355566  0.722166
...                 ...             ...       ...       ...       ...
GPR137     1.846095e+05       -0.413830  0.372690 -1.333032  0.182521
DDX52      1.060108e+05       -1.017063  0.374443 -3.114397  0.001843
TOR1AIP1   3.617321e+05       -0.308603  0.280587 -1.282453  0.199684
ACTBP11    1.143529e+04       -0.393443  0.174144 -2.356862  0.018430
RPS3AP49   3.806653e+03       -0.203919  0.498941 -0.565448  0.571769

               padj
MIA3       0.041600
CTNNB1     0.847139
DDX10      0.895135
RNU6-322P  0.649004
RN7SL130P  0.870298
...             ...
GPR137     0.386097
DDX52      0.008466
TOR1AIP1   0.411920
ACTBP11    0.062965
RPS3AP49   0.778079

[4988 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.15 seconds.

Fitting dispersion trend curve...
... done in 0.15 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 1.69 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 485 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 485)
Number of True values in replace_mask: 1055
replacement_counts_trimmed shape: (40, 485)

... done in 0.11 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.27 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
MIA3       4.880297e+05        0.824283  0.196334 -5.207341  1.915656e-07
CTNNB1     2.289031e+06        1.991706  0.117952  0.412435  6.800209e-01
DDX10      1.530128e+05        1.820237  0.189967  0.290841  7.711733e-01
RNU6-322P  4.257441e+02       -0.469573  0.585457 -1.245957  2.127803e-01
RN7SL130P  7.547578e+02       -0.124496  0.522674 -0.355554  7.221749e-01
...                 ...             ...       ...       ...           ...
GPR137     1.846095e+05        1.155567  0.306358 -2.052211  4.014918e-02
DDX52      1.060108e+05        0.501622  0.363527 -4.546589  5.452228e-06
TOR1AIP1   3.617321e+05        1.026218  0.210548 -3.547685  3.886331e-04
ACTBP11    1.143529e+04       -1.095833  0.175242 -6.236721  4.468370e-10
RPS3AP49   3.806653e+03       -0.220289  0.501260 -0.565443  5.717725e-01

                   padj
MIA3       1.099573e-06
CTNNB1     8.701756e-01
DDX10      9.286848e-01
RNU6-322P  4.165417e-01
RN7SL130P  8.965178e-01
...                 ...
GPR137     1.058478e-01
DDX52      2.635243e-05
TOR1AIP1   1.470790e-03
ACTBP11    3.304604e-09
RPS3AP49   7.974444e-01

[4988 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R14.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R14.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R14.csv
============================================================
[INFO] (67/160) sim_S20_G5000_CNweak_R15.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=15
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.94 seconds.

Fitting dispersion trend curve...
... done in 0.19 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 0.66 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 511 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.14 seconds.

Fitting LFCs...
... done in 0.25 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.41 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
BBIP1       253575.743936       -0.144671  0.331025 -0.558083  0.576788
DMWD        463899.376167        1.117793  0.247068  4.792616  0.000002
TMEM163      17030.528700       -0.289420  0.406156 -0.879256  0.379262
RPTOR       275830.649055        0.387737  0.265038  1.536244  0.124479
CRYGS        35914.740556        0.624459  0.292731  2.318112  0.020443
...                   ...             ...       ...       ...       ...
VWA8        151310.821321       -0.084863  0.314257 -0.347597  0.728143
FGB          34644.524935       -0.106341  0.570699 -0.292432  0.769956
THAP6        77127.052633       -0.400071  0.621194 -1.036226  0.300097
HNRNPA3P13     288.927672        0.386357  1.000535  1.046753  0.295214
GUSBP5        4309.720155        0.231273  0.255974  0.971401  0.331348

                padj
BBIP1       0.766133
DMWD        0.000013
TMEM163     0.609974
RPTOR       0.293767
CRYGS       0.068085
...              ...
VWA8        0.864683
FGB         0.888575
THAP6       0.532806
HNRNPA3P13  0.528082
GUSBP5      0.563236

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.11 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.55 seconds.

Fitting LFCs...
... done in 0.91 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 509 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 509)
Number of True values in replace_mask: 1095
replacement_counts_trimmed shape: (40, 509)

... done in 0.15 seconds.

Fitting LFCs...
... done in 0.13 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.02 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
BBIP1       253575.743936        1.469402  0.304028 -0.558083  0.576788
DMWD        463899.376167        2.158566  0.157305  2.684096  0.007273
TMEM163      17030.528700       -0.295537  0.407693 -0.879254  0.379264
RPTOR       275830.649055        1.466139  0.207081 -0.662638  0.507562
CRYGS        35914.740556        1.310650  0.296034  0.339188  0.734468
...                   ...             ...       ...       ...       ...
VWA8        151310.821321        1.531942  0.278885 -0.347597  0.728143
FGB          34644.524935        1.041419  0.673234 -0.292432  0.769956
THAP6        77127.052633        0.708612  0.621609 -1.769470  0.076815
HNRNPA3P13      58.373375        1.521424  0.034853  0.002302  0.998164
GUSBP5        4309.720155        0.240719  0.255438  0.971369  0.331364

                padj
BBIP1       0.792944
DMWD        0.022620
TMEM163     0.613935
RPTOR       0.734272
CRYGS       0.902306
...              ...
VWA8        0.898962
FGB         0.924726
THAP6       0.185405
HNRNPA3P13  0.999992
GUSBP5      0.560965

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R15.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R15.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R15.csv
============================================================
[INFO] (68/160) sim_S20_G5000_CNweak_R16.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=16
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.90 seconds.

Fitting dispersion trend curve...
... done in 0.14 seconds.

Fitting MAP dispersions...
... done in 1.45 seconds.

Fitting LFCs...
... done in 0.70 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 496 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.12 seconds.

Fitting LFCs...
... done in 0.22 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.51 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
TMEM167A   463474.173290        0.113472  0.149185  0.732626  4.637869e-01
LINC02021    3824.894921       -1.241853  0.416203 -3.401729  6.696097e-04
FAAP100    197401.750520       -0.680542  0.264642 -2.813314  4.903380e-03
MYOM2       14354.993270        0.110462  0.497301  0.305159  7.602452e-01
FOXN3-AS1   12209.394937       -0.023815  0.384583 -0.082503  9.342471e-01
...                  ...             ...       ...       ...           ...
IPO8P1      14605.142015        0.984660  0.273379  3.840262  1.229032e-04
ATP6V1B1   119059.950000        0.692879  0.728004  1.562777  1.181051e-01
KCNH3        5102.054351       -1.418853  0.179189 -8.112710  4.950315e-16
KRTAP1-5      162.875890       -0.320909  0.267674 -1.318757  1.872504e-01
AGA        114396.149261       -0.293531  0.195370 -1.621916  1.048213e-01

                   padj
TMEM167A   6.829494e-01
LINC02021  3.428023e-03
FAAP100    1.974412e-02
MYOM2      8.920187e-01
FOXN3-AS1  9.748920e-01
...                 ...
IPO8P1     7.371623e-04
ATP6V1B1   2.812535e-01
KCNH3      1.122596e-14
KRTAP1-5   3.905544e-01
AGA        2.574857e-01

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.14 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 0.92 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 494 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 494)
Number of True values in replace_mask: 1069
replacement_counts_trimmed shape: (40, 494)

... done in 0.11 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.24 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
TMEM167A   463474.173290        2.291020  0.159601  0.732625  4.637873e-01
LINC02021    3824.894921       -1.615157  0.416798 -4.414503  1.012421e-05
FAAP100    197401.750520        2.055252  0.255470  0.457579  6.472549e-01
MYOM2       14354.993270        0.111271  0.498846  0.305158  7.602458e-01
FOXN3-AS1   12209.394937       -0.149120  0.379189 -0.082502  9.342475e-01
...                  ...             ...       ...       ...           ...
IPO8P1      14605.142015        1.820513  0.271313  7.034584  1.998557e-12
ATP6V1B1   119059.950000        2.261213  0.532152  1.317930  1.875271e-01
KCNH3        5102.054351       -1.601641  0.179648 -9.478554  2.578322e-21
KRTAP1-5      162.875890       -0.575048  0.270805 -2.344695  1.904264e-02
AGA        114396.149261        1.413849  0.206125 -1.621921  1.048204e-01

                   padj
TMEM167A   7.018001e-01
LINC02021  4.894350e-05
FAAP100    8.538219e-01
MYOM2      9.291488e-01
FOXN3-AS1  9.999972e-01
...                 ...
IPO8P1     1.891993e-11
ATP6V1B1   3.798509e-01
KCNH3      3.828348e-20
KRTAP1-5   5.447460e-02
AGA        2.406575e-01

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R16.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R16.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R16.csv
============================================================
[INFO] (69/160) sim_S20_G5000_CNweak_R17.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=17
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.54 seconds.

Fitting LFCs...
... done in 0.77 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 472 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.14 seconds.

Fitting MAP dispersions...
... done in 0.20 seconds.

Fitting LFCs...
... done in 0.22 seconds.

Running Wald tests...
... done in 0.40 seconds.

Fitting MAP LFCs...
... done in 1.51 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
DNAJB14  2.375285e+05        0.261312  0.210097  1.284178  0.199080  0.402431
GAL3ST3  4.309896e+01       -0.971942  1.569512 -1.719680  0.085491  0.215777
KCTD3    6.468716e+05        0.210975  0.303621  0.762222  0.445927  0.673714
SFRP2    2.019191e+06       -0.704287  0.559891 -1.748096  0.080447  0.206198
WDR1     1.539829e+06        0.315172  0.211625  1.623990  0.104378  0.252990
...               ...             ...       ...       ...       ...       ...
TDG      1.300701e+05        0.246699  0.517710  0.652015  0.514391  0.730269
DBN1     4.935432e+05       -0.667812  0.171329 -4.075498  0.000046  0.000279
SIGLEC1  1.015484e+05       -0.076289  0.794587 -0.297023  0.766449  0.889352
ENGASE   3.790454e+05        0.548812  0.164815  3.357643  0.000786  0.003785
OR7E2P   3.447738e+02        0.153270  0.298291  0.575090  0.565230  0.769620

[4993 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.22 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.44 seconds.

Fitting LFCs...
... done in 1.11 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 476 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 476)
Number of True values in replace_mask: 1027
replacement_counts_trimmed shape: (40, 476)

... done in 0.12 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.36 seconds.

Fitting MAP LFCs...
... done in 1.38 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE       stat        pvalue  \
DNAJB14  2.375285e+05        1.881509  0.199610   1.284177  1.990802e-01
GAL3ST3  9.441908e+00       -3.237042  0.098468   0.089666  9.285529e-01
KCTD3    6.468716e+05        1.366429  0.166589  -1.625388  1.040800e-01
SFRP2    2.019191e+06        1.330579  0.199614  -1.748096  8.044744e-02
WDR1     1.539829e+06        2.249788  0.101384   1.623989  1.043781e-01
...               ...             ...       ...        ...           ...
TDG      1.300701e+05        1.695270  0.508765   0.652015  5.143916e-01
DBN1     4.935432e+05        1.356010  0.149302  -5.510403  3.580123e-08
SIGLEC1  2.005275e+04        0.544314  0.002447 -58.969540  0.000000e+00
ENGASE   3.790454e+05        1.514386  0.157327  -1.129086  2.588618e-01
OR7E2P   3.447738e+02        0.151952  0.297043   0.574921  5.653449e-01

                 padj
DNAJB14  4.012948e-01
GAL3ST3  9.999972e-01
KCTD3    2.397008e-01
SFRP2    1.932054e-01
WDR1     2.400551e-01
...               ...
TDG      7.536259e-01
DBN1     2.259868e-07
SIGLEC1  0.000000e+00
ENGASE   4.868907e-01
OR7E2P   7.949217e-01

[4993 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R17.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R17.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R17.csv
============================================================
[INFO] (70/160) sim_S20_G5000_CNweak_R18.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=18
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.15 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.34 seconds.

Fitting LFCs...
... done in 0.85 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 487 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 0.19 seconds.

Fitting LFCs...
... done in 0.23 seconds.

Running Wald tests...
... done in 0.36 seconds.

Fitting MAP LFCs...
... done in 1.57 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC02766  8.180134e+02        0.276377  0.738442   0.704989  4.808171e-01
SLC25A48   1.792054e+04        0.097175  0.627570   0.244200  8.070760e-01
TYSND1     1.907191e+05        0.258920  0.235919   1.124748  2.606960e-01
RAD51D     1.211731e+05       -0.004229  0.318666  -0.030681  9.755236e-01
SIGLEC5    1.215854e+04       -0.384268  0.383860  -1.203930  2.286167e-01
...                 ...             ...       ...        ...           ...
ARLNC1     6.579266e+02       -0.144261  0.738970  -1.601033  1.093695e-01
CXCL9      1.108121e+05       -0.600164  0.879244  -2.705527  6.819607e-03
AP2A1      1.448819e+06        1.402728  0.485997   3.361644  7.747993e-04
RFC2       5.649271e+05        2.418900  0.177099  13.797921  2.623083e-43
QRICH1     3.913126e+05       -0.013836  0.387596  -0.092326  9.264389e-01

                   padj
LINC02766  6.992305e-01
SLC25A48   9.217657e-01
TYSND1     4.827955e-01
RAD51D     9.895472e-01
SIGLEC5    4.412321e-01
...                 ...
ARLNC1     2.625605e-01
CXCL9      2.630707e-02
AP2A1      3.747115e-03
RFC2       3.193124e-41
QRICH1     9.713750e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.33 seconds.

Fitting LFCs...
... done in 0.89 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 484 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 484)
Number of True values in replace_mask: 1062
replacement_counts_trimmed shape: (40, 484)

... done in 0.13 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.02 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC02766  8.180134e+02        0.260874  0.722952   0.704978  4.808239e-01
SLC25A48   1.792054e+04        0.945978  0.766515   0.245519  8.060547e-01
TYSND1     1.907191e+05        1.862900  0.223012   1.124747  2.606964e-01
RAD51D     1.211731e+05        1.575221  0.299725  -0.030681  9.755237e-01
SIGLEC5    1.215854e+04       -0.674366  0.403438  -2.638724  8.321870e-03
...                 ...             ...       ...        ...           ...
ARLNC1     2.063251e+02       -0.451899  0.022318 -16.278499  1.402680e-59
CXCL9      2.769464e+04       -2.082984  0.002048  -0.001202  9.990411e-01
AP2A1      1.448819e+06        2.560202  0.176305   2.493605  1.264531e-02
RFC2       5.649271e+05        3.374786  0.132401  11.704010  1.215697e-31
QRICH1     3.913126e+05        1.687714  0.294969  -0.092326  9.264389e-01

                   padj
LINC02766  7.216716e-01
SLC25A48   9.596896e-01
TYSND1     4.806560e-01
RAD51D     9.999857e-01
SIGLEC5    2.627100e-02
...                 ...
ARLNC1     3.646238e-58
CXCL9      9.999857e-01
AP2A1      3.827334e-02
RFC2       2.370135e-30
QRICH1     9.999857e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R18.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R18.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R18.csv
============================================================
[INFO] (71/160) sim_S20_G5000_CNweak_R19.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=19
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.06 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.67 seconds.

Fitting LFCs...
... done in 0.77 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 462 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.16 seconds.

Fitting MAP dispersions...
... done in 0.21 seconds.

Fitting LFCs...
... done in 0.17 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.69 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE       stat        pvalue  \
NOTCH1   593563.217872        0.237194  0.306789   0.852077  3.941713e-01
TMEM30A  666066.914399       -0.990835  0.212505  -4.915564  8.852721e-07
ZIC4      12200.238218        1.366902  1.061360   2.292878  2.185502e-02
ZBTB24   436259.612130        3.095191  0.256719  12.194682  3.317973e-34
SVIP     438128.502758        1.912813  0.301335   6.594778  4.258929e-11
...                ...             ...       ...        ...           ...
ZHX2     284189.370405       -0.141540  0.487692  -0.401518  6.880385e-01
HOXD3     26730.096372        0.171184  0.504456   0.459955  6.455488e-01
RARS2    168710.805514        0.186806  0.405447   0.554579  5.791823e-01
PRAL     368199.147998        0.069912  0.190804   0.272402  7.853126e-01
GRIK1     15548.386723        1.511189  0.404273   4.109026  3.973319e-05

                 padj
NOTCH1   6.340519e-01
TMEM30A  6.842359e-06
ZIC4     7.150860e-02
ZBTB24   2.715843e-32
SVIP     5.480627e-10
...               ...
ZHX2     8.480316e-01
HOXD3    8.207857e-01
RARS2    7.763376e-01
PRAL     9.069809e-01
GRIK1    2.489182e-04

[4993 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.21 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.36 seconds.

Fitting LFCs...
... done in 0.88 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 459 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 459)
Number of True values in replace_mask: 1012
replacement_counts_trimmed shape: (40, 459)

... done in 0.18 seconds.

Fitting LFCs...
... done in 0.12 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.32 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE       stat        pvalue  \
NOTCH1   593563.217872        1.907095  0.208383   0.852077  3.941713e-01
TMEM30A  666066.914399        1.000878  0.170996  -6.415910  1.399842e-10
ZIC4      12200.238218        2.492522  0.912919   1.736915  8.240214e-02
ZBTB24   436259.612130        3.768444  0.148901  10.722927  7.944846e-27
SVIP     438128.502758        2.799795  0.210520   5.434388  5.498483e-08
...                ...             ...       ...        ...           ...
ZHX2     284189.370405        1.160731  0.346767  -1.686418  9.171533e-02
HOXD3     26730.096372        1.243686  0.580227   0.459954  6.455492e-01
RARS2    168710.805514        1.635977  0.381970   0.554580  5.791818e-01
PRAL     368199.147998        1.864720  0.179398   0.272402  7.853127e-01
GRIK1     15548.386723        1.961416  0.410030   2.883879  3.928098e-03

                 padj
NOTCH1   6.444327e-01
TMEM30A  1.130972e-09
ZIC4     1.973304e-01
ZBTB24   1.453063e-25
SVIP     3.484001e-07
...               ...
ZHX2     2.156001e-01
HOXD3    8.497831e-01
RARS2    8.015118e-01
PRAL     9.444645e-01
GRIK1    1.307533e-02

[4993 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R19.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R19.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R19.csv
============================================================
[INFO] (72/160) sim_S20_G5000_CNweak_R2.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=2
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.22 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.72 seconds.

Fitting LFCs...
... done in 0.82 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 499 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 0.23 seconds.

Fitting LFCs...
... done in 0.21 seconds.

Running Wald tests...
... done in 0.39 seconds.

Fitting MAP LFCs...
... done in 1.51 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SPHKAP     4.678104e+02        1.810450  1.210495  1.789196  0.073583
P2RX3      6.676155e+01        0.472924  0.872574  1.123354  0.261287
SRSF5      2.022675e+06        0.027090  0.266050  0.215906  0.829061
MFSD2A     4.940135e+04        0.002417  0.497968 -0.003436  0.997259
SMOC2      3.492667e+05        0.224846  0.411471  0.613426  0.539595
...                 ...             ...       ...       ...       ...
RNU6-395P  2.264349e+03        0.122009  0.605115  0.318519  0.750091
ZNF33A     8.524229e+05        1.527673  0.651626  2.926074  0.003433
CHTF18     2.178018e+05        0.366287  0.463870  1.123357  0.261286
ZC3H7B     6.058319e+05       -0.140143  0.429024 -0.298353  0.765433
NOX4       5.122279e+04        0.029015  0.210640  0.185885  0.852535

               padj
SPHKAP     0.199661
P2RX3      0.494577
SRSF5      0.922390
MFSD2A     0.998659
SMOC2      0.756396
...             ...
RNU6-395P  0.884187
ZNF33A     0.014989
CHTF18     0.494577
ZC3H7B     0.891131
NOX4       0.932297

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.14 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.35 seconds.

Fitting LFCs...
... done in 0.87 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 496 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 496)
Number of True values in replace_mask: 1076
replacement_counts_trimmed shape: (40, 496)

... done in 0.13 seconds.

Fitting LFCs...
... done in 0.12 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.63 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SPHKAP     2.168504e+02        2.743453  0.018748  0.009903  0.992099
P2RX3      2.451643e+01        0.705221  0.054113 -3.750498  0.000176
SRSF5      2.022675e+06        1.920267  0.124756  0.215906  0.829061
MFSD2A     4.940135e+04        1.330441  0.542086 -0.003436  0.997259
SMOC2      3.492667e+05        1.841475  0.306166  0.613428  0.539593
...                 ...             ...       ...       ...       ...
RNU6-395P  2.264349e+03        0.130997  0.594634  0.318516  0.750093
ZNF33A     8.524229e+05        2.632248  0.204074  2.096254  0.036060
CHTF18     2.178018e+05        1.454428  0.340122 -0.493318  0.621788
ZC3H7B     6.058319e+05        1.668589  0.269196 -0.296660  0.766726
NOX4       5.122279e+04        1.346059  0.228026  0.185884  0.852536

               padj
SPHKAP     0.999979
P2RX3      0.000727
SRSF5      0.965883
MFSD2A     0.999979
SMOC2      0.773793
...             ...
RNU6-395P  0.921421
ZNF33A     0.097706
CHTF18     0.838062
ZC3H7B     0.930851
NOX4       0.977453

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R2.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R2.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R2.csv
============================================================
[INFO] (73/160) sim_S20_G5000_CNweak_R20.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=20
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.36 seconds.

Fitting dispersion trend curve...
... done in 0.19 seconds.

Fitting MAP dispersions...
... done in 1.67 seconds.

Fitting LFCs...
... done in 0.79 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 498 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 0.23 seconds.

Fitting LFCs...
... done in 0.24 seconds.

Running Wald tests...
... done in 0.36 seconds.

Fitting MAP LFCs...
... done in 1.44 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                   baseMean  log2FoldChange     lfcSE      stat        pvalue  \
PRICKLE2-AS2     124.929929       -0.238579  0.788978 -0.538592  5.901685e-01
HCCAT5            67.546751        0.362461  0.949528 -1.434065  1.515538e-01
THY1          324411.425046        0.307843  0.542247  0.734803  4.624595e-01
PPARD         200639.140412       -1.608773  0.226434 -7.377644  1.611150e-13
FAM180A        52292.406663        0.880911  0.437288  2.402723  1.627353e-02
...                     ...             ...       ...       ...           ...
MYHAS           2349.259726       -0.432570  0.431327 -1.258225  2.083105e-01
SYCE1L         19254.795985       -0.237908  0.208677 -1.236303  2.163460e-01
SAR1B         365471.140246       -0.318618  0.285429 -1.285053  1.987736e-01
TXNL4B         38400.978929       -0.003364  0.628383 -0.020451  9.836832e-01
HSD17B6        32381.021035        1.390345  0.263887  5.504190  3.708698e-08

                      padj
PRICKLE2-AS2  7.793411e-01
HCCAT5        3.358961e-01
THY1          6.838205e-01
PPARD         3.010498e-12
FAM180A       5.603457e-02
...                    ...
MYHAS         4.183821e-01
SYCE1L        4.287867e-01
SAR1B         4.057617e-01
TXNL4B        9.948501e-01
HSD17B6       3.730382e-07

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.14 seconds.

Fitting dispersion trend curve...
... done in 0.16 seconds.

Fitting MAP dispersions...
... done in 1.58 seconds.

Fitting LFCs...
... done in 1.05 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 489 outlier genes.

Fitting dispersions...

replace_mask before filtering: (40, 489)
Number of True values in replace_mask: 1088
replacement_counts_trimmed shape: (40, 489)

... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.16 seconds.

Fitting LFCs...
... done in 0.13 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.06 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                   baseMean  log2FoldChange     lfcSE      stat        pvalue  \
PRICKLE2-AS2      36.833308       -0.890411  0.042858 -0.048667  9.611850e-01
HCCAT5            22.830400        1.255073  0.055449 -0.001553  9.987609e-01
THY1          324411.425046        1.961342  0.395234  0.734803  4.624595e-01
PPARD         200639.140412        0.264088  0.244197 -9.172804  4.608719e-20
FAM180A        52292.406663        1.735594  0.428534  1.453815  1.459977e-01
...                     ...             ...       ...       ...           ...
MYHAS           2349.259726       -0.426722  0.428738 -1.258199  2.083199e-01
SYCE1L         19254.795985       -0.362695  0.203965 -1.236289  2.163511e-01
SAR1B         365471.140246        1.570356  0.201837 -1.285053  1.987738e-01
TXNL4B         38400.978929        1.215314  0.770225 -0.020451  9.836832e-01
HSD17B6        32381.021035        2.041577  0.265178  3.979658  6.901442e-05

                      padj
PRICKLE2-AS2  9.999963e-01
HCCAT5        9.999963e-01
THY1          7.081678e-01
PPARD         6.802632e-19
FAM180A       3.171017e-01
...                    ...
MYHAS         4.168905e-01
SYCE1L        4.281121e-01
SAR1B         4.027954e-01
TXNL4B        9.999963e-01
HSD17B6       3.049716e-04

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R20.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R20.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R20.csv
============================================================
[INFO] (74/160) sim_S20_G5000_CNweak_R3.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=3
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.03 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.49 seconds.

Fitting LFCs...
... done in 0.68 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 517 outlier genes.

Fitting dispersions...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 0.24 seconds.

Fitting LFCs...
... done in 0.22 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.24 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SULT2B1   131303.105922        1.245447  0.633028  2.569002  1.019918e-02
MORN2      44802.796857       -1.146715  0.360590 -3.536627  4.052712e-04
PRR7-AS1    2684.706057        1.369562  0.416193  3.687295  2.266510e-04
FMO2      518867.657838       -0.579014  0.626164 -1.423271  1.546577e-01
NFYC      309256.529930        0.037175  0.153843  0.166613  8.676747e-01
...                 ...             ...       ...       ...           ...
GAS2        5840.482277       -1.783877  0.291727 -6.387851  1.682328e-10
AGMAT       8822.746517       -0.136265  0.822577  0.240561  8.098953e-01
LIPT1      38879.874431        0.021047  0.194541  0.119453  9.049168e-01
PGPEP1    107116.693408       -1.810150  0.410285 -4.845627  1.262124e-06
ADAMTS15   80427.711710        0.402437  0.863943 -1.055591  2.911552e-01

                  padj
SULT2B1   3.776214e-02
MORN2     2.159140e-03
PRR7-AS1  1.254370e-03
FMO2      3.402605e-01
NFYC      9.417887e-01
...                ...
GAS2      2.073626e-09
AGMAT     9.107901e-01
LIPT1     9.595040e-01
PGPEP1    9.723030e-06
ADAMTS15  5.231991e-01

[4992 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.61 seconds.

Fitting dispersion trend curve...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 1.30 seconds.

Fitting LFCs...
... done in 0.99 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 510 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 510)
Number of True values in replace_mask: 1111
replacement_counts_trimmed shape: (40, 510)

... done in 0.19 seconds.

Fitting LFCs...
... done in 0.12 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.15 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE        stat         pvalue  \
SULT2B1   131303.105922        2.364985  0.445264    1.841844   6.549797e-02
MORN2      44802.796857        0.245474  0.364534   -3.890786   9.992013e-05
PRR7-AS1    2684.706057        1.033164  0.416396    2.858198   4.260545e-03
FMO2      518867.657838        0.971353  0.349475   -2.466452   1.364591e-02
NFYC      309256.529930        2.051006  0.170061    0.166612   8.676756e-01
...                 ...             ...       ...         ...            ...
GAS2        5840.482277       -2.161794  0.292279   -7.962669   1.683675e-15
AGMAT       2282.090486       -0.735752  0.007060  -28.496431  1.297022e-178
LIPT1      38879.874431        0.217930  0.199523    0.119452   9.049174e-01
PGPEP1    107116.693408        0.342570  0.401706   -5.737885   9.586636e-09
ADAMTS15   39518.424705        1.226607  0.001959 -220.377056   0.000000e+00

                   padj
SULT2B1    1.647183e-01
MORN2      4.202201e-04
PRR7-AS1   1.404798e-02
FMO2       4.086307e-02
NFYC       9.977497e-01
...                 ...
GAS2       1.901563e-14
AGMAT     3.948010e-177
LIPT1      9.999980e-01
PGPEP1     6.406491e-08
ADAMTS15   0.000000e+00

[4992 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R3.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R3.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R3.csv
============================================================
[INFO] (75/160) sim_S20_G5000_CNweak_R4.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=4
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.44 seconds.

Fitting LFCs...
... done in 0.66 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 489 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.16 seconds.

Fitting LFCs...
... done in 0.21 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.27 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
TCP11        5981.401971        1.054545  0.761137  2.104384  3.534498e-02
RNA5SP216   24351.920684        2.109758  0.237919  9.090622  9.847367e-20
EML5        88568.501739        0.242777  0.164423  1.515030  1.297648e-01
TEX19         999.981003        0.821383  1.523726  1.685664  9.186048e-02
PA2G4P5     36858.130891        1.161529  0.178552  6.632151  3.308304e-11
...                  ...             ...       ...       ...           ...
LINC02345     928.066080        0.571453  0.894809  0.530046  5.960798e-01
DOCK1      470461.047300        0.260757  0.194867  1.236977  2.160956e-01
ANKRD39     94116.838858       -0.156815  0.596141 -0.425181  6.707046e-01
IFT81       98820.183741       -0.119229  0.298114 -0.415074  6.780875e-01
SCN3B       29226.063122       -0.333603  0.339733 -1.147769  2.510640e-01

                   padj
TCP11      1.078270e-01
RNA5SP216  2.747360e-18
EML5       2.993282e-01
TEX19      2.310488e-01
PA2G4P5    4.151174e-10
...                 ...
LINC02345  7.804216e-01
DOCK1      4.327110e-01
ANKRD39    8.268727e-01
IFT81      8.325130e-01
SCN3B      4.758561e-01

[4994 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.02 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.36 seconds.

Fitting LFCs...
... done in 0.89 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 481 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 481)
Number of True values in replace_mask: 1040
replacement_counts_trimmed shape: (40, 481)

... done in 0.13 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.09 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat         pvalue  \
TCP11        5981.401971        0.677951  0.729151   1.436673   1.508109e-01
RNA5SP216   24351.920684        2.293721  0.247440   7.679526   1.596784e-14
EML5        88568.501739        2.018554  0.180930   1.515024   1.297663e-01
TEX19         288.350821        1.731774  0.017822 -12.920735   3.438394e-38
PA2G4P5     36858.130891        1.000224  0.181833   5.014285   5.323099e-07
...                  ...             ...       ...        ...            ...
LINC02345     394.066281        1.262462  0.017451 -22.176330  5.813224e-109
DOCK1      470461.047300        2.117553  0.171112   1.236976   2.160958e-01
ANKRD39     94116.838858        1.394063  0.590191  -0.425181   6.707046e-01
IFT81       98820.183741        1.404963  0.299239  -0.415074   6.780878e-01
SCN3B       29226.063122        0.628501  0.366979  -1.147766   2.510652e-01

                    padj
TCP11       3.183280e-01
RNA5SP216   1.557488e-13
EML5        2.823761e-01
TEX19       7.338180e-37
PA2G4P5     2.828038e-06
...                  ...
LINC02345  1.668462e-107
DOCK1       4.186123e-01
ANKRD39     8.517280e-01
IFT81       8.570919e-01
SCN3B       4.650896e-01

[4994 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R4.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R4.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R4.csv
============================================================
[INFO] (76/160) sim_S20_G5000_CNweak_R5.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=5
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.02 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.35 seconds.

Fitting LFCs...
... done in 1.10 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 484 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.11 seconds.

Fitting LFCs...
... done in 0.14 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.20 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
MLYCD      9.790284e+04       -0.266600  0.360322  -0.898110  3.691268e-01
RPL26      1.972314e+06        0.231592  0.206054   1.279432  2.007449e-01
FASTKD5    1.614463e+05        0.936431  0.269815   3.654802  2.573806e-04
ADCY10     3.040454e+03       -0.148576  0.499008  -0.416002  6.774082e-01
UPK2       4.410004e+03        0.212864  0.396075   0.649725  5.158700e-01
...                 ...             ...       ...        ...           ...
RPS15AP14  5.736677e+02       -0.208249  0.762554  -0.588522  5.561818e-01
POMT2      3.575286e+04        0.351903  0.925887   0.283137  7.770716e-01
NKX2-8     5.330240e+02       -0.221834  0.149367  -1.529984  1.260207e-01
NHLH1      1.512544e+03       -0.668661  0.435320  -1.878123  6.036427e-02
REEP1      1.621860e+05        2.208976  0.201626  11.100981  1.240742e-28

                   padj
MLYCD      5.932472e-01
RPL26      4.021345e-01
FASTKD5    1.420718e-03
ADCY10     8.300897e-01
UPK2       7.168009e-01
...                 ...
RPS15AP14  7.480721e-01
POMT2      8.911544e-01
NKX2-8     2.893895e-01
NHLH1      1.629084e-01
REEP1      5.896479e-27

[4990 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.02 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.38 seconds.

Fitting LFCs...
... done in 0.90 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 483 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 483)
Number of True values in replace_mask: 1073
replacement_counts_trimmed shape: (40, 483)

... done in 0.12 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.02 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE        stat        pvalue  \
MLYCD      9.790284e+04        1.336479  0.348492   -0.898109  3.691273e-01
RPL26      1.972314e+06        2.308403  0.097767    1.279431  2.007454e-01
FASTKD5    1.614463e+05        1.706340  0.236325    1.178076  2.387664e-01
ADCY10     3.040454e+03       -0.625384  0.534510   -1.698712  8.937351e-02
UPK2       4.410004e+03        0.141319  0.388950    0.649716  5.158754e-01
...                 ...             ...       ...         ...           ...
RPS15AP14  5.736677e+02       -0.207263  0.733689   -0.588514  5.561876e-01
POMT2      1.956729e+04        1.229537  0.002632 -155.515337  0.000000e+00
NKX2-8     5.330240e+02       -0.704476  0.150424   -4.808074  1.523914e-06
NHLH1      1.512544e+03       -1.521917  0.452531   -3.874113  1.070140e-04
REEP1      1.621860e+05        2.931254  0.189900    9.230553  2.692374e-20

                   padj
MLYCD      6.087063e-01
RPL26      4.047352e-01
FASTKD5    4.568422e-01
ADCY10     2.140240e-01
UPK2       7.430740e-01
...                 ...
RPS15AP14  7.763290e-01
POMT2      0.000000e+00
NKX2-8     8.072539e-06
NHLH1      4.494947e-04
REEP1      3.882932e-19

[4990 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R5.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R5.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R5.csv
============================================================
[INFO] (77/160) sim_S20_G5000_CNweak_R6.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=6
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.66 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 478 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.15 seconds.

Fitting LFCs...
... done in 0.21 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.19 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SYCP2L        5252.523912       -2.085368  0.443806 -5.095867  3.471494e-07
RNA5SP187      169.730004       -0.953410  0.772261 -1.975829  4.817416e-02
PRR13       431614.217359       -0.186592  0.225165 -0.899017  3.686436e-01
SLC44A3      44715.021601       -0.136720  0.389811 -0.436707  6.623241e-01
CCDC92      311533.532966       -0.547553  0.247672 -2.355828  1.848148e-02
...                   ...             ...       ...       ...           ...
MTSS1       377385.565325       -0.105505  0.658174 -0.297468  7.661092e-01
GRHL2       313258.483804       -0.127732  0.268553 -0.581797  5.607035e-01
SHC2        133132.606852        0.104707  0.610868  0.258040  7.963762e-01
ZNF829       35969.580367        0.710249  1.002030  1.603520  1.088198e-01
RNU6-1330P     361.496385       -0.182719  0.381834 -0.580735  5.614191e-01

                padj
SYCP2L      0.000003
RNA5SP187   0.137103
PRR13       0.597706
SLC44A3     0.831357
CCDC92      0.062132
...              ...
MTSS1       0.892076
GRHL2       0.760977
SHC2        0.908544
ZNF829      0.262145
RNU6-1330P  0.761401

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.02 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 1.33 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 471 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 471)
Number of True values in replace_mask: 1038
replacement_counts_trimmed shape: (40, 471)

... done in 0.11 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 0.95 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SYCP2L        5252.523912       -2.687874  0.436377 -6.246221  4.205011e-10
RNA5SP187      169.730004       -0.908200  0.776224 -1.975572  4.820325e-02
PRR13       431614.217359        1.780889  0.182875 -0.899017  3.686438e-01
SLC44A3      44715.021601        1.138901  0.425016 -0.436707  6.623241e-01
CCDC92      311533.532966        1.463781  0.211681 -2.355827  1.848154e-02
...                   ...             ...       ...       ...           ...
MTSS1       377385.565325        1.245974  0.333476 -1.271828  2.034343e-01
GRHL2       313258.483804        0.997645  0.216047 -3.554648  3.784849e-04
SHC2        133132.606852        1.761149  0.512490  0.258040  7.963760e-01
ZNF829       35969.580367        1.992114  0.923403  0.909877  3.628871e-01
RNU6-1330P     361.496385       -0.173799  0.378771 -0.580640  5.614833e-01

                    padj
SYCP2L      3.169003e-09
RNA5SP187   1.250577e-01
PRR13       6.065738e-01
SLC44A3     8.607413e-01
CCDC92      5.363838e-02
...                  ...
MTSS1       4.040340e-01
GRHL2       1.455868e-03
SHC2        9.461858e-01
ZNF829      6.004789e-01
RNU6-1330P  7.835636e-01

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R6.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R6.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R6.csv
============================================================
[INFO] (78/160) sim_S20_G5000_CNweak_R7.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=7
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.66 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 490 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.17 seconds.

Fitting LFCs...
... done in 0.21 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.16 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC01908       9.059979        0.409468  1.103545   1.437714  1.505153e-01
PCSK6      167922.456115       -1.149767  0.573491  -2.600698  9.303424e-03
NRF1       284701.834450        2.072313  0.117076  17.959052  4.077080e-72
EFCAB11     34664.049859       -0.792911  0.299501  -2.921298  3.485764e-03
VANGL1     196231.548194        0.361374  0.464368   1.004880  3.149548e-01
...                  ...             ...       ...        ...           ...
RCN1       291166.678665        0.038083  0.842291   0.024866  9.801617e-01
UBE2D1     124016.834595       -0.144513  0.792436  -0.447238  6.547034e-01
ZNF512     155039.078089       -0.427103  0.430388  -1.244910  2.131648e-01
PRR22       16352.893098       -0.145761  0.204043  -0.746698  4.552456e-01
CACNA1G     25210.330508        1.043516  0.178766   5.983895  2.178645e-09

                   padj
LINC01908  3.352479e-01
PCSK6      3.493688e-02
NRF1       4.066480e-69
EFCAB11    1.451044e-02
VANGL1     5.427177e-01
...                 ...
RCN1       9.896875e-01
UBE2D1     8.121394e-01
ZNF512     4.227895e-01
PRR22      6.737159e-01
CACNA1G    2.336538e-08

[4987 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.91 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 489 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 489)
Number of True values in replace_mask: 1093
replacement_counts_trimmed shape: (40, 489)

... done in 0.12 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.00 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE        stat        pvalue  \
LINC01908       2.585703        1.722614  0.150968   -0.161998  8.713072e-01
PCSK6      167922.456115        0.719469  0.524699   -2.600698  9.303441e-03
NRF1       284701.834450        3.596429  0.127419   13.261705  3.860170e-40
EFCAB11     34664.049859        0.239236  0.309897   -2.921288  3.485875e-03
VANGL1     196231.548194        1.894346  0.402264    1.004879  3.149549e-01
...                  ...             ...       ...         ...           ...
RCN1       100415.668520       -0.414698  0.001128 -176.453597  0.000000e+00
UBE2D1     124016.834595        1.239131  0.919728   -0.447257  6.546892e-01
ZNF512     155039.078089        1.015057  0.370524   -2.242204  2.494817e-02
PRR22       16352.893098        0.032838  0.208381   -0.746688  4.552518e-01
CACNA1G     25210.330508        0.290872  0.174280    2.144891  3.196159e-02

                   padj
LINC01908  9.879966e-01
PCSK6      2.849893e-02
NRF1       8.369856e-39
EFCAB11    1.173806e-02
VANGL1     5.517723e-01
...                 ...
RCN1       0.000000e+00
UBE2D1     8.544713e-01
ZNF512     7.077162e-02
PRR22      6.974247e-01
CACNA1G    8.825318e-02

[4987 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R7.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R7.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R7.csv
============================================================
[INFO] (79/160) sim_S20_G5000_CNweak_R8.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=8
[INFO] Running PyDESeq2 (CN-naive)

Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.01 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.41 seconds.

Fitting LFCs...
... done in 1.24 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 475 outlier genes.

Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.13 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.25 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
ZNF542P     209081.076529        1.875075  0.276377   6.997555  2.604676e-12
RFX7        142554.522738       -0.188346  0.199274  -0.991979  3.212079e-01
GEMIN7-AS1   13804.299458       -2.572698  0.234038 -11.177811  5.236594e-29
MIR6774        272.382501        0.363990  0.724785   0.929180  3.527957e-01
RMDN1       183246.433819       -0.440433  0.270037  -1.810607  7.020169e-02
...                   ...             ...       ...        ...           ...
LCNL1         6474.277345        0.303886  0.381617   0.956971  3.385820e-01
ENDOD1      138777.174195       -0.018871  0.763730  -0.075706  9.396528e-01
ZNF335      133318.756473        0.083929  0.657613   0.210956  8.329218e-01
PGF          64005.916472       -0.001474  0.428017  -0.007290  9.941832e-01
PKNOX2       12920.151412        0.026054  0.573600   0.060421  9.518203e-01

                    padj
ZNF542P     4.570020e-11
RFX7        5.533823e-01
GEMIN7-AS1  4.020899e-27
MIR6774     5.874071e-01
RMDN1       1.887722e-01
...                  ...
LCNL1       5.720592e-01
ENDOD1      9.764934e-01
ZNF335      9.298124e-01
PGF         9.981790e-01
PKNOX2      9.805377e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.34 seconds.

Fitting LFCs...
... done in 0.92 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 464 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 464)
Number of True values in replace_mask: 1042
replacement_counts_trimmed shape: (40, 464)

... done in 0.13 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.03 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
ZNF542P     209081.076529        2.695650  0.209809   5.467064  4.575515e-08
RFX7        142554.522738        1.609441  0.197748  -0.991977  3.212087e-01
GEMIN7-AS1   13804.299458       -3.065138  0.234097 -12.806419  1.509402e-37
MIR6774        272.382501        0.341954  0.713157   0.929131  3.528212e-01
RMDN1       183246.433819        6.169372  0.353607  10.729047  7.435868e-27
...                   ...             ...       ...        ...           ...
LCNL1         6474.277345        0.233239  0.378095   0.956962  3.385866e-01
ENDOD1      138777.174195        1.562097  0.779420  -0.075686  9.396692e-01
ZNF335      133318.756473        1.192070  0.655662  -0.744758  4.564179e-01
PGF          64005.916472        1.405774  0.436807  -0.007290  9.941832e-01
PKNOX2       12920.151412       -0.129022  0.576671   0.060421  9.518204e-01

                    padj
ZNF542P     2.973489e-07
RFX7        5.582720e-01
GEMIN7-AS1  3.348190e-36
MIR6774     5.939428e-01
RMDN1       1.421932e-25
...                  ...
LCNL1       5.783319e-01
ENDOD1      9.999959e-01
ZNF335      7.026471e-01
PGF         9.999959e-01
PKNOX2      9.999959e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R8.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R8.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R8.csv
============================================================
[INFO] (80/160) sim_S20_G5000_CNweak_R9.pkl
[INFO] Running analysis for S=20, G=5000, CN=weak, R=9
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.99 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.71 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 479 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.18 seconds.

Fitting LFCs...
... done in 0.19 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.16 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
VN1R81P      2.105941e+03       -0.986243  0.412557 -2.781919  5.403853e-03
MIR7844      1.756543e+03       -0.879674  0.451159 -2.362463  1.815394e-02
CFAP69       3.968524e+04       -1.184571  0.422268 -3.229553  1.239839e-03
BCAR3        2.384607e+05        0.173180  0.359563  0.531728  5.949143e-01
CEP57        2.581039e+05        0.402366  0.188527  2.166643  3.026207e-02
...                   ...             ...       ...       ...           ...
ARPC4-TTLL3  1.453446e+06        1.715840  0.258295  6.808901  9.834718e-12
SRGAP3-AS4   1.250571e+02       -1.954932  0.401242 -5.238240  1.621149e-07
GPR45        2.242941e+02       -0.306932  0.702490 -0.805602  4.204722e-01
SULT4A1      9.730213e+03        0.305288  0.594913  0.780918  4.348508e-01
GTSE1-DT     3.043612e+03        0.245553  0.185888  1.376617  1.686308e-01

                     padj
VN1R81P      2.107460e-02
MIR7844      6.008751e-02
CFAP69       5.627221e-03
BCAR3        7.900922e-01
CEP57        9.226601e-02
...                   ...
ARPC4-TTLL3  1.413705e-10
SRGAP3-AS4   1.384639e-06
GPR45        6.487211e-01
SULT4A1      6.623011e-01
GTSE1-DT     3.631823e-01

[4988 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.87 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 472 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 472)
Number of True values in replace_mask: 1088
replacement_counts_trimmed shape: (40, 472)

... done in 0.11 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.33 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
VN1R81P      2.105941e+03       -1.266533  0.411119 -3.550309  3.847786e-04
MIR7844      1.756543e+03       -1.245991  0.458309 -3.252121  1.145474e-03
CFAP69       3.968524e+04       -0.165605  0.414213 -4.504289  6.659565e-06
BCAR3        2.384607e+05        1.687374  0.317277  0.531728  5.949141e-01
CEP57        2.581039e+05        2.015940  0.187578  2.166641  3.026224e-02
...                   ...             ...       ...       ...           ...
ARPC4-TTLL3  1.453446e+06        2.754499  0.127480  5.406044  6.443202e-08
SRGAP3-AS4   1.250571e+02       -2.147935  0.401423 -5.704211  1.168830e-08
GPR45        2.242941e+02       -0.284404  0.683599 -0.805557  4.204984e-01
SULT4A1      9.730213e+03        0.097515  0.576400  0.780916  4.348519e-01
GTSE1-DT     3.043612e+03        0.264104  0.186058  1.376492  1.686693e-01

                     padj
VN1R81P      1.455099e-03
MIR7844      4.072433e-03
CFAP69       3.148617e-05
BCAR3        8.141102e-01
CEP57        8.067255e-02
...                   ...
ARPC4-TTLL3  3.741408e-07
SRGAP3-AS4   7.324277e-08
GPR45        6.568889e-01
SULT4A1      6.704919e-01
GTSE1-DT     3.463657e-01

[4988 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S20_G5000_CNweak_R9.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S20_G5000_CNweak_R9.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S20_G5000_CNweak_R9.csv
============================================================
[INFO] (81/160) sim_S40_G5000_CNstrong_R1.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=1
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.97 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.43 seconds.

Fitting LFCs...
... done in 0.74 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 179 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.18 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
JMJD6       2.786055e+05        1.310410  0.156167   8.539811  1.344420e-17
PLA2G12AP1  4.164931e+03        0.356633  0.151836   2.413558  1.579763e-02
VEGFA       5.029691e+06        2.834496  0.443172   5.622196  1.885453e-08
RHO         7.280777e+02        1.280759  0.710478   2.486218  1.291089e-02
TK1         1.762845e+05       -1.056580  0.502549  -2.622757  8.722144e-03
...                  ...             ...       ...        ...           ...
SCN9A       1.156865e+04        0.486269  0.294072   1.847416  6.468688e-02
BCL2L2      5.693928e+05        0.588515  0.488324   1.590921  1.116273e-01
NADSYN1     6.073103e+05        1.033666  0.143696   7.163172  7.883129e-13
CUL7        1.059643e+06        2.467063  0.160155  15.571342  1.139897e-54
POGK        3.252016e+05       -0.516264  0.363459  -1.696194  8.984922e-02

                    padj
JMJD6       1.462691e-16
PLA2G12AP1  4.595546e-02
VEGFA       1.099334e-07
RHO         3.819694e-02
TK1         2.657645e-02
...                  ...
SCN9A       1.575084e-01
BCL2L2      2.451087e-01
NADSYN1     6.439394e-12
CUL7        6.615379e-53
POGK        2.055367e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.05 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.97 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 177 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 177)
Number of True values in replace_mask: 286
replacement_counts_trimmed shape: (76, 177)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.03 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
JMJD6       2.786055e+05        1.518083  0.130160   0.356198  7.216921e-01
PLA2G12AP1  4.164931e+03        0.369276  0.151962   2.413436  1.580292e-02
VEGFA       5.029691e+06        3.229594  0.055168   4.878584  1.068502e-06
RHO         7.280777e+02        0.707177  0.667466   1.598883  1.098467e-01
TK1         1.762845e+05        1.465162  0.416959  -0.886629  3.752787e-01
...                  ...             ...       ...        ...           ...
SCN9A       1.156865e+04        0.477549  0.293825   1.847407  6.468818e-02
BCL2L2      5.693928e+05        2.155267  0.256673   1.298395  1.941515e-01
NADSYN1     6.073103e+05        1.646989  0.099431  -0.266456  7.898878e-01
CUL7        1.059643e+06        3.315175  0.072676  12.918155  3.555640e-38
POGK        3.252016e+05        0.854515  0.249229  -4.426376  9.582932e-06

                    padj
JMJD6       8.608903e-01
PLA2G12AP1  4.328891e-02
VEGFA       4.843680e-06
RHO         2.370276e-01
TK1         5.889987e-01
...                  ...
SCN9A       1.542564e-01
BCL2L2      3.738466e-01
NADSYN1     8.952717e-01
CUL7        1.109137e-36
POGK        3.956031e-05

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R1.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R1.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R1.csv
============================================================
[INFO] (82/160) sim_S40_G5000_CNstrong_R10.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=10
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.97 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.70 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 196 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.36 seconds.

Fitting MAP LFCs...
... done in 1.65 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
CCL18     27942.243438        0.030936  0.463468  0.081186  9.352942e-01
TMPRSS3   65590.971031       -0.249892  0.533763 -3.514135  4.411880e-04
NPC2     906249.075934       -0.122203  0.188011 -0.716660  4.735837e-01
GZMH       6195.254270        0.581947  0.367364  1.838897  6.593036e-02
OTOGL      3753.492429       -2.103896  0.393081 -5.707743  1.144839e-08
...                ...             ...       ...       ...           ...
CCDC196    1355.908227       -0.717295  0.606018 -1.704106  8.836128e-02
PBOV1       218.306284       -0.331525  0.173331 -1.987877  4.682534e-02
CDHR2      4603.581269        0.171838  0.727581  0.457544  6.472803e-01
FAM215A     231.172512        0.325129  0.218317  1.582315  1.135778e-01
POLD3    143947.989968       -3.331091  1.045058 -4.073255  4.636068e-05

                 padj
CCL18    9.717062e-01
TMPRSS3  1.661354e-03
NPC2     6.808106e-01
GZMH     1.603183e-01
OTOGL    6.706638e-08
...               ...
CCDC196  2.029142e-01
PBOV1    1.206736e-01
CDHR2    8.105773e-01
FAM215A  2.494717e-01
POLD3    1.964922e-04

[4997 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.91 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 191 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 191)
Number of True values in replace_mask: 324
replacement_counts_trimmed shape: (78, 191)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.35 seconds.

Fitting MAP LFCs...
... done in 1.08 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
CCL18     27942.243438        1.191950  0.521526  0.081186  9.352943e-01
TMPRSS3   27330.577168        0.671058  0.112870 -0.251398  8.015067e-01
NPC2     906249.075934        1.757523  0.127435 -0.716660  4.735838e-01
GZMH       6195.254270        0.783623  0.381645  1.838886  6.593196e-02
OTOGL      3753.492429       -2.442645  0.393602 -6.670059  2.556999e-11
...                ...             ...       ...       ...           ...
CCDC196    1355.908227       -0.645758  0.596953 -1.704089  8.836453e-02
PBOV1       218.306284       -0.769282  0.174675 -4.547318  5.433374e-06
CDHR2      4603.581269        0.325612  0.756164  0.308142  7.579742e-01
FAM215A     231.172512        0.324573  0.218259  1.581627  1.137346e-01
POLD3    143947.989968        0.189539  0.616824 -4.455386  8.374231e-06

                 padj
CCL18    9.737347e-01
TMPRSS3  9.100498e-01
NPC2     6.771096e-01
GZMH     1.537387e-01
OTOGL    1.710485e-10
...               ...
CCDC196  1.961606e-01
PBOV1    2.295061e-05
CDHR2    8.863824e-01
FAM215A  2.429072e-01
POLD3    3.461210e-05

[4997 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R10.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R10.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R10.csv
============================================================
[INFO] (83/160) sim_S40_G5000_CNstrong_R11.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=11
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.98 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.47 seconds.

Fitting LFCs...
... done in 0.72 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 178 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.37 seconds.

Fitting MAP LFCs...
... done in 1.18 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE       stat        pvalue  \
OSGEPL1-AS1    2253.397000        0.196463  0.158632   1.276582  2.017499e-01
CPLANE1      225874.050566        0.554157  0.193090   2.972007  2.958596e-03
NPEPL1       263757.796072       -0.017092  0.362082  -0.092234  9.265123e-01
ZNF467       379025.033778        2.987328  0.276955  10.975012  5.039937e-28
ABHD17A      323831.606509        0.343855  0.209559   1.737814  8.224353e-02
...                    ...             ...       ...        ...           ...
TGDS          64592.102028        0.128772  0.207424   0.628177  5.298878e-01
NPAP1           253.134153        0.275036  0.379742   0.860981  3.892484e-01
NOD1         283467.884647        0.650608  0.347545   2.075384  3.795100e-02
NT5C1B         6066.529216        1.849535  0.193086   9.738531  2.065183e-22
NHP2P2          748.855212        0.979999  0.158080   6.337488  2.335421e-10

                     padj
OSGEPL1-AS1  3.907901e-01
CPLANE1      9.721100e-03
NPEPL1       9.649468e-01
ZNF467       9.180411e-27
ABHD17A      1.936215e-01
...                   ...
TGDS         7.216017e-01
NPAP1        6.012961e-01
NOD1         9.958645e-02
NT5C1B       2.961876e-21
NHP2P2       1.486745e-09

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.03 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.41 seconds.

Fitting LFCs...
... done in 0.93 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 183 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 183)
Number of True values in replace_mask: 297
replacement_counts_trimmed shape: (77, 183)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.36 seconds.

Fitting MAP LFCs...
... done in 1.05 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE       stat        pvalue  \
OSGEPL1-AS1    2253.397000        0.177052  0.158616   1.276474  2.017880e-01
CPLANE1      225874.050566        1.165421  0.160560  -2.413171  1.581442e-02
NPEPL1       263757.796072        0.968067  0.267292  -3.197157  1.387892e-03
ZNF467       379025.033778        3.750059  0.177659  10.124334  4.309039e-24
ABHD17A      323831.606509        1.863407  0.176320   1.737814  8.224364e-02
...                    ...             ...       ...        ...           ...
TGDS          64592.102028        1.402101  0.213366   0.628176  5.298885e-01
NPAP1           253.134153        0.272368  0.378976   0.860876  3.893062e-01
NOD1         283467.884647        1.357999  0.231017  -1.230232  2.186101e-01
NT5C1B         6066.529216        1.527064  0.191227   8.262664  1.424568e-16
NHP2P2          748.855212       -0.043060  0.156608  -0.342443  7.320173e-01

                     padj
OSGEPL1-AS1  3.838125e-01
CPLANE1      4.329662e-02
NPEPL1       4.389715e-03
ZNF467       6.400718e-23
ABHD17A      1.882927e-01
...                   ...
TGDS         7.241713e-01
NPAP1        6.018561e-01
NOD1         4.086189e-01
NT5C1B       1.362073e-15
NHP2P2       8.593753e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R11.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R11.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R11.csv
============================================================
[INFO] (84/160) sim_S40_G5000_CNstrong_R12.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=12
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.19 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.74 seconds.

Fitting LFCs...
... done in 0.91 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 212 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.35 seconds.

Fitting MAP LFCs...
... done in 1.61 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
PCGF1     71191.150705       -0.227234  0.147432 -1.607862  0.107865  0.238961
NPAS3     12072.970369       -1.187508  0.281102 -4.527242  0.000006  0.000027
USP8     338874.642731        0.077586  0.099571  0.776288  0.437579  0.646084
YRDC      84604.058012       -0.529381  0.221766 -2.570468  0.010156  0.030877
OSR2     134051.765591        0.812046  0.280928  3.084797  0.002037  0.006880
...                ...             ...       ...       ...       ...       ...
SLC10A7   60492.227861        0.046824  0.172647  0.222058  0.824269  0.917305
MYOM1     62301.209051       -0.328718  0.603379 -0.850612  0.394985  0.605959
ZNF644   263810.398911       -0.128351  0.191149 -0.717280  0.473202  0.680310
FABP9       534.605388       -0.188823  0.359133 -0.624694  0.532172  0.727797
DCAF1    264875.792418       -0.129372  0.611267 -0.287818  0.773486  0.889333

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.41 seconds.

Fitting LFCs...
... done in 0.91 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 210 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 210)
Number of True values in replace_mask: 339
replacement_counts_trimmed shape: (78, 210)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.05 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
PCGF1     71191.150705        0.994926  0.155705 -3.628925  2.846043e-04
NPAS3     12072.970369       -1.352073  0.290102 -6.063197  1.334423e-09
USP8     338874.642731        2.431569  0.106895  0.776287  4.375793e-01
YRDC      84604.058012        1.048133  0.224695 -2.570465  1.015620e-02
OSR2     134051.765591        2.869029  0.243976  6.177728  6.503045e-10
...                ...             ...       ...       ...           ...
SLC10A7   60492.227861        1.182971  0.184783  0.222057  8.242693e-01
MYOM1     62301.209051        1.109361  0.624840 -0.850619  3.949808e-01
ZNF644   263810.398911        1.638383  0.153836 -0.717279  4.732020e-01
FABP9       534.605388       -1.282096  0.381038 -3.725110  1.952301e-04
DCAF1    264875.792418        1.614031  0.388728 -0.287785  7.735116e-01

                 padj
PCGF1    9.819439e-04
NPAS3    7.599811e-09
USP8     6.458826e-01
YRDC     2.869156e-02
OSR2     3.776914e-09
...               ...
SLC10A7  9.158751e-01
MYOM1    6.044660e-01
ZNF644   6.815256e-01
FABP9    6.825530e-04
DCAF1    8.899595e-01

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R12.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R12.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R12.csv
============================================================
[INFO] (85/160) sim_S40_G5000_CNstrong_R13.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=13
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.30 seconds.

Fitting dispersion trend curve...
... done in 0.35 seconds.

Fitting MAP dispersions...
... done in 1.58 seconds.

Fitting LFCs...
... done in 0.94 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 182 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.13 seconds.

Running Wald tests...
... done in 0.39 seconds.

Fitting MAP LFCs...
... done in 1.19 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
EPDR1       68264.990315       -0.523492  0.336603  -1.793888  7.283099e-02
INTS12     126162.300749        0.184793  0.098571   1.774844  7.592358e-02
LINC00943     469.586099       -0.349814  0.483350  -0.974099  3.300075e-01
PCDH9       32963.361763        0.101848  0.424773   0.296132  7.671294e-01
LRGUK       15500.245305        1.641101  0.388448   4.593484  4.359069e-06
...                  ...             ...       ...        ...           ...
MIR155HG     5635.973560       -0.456649  0.154537  -3.052029  2.273004e-03
TNFAIP3    215509.741192       -1.526601  0.204972  -7.710026  1.257922e-14
CRYBG3     190681.863819       -2.129413  0.128280 -16.786064  3.086459e-63
ATXN3      193718.761010       -0.587922  0.358810  -1.931525  5.341818e-02
NCR1          479.437004       -1.380636  0.110910 -12.559229  3.537629e-36

                   padj
EPDR1      1.790414e-01
INTS12     1.853636e-01
LINC00943  5.529346e-01
PCDH9      8.862985e-01
LRGUK      2.071000e-05
...                 ...
MIR155HG   7.768437e-03
TNFAIP3    1.203114e-13
CRYBG3     3.015652e-61
ATXN3      1.370663e-01
NCR1       1.137291e-34

[4983 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 1.33 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 174 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 174)
Number of True values in replace_mask: 299
replacement_counts_trimmed shape: (78, 174)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.16 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
EPDR1       68264.990315        0.776068  0.336888  -2.994957  2.744833e-03
INTS12     126162.300749        2.405767  0.113273   1.774837  7.592473e-02
LINC00943     469.586099       -0.361164  0.483058  -0.974061  3.300261e-01
PCDH9       32963.361763        1.337721  0.462213   0.296132  7.671295e-01
LRGUK       15500.245305        2.393362  0.378206   4.030419  5.567753e-05
...                  ...             ...       ...        ...           ...
MIR155HG     5635.973560       -0.776702  0.155868  -5.302590  1.141710e-07
TNFAIP3    215509.741192        0.690416  0.200934  -8.978209  2.752090e-19
CRYBG3     190681.863819        0.165705  0.157194 -18.994237  1.903335e-80
ATXN3      193718.761010        1.152185  0.321386  -1.931524  5.341823e-02
NCR1          479.437004       -1.855499  0.110991 -16.750599  5.605899e-63

                   padj
EPDR1      8.474291e-03
INTS12     1.776211e-01
LINC00943  5.463522e-01
PCDH9      8.862987e-01
LRGUK      2.113032e-04
...                 ...
MIR155HG   5.577587e-07
TNFAIP3    3.181825e-18
CRYBG3     3.951800e-78
ATXN3      1.305915e-01
NCR1       5.943446e-61

[4983 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R13.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R13.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R13.csv
============================================================
[INFO] (86/160) sim_S40_G5000_CNstrong_R14.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=14
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.85 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.34 seconds.

Fitting LFCs...
... done in 0.65 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 181 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.21 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
MIA3       5.848402e+05       -0.050437  0.210881 -0.358591  7.199014e-01
CTNNB1     2.272242e+06       -0.064307  0.172408 -0.363288  7.163898e-01
DDX10      1.818631e+05        0.069474  0.171141  0.329961  7.414291e-01
RNU6-322P  3.518118e+02       -1.011804  0.405099 -2.879259  3.986106e-03
RN7SL130P  6.632020e+02       -0.126788  0.386720 -0.401335  6.881735e-01
...                 ...             ...       ...       ...           ...
GPR137     2.156819e+05       -0.275832  0.258460 -1.234242  2.171127e-01
DDX52      1.378359e+05       -1.847264  0.226896 -8.384130  5.110216e-17
TOR1AIP1   4.545307e+05       -0.272274  0.168266 -1.844779  6.506972e-02
ACTBP11    1.267955e+04       -0.335140  0.119882 -2.859025  4.249453e-03
RPS3AP49   9.128269e+03        0.013653  0.504792  0.030876  9.753681e-01

                   padj
MIA3       8.545326e-01
CTNNB1     8.535857e-01
DDX10      8.646942e-01
RNU6-322P  1.294446e-02
RN7SL130P  8.375412e-01
...                 ...
GPR137     4.069742e-01
DDX52      5.201991e-16
TOR1AIP1   1.567203e-01
ACTBP11    1.373705e-02
RPS3AP49   9.874439e-01

[4988 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.03 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 1.07 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 173 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 173)
Number of True values in replace_mask: 310
replacement_counts_trimmed shape: (77, 173)

... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.12 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.01 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
MIA3       5.848402e+05        0.887283  0.129855  -5.731600  9.948776e-09
CTNNB1     2.272242e+06        1.950466  0.062911  -0.363288  7.163898e-01
DDX10      1.818631e+05        1.662454  0.159505   0.329961  7.414293e-01
RNU6-322P  3.518118e+02       -1.320389  0.408708  -3.648347  2.639335e-04
RN7SL130P  6.632020e+02       -0.130721  0.387056  -0.401318  6.881861e-01
...                 ...             ...       ...        ...           ...
GPR137     2.156819e+05        1.119527  0.201582  -3.092400  1.985451e-03
DDX52      1.378359e+05        0.390131  0.240146  -9.482690  2.478109e-21
TOR1AIP1   4.545307e+05        0.722097  0.128257  -8.020242  1.055370e-15
ACTBP11    1.267955e+04       -1.413861  0.118633 -11.254815  2.192851e-29
RPS3AP49   9.128269e+03        0.412894  0.538543   0.030875  9.753692e-01

                   padj
MIA3       5.089692e-08
CTNNB1     8.573302e-01
DDX10      8.691663e-01
RNU6-322P  8.895271e-04
RN7SL130P  8.423842e-01
...                 ...
GPR137     6.068277e-03
DDX52      3.252844e-20
TOR1AIP1   9.076184e-15
ACTBP11    4.883010e-28
RPS3AP49   9.864439e-01

[4988 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R14.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R14.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R14.csv
============================================================
[INFO] (87/160) sim_S40_G5000_CNstrong_R15.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=15
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.85 seconds.

Fitting dispersion trend curve...
... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 1.22 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 189 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
... done in 1.03 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
BBIP1       377874.709428        0.157787  0.245981  0.632815  5.268542e-01
DMWD        373767.626659        1.294333  0.134090  9.602735  7.785064e-22
TMEM163      18269.194760       -0.041614  0.321638 -0.160317  8.726311e-01
RPTOR       325511.174384        0.940102  0.165172  5.812400  6.158356e-09
CRYGS        43364.163088        0.736963  0.185484  4.102918  4.079724e-05
...                   ...             ...       ...       ...           ...
VWA8        161449.244674        0.159004  0.281646  0.565371  5.718214e-01
FGB          29429.158458       -0.665755  0.505376 -1.739597  8.192974e-02
THAP6        71899.324376       -0.598356  0.429873 -1.742979  8.133724e-02
HNRNPA3P13     424.039243        0.523356  0.901916  1.299740  1.936903e-01
GUSBP5        4188.418766        0.230412  0.185067  1.288340  1.976277e-01

                    padj
BBIP1       7.337983e-01
DMWD        1.109705e-20
TMEM163     9.406994e-01
RPTOR       3.635981e-08
CRYGS       1.687707e-04
...                  ...
VWA8        7.642156e-01
FGB         1.940871e-01
THAP6       1.929584e-01
HNRNPA3P13  3.820328e-01
GUSBP5      3.869564e-01

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.16 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.86 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 189 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 189)
Number of True values in replace_mask: 300
replacement_counts_trimmed shape: (79, 189)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.06 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
BBIP1       377874.709428        1.783058  0.188877  0.632815  5.268543e-01
DMWD        373767.626659        2.411407  0.113658  6.740633  1.576983e-11
TMEM163      18269.194760        0.822799  0.352372 -0.160317  8.726314e-01
RPTOR       325511.174384        1.591412  0.128408  0.142579  8.866224e-01
CRYGS        43364.163088        1.060934  0.187773 -1.147374  2.512272e-01
...                   ...             ...       ...       ...           ...
VWA8        161449.244674        1.602776  0.263541  0.565371  5.718215e-01
FGB          29429.158458        0.550663  0.506515 -1.739596  8.192994e-02
THAP6        71899.324376        0.773824  0.419141 -2.678889  7.386696e-03
HNRNPA3P13     424.039243        0.525412  0.904199  1.299684  1.937095e-01
GUSBP5        4188.418766        0.239927  0.185080  1.288297  1.976426e-01

                    padj
BBIP1       7.319605e-01
DMWD        9.773377e-11
TMEM163     9.393395e-01
RPTOR       9.461731e-01
CRYGS       4.520200e-01
...                  ...
VWA8        7.632127e-01
FGB         1.882766e-01
THAP6       2.122824e-02
HNRNPA3P13  3.747743e-01
GUSBP5      3.801229e-01

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R15.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R15.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R15.csv
============================================================
[INFO] (88/160) sim_S40_G5000_CNstrong_R16.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=16
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 0.74 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 207 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.30 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
TMEM167A   466854.416662       -0.198912  0.146475 -1.430741  1.525045e-01
LINC02021    2888.639709       -0.899043  0.315778 -3.136820  1.707911e-03
FAAP100    179704.768257       -0.904992  0.181930 -5.170790  2.331061e-07
MYOM2       20044.108609       -0.339825  0.373028 -1.093610  2.741263e-01
FOXN3-AS1   12334.878407        0.066378  0.248247  0.272734  7.850577e-01
...                  ...             ...       ...       ...           ...
IPO8P1      15527.847259        0.267572  0.201640  1.373593  1.695679e-01
ATP6V1B1   222106.610843        2.345081  0.563179  4.628267  3.687383e-06
KCNH3        5974.497457       -1.355958  0.149376 -9.226826  2.787699e-20
KRTAP1-5      158.798581       -0.487042  0.192672 -2.647367  8.112121e-03
AGA        126106.342886        0.008100  0.133719  0.008756  9.930139e-01

                   padj
TMEM167A   3.159364e-01
LINC02021  5.917200e-03
FAAP100    1.246481e-06
MYOM2      4.810468e-01
FOXN3-AS1  8.999791e-01
...                 ...
IPO8P1     3.430553e-01
ATP6V1B1   1.747042e-05
KCNH3      3.485672e-19
KRTAP1-5   2.475313e-02
AGA        9.976833e-01

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.01 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.34 seconds.

Fitting LFCs...
... done in 0.89 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 207 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 207)
Number of True values in replace_mask: 337
replacement_counts_trimmed shape: (79, 207)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.28 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
TMEM167A   466854.416662        1.771396  0.124833  -1.430740  1.525047e-01
LINC02021    2888.639709       -1.195072  0.317258  -4.159206  3.193559e-05
FAAP100    179704.768257        1.912140  0.185931  -0.372402  7.095934e-01
MYOM2       20044.108609        0.606160  0.398912  -1.093608  2.741270e-01
FOXN3-AS1   12334.878407       -0.025467  0.243967   0.272732  7.850589e-01
...                  ...             ...       ...        ...           ...
IPO8P1      15527.847259        1.053583  0.201133   5.641995  1.680910e-08
ATP6V1B1   222106.610843        3.272412  0.296127   4.056725  4.976568e-05
KCNH3        5974.497457       -1.730259  0.149761 -12.150865  5.676205e-34
KRTAP1-5      158.798581       -0.756822  0.193799  -4.064474  4.814100e-05
AGA        126106.342886        1.690446  0.137090   0.008756  9.930139e-01

                   padj
TMEM167A   3.087849e-01
LINC02021  1.187233e-04
FAAP100    8.498380e-01
MYOM2      4.770212e-01
FOXN3-AS1  8.920052e-01
...                 ...
IPO8P1     8.394453e-08
ATP6V1B1   1.808310e-04
KCNH3      1.401910e-32
KRTAP1-5   1.750550e-04
AGA        9.973641e-01

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R16.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R16.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R16.csv
============================================================
[INFO] (89/160) sim_S40_G5000_CNstrong_R17.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=17
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.84 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.32 seconds.

Fitting LFCs...
... done in 0.85 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 186 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.36 seconds.

Fitting MAP LFCs...
... done in 1.18 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE       stat        pvalue  \
DNAJB14  2.333396e+05       -0.198433  0.127930  -1.590462  1.117307e-01
GAL3ST3  1.068684e+02       -1.603974  1.042235  -1.681329  9.269902e-02
KCTD3    6.624198e+05       -0.077144  0.233305  -0.292351  7.700186e-01
SFRP2    2.236516e+06       -0.377080  0.397713  -1.045098  2.959775e-01
WDR1     1.765162e+06       -0.204598  0.145879  -1.608935  1.076305e-01
...               ...             ...       ...        ...           ...
TDG      1.512423e+05        0.041464  0.402683   0.077847  9.379495e-01
DBN1     5.454359e+05       -0.731717  0.126202  -5.760888  8.367234e-09
SIGLEC1  1.144322e+05       -0.420036  0.791223  -1.097352  2.724874e-01
ENGASE   4.802745e+05        1.135090  0.102145  10.944714  7.043993e-28
OR7E2P   4.165892e+02        0.166340  0.234666   0.759018  4.478416e-01

                 padj
DNAJB14  2.463184e-01
GAL3ST3  2.105761e-01
KCTD3    8.788875e-01
SFRP2    5.053883e-01
WDR1     2.390565e-01
...               ...
TDG      9.698037e-01
DBN1     4.694112e-08
SIGLEC1  4.773788e-01
ENGASE   1.260597e-26
OR7E2P   6.631297e-01

[4993 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.35 seconds.

Fitting LFCs...
... done in 0.86 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 180 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 180)
Number of True values in replace_mask: 308
replacement_counts_trimmed shape: (77, 180)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.04 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat        pvalue  \
DNAJB14  2.333396e+05        1.786742  0.126841 -1.590460  1.117312e-01
GAL3ST3  1.551851e+01       -2.725984  0.057424  1.232941  2.175979e-01
KCTD3    6.624198e+05        1.097490  0.126338 -4.202024  2.645392e-05
SFRP2    2.236516e+06        1.598653  0.128350 -1.045098  2.959775e-01
WDR1     1.765162e+06        1.955259  0.076319 -1.608935  1.076305e-01
...               ...             ...       ...       ...           ...
TDG      1.512423e+05        1.558653  0.373466  0.077847  9.379501e-01
DBN1     5.454359e+05        1.334448  0.102819 -8.166568  3.172870e-16
SIGLEC1  1.144322e+05        0.981259  0.944138 -0.241828  8.089135e-01
ENGASE   4.802745e+05        1.606219  0.096661 -0.844924  3.981536e-01
OR7E2P   4.165892e+02        0.167802  0.234773  0.758865  4.479335e-01

                 padj
DNAJB14  2.442529e-01
GAL3ST3  4.066116e-01
KCTD3    1.018384e-04
SFRP2    5.050490e-01
WDR1     2.370530e-01
...               ...
TDG      9.688012e-01
DBN1     2.864763e-15
SIGLEC1  9.035552e-01
ENGASE   6.177458e-01
OR7E2P   6.586693e-01

[4993 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R17.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R17.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R17.csv
============================================================
[INFO] (90/160) sim_S40_G5000_CNstrong_R18.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=18
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.90 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.45 seconds.

Fitting LFCs...
... done in 0.67 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 190 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.36 seconds.

Fitting MAP LFCs...
... done in 1.62 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC02766  6.888768e+02        0.504451  0.639487   1.215775  2.240707e-01
SLC25A48   1.041661e+04        0.038584  0.501188   0.098099  9.218536e-01
TYSND1     1.709673e+05        0.067829  0.180632   0.357264  7.208939e-01
RAD51D     1.045480e+05        0.211348  0.186173   1.157338  2.471344e-01
SIGLEC5    1.163814e+04       -0.747939  0.273023  -2.982804  2.856212e-03
...                 ...             ...       ...        ...           ...
ARLNC1     1.537136e+03       -0.518711  0.609128  -1.270038  2.040711e-01
CXCL9      2.124546e+05       -1.258994  0.622428  -2.637060  8.362796e-03
AP2A1      1.310951e+06        1.216000  0.371535   3.641685  2.708591e-04
RFC2       6.125440e+05        2.447340  0.132084  18.539117  9.984729e-77
QRICH1     5.027740e+05        0.389417  0.259278   1.653574  9.821405e-02

                   padj
LINC02766  4.191667e-01
SLC25A48   9.651038e-01
TYSND1     8.606561e-01
RAD51D     4.496711e-01
SIGLEC5    9.464597e-03
...                 ...
ARLNC1     3.905467e-01
CXCL9      2.552827e-02
AP2A1      1.027247e-03
RFC2       1.245845e-74
QRICH1     2.232178e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.90 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.36 seconds.

Fitting LFCs...
... done in 0.89 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 187 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 187)
Number of True values in replace_mask: 305
replacement_counts_trimmed shape: (78, 187)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.04 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC02766  6.888768e+02        0.522217  0.641959   1.215755  2.240784e-01
SLC25A48   1.041661e+04       -0.069117  0.503015   0.098099  9.218537e-01
TYSND1     1.709673e+05        1.658055  0.165218   0.357264  7.208941e-01
RAD51D     1.045480e+05        1.614515  0.184463   1.157336  2.471350e-01
SIGLEC5    1.163814e+04       -0.931192  0.282744  -4.612757  3.973635e-06
...                 ...             ...       ...        ...           ...
ARLNC1     1.537136e+03       -0.469869  0.602484  -1.270028  2.040746e-01
CXCL9      2.124546e+05        0.869475  0.443727  -3.135295  1.716814e-03
AP2A1      1.310951e+06        2.297826  0.104041   2.225496  2.604798e-02
RFC2       6.125440e+05        3.281806  0.090271  15.086309  1.992819e-51
QRICH1     5.027740e+05        2.012846  0.170555   1.653593  9.821024e-02

                   padj
LINC02766  4.148276e-01
SLC25A48   9.641841e-01
TYSND1     8.610680e-01
RAD51D     4.465789e-01
SIGLEC5    1.622947e-05
...                 ...
ARLNC1     3.862500e-01
CXCL9      5.375546e-03
AP2A1      6.792343e-02
RFC2       1.092985e-49
QRICH1     2.186295e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R18.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R18.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R18.csv
============================================================
[INFO] (91/160) sim_S40_G5000_CNstrong_R19.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=19
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.03 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.33 seconds.

Fitting LFCs...
... done in 0.65 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 198 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.17 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE       stat        pvalue  \
NOTCH1   516530.394453       -0.357119  0.297952  -1.315026  1.885012e-01
TMEM30A  659960.312078       -1.034141  0.154999  -7.023470  2.164252e-12
ZIC4       8199.467986        1.190018  0.742196   2.302653  2.129838e-02
ZBTB24   330335.993261        2.455529  0.154248  15.992325  1.445355e-57
SVIP     554113.744687        2.626155  0.287465   9.343063  9.358639e-21
...                ...             ...       ...        ...           ...
ZHX2     316275.048170        0.239660  0.433218   0.674580  4.999424e-01
HOXD3     30140.654973       -0.282248  0.346990  -0.947534  3.433665e-01
RARS2    197857.861664        0.068067  0.290814   0.205392  8.372659e-01
PRAL     341533.914761        0.052606  0.103661   0.499171  6.176592e-01
GRIK1     13337.085742        1.618696  0.328225   5.227269  1.720319e-07

                 padj
NOTCH1   3.681186e-01
TMEM30A  1.579841e-11
ZIC4     5.901376e-02
ZBTB24   1.223162e-55
SVIP     1.128688e-19
...               ...
ZHX2     6.930073e-01
HOXD3    5.528633e-01
RARS2    9.179458e-01
PRAL     7.885453e-01
GRIK1    8.773804e-07

[4993 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.99 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.87 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 199 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 199)
Number of True values in replace_mask: 320
replacement_counts_trimmed shape: (78, 199)

... done in 0.10 seconds.

Fitting LFCs...
... done in 0.13 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.07 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE       stat        pvalue  \
NOTCH1   516530.394453        1.514168  0.197808  -1.315026  1.885012e-01
TMEM30A  659960.312078        1.071128  0.123175  -8.673166  4.202681e-18
ZIC4       8199.467986        1.498296  0.746723   0.888068  3.745044e-01
ZBTB24   330335.993261        3.281012  0.113677  13.796317  2.682090e-43
SVIP     554113.744687        3.409224  0.160730   8.239690  1.726573e-16
...                ...             ...       ...        ...           ...
ZHX2     316275.048170        1.323638  0.275099  -1.400650  1.613187e-01
HOXD3     30140.654973        0.906460  0.373993  -0.947533  3.433671e-01
RARS2    197857.861664        1.583817  0.259208   0.205392  8.372660e-01
PRAL     341533.914761        2.410267  0.104602   0.499170  6.176597e-01
GRIK1     13337.085742        2.124640  0.331005   4.067883  4.744213e-05

                 padj
NOTCH1   3.658296e-01
TMEM30A  4.273724e-17
ZIC4     5.830685e-01
ZBTB24   1.144588e-41
SVIP     1.542178e-15
...               ...
ZHX2     3.247414e-01
HOXD3    5.550688e-01
RARS2    9.169401e-01
PRAL     7.885514e-01
GRIK1    1.794535e-04

[4993 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R19.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R19.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R19.csv
============================================================
[INFO] (92/160) sim_S40_G5000_CNstrong_R2.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=2
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.43 seconds.

Fitting dispersion trend curve...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 1.11 seconds.

Fitting LFCs...
... done in 0.67 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 178 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.05 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.16 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SPHKAP     5.273611e+03       -1.856134  0.959777 -2.846096  4.425891e-03
P2RX3      1.140842e+02        0.237003  0.764652  1.703534  8.846812e-02
SRSF5      2.077748e+06       -0.107267  0.210008 -0.150469  8.803943e-01
MFSD2A     7.263917e+04        0.325689  0.378337  0.979208  3.274772e-01
SMOC2      5.100185e+05        0.032540  0.378275  0.068321  9.455302e-01
...                 ...             ...       ...       ...           ...
RNU6-395P  1.845927e+03       -0.062260  0.510504 -0.176739  8.597134e-01
ZNF33A     1.160497e+06        2.790428  0.554492  5.109291  3.233694e-07
CHTF18     2.174302e+05        0.925825  0.357346  2.874849  4.042206e-03
ZC3H7B     5.470512e+05        0.032743  0.376848  0.061625  9.508616e-01
NOX4       5.825380e+04        0.104688  0.163407  0.622029  5.339228e-01

               padj
SPHKAP     0.014160
P2RX3      0.201803
SRSF5      0.939100
MFSD2A     0.535687
SMOC2      0.972818
...             ...
RNU6-395P  0.929705
ZNF33A     0.000002
CHTF18     0.013050
ZC3H7B     0.975889
NOX4       0.723873

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.99 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.50 seconds.

Fitting LFCs...
... done in 0.88 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

Replacing 176 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 176)
Number of True values in replace_mask: 269
replacement_counts_trimmed shape: (76, 176)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.04 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SPHKAP     5.273611e+03       -0.971368  0.987151 -2.846089  0.004426
P2RX3      6.584326e+00        0.396933  0.053753  0.514060  0.607210
SRSF5      2.077748e+06        1.820336  0.089362 -0.150469  0.880394
MFSD2A     7.263917e+04        1.751710  0.338807  0.979206  0.327478
SMOC2      5.100185e+05        1.748401  0.228438  0.068321  0.945530
...                 ...             ...       ...       ...       ...
RNU6-395P  1.845927e+03       -0.121471  0.510832 -0.176738  0.859714
ZNF33A     1.160497e+06        3.383008  0.136940  4.343725  0.000014
CHTF18     2.174302e+05        1.607390  0.248184  0.051543  0.958893
ZC3H7B     5.470512e+05        1.759717  0.224041  0.061625  0.950862
NOX4       5.825380e+04        1.513838  0.167151  0.622027  0.533924

               padj
SPHKAP     0.013094
P2RX3      0.785408
SRSF5      0.945160
MFSD2A     0.534896
SMOC2      0.975231
...             ...
RNU6-395P  0.935812
ZNF33A     0.000054
CHTF18     0.981307
ZC3H7B     0.976894
NOX4       0.728845

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R2.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R2.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R2.csv
============================================================
[INFO] (93/160) sim_S40_G5000_CNstrong_R20.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=20
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.88 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.31 seconds.

Fitting LFCs...
... done in 0.66 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 200 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.16 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                   baseMean  log2FoldChange     lfcSE      stat        pvalue  \
PRICKLE2-AS2     197.064272       -0.392904  0.793792 -1.039090  2.987627e-01
HCCAT5            86.321424        0.138316  0.713768 -0.380478  7.035906e-01
THY1          774907.819551       -0.495410  0.483688 -1.387602  1.652581e-01
PPARD         191366.802608       -1.374003  0.150473 -9.359842  7.985630e-21
FAM180A        54774.274372        1.735218  0.336204  5.433709  5.519441e-08
...                     ...             ...       ...       ...           ...
MYHAS           2696.651545        0.063997  0.328987  0.220579  8.254202e-01
SYCE1L         18093.167763       -0.111316  0.157028 -0.762425  4.458061e-01
SAR1B         368588.189023        0.126177  0.202650  0.660586  5.088776e-01
TXNL4B         47718.284740       -0.275047  0.485292 -0.756181  4.495406e-01
HSD17B6        30733.792739        1.053857  0.169621  6.374457  1.836128e-10

                      padj
PRICKLE2-AS2  5.089991e-01
HCCAT5        8.422699e-01
THY1          3.334362e-01
PPARD         1.079683e-19
FAM180A       2.951393e-07
...                    ...
MYHAS         9.152238e-01
SYCE1L        6.476781e-01
SAR1B         6.984293e-01
TXNL4B        6.506108e-01
HSD17B6       1.200583e-09

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.22 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.50 seconds.

Fitting LFCs...
... done in 1.25 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 198 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 198)
Number of True values in replace_mask: 335
replacement_counts_trimmed shape: (79, 198)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.03 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                   baseMean  log2FoldChange     lfcSE       stat  \
PRICKLE2-AS2     197.064272       -0.381365  0.784833  -1.039061
HCCAT5            10.021150        0.315365  0.048420  -0.379603
THY1          774907.819551        1.442157  0.179896  -1.387602
PPARD         191366.802608        0.236468  0.165101 -12.225787
FAM180A        54774.274372        2.472888  0.306908   4.468237
...                     ...             ...       ...        ...
MYHAS           2696.651545       -0.002750  0.328153   0.220576
SYCE1L         18093.167763       -0.187520  0.155332  -0.762417
SAR1B         368588.189023        1.729956  0.170410   0.660586
TXNL4B         47718.284740        1.119150  0.508103  -0.756181
HSD17B6        30733.792739        1.780051  0.175065   4.572188

                    pvalue          padj
PRICKLE2-AS2  2.987762e-01  5.096049e-01
HCCAT5        7.042399e-01  8.468193e-01
THY1          1.652581e-01  3.286663e-01
PPARD         2.263776e-34  5.348251e-33
FAM180A       7.886684e-06  3.127716e-05
...                    ...           ...
MYHAS         8.254228e-01  9.102640e-01
SYCE1L        4.458109e-01  6.535853e-01
SAR1B         5.088777e-01  7.058079e-01
TXNL4B        4.495408e-01  6.563423e-01
HSD17B6       4.826577e-06  1.964094e-05

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R20.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R20.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R20.csv
============================================================
[INFO] (94/160) sim_S40_G5000_CNstrong_R3.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=3
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.99 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.70 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 191 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.34 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
SULT2B1   113524.439575        0.949888  0.458048   2.450229  1.427653e-02
MORN2      45188.273958       -1.028281  0.229930  -4.720435  2.353404e-06
PRR7-AS1    2449.256644        1.087527  0.257423   4.462358  8.106275e-06
FMO2      467389.281220       -0.187253  0.377569  -0.538780  5.900387e-01
NFYC      297956.375568       -0.065551  0.130147  -0.574849  5.653934e-01
...                 ...             ...       ...        ...           ...
GAS2        5053.895896       -1.921316  0.187860 -10.400490  2.466626e-25
AGMAT      10423.952482        0.235611  0.703228   0.597176  5.503900e-01
LIPT1      32579.886605       -0.047214  0.135438  -0.390106  6.964582e-01
PGPEP1     92693.587499       -1.496608  0.265333  -5.915642  3.305837e-09
ADAMTS15  258014.678317        0.316914  0.605727  -0.131288  8.955475e-01

                  padj
SULT2B1   4.184877e-02
MORN2     1.108320e-05
PRR7-AS1  3.665446e-05
FMO2      7.760043e-01
NFYC      7.609716e-01
...                ...
GAS2      4.104465e-24
AGMAT     7.488544e-01
LIPT1     8.439406e-01
PGPEP1    2.014987e-08
ADAMTS15  9.524841e-01

[4992 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.33 seconds.

Fitting LFCs...
... done in 0.87 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 187 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 187)
Number of True values in replace_mask: 321
replacement_counts_trimmed shape: (78, 187)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.01 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
SULT2B1   113524.439575        2.038180  0.346296   1.516606  1.293662e-01
MORN2      45188.273958        0.055567  0.245752  -6.300127  2.974026e-10
PRR7-AS1    2449.256644        0.850035  0.256351   3.492710  4.781454e-04
FMO2      467389.281220        1.016382  0.222600  -3.298089  9.734536e-04
NFYC      297956.375568        1.940432  0.115737  -0.584036  5.591963e-01
...                 ...             ...       ...        ...           ...
GAS2        5053.895896       -2.367169  0.188961 -12.866191  6.975826e-38
AGMAT      10423.952482        1.342320  0.886592   0.597163  5.503987e-01
LIPT1      32579.886605       -0.073534  0.135147  -0.390102  6.964613e-01
PGPEP1     92693.587499        0.328522  0.275388  -7.424456  1.132442e-13
ADAMTS15   82549.928805        2.172247  0.127477  -0.779535  4.356645e-01

                  padj
SULT2B1   2.716853e-01
MORN2     1.734385e-09
PRR7-AS1  1.583877e-03
FMO2      3.149372e-03
NFYC      7.532402e-01
...                ...
GAS2      2.204008e-36
AGMAT     7.486622e-01
LIPT1     8.432589e-01
PGPEP1    8.617608e-13
ADAMTS15  6.513438e-01

[4992 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R3.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R3.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R3.csv
============================================================
[INFO] (95/160) sim_S40_G5000_CNstrong_R4.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=4
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.87 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.46 seconds.

Fitting LFCs...
... done in 1.34 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 183 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
... done in 1.16 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
TCP11        5102.537921        1.076419  0.605577   2.340467  1.925963e-02
RNA5SP216   20098.990873        1.752485  0.188529   9.474968  2.668427e-21
EML5        89684.721967       -0.058500  0.102392  -0.558916  5.762187e-01
TEX19        1640.294838        0.869562  0.973606   1.804433  7.116343e-02
PA2G4P5     37689.975058        1.325176  0.123283  10.883829  1.376569e-27
...                  ...             ...       ...        ...           ...
LINC02345    1269.861662        0.272660  0.638143   0.694717  4.872324e-01
DOCK1      514480.908952        0.003682  0.137167  -0.107955  9.140317e-01
ANKRD39     68772.399538       -0.264448  0.376174  -0.865546  3.867392e-01
IFT81       85361.334088       -0.289274  0.168486  -1.784103  7.440697e-02
SCN3B       31521.641954        0.297772  0.211940   1.461195  1.439619e-01

                   padj
TCP11      5.588763e-02
RNA5SP216  3.398496e-20
EML5       7.628339e-01
TEX19      1.761101e-01
PA2G4P5    2.499850e-26
...                 ...
LINC02345  7.018282e-01
DOCK1      9.597901e-01
ANKRD39    6.110014e-01
IFT81      1.824194e-01
SCN3B      3.093570e-01

[4994 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.99 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.32 seconds.

Fitting LFCs...
... done in 0.85 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 182 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 182)
Number of True values in replace_mask: 302
replacement_counts_trimmed shape: (76, 182)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.04 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
TCP11        5102.537921        1.322284  0.636063  1.554141  1.201509e-01
RNA5SP216   20098.990873        1.946576  0.196207  7.731203  1.065347e-14
EML5        89684.721967        0.466034  0.109669 -0.558914  5.762207e-01
TEX19        1640.294838        0.435884  0.814198  0.533794  5.934843e-01
PA2G4P5     37689.975058        1.217231  0.127487  7.693294  1.433948e-14
...                  ...             ...       ...       ...           ...
LINC02345    1269.861662        0.256634  0.636891  0.694713  4.872355e-01
DOCK1      514480.908952        1.921669  0.118054 -0.107955  9.140317e-01
ANKRD39     68772.399538        1.259985  0.361426 -0.865546  3.867394e-01
IFT81       85361.334088        1.065431  0.179636 -1.784099  7.440754e-02
SCN3B       31521.641954        1.539221  0.216753  1.461190  1.439633e-01

                   padj
TCP11      2.588582e-01
RNA5SP216  8.526188e-14
EML5       7.588729e-01
TEX19      7.683684e-01
PA2G4P5    1.140309e-13
...                 ...
LINC02345  6.945112e-01
DOCK1      9.579773e-01
ANKRD39    6.039327e-01
IFT81      1.730746e-01
SCN3B      2.986924e-01

[4994 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R4.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R4.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R4.csv
============================================================
[INFO] (96/160) sim_S40_G5000_CNstrong_R5.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=5
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.05 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.33 seconds.

Fitting LFCs...
... done in 0.66 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 205 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.35 seconds.

Fitting MAP LFCs...
... done in 1.19 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
MLYCD      9.600855e+04        0.305614  0.192980   1.671306  9.466126e-02
RPL26      1.982481e+06       -0.176738  0.152367  -0.781045  4.347761e-01
FASTKD5    1.793557e+05        1.373046  0.219293   6.424953  1.319104e-10
ADCY10     3.202376e+03        0.564243  0.374131   1.762086  7.805479e-02
UPK2       4.521873e+03       -0.000074  0.256841  -0.003000  9.976063e-01
...                 ...             ...       ...        ...           ...
RPS15AP14  5.484145e+01        1.281125  0.869698   0.374099  7.083308e-01
POMT2      2.284540e+05        0.610677  0.886554   1.378650  1.680028e-01
NKX2-8     5.477618e+02       -0.407461  0.109286  -3.786876  1.525533e-04
NHLH1      1.660175e+03       -0.008642  0.263170  -0.038749  9.690906e-01
REEP1      1.847635e+05        2.148297  0.154795  13.927054  4.338845e-44

                   padj
MLYCD      2.140279e-01
RPL26      6.464639e-01
FASTKD5    8.729878e-10
ADCY10     1.822618e-01
UPK2       9.988073e-01
...                 ...
RPS15AP14  8.424879e-01
POMT2      3.343973e-01
NKX2-8     5.919448e-04
NHLH1      9.868902e-01
REEP1      1.615734e-42

[4990 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.98 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.34 seconds.

Fitting LFCs...
... done in 0.87 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 204 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 204)
Number of True values in replace_mask: 356
replacement_counts_trimmed shape: (78, 204)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.50 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
MLYCD      9.600855e+04        1.675211  0.189304   1.671304  9.466170e-02
RPL26      1.982481e+06        1.973608  0.068106  -0.781045  4.347761e-01
FASTKD5    1.793557e+05        1.693037  0.179879   1.490540  1.360824e-01
ADCY10     3.202376e+03       -0.453873  0.365712  -1.328557  1.839941e-01
UPK2       4.521873e+03       -0.030621  0.255970  -0.003000  9.976064e-01
...                 ...             ...       ...        ...           ...
RPS15AP14  1.870529e+01        1.906187  0.161807  -2.117579  3.421072e-02
POMT2      2.284540e+05        2.584081  0.471157   1.378637  1.680066e-01
NKX2-8     5.477618e+02       -0.775070  0.109555  -7.148702  8.760243e-13
NHLH1      1.660175e+03       -1.245582  0.272387  -4.884679  1.035976e-06
REEP1      1.847635e+05        2.791639  0.135473  10.756489  5.523471e-27

                   padj
MLYCD      2.100320e-01
RPL26      6.414941e-01
FASTKD5    2.777306e-01
ADCY10     3.485690e-01
UPK2       9.990078e-01
...                 ...
RPS15AP14  8.714217e-02
POMT2      3.263343e-01
NKX2-8     5.907245e-12
NHLH1      4.366148e-06
REEP1      8.891007e-26

[4990 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R5.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R5.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R5.csv
============================================================
[INFO] (97/160) sim_S40_G5000_CNstrong_R6.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=6
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.90 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.48 seconds.

Fitting LFCs...
... done in 0.70 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 172 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.21 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SYCP2L        5792.234317       -1.811662  0.402018 -4.886208  0.000001
RNA5SP187      236.026366       -0.005159  0.515825 -0.019102  0.984760
PRR13       476449.525463        0.134925  0.166829  0.674279  0.500134
SLC44A3      49835.935787       -0.137940  0.283652 -0.549874  0.582406
CCDC92      311604.947593       -0.369141  0.190620 -2.101080  0.035634
...                   ...             ...       ...       ...       ...
MTSS1       444681.049200        0.040003  0.551491  0.286728  0.774321
GRHL2       350446.988336        0.048434  0.172837  0.215113  0.829679
SHC2        249506.887580       -0.087206  0.512127 -0.254075  0.799438
ZNF829       46254.503795        1.249591  0.827534  2.296449  0.021650
RNU6-1330P     389.058433        0.132554  0.240219  0.594840  0.551950

                padj
SYCP2L      0.000005
RNA5SP187   0.991917
PRR13       0.711077
SLC44A3     0.774833
CCDC92      0.096776
...              ...
MTSS1       0.894647
GRHL2       0.922297
SHC2        0.906865
ZNF829      0.062255
RNU6-1330P  0.747470

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.05 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.99 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 168 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 168)
Number of True values in replace_mask: 276
replacement_counts_trimmed shape: (80, 168)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.09 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SYCP2L        5792.234317       -2.202066  0.402468 -6.073711  1.249875e-09
RNA5SP187      236.026366       -0.005478  0.512611 -0.019101  9.847607e-01
PRR13       476449.525463        1.932302  0.119726  0.674285  5.001300e-01
SLC44A3      49835.935787        1.196798  0.292117 -0.549875  5.824051e-01
CCDC92      311604.947593        1.495242  0.148110 -2.101095  3.563262e-02
...                   ...             ...       ...       ...           ...
MTSS1       444681.049200        1.211730  0.252376 -1.702574  8.864790e-02
GRHL2       350446.988336        0.835527  0.138513 -6.096454  1.084469e-09
SHC2        249506.887580        1.651042  0.317236 -0.254075  7.994380e-01
ZNF829       46254.503795        2.094267  0.537573  0.992349  3.210275e-01
RNU6-1330P     389.058433        0.138509  0.240157  0.594720  5.520307e-01

                    padj
SYCP2L      6.704976e-09
RNA5SP187   9.999893e-01
PRR13       7.186488e-01
SLC44A3     7.829747e-01
CCDC92      9.139905e-02
...                  ...
MTSS1       2.039965e-01
GRHL2       5.849747e-09
SHC2        9.228126e-01
ZNF829      5.446231e-01
RNU6-1330P  7.555779e-01

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R6.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R6.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R6.csv
============================================================
[INFO] (98/160) sim_S40_G5000_CNstrong_R7.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=7
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.97 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.70 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 169 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.17 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat         pvalue  \
LINC01908  1.133114e+02       -0.918681  1.093252  -1.909165   5.624086e-02
PCSK6      1.871043e+05       -0.022679  0.338103  -0.100711   9.197797e-01
NRF1       2.608445e+05        1.770227  0.081757  21.901328  2.523165e-106
EFCAB11    3.731811e+04       -0.099182  0.261053  -0.419044   6.751841e-01
VANGL1     1.902983e+05       -0.136581  0.307806  -0.544241   5.862757e-01
...                 ...             ...       ...        ...            ...
RCN1       1.100183e+06        0.269543  0.766428   0.725490   4.681513e-01
UBE2D1     7.535497e+04        0.164984  0.651685   0.416849   6.767887e-01
ZNF512     1.917191e+05       -0.519747  0.332239  -1.818940   6.892053e-02
PRR22      1.582972e+04       -0.059706  0.156719  -0.439262   6.604719e-01
CACNA1G    3.824493e+04        1.512358  0.168554   9.105992   8.548143e-20

                    padj
LINC01908   1.399567e-01
PCSK6       9.604148e-01
NRF1       7.864389e-104
EFCAB11     8.209893e-01
VANGL1      7.621890e-01
...                  ...
RCN1        6.722622e-01
UBE2D1      8.218031e-01
ZNF512      1.660419e-01
PRR22       8.140814e-01
CACNA1G     9.890856e-19

[4987 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.43 seconds.

Fitting LFCs...
... done in 0.85 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 171 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 171)
Number of True values in replace_mask: 279
replacement_counts_trimmed shape: (78, 171)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.03 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC01908  1.133114e+02       -0.884235  1.087257  -1.909057  5.625471e-02
PCSK6      1.871043e+05        1.532961  0.298524  -0.100711  9.197796e-01
NRF1       2.608445e+05        3.489484  0.089889  17.133621  8.330399e-66
EFCAB11    3.731811e+04        1.053096  0.277968  -0.419043  6.751846e-01
VANGL1     1.902983e+05        1.418165  0.276018  -0.544241  5.862757e-01
...                 ...             ...       ...        ...           ...
RCN1       1.100183e+06        1.805090  0.198120  -0.004072  9.967513e-01
UBE2D1     7.535497e+04        1.733696  0.638013   0.416821  6.768093e-01
ZNF512     1.917191e+05        0.908470  0.310653  -2.882087  3.950505e-03
PRR22      1.582972e+04       -0.171961  0.153206  -0.439256  6.604758e-01
CACNA1G    3.824493e+04        1.341680  0.171808   1.744708  8.103570e-02

                   padj
LINC01908  1.357900e-01
PCSK6      9.592097e-01
NRF1       9.661326e-64
EFCAB11    8.220582e-01
VANGL1     7.669876e-01
...                 ...
RCN1       9.984155e-01
UBE2D1     8.228298e-01
ZNF512     1.199827e-02
PRR22      8.148918e-01
CACNA1G    1.848696e-01

[4987 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R7.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R7.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R7.csv
============================================================
[INFO] (99/160) sim_S40_G5000_CNstrong_R8.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=8
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.92 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.33 seconds.

Fitting LFCs...
... done in 0.65 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 178 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.05 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.36 seconds.

Fitting MAP LFCs...
... done in 1.29 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
ZNF542P     259970.821709        2.290580  0.178528  12.917739  3.574936e-38
RFX7        136267.916529        0.130921  0.138887   0.969026  3.325320e-01
GEMIN7-AS1   11639.995511       -2.007407  0.210785  -9.715103  2.599862e-22
MIR6774        173.351327       -0.538959  0.564364  -1.365886  1.719747e-01
RMDN1       205832.200094       -0.626864  0.198594  -3.393967  6.888806e-04
...                   ...             ...       ...        ...           ...
LCNL1         7145.320760        0.250520  0.256633   1.081983  2.792602e-01
ENDOD1      177036.145225        0.355592  0.742483   1.236923  2.161157e-01
ZNF335      220074.012756        0.511106  0.414225   1.452325  1.464112e-01
PGF          72977.564757        0.052620  0.385118   0.156656  8.755163e-01
PKNOX2       16190.538480       -0.198295  0.417083  -0.604593  5.454498e-01

                    padj
ZNF542P     1.341542e-36
RFX7        5.506527e-01
GEMIN7-AS1  3.908407e-21
MIR6774     3.427818e-01
RMDN1       2.505979e-03
...                  ...
LCNL1       4.895637e-01
ENDOD1      4.074928e-01
ZNF335      3.038412e-01
PGF         9.490179e-01
PKNOX2      7.423180e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.98 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.32 seconds.

Fitting LFCs...
... done in 0.86 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 175 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 175)
Number of True values in replace_mask: 316
replacement_counts_trimmed shape: (78, 175)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 0.96 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
ZNF542P     259970.821709        2.951715  0.129257  10.144048  3.521949e-24
RFX7        136267.916529        1.830408  0.135730   0.969025  3.325329e-01
GEMIN7-AS1   11639.995511       -2.232036  0.211666 -11.175425  5.379215e-29
MIR6774        173.351327       -0.530254  0.562885  -1.365774  1.720099e-01
RMDN1       205832.200094        5.693528  0.265977  13.900557  6.285053e-44
...                   ...             ...       ...        ...           ...
LCNL1         7145.320760        0.238429  0.256571   1.081972  2.792650e-01
ENDOD1       43205.296075        2.333753  0.118333  -1.743467  8.125207e-02
ZNF335      220074.012756        1.398159  0.226612  -1.223339  2.212018e-01
PGF          72977.564757        1.534838  0.359784   0.156656  8.755163e-01
PKNOX2       16190.538480        1.012658  0.453807  -0.604592  5.454504e-01

                    padj
ZNF542P     5.744460e-23
RFX7        5.551699e-01
GEMIN7-AS1  1.137613e-27
MIR6774     3.429889e-01
RMDN1       3.045505e-42
...                  ...
LCNL1       4.920530e-01
ENDOD1      1.855968e-01
ZNF335      4.170828e-01
PGF         9.570939e-01
PKNOX2      7.486494e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R8.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R8.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R8.csv
============================================================
[INFO] (100/160) sim_S40_G5000_CNstrong_R9.pkl
[INFO] Running analysis for S=40, G=5000, CN=strong, R=9
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.90 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.47 seconds.

Fitting LFCs...
... done in 1.22 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 179 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.36 seconds.

Fitting MAP LFCs...
... done in 1.40 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
VN1R81P      1.730171e+03       -1.268673  0.256140  -5.202927  1.961743e-07
MIR7844      2.143746e+03       -1.125818  0.324967  -3.784219  1.541921e-04
CFAP69       4.728117e+04       -2.327179  0.329660  -7.336412  2.193966e-13
BCAR3        2.297256e+05       -0.267908  0.249437  -1.245681  2.128814e-01
CEP57        2.313464e+05       -0.083181  0.130767  -0.693422  4.880449e-01
...                   ...             ...       ...        ...           ...
ARPC4-TTLL3  1.379549e+06        1.619588  0.160944  10.290387  7.786259e-25
SRGAP3-AS4   1.197431e+02       -1.394153  0.343891  -4.389776  1.134673e-05
GPR45        2.555941e+02       -0.312632  0.591585  -0.809295  4.183453e-01
SULT4A1      9.195182e+03       -0.254209  0.414968  -0.766254  4.435249e-01
GTSE1-DT     2.855125e+03       -0.006804  0.126829  -0.055265  9.559273e-01

                     padj
VN1R81P      9.640566e-07
MIR7844      5.709802e-04
CFAP69       1.691422e-12
BCAR3        4.052871e-01
CEP57        6.965288e-01
...                   ...
ARPC4-TTLL3  1.149049e-23
SRGAP3-AS4   4.696885e-05
GPR45        6.386885e-01
SULT4A1      6.617715e-01
GTSE1-DT     9.835325e-01

[4988 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.41 seconds.

Fitting dispersion trend curve...
... done in 0.23 seconds.

Fitting MAP dispersions...
... done in 2.13 seconds.

Fitting LFCs...
... done in 1.23 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 176 outlier genes.

Fitting dispersions...
... done in 0.04 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 176)
Number of True values in replace_mask: 285
replacement_counts_trimmed shape: (80, 176)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.29 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
VN1R81P      1.730171e+03       -1.408369  0.255994 -5.860557  4.613171e-09
MIR7844      2.143746e+03       -1.493988  0.325032 -4.880146  1.060075e-06
CFAP69       4.728117e+04       -0.286910  0.384224 -8.711571  2.996931e-18
BCAR3        2.297256e+05        1.374706  0.229305 -1.245681  2.128815e-01
CEP57        2.313464e+05        1.864551  0.124759 -0.693421  4.880455e-01
...                   ...             ...       ...       ...           ...
ARPC4-TTLL3  1.379549e+06        2.743330  0.067645  7.841498  4.452031e-15
SRGAP3-AS4   1.197431e+02       -1.733228  0.344473 -5.354630  8.573151e-08
GPR45        2.555941e+02       -0.310268  0.589035 -0.809261  4.183650e-01
SULT4A1      9.195182e+03        0.073613  0.420934 -0.766252  4.435261e-01
GTSE1-DT     2.855125e+03       -0.006940  0.126925 -0.055259  9.559319e-01

                     padj
VN1R81P      2.242738e-08
MIR7844      4.281500e-06
CFAP69       2.462717e-17
BCAR3        4.077777e-01
CEP57        7.060240e-01
...                   ...
ARPC4-TTLL3  3.087631e-14
SRGAP3-AS4   3.767654e-07
GPR45        6.480760e-01
SULT4A1      6.701934e-01
GTSE1-DT     9.966949e-01

[4988 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNstrong_R9.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNstrong_R9.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNstrong_R9.csv
============================================================
[INFO] (101/160) sim_S40_G5000_CNweak_R1.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=1
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.45 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.60 seconds.

Fitting LFCs...
... done in 0.72 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 188 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.35 seconds.

Fitting MAP LFCs...
... done in 1.19 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
JMJD6       2.176283e+05        0.851868  0.156143   5.474787  4.380370e-08
PLA2G12AP1  4.188987e+03        0.423690  0.152646   2.854230  4.314125e-03
VEGFA       5.111691e+06        2.899501  0.442889   5.764844  8.173331e-09
RHO         7.338693e+02        1.332970  0.712281   2.562910  1.037991e-02
TK1         1.740562e+05       -1.005712  0.500580  -2.529010  1.143849e-02
...                  ...             ...       ...        ...           ...
SCN9A       1.397230e+04        0.393496  0.296220   1.478030  1.393997e-01
BCL2L2      7.159294e+05        1.093315  0.531996   2.624324  8.682122e-03
NADSYN1     5.433445e+05        0.812933  0.132880   6.116485  9.566168e-10
CUL7        1.071254e+06        2.391723  0.122476  19.456511  2.566746e-84
POGK        3.612717e+05       -1.110773  0.370820  -3.432506  5.980316e-04

                    padj
JMJD6       2.763897e-07
PLA2G12AP1  1.425003e-02
VEGFA       5.475583e-08
RHO         3.186109e-02
TK1         3.476828e-02
...                  ...
SCN9A       2.903773e-01
BCL2L2      2.715067e-02
NADSYN1     6.899530e-09
CUL7        4.270210e-82
POGK        2.274981e-03

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.08 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.64 seconds.

Fitting LFCs...
... done in 1.34 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 185 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 185)
Number of True values in replace_mask: 314
replacement_counts_trimmed shape: (78, 185)

... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.93 seconds.

Fitting MAP LFCs...
... done in 1.61 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
JMJD6       2.176283e+05        1.608413  0.139820   0.813733  4.157980e-01
PLA2G12AP1  4.188987e+03        0.371756  0.151444   2.854087  4.316070e-03
VEGFA       5.111691e+06        3.275428  0.054774   5.013877  5.334419e-07
RHO         7.338693e+02        0.743359  0.672916   1.676801  9.358147e-02
TK1         1.740562e+05        1.493094  0.416386  -0.789784  4.296540e-01
...                  ...             ...       ...        ...           ...
SCN9A       1.397230e+04        0.484553  0.301806   1.478024  1.394012e-01
BCL2L2      7.159294e+05        2.456896  0.178636   1.965600  4.934478e-02
NADSYN1     5.433445e+05        1.852641  0.103753   0.902011  3.670509e-01
CUL7        1.071254e+06        3.370961  0.075648  15.872211  9.870107e-57
POGK        3.612717e+05        0.839938  0.243726  -5.288819  1.231084e-07

                    padj
JMJD6       6.266076e-01
PLA2G12AP1  1.319137e-02
VEGFA       2.515628e-06
RHO         2.104845e-01
TK1         6.408966e-01
...                  ...
SCN9A       2.902593e-01
BCL2L2      1.214397e-01
NADSYN1     5.777658e-01
CUL7        6.938268e-55
POGK        6.138202e-07

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R1.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R1.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R1.csv
============================================================
[INFO] (102/160) sim_S40_G5000_CNweak_R10.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=10
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.07 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 0.73 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 173 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.99 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
CCL18     27813.415608        0.059241  0.461563  0.165254  8.687442e-01
TMPRSS3   64199.277514       -0.216506  0.528307 -3.406804  6.572843e-04
NPC2     902648.823299       -0.064724  0.188251 -0.391427  6.954815e-01
GZMH       6199.327837        0.630172  0.368729  1.990982  4.648286e-02
OTOGL      3680.739921       -2.042961  0.392892 -5.562882  2.653551e-08
...                ...             ...       ...       ...           ...
CCDC196    1521.013358       -0.258812  0.596085 -0.702065  4.826385e-01
PBOV1       214.195500       -0.542136  0.206935 -2.765766  5.678925e-03
CDHR2      2986.295729        3.172190  0.946432  3.994368  6.486712e-05
FAM215A     264.670459        0.193601  0.212286  0.969401  3.323453e-01
POLD3    146316.356822       -1.619686  1.111648 -2.558255  1.051990e-02

                 padj
CCL18    9.441310e-01
TMPRSS3  2.590260e-03
NPC2     8.382430e-01
GZMH     1.232881e-01
OTOGL    1.728787e-07
...               ...
CCDC196  6.824793e-01
PBOV1    1.917172e-02
CDHR2    2.968324e-04
FAM215A  5.432546e-01
POLD3    3.339767e-02

[4997 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.46 seconds.

Fitting dispersion trend curve...
... done in 0.36 seconds.

Fitting MAP dispersions...
... done in 1.62 seconds.

Fitting LFCs...
... done in 1.00 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

Replacing 168 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 168)
Number of True values in replace_mask: 270
replacement_counts_trimmed shape: (78, 168)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.23 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
CCL18     27813.415608        1.223470  0.522301  0.165254  8.687442e-01
TMPRSS3   36078.712283        0.546323  0.200068 -3.541963  3.971608e-04
NPC2     902648.823299        1.808686  0.127325 -0.391427  6.954816e-01
GZMH       6199.327837        0.582907  0.364781  1.990970  4.648415e-02
OTOGL      3680.739921       -2.376993  0.393118 -6.527490  6.688100e-11
...                ...             ...       ...       ...           ...
CCDC196    1521.013358       -0.299393  0.605116 -0.702063  4.826401e-01
PBOV1       214.195500       -0.897448  0.208630 -4.496238  6.916642e-06
CDHR2      2986.295729        3.570843  0.881611  3.613803  3.017381e-04
FAM215A     264.670459        0.190489  0.212369  0.969020  3.325350e-01
POLD3    146316.356822        0.426196  0.673530 -2.904037  3.683842e-03

                 padj
CCL18    9.451589e-01
TMPRSS3  1.372484e-03
NPC2     8.418657e-01
GZMH     1.173756e-01
OTOGL    4.584422e-10
...               ...
CCDC196  6.887239e-01
PBOV1    2.961650e-05
CDHR2    1.064820e-03
FAM215A  5.487707e-01
POLD3    1.130722e-02

[4997 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R10.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R10.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R10.csv
============================================================
[INFO] (103/160) sim_S40_G5000_CNweak_R11.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=11
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.99 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.65 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 186 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.82 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE       stat        pvalue  \
OSGEPL1-AS1    2261.751750        0.246752  0.160090   1.591276  1.115475e-01
CPLANE1      190676.261620        0.189143  0.190898   0.982436  3.258852e-01
NPEPL1       285766.643650        0.213830  0.351136   0.646478  5.179698e-01
ZNF467       393388.714607        2.788238  0.278949  10.196849  2.048099e-24
ABHD17A      324086.549628        0.396115  0.209261   1.988827  4.672028e-02
...                    ...             ...       ...        ...           ...
TGDS          65306.701568        0.122431  0.202987   0.609413  5.422505e-01
NPAP1           255.758928        0.375767  0.430178   1.090148  2.756478e-01
NOD1         256025.880752        0.709873  0.374999   2.134773  3.277956e-02
NT5C1B         6041.048626        1.877902  0.191299   9.976206  1.937341e-23
NHP2P2          629.071078        0.601047  0.155163   3.987226  6.685046e-05

                     padj
OSGEPL1-AS1  2.406975e-01
CPLANE1      5.265435e-01
NPEPL1       7.041221e-01
ZNF467       3.214485e-23
ABHD17A      1.189677e-01
...                   ...
TGDS         7.234355e-01
NPAP1        4.695670e-01
NOD1         8.852964e-02
NT5C1B       2.894990e-22
NHP2P2       2.873821e-04

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.06 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.38 seconds.

Fitting LFCs...
... done in 0.87 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 185 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 185)
Number of True values in replace_mask: 312
replacement_counts_trimmed shape: (78, 185)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.05 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat        pvalue  \
OSGEPL1-AS1    2261.751750        0.223126  0.159969  1.591144  1.115771e-01
CPLANE1      190676.261620        1.236316  0.167588 -2.180059  2.925308e-02
NPEPL1       285766.643650        1.351868  0.229775 -1.504492  1.324548e-01
ZNF467       393388.714607        3.595153  0.177413  9.361583  7.855075e-21
ABHD17A      324086.549628        1.906696  0.175815  1.988826  4.672036e-02
...                    ...             ...       ...       ...           ...
TGDS          65306.701568        1.390774  0.209701  0.609412  5.422512e-01
NPAP1           255.758928        0.370908  0.429049  1.090045  2.756932e-01
NOD1         256025.880752        1.753465  0.232817  0.378780  7.048510e-01
NT5C1B         6041.048626        1.575495  0.189604  8.580744  9.426118e-18
NHP2P2          629.071078       -0.020764  0.154165 -0.152725  8.786153e-01

                     padj
OSGEPL1-AS1  2.425442e-01
CPLANE1      7.716815e-02
NPEPL1       2.807142e-01
ZNF467       9.825734e-20
ABHD17A      1.158953e-01
...                   ...
TGDS         7.388414e-01
NPAP1        4.835867e-01
NOD1         8.438262e-01
NT5C1B       9.967321e-17
NHP2P2       9.410415e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R11.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R11.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R11.csv
============================================================
[INFO] (104/160) sim_S40_G5000_CNweak_R12.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=12
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.91 seconds.

Fitting dispersion trend curve...
... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 1.34 seconds.

Fitting LFCs...
... done in 0.66 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 190 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.19 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
PCGF1     71035.586927       -0.173476  0.146393 -1.236309  0.216344  0.401540
NPAS3     11968.012153       -1.138396  0.280298 -4.368257  0.000013  0.000062
USP8     339903.263063        0.122035  0.101324  1.331366  0.183069  0.357048
YRDC      84372.231382       -0.473312  0.221552 -2.310619  0.020854  0.059384
OSR2     134569.721188        0.858010  0.280863  3.262660  0.001104  0.004122
...                ...             ...       ...       ...       ...       ...
SLC10A7   61825.785108        0.315724  0.181067  1.824435  0.068086  0.162062
MYOM1     71652.194319       -0.100702  0.551846 -0.290530  0.771411  0.883307
ZNF644   252181.510057       -0.015017  0.186107 -0.000466  0.999628  0.999829
FABP9       397.767300       -0.347796  0.359937 -1.147292  0.251261  0.445150
DCAF1    447623.494661        0.056330  0.593648 -1.043999  0.296486  0.495866

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.99 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.34 seconds.

Fitting LFCs...
... done in 0.87 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 189 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 189)
Number of True values in replace_mask: 318
replacement_counts_trimmed shape: (79, 189)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.43 seconds.

Fitting MAP LFCs...
... done in 1.21 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
PCGF1     71035.586927        1.040090  0.155034 -3.278393  1.044000e-03
NPAS3     11968.012153       -1.303445  0.289041 -5.900928  3.614621e-09
USP8     339903.263063        2.487815  0.106292  1.331364  1.830693e-01
YRDC      84372.231382        1.095861  0.224734 -2.310616  2.085407e-02
OSR2     134569.721188        2.911375  0.243480  6.361556  1.997201e-10
...                ...             ...       ...       ...           ...
SLC10A7   61825.785108        1.468647  0.190785  1.824431  6.808692e-02
MYOM1     71652.194319        1.404613  0.556875 -0.290519  7.714189e-01
ZNF644   252181.510057        1.740093  0.153334 -0.000466  9.996283e-01
FABP9       397.767300       -1.142050  0.379076 -3.405565  6.602732e-04
DCAF1    129413.220648        2.731482  0.080988 -0.517358  6.049065e-01

                 padj
PCGF1    3.528806e-03
NPAS3    2.042281e-08
USP8     3.665060e-01
YRDC     5.704001e-02
OSR2     1.254916e-09
...               ...
SLC10A7  1.636251e-01
MYOM1    8.877990e-01
ZNF644   9.998287e-01
FABP9    2.297143e-03
DCAF1    7.927054e-01

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R12.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R12.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R12.csv
============================================================
[INFO] (105/160) sim_S40_G5000_CNweak_R13.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=13
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.25 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.44 seconds.

Fitting LFCs...
... done in 1.08 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 170 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.16 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
EPDR1       67826.406504       -0.468862  0.334701  -1.622189  1.047629e-01
INTS12     126565.127661        0.232138  0.100253   2.317144  2.049588e-02
LINC00943     470.600999       -0.304341  0.480057  -0.859344  3.901508e-01
PCDH9       32707.563840        0.125589  0.423662   0.369391  7.118360e-01
LRGUK       15676.469319        1.697359  0.388687   4.735871  2.181162e-06
...                  ...             ...       ...        ...           ...
MIR155HG     5261.071729       -0.366849  0.139485  -2.703168  6.868206e-03
TNFAIP3    198715.209481       -1.128454  0.185873  -6.303109  2.917334e-10
CRYBG3     191515.694516       -2.245879  0.143125 -15.778236  4.392975e-56
ATXN3      185445.760719        0.338746  0.346747   1.169249  2.423033e-01
NCR1          486.517323       -1.232015  0.101671 -12.219182  2.455442e-34

                   padj
EPDR1      2.329467e-01
INTS12     5.920636e-02
LINC00943  6.011507e-01
PCDH9      8.500069e-01
LRGUK      1.158713e-05
...                 ...
MIR155HG   2.236881e-02
TNFAIP3    2.278539e-09
CRYBG3     3.316696e-54
ATXN3      4.338275e-01
NCR1       6.951969e-33

[4983 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.02 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.33 seconds.

Fitting LFCs...
... done in 0.86 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 160 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 160)
Number of True values in replace_mask: 270
replacement_counts_trimmed shape: (80, 160)

... done in 0.08 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.00 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
EPDR1       67826.406504        0.813946  0.336481  -2.824531  4.734986e-03
INTS12     126565.127661        2.030079  0.118348   2.317135  2.049637e-02
LINC00943     470.600999       -0.320105  0.479827  -0.859311  3.901688e-01
PCDH9       32707.563840        1.360687  0.461348   0.369391  7.118362e-01
LRGUK       15676.469319        2.443303  0.377532   4.174803  2.982437e-05
...                  ...             ...       ...        ...           ...
MIR155HG     5261.071729       -0.655868  0.140041  -5.050629  4.403571e-07
TNFAIP3    198715.209481        0.836466  0.184357  -7.394201  1.422616e-13
CRYBG3     191515.694516        0.372940  0.168890 -17.869179  2.049887e-71
ATXN3      185445.760719        1.845896  0.293767   1.169249  2.423034e-01
NCR1          486.517323       -1.711907  0.101701 -16.855134  9.619039e-64

                   padj
EPDR1      1.422208e-02
INTS12     5.562821e-02
LINC00943  6.144797e-01
PCDH9      8.695955e-01
LRGUK      1.143259e-04
...                 ...
MIR155HG   2.031759e-06
TNFAIP3    1.102472e-12
CRYBG3     1.110281e-69
ATXN3      4.433833e-01
NCR1       4.564921e-62

[4983 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R13.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R13.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R13.csv
============================================================
[INFO] (106/160) sim_S40_G5000_CNweak_R14.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=14
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.36 seconds.

Fitting LFCs...
... done in 1.11 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 193 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.18 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
MIA3       5.408775e+05       -0.221980  0.213912 -1.202236  2.292721e-01
CTNNB1     2.275729e+06       -0.002928  0.172750 -0.011931  9.904804e-01
DDX10      1.820506e+05        0.122675  0.170761  0.657483  5.108706e-01
RNU6-322P  3.482392e+02       -0.948119  0.403705 -2.734839  6.241072e-03
RN7SL130P  6.647720e+02       -0.072849  0.385094 -0.235673  8.136864e-01
...                 ...             ...       ...       ...           ...
GPR137     2.215040e+05       -0.248945  0.225487 -1.233735  2.173016e-01
DDX52      1.210764e+05       -1.483907  0.233135 -6.660566  2.727757e-11
TOR1AIP1   4.263145e+05       -0.346258  0.179724 -2.162952  3.054485e-02
ACTBP11    1.267507e+04       -0.500535  0.142758 -3.602957  3.146180e-04
RPS3AP49   8.619002e+03        0.204412  0.448732  0.589707  5.553870e-01

                   padj
MIA3       4.167984e-01
CTNNB1     9.969674e-01
DDX10      7.046909e-01
RNU6-322P  2.017529e-02
RN7SL130P  9.096073e-01
...                 ...
GPR137     4.020012e-01
DDX52      2.163125e-10
TOR1AIP1   8.246153e-02
ACTBP11    1.301256e-03
RPS3AP49   7.405047e-01

[4988 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.04 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.47 seconds.

Fitting LFCs...
... done in 1.69 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 190 outlier genes.

Fitting dispersions...
... done in 0.04 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 190)
Number of True values in replace_mask: 306
replacement_counts_trimmed shape: (80, 190)

... done in 0.09 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.39 seconds.

Fitting MAP LFCs...
... done in 1.55 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
MIA3       5.408775e+05        1.045254  0.132470 -4.923263  8.511275e-07
CTNNB1     2.275729e+06        2.002728  0.062861 -0.011931  9.904804e-01
DDX10      1.820506e+05        1.712018  0.159306  0.657482  5.108709e-01
RNU6-322P  3.482392e+02       -1.255546  0.408027 -3.500217  4.648797e-04
RN7SL130P  6.647720e+02       -0.077545  0.385442 -0.235662  8.136948e-01
...                 ...             ...       ...       ...           ...
GPR137     2.215040e+05        1.165920  0.182334 -3.166554  1.542567e-03
DDX52      1.210764e+05        0.561405  0.239721 -7.456598  8.878499e-14
TOR1AIP1   4.263145e+05        0.925289  0.135553 -6.272968  3.542288e-10
ACTBP11    1.267507e+04       -1.284140  0.141405 -8.718551  2.817836e-18
RPS3AP49   8.619002e+03        0.065799  0.441684  0.589706  5.553881e-01

                   padj
MIA3       3.628567e-06
CTNNB1     9.999970e-01
DDX10      7.194095e-01
RNU6-322P  1.516560e-03
RN7SL130P  9.289792e-01
...                 ...
GPR137     4.761338e-03
DDX52      6.580380e-13
TOR1AIP1   1.987507e-09
ACTBP11    2.708163e-17
RPS3AP49   7.546856e-01

[4988 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R14.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R14.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R14.csv
============================================================
[INFO] (107/160) sim_S40_G5000_CNweak_R15.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=15
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 3.07 seconds.

Fitting dispersion trend curve...
... done in 0.31 seconds.

Fitting MAP dispersions...
... done in 1.63 seconds.

Fitting LFCs...
... done in 0.78 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 196 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.12 seconds.

Running Wald tests...
... done in 0.36 seconds.

Fitting MAP LFCs...
... done in 1.39 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
BBIP1       378028.715558        0.207959  0.245499   0.853756  3.932403e-01
DMWD        377161.703380        1.349370  0.133435  10.083918  6.507831e-24
TMEM163      18300.665257       -0.000827  0.321490  -0.014775  9.882116e-01
RPTOR       281879.618672        0.656750  0.163416   4.120944  3.773233e-05
CRYGS        37334.549826        0.423420  0.185127   2.361880  1.818253e-02
...                   ...             ...       ...        ...           ...
VWA8        164979.189363        0.079854  0.275321   0.270116  7.870712e-01
FGB          31555.181339        0.040787  0.486570   0.107020  9.147733e-01
THAP6        66150.695395       -0.407544  0.423427  -1.220645  2.222206e-01
HNRNPA3P13     654.761783       -0.182256  0.659850  -0.502159  6.155557e-01
GUSBP5        4672.594565        0.202830  0.207577   1.031648  3.022373e-01

                    padj
BBIP1       5.988633e-01
DMWD        1.075085e-22
TMEM163     9.921891e-01
RPTOR       1.686797e-04
CRYGS       5.174709e-02
...                  ...
VWA8        8.916208e-01
FGB         9.585780e-01
THAP6       4.061606e-01
HNRNPA3P13  7.848218e-01
GUSBP5      5.006181e-01

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.09 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 1.34 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

Replacing 193 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 193)
Number of True values in replace_mask: 312
replacement_counts_trimmed shape: (78, 193)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.11 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.35 seconds.

Fitting MAP LFCs...
... done in 1.36 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
BBIP1       378028.715558        1.826692  0.188175  0.853756  3.932404e-01
DMWD        377161.703380        2.464147  0.113671  7.213229  5.464036e-13
TMEM163      18300.665257        0.867490  0.352618 -0.014800  9.881915e-01
RPTOR       281879.618672        1.670597  0.135016  0.472030  6.369055e-01
CRYGS        37334.549826        1.101205  0.192089 -0.860311  3.896179e-01
...                   ...             ...       ...       ...           ...
VWA8        164979.189363        1.554718  0.260685  0.270116  7.870712e-01
FGB          31555.181339        1.267945  0.548890  0.107020  9.147734e-01
THAP6        66150.695395        0.837016  0.425068 -2.225959  2.601694e-02
HNRNPA3P13     654.761783       -0.203136  0.660652 -0.502159  6.155556e-01
GUSBP5        4672.594565        0.153541  0.206272  1.031623  3.022486e-01

                    padj
BBIP1       6.040260e-01
DMWD        4.111626e-12
TMEM163     9.919692e-01
RPTOR       8.039938e-01
CRYGS       6.008667e-01
...                  ...
VWA8        8.924315e-01
FGB         9.577740e-01
THAP6       6.835097e-02
HNRNPA3P13  7.896270e-01
GUSBP5      5.049960e-01

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R15.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R15.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R15.csv
============================================================
[INFO] (108/160) sim_S40_G5000_CNweak_R16.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=16
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.17 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.59 seconds.

Fitting LFCs...
... done in 0.83 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 196 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.11 seconds.

Fitting LFCs...
... done in 0.19 seconds.

Running Wald tests...
... done in 0.47 seconds.

Fitting MAP LFCs...
... done in 2.13 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
TMEM167A   465883.630235       -0.132483  0.146801 -0.954052  3.400572e-01
LINC02021    2864.803941       -0.829285  0.315247 -2.914613  3.561304e-03
FAAP100    178146.790957       -0.847029  0.181226 -4.862660  1.158187e-06
MYOM2       20017.982593       -0.287729  0.371651 -0.934107  3.502485e-01
FOXN3-AS1   12358.768765        0.123449  0.249094  0.521908  6.017343e-01
...                  ...             ...       ...       ...           ...
IPO8P1      16135.413831        0.298005  0.198392  1.558023  1.192277e-01
ATP6V1B1   213679.115102        0.707312  0.539301  1.699638  8.919903e-02
KCNH3        6012.448084       -1.136781  0.158441 -7.332669  2.256143e-13
KRTAP1-5      190.611522       -0.520049  0.170085 -3.169843  1.525214e-03
AGA        105305.118442       -0.414087  0.143949 -3.020282  2.525397e-03

                   padj
TMEM167A   5.397854e-01
LINC02021  1.175089e-02
FAAP100    6.193134e-06
MYOM2      5.496665e-01
FOXN3-AS1  7.644893e-01
...                 ...
IPO8P1     2.533335e-01
ATP6V1B1   2.003665e-01
KCNH3      2.143981e-12
KRTAP1-5   5.454691e-03
AGA        8.606014e-03

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.26 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.71 seconds.

Fitting LFCs...
... done in 1.00 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

Replacing 197 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 197)
Number of True values in replace_mask: 339
replacement_counts_trimmed shape: (79, 197)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.12 seconds.

Fitting LFCs...
... done in 0.12 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.19 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
TMEM167A   465883.630235        1.836733  0.124918  -0.954052  3.400575e-01
LINC02021    2864.803941       -1.126497  0.317213  -3.940098  8.144827e-05
FAAP100    178146.790957        1.966585  0.185725  -0.047791  9.618825e-01
MYOM2       20017.982593        0.657863  0.401336  -0.934106  3.502493e-01
FOXN3-AS1   12358.768765        0.029850  0.244687   0.521905  6.017365e-01
...                  ...             ...       ...        ...           ...
IPO8P1      16135.413831        1.470790  0.209322   5.900540  3.623143e-09
ATP6V1B1   213679.115102        2.038317  0.323802   0.986815  3.237335e-01
KCNH3        6012.448084       -1.568507  0.158174 -10.079488  6.807984e-24
KRTAP1-5      190.611522       -0.764739  0.170789  -4.619372  3.849037e-06
AGA        105305.118442        1.320533  0.151518  -3.020275  2.525454e-03

                   padj
TMEM167A   5.428950e-01
LINC02021  2.959544e-04
FAAP100    9.831657e-01
MYOM2      5.533229e-01
FOXN3-AS1  7.676175e-01
...                 ...
IPO8P1     1.956262e-08
ATP6V1B1   5.274678e-01
KCNH3      1.016917e-22
KRTAP1-5   1.584393e-05
AGA        7.744000e-03

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R16.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R16.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R16.csv
============================================================
[INFO] (109/160) sim_S40_G5000_CNweak_R17.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=17
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.21 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 2.29 seconds.

Fitting LFCs...
... done in 1.02 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 184 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.28 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat        pvalue  \
DNAJB14  2.333997e+05       -0.132355  0.127866 -1.058808  2.896870e-01
GAL3ST3  1.065361e+02       -1.523310  1.045490 -1.625672  1.040194e-01
KCTD3    5.886670e+05       -0.319401  0.233402 -1.519290  1.286896e-01
SFRP2    2.234854e+06       -0.326891  0.395417 -0.879632  3.790585e-01
WDR1     1.767000e+06       -0.142438  0.146449 -1.159701  2.461706e-01
...               ...             ...       ...       ...           ...
TDG      1.598291e+05        0.210489  0.337102  0.663730  5.068634e-01
DBN1     5.070072e+05       -0.452412  0.132245 -3.649201  2.630576e-04
SIGLEC1  1.117074e+05       -0.592938  0.819494 -1.450824  1.468288e-01
ENGASE   4.678089e+05        0.904332  0.116354  7.617265  2.591070e-14
OR7E2P   4.083504e+02        0.171145  0.206777  0.873853  3.821982e-01

                 padj
DNAJB14  4.976422e-01
GAL3ST3  2.336186e-01
KCTD3    2.765307e-01
SFRP2    5.957316e-01
WDR1     4.438895e-01
...               ...
TDG      7.118900e-01
DBN1     1.049079e-03
SIGLEC1  3.048300e-01
ENGASE   2.343698e-13
OR7E2P   5.985934e-01

[4993 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.37 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.73 seconds.

Fitting LFCs...
... done in 1.07 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

Replacing 177 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 177)
Number of True values in replace_mask: 294
replacement_counts_trimmed shape: (78, 177)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.36 seconds.

Fitting MAP LFCs...
... done in 1.30 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat        pvalue  \
DNAJB14  2.333997e+05        1.854469  0.127194 -1.058807  2.896877e-01
GAL3ST3  1.645547e+01       -2.666687  0.056415 -0.524747  5.997594e-01
KCTD3    5.886670e+05        1.118786  0.171980 -3.921613  8.795801e-05
SFRP2    2.234854e+06        1.639777  0.127564 -0.879632  3.790585e-01
WDR1     1.767000e+06        2.014966  0.076315 -1.159701  2.461707e-01
...               ...             ...       ...       ...           ...
TDG      1.598291e+05        1.676081  0.304732  0.662720  5.075098e-01
DBN1     5.070072e+05        1.265129  0.123411 -6.163994  7.093265e-10
SIGLEC1  1.117074e+05        1.169059  0.819472 -0.528830  5.969235e-01
ENGASE   4.678089e+05        1.821197  0.104948  0.966142  3.339731e-01
OR7E2P   4.083504e+02        0.179712  0.206754  0.873619  3.823260e-01

                 padj
DNAJB14  5.038025e-01
GAL3ST3  7.896555e-01
KCTD3    3.277420e-04
SFRP2    6.027514e-01
WDR1     4.494078e-01
...               ...
TDG      7.223795e-01
DBN1     4.221296e-09
SIGLEC1  7.878507e-01
ENGASE   5.534443e-01
OR7E2P   6.064021e-01

[4993 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R17.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R17.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R17.csv
============================================================
[INFO] (110/160) sim_S40_G5000_CNweak_R18.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=18
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.21 seconds.

Fitting dispersion trend curve...
... done in 0.32 seconds.

Fitting MAP dispersions...
... done in 1.53 seconds.

Fitting LFCs...
... done in 0.88 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 186 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 0.17 seconds.

Fitting LFCs...
... done in 0.13 seconds.

Running Wald tests...
... done in 0.40 seconds.

Fitting MAP LFCs...
... done in 1.65 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC02766     692.758466        0.544791  0.645472   1.315542  1.883277e-01
SLC25A48    10396.733668        0.076417  0.499870   0.205195  8.374194e-01
TYSND1     170862.488842        0.124995  0.180024   0.690495  4.898829e-01
RAD51D     104596.019027        0.265169  0.185728   1.461474  1.438853e-01
SIGLEC5     11605.176255       -0.687837  0.273380  -2.754708  5.874449e-03
...                  ...             ...       ...        ...           ...
ARLNC1       1375.967288       -0.498443  0.583927  -1.255208  2.094031e-01
CXCL9      148521.215360       -1.340274  0.586283  -2.913604  3.572828e-03
AP2A1      973271.332955        1.066372  0.348403   3.476310  5.083638e-04
RFC2       606492.892458        2.680536  0.142315  18.883364  1.563077e-79
QRICH1     487626.297838        0.079175  0.274461   0.324476  7.455780e-01

                   padj
LINC02766  3.587570e-01
SLC25A48   9.121694e-01
TYSND1     6.899000e-01
RAD51D     2.929953e-01
SIGLEC5    1.902620e-02
...                 ...
ARLNC1     3.859419e-01
CXCL9      1.213060e-02
AP2A1      1.974509e-03
RFC2       2.294505e-77
QRICH1     8.669518e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.24 seconds.

Fitting dispersion trend curve...
... done in 0.14 seconds.

Fitting MAP dispersions...
... done in 1.64 seconds.

Fitting LFCs...
... done in 1.13 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 183 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 183)
Number of True values in replace_mask: 303
replacement_counts_trimmed shape: (79, 183)

... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.34 seconds.

Fitting LFCs...
... done in 0.13 seconds.

Running Wald tests...
... done in 0.50 seconds.

Fitting MAP LFCs...
... done in 1.50 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC02766     692.758466        0.567964  0.649135   1.315522  1.883347e-01
SLC25A48    10396.733668       -0.032804  0.501256   0.205195  8.374197e-01
TYSND1     170862.488842        1.709689  0.164822   0.690494  4.898833e-01
RAD51D     104596.019027        1.662811  0.184004   1.461472  1.438858e-01
SIGLEC5     11605.176255       -0.870789  0.283414  -4.384925  1.160256e-05
...                  ...             ...       ...        ...           ...
ARLNC1       1375.967288       -0.470050  0.578855  -1.255197  2.094074e-01
CXCL9      148521.215360        0.856236  0.457549  -2.992393  2.767995e-03
AP2A1      973271.332955        2.298458  0.155587   2.404389  1.619954e-02
RFC2       606492.892458        3.404654  0.091511  15.403900  1.540894e-53
QRICH1     487626.297838        1.801991  0.185123   0.324476  7.455774e-01

                   padj
LINC02766  3.609748e-01
SLC25A48   9.161687e-01
TYSND1     6.965834e-01
RAD51D     2.933555e-01
SIGLEC5    4.651275e-05
...                 ...
ARLNC1     3.894010e-01
CXCL9      8.517301e-03
AP2A1      4.422970e-02
RFC2       9.378786e-52
QRICH1     8.726963e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R18.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R18.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R18.csv
============================================================
[INFO] (111/160) sim_S40_G5000_CNweak_R19.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=19
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.02 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.45 seconds.

Fitting LFCs...
... done in 0.73 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 170 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 0.16 seconds.

Fitting LFCs...
... done in 0.20 seconds.

Running Wald tests...
... done in 0.35 seconds.

Fitting MAP LFCs...
... done in 1.39 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE       stat        pvalue  \
NOTCH1   514483.154408       -0.303315  0.297243  -1.120498  2.625015e-01
TMEM30A  653218.818530       -0.981404  0.154432  -6.694393  2.165694e-11
ZIC4       5198.611090        0.418069  0.653708   1.044127  2.964267e-01
ZBTB24   356335.081119        2.549259  0.158158  16.166603  8.675217e-59
SVIP     558186.548896        2.680332  0.285089   9.606377  7.514632e-22
...                ...             ...       ...        ...           ...
ZHX2     205811.713776       -0.840586  0.424249  -2.381836  1.722655e-02
HOXD3     36545.585946       -0.590317  0.354075  -1.956322  5.042720e-02
RARS2    169942.350511        0.140780  0.265545   0.521182  6.022399e-01
PRAL     333111.584456        0.080525  0.103418   0.787364  4.310689e-01
GRIK1     14610.323360        1.730213  0.311077   5.843176  5.121490e-09

                 padj
NOTCH1   4.576362e-01
TMEM30A  1.626062e-10
ZIC4     4.958320e-01
ZBTB24   5.853427e-57
SVIP     1.011336e-20
...               ...
ZHX2     4.946072e-02
HOXD3    1.266514e-01
RARS2    7.705079e-01
PRAL     6.373488e-01
GRIK1    3.286838e-08

[4993 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.12 seconds.

Fitting dispersion trend curve...
... done in 0.18 seconds.

Fitting MAP dispersions...
... done in 1.58 seconds.

Fitting LFCs...
... done in 1.66 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 166 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 166)
Number of True values in replace_mask: 291
replacement_counts_trimmed shape: (79, 166)

... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.42 seconds.

Fitting MAP LFCs...
... done in 1.33 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE       stat        pvalue  \
NOTCH1   514483.154408        1.555189  0.197421  -1.120498  2.625016e-01
TMEM30A  653218.818530        1.119500  0.122976  -8.355098  6.537855e-17
ZIC4       5198.611090        0.412825  0.651083   0.255316  7.984794e-01
ZBTB24   356335.081119        3.374576  0.111793  14.115412  3.052248e-45
SVIP     558186.548896        3.455653  0.159902   8.458671  2.704426e-17
...                ...             ...       ...        ...           ...
ZHX2     205811.713776        0.842577  0.322725  -3.870233  1.087316e-04
HOXD3     36545.585946        0.756026  0.371253  -1.956320  5.042744e-02
RARS2    169942.350511        1.586150  0.248471   0.521182  6.022400e-01
PRAL     333111.584456        2.434139  0.105799   0.787363  4.310695e-01
GRIK1     14610.323360        2.244168  0.311958   4.662906  3.117758e-06

                 padj
NOTCH1   4.613412e-01
TMEM30A  6.101591e-16
ZIC4     9.017887e-01
ZBTB24   1.239014e-43
SVIP     2.596769e-16
...               ...
ZHX2     4.060560e-04
HOXD3    1.252658e-01
RARS2    7.798196e-01
PRAL     6.434470e-01
GRIK1    1.364327e-05

[4993 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R19.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R19.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R19.csv
============================================================
[INFO] (112/160) sim_S40_G5000_CNweak_R2.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=2
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.11 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.47 seconds.

Fitting LFCs...
... done in 0.77 seconds.

Calculating cook's distance...
... done in 0.08 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 171 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.18 seconds.

Fitting LFCs...
... done in 0.17 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.48 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SPHKAP     5.222400e+03       -1.767556  0.964872 -2.768445  5.632454e-03
P2RX3      1.153961e+02        0.260780  0.769614  1.781609  7.481304e-02
SRSF5      2.078986e+06       -0.052073  0.210330  0.138129  8.901387e-01
MFSD2A     7.278438e+04        0.369383  0.379502  1.120726  2.624046e-01
SMOC2      5.112323e+05        0.095505  0.378657  0.263125  7.924541e-01
...                 ...             ...       ...       ...           ...
RNU6-395P  1.842221e+03       -0.027577  0.508622 -0.082095  9.345713e-01
ZNF33A     1.175766e+06        2.875700  0.553871  5.251554  1.508213e-07
CHTF18     1.847956e+05        0.601469  0.351019  2.016135  4.378585e-02
ZC3H7B     5.484351e+05        0.087280  0.377166  0.230684  8.175606e-01
NOX4       5.837907e+04        0.168539  0.164515  1.022525  3.065324e-01

                   padj
SPHKAP     1.808982e-02
P2RX3      1.727067e-01
SRSF5      9.456108e-01
MFSD2A     4.531700e-01
SMOC2      8.948369e-01
...                 ...
RNU6-395P  9.673259e-01
ZNF33A     8.940015e-07
CHTF18     1.102599e-01
ZC3H7B     9.080611e-01
NOX4       5.028195e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.48 seconds.

Fitting dispersion trend curve...
... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 1.89 seconds.

Fitting LFCs...
... done in 1.53 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 171 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 171)
Number of True values in replace_mask: 303
replacement_counts_trimmed shape: (78, 171)

... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.15 seconds.

Fitting LFCs...
... done in 0.34 seconds.

Running Wald tests...
... done in 0.94 seconds.

Fitting MAP LFCs...
... done in 1.91 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SPHKAP     5.222400e+03       -0.497029  0.775398 -2.768439  0.005633
P2RX3      6.932861e+00        0.434181  0.047335  0.008890  0.992907
SRSF5      2.078986e+06        1.870096  0.089182  0.138129  0.890139
MFSD2A     7.278438e+04        1.794532  0.337901  1.120724  0.262406
SMOC2      5.112323e+05        1.801590  0.227218  0.263125  0.792454
...                 ...             ...       ...       ...       ...
RNU6-395P  1.842221e+03       -0.098124  0.508499 -0.082094  0.934572
ZNF33A     1.175766e+06        3.441137  0.135817  4.485769  0.000007
CHTF18     1.847956e+05        1.659897  0.251294  0.214958  0.829800
ZC3H7B     5.484351e+05        1.806082  0.223112  0.230684  0.817561
NOX4       5.837907e+04        1.576391  0.167763  1.022522  0.306534

               padj
SPHKAP     0.016269
P2RX3      0.996558
SRSF5      0.946819
MFSD2A     0.458406
SMOC2      0.897060
...             ...
RNU6-395P  0.968733
ZNF33A     0.000030
CHTF18     0.913252
ZC3H7B     0.908870
NOX4       0.509009

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R2.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R2.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R2.csv
============================================================
[INFO] (113/160) sim_S40_G5000_CNweak_R20.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=20
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.03 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 2.19 seconds.

Fitting dispersion trend curve...
... done in 0.26 seconds.

Fitting MAP dispersions...
... done in 2.38 seconds.

Fitting LFCs...
... done in 1.18 seconds.

Calculating cook's distance...
... done in 0.09 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 217 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.20 seconds.

Fitting MAP dispersions...
... done in 0.28 seconds.

Fitting LFCs...
... done in 0.26 seconds.

Running Wald tests...
... done in 0.62 seconds.

Fitting MAP LFCs...
... done in 3.67 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                   baseMean  log2FoldChange     lfcSE      stat        pvalue  \
PRICKLE2-AS2     194.360281       -0.355254  0.774547 -0.979135  3.275135e-01
HCCAT5            86.140741        0.158640  0.712392 -0.334303  7.381509e-01
THY1          770319.041633       -0.458276  0.480353 -1.269398  2.042991e-01
PPARD         189597.211897       -1.312188  0.150951 -8.928725  4.309468e-19
FAM180A        55430.365830        1.792927  0.336636  5.602295  2.115320e-08
...                     ...             ...       ...       ...           ...
MYHAS           2227.575762        0.359504  0.415325  1.074850  2.824420e-01
SYCE1L         19910.795092       -0.092423  0.140437 -0.701416  4.830432e-01
SAR1B         342595.875512       -0.135149  0.201577 -0.793444  4.275193e-01
TXNL4B         85657.426541        0.229521  0.521230  0.652399  5.141435e-01
HSD17B6        36975.626981        1.227560  0.159293  7.863892  3.723793e-15

                      padj
PRICKLE2-AS2  5.344317e-01
HCCAT5        8.679318e-01
THY1          3.842942e-01
PPARD         5.664447e-18
FAM180A       1.294887e-07
...                    ...
MYHAS         4.863175e-01
SYCE1L        6.838672e-01
SAR1B         6.340587e-01
TXNL4B        7.109374e-01
HSD17B6       3.944374e-14

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.03 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.71 seconds.

Fitting dispersion trend curve...
... done in 0.48 seconds.

Fitting MAP dispersions...
... done in 2.11 seconds.

Fitting LFCs...
... done in 1.59 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 211 outlier genes.

replace_mask before filtering: (80, 211)
Number of True values in replace_mask: 350
replacement_counts_trimmed shape: (78, 211)

Fitting dispersions...
... done in 0.39 seconds.

Fitting MAP dispersions...
... done in 0.32 seconds.

Fitting LFCs...
... done in 0.15 seconds.

Running Wald tests...
... done in 0.38 seconds.

Fitting MAP LFCs...
... done in 1.22 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                   baseMean  log2FoldChange     lfcSE       stat  \
PRICKLE2-AS2     194.360281       -0.332996  0.761415  -0.979110
HCCAT5             9.912958        0.377023  0.050151  -0.113930
THY1          770319.041633        1.473934  0.179075  -1.269398
PPARD         189597.211897        0.298291  0.165361 -11.781623
FAM180A        55430.365830        2.523381  0.306301   4.636230
...                     ...             ...       ...        ...
MYHAS           2227.575762        0.313826  0.414951   1.074837
SYCE1L         19910.795092       -0.187060  0.137442  -0.701408
SAR1B         342595.875512        1.666583  0.141781  -0.793444
TXNL4B         85657.426541        1.808152  0.456523   0.652399
HSD17B6        36975.626981        1.978331  0.163460   5.987323

                    pvalue          padj
PRICKLE2-AS2  3.275258e-01  5.406213e-01
HCCAT5        9.092936e-01  9.558778e-01
THY1          2.042991e-01  3.866648e-01
PPARD         4.854921e-32  1.281545e-30
FAM180A       3.548211e-06  1.503995e-05
...                    ...           ...
MYHAS         2.824476e-01  4.932206e-01
SYCE1L        4.830485e-01  6.869858e-01
SAR1B         4.275195e-01  6.386209e-01
TXNL4B        5.141436e-01  7.135084e-01
HSD17B6       2.133232e-09  1.243305e-08

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R20.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R20.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R20.csv
============================================================
[INFO] (114/160) sim_S40_G5000_CNweak_R3.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=3
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.15 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.53 seconds.

Fitting LFCs...
... done in 0.80 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 194 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.38 seconds.

Fitting MAP LFCs...
... done in 1.42 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SULT2B1   114095.008610        1.002187  0.459459  2.576715  9.974424e-03
MORN2      44810.462294       -0.967484  0.230142 -4.448458  8.648902e-06
PRR7-AS1    2462.094957        1.144636  0.257392  4.691986  2.705662e-06
FMO2      426352.523401       -0.353953  0.382314 -1.105131  2.691030e-01
NFYC      297260.545582       -0.009577  0.129890 -0.140894  8.879536e-01
...                 ...             ...       ...       ...           ...
GAS2        5166.556914       -1.791758  0.190713 -9.577225  9.968685e-22
AGMAT       8366.357555       -0.848482  0.963374 -1.828630  6.745512e-02
LIPT1      36292.894988        0.244942  0.143003  1.726088  8.433154e-02
PGPEP1    105325.207392       -1.779101  0.282969 -6.602256  4.049485e-11
ADAMTS15  586014.390511        0.232905  0.611779  0.516124  6.057678e-01

                  padj
SULT2B1   3.026889e-02
MORN2     4.237029e-05
PRR7-AS1  1.406944e-05
FMO2      4.702002e-01
NFYC      9.503997e-01
...                ...
GAS2      1.405754e-20
AGMAT     1.613493e-01
LIPT1     1.948996e-01
PGPEP1    3.100465e-10
ADAMTS15  7.912070e-01

[4992 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.03 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.51 seconds.

Fitting LFCs...
... done in 0.93 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

Replacing 189 outlier genes.

Fitting dispersions...
... done in 0.04 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 189)
Number of True values in replace_mask: 302
replacement_counts_trimmed shape: (80, 189)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.06 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
SULT2B1   114095.008610        2.080328  0.345104   1.641445  1.007051e-01
MORN2      44810.462294        0.104520  0.245214  -6.026996  1.670356e-09
PRR7-AS1    2462.094957        0.904848  0.256505   3.722805  1.970216e-04
FMO2      426352.523401        1.077370  0.223600  -3.113748  1.847274e-03
NFYC      297260.545582        1.988680  0.115451  -0.140894  8.879540e-01
...                 ...             ...       ...        ...           ...
GAS2        5166.556914       -2.299345  0.189369 -11.926990  8.561305e-33
AGMAT       8366.357555        0.027385  0.644751  -1.828613  6.745762e-02
LIPT1      36292.894988        0.619194  0.149933   1.726077  8.433354e-02
PGPEP1    105325.207392        0.340332  0.295113  -8.014314  1.107530e-15
ADAMTS15  586014.390511        2.014703  0.246069   0.516163  6.057405e-01

                  padj
SULT2B1   2.279909e-01
MORN2     8.985364e-09
PRR7-AS1  6.877845e-04
FMO2      5.796097e-03
NFYC      9.680322e-01
...                ...
GAS2      1.625020e-31
AGMAT     1.618983e-01
LIPT1     1.960843e-01
PGPEP1    8.817848e-15
ADAMTS15  8.093834e-01

[4992 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R3.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R3.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R3.csv
============================================================
[INFO] (115/160) sim_S40_G5000_CNweak_R4.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=4
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.61 seconds.

Fitting dispersion trend curve...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 1.25 seconds.

Fitting LFCs...
... done in 0.72 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 197 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.25 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
TCP11        5161.823768        1.111863  0.608117   2.408154  1.603342e-02
RNA5SP216   20335.669340        1.807253  0.187811   9.802093  1.102768e-22
EML5        89930.078022       -0.008435  0.102659  -0.062604  9.500815e-01
TEX19         341.691525        0.541911  0.804244   0.314727  7.529688e-01
PA2G4P5     37932.627748        1.376074  0.113632  12.166257  4.701524e-34
...                  ...             ...       ...        ...           ...
LINC02345    2183.296466        0.201714  0.654724   0.529513  5.964495e-01
DOCK1      530148.219379        0.159965  0.125279   1.104780  2.692547e-01
ANKRD39     63756.570063       -0.289690  0.438775  -0.858692  3.905102e-01
IFT81       98714.858926        0.138811  0.196165   0.751854  4.521391e-01
SCN3B       26815.035317       -0.001235  0.195942  -0.002022  9.983869e-01

                   padj
TCP11      4.715601e-02
RNA5SP216  1.643947e-21
EML5       9.765558e-01
TEX19      8.715532e-01
PA2G4P5    1.204072e-32
...                 ...
LINC02345  7.704782e-01
DOCK1      4.699369e-01
ANKRD39    5.998794e-01
IFT81      6.561996e-01
SCN3B      9.987869e-01

[4994 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.11 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.53 seconds.

Fitting LFCs...
... done in 0.96 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 196 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 196)
Number of True values in replace_mask: 317
replacement_counts_trimmed shape: (78, 196)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.17 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
TCP11        5161.823768        1.369043  0.637998  1.621552  1.048993e-01
RNA5SP216   20335.669340        2.001226  0.195405  8.062569  7.470750e-16
EML5        89930.078022        0.507613  0.109920 -0.062604  9.500817e-01
TEX19         104.057865        0.592344  0.167224 -4.147596  3.359846e-05
PA2G4P5     37932.627748        0.994126  0.113292  8.933400  4.131129e-19
...                  ...             ...       ...       ...           ...
LINC02345    2183.296466        0.237870  0.658325  0.529513  5.964496e-01
DOCK1      530148.219379        2.072817  0.117539  1.087439  2.768427e-01
ANKRD39     63756.570063        1.228138  0.430805 -0.858692  3.905104e-01
IFT81       98714.858926        1.560164  0.193840  0.751853  4.521397e-01
SCN3B       26815.035317        0.750190  0.210497 -0.002022  9.983869e-01

                   padj
TCP11      2.305753e-01
RNA5SP216  6.986690e-15
EML5       9.756600e-01
TEX19      1.263484e-04
PA2G4P5    4.721020e-18
...                 ...
LINC02345  7.771746e-01
DOCK1      4.847660e-01
ANKRD39    6.081100e-01
IFT81      6.643088e-01
SCN3B      9.991872e-01

[4994 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R4.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R4.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R4.csv
============================================================
[INFO] (116/160) sim_S40_G5000_CNweak_R5.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=5
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.15 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.53 seconds.

Fitting LFCs...
... done in 0.94 seconds.

Calculating cook's distance...
... done in 0.08 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 177 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 0.14 seconds.

Fitting LFCs...
... done in 0.14 seconds.

Running Wald tests...
... done in 0.56 seconds.

Fitting MAP LFCs...
... done in 1.88 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
MLYCD      9.614524e+04        0.366513  0.193057   2.002773  4.520164e-02
RPL26      1.979115e+06       -0.115552  0.152299  -0.371260  7.104441e-01
FASTKD5    1.489497e+05        1.021479  0.221164   4.864814  1.145645e-06
ADCY10     2.875942e+03        0.382879  0.371963   1.220394  2.223156e-01
UPK2       4.522904e+03        0.065521  0.257217   0.274918  7.833791e-01
...                 ...             ...       ...        ...           ...
RPS15AP14  1.937307e+02       -0.935386  1.018692  -1.924080  5.434456e-02
POMT2      2.562178e+04        0.241489  0.696225   0.259761  7.950479e-01
NKX2-8     5.352784e+02       -0.548441  0.114123  -4.887273  1.022422e-06
NHLH1      1.606171e+03       -0.251144  0.269907  -1.028133  3.038871e-01
REEP1      1.841003e+05        1.959039  0.154397  12.748401  3.182056e-37

                   padj
MLYCD      1.130607e-01
RPL26      8.441359e-01
FASTKD5    6.147063e-06
ADCY10     4.034018e-01
UPK2       8.883664e-01
...                 ...
RPS15AP14  1.324118e-01
POMT2      8.935336e-01
NKX2-8     5.521523e-06
NHLH1      5.056342e-01
REEP1      9.508061e-36

[4990 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.11 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.48 seconds.

Fitting LFCs...
... done in 1.25 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 179 outlier genes.

Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 179)
Number of True values in replace_mask: 310
replacement_counts_trimmed shape: (78, 179)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.00 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
MLYCD      9.614524e+04        1.731068  0.188973  2.002770  4.520193e-02
RPL26      1.979115e+06        2.031187  0.068125 -0.371260  7.104441e-01
FASTKD5    1.489497e+05        1.762889  0.186738  1.778211  7.536921e-02
ADCY10     2.875942e+03       -0.407495  0.367642 -1.160762  2.457387e-01
UPK2       4.522904e+03        0.030697  0.256047  0.274914  7.833823e-01
...                 ...             ...       ...       ...           ...
RPS15AP14  1.937307e+02       -0.888273  1.005373 -1.924013  5.435292e-02
POMT2      5.934710e+03        0.669775  0.061935 -0.779987  4.353984e-01
NKX2-8     5.352784e+02       -0.918577  0.114456 -8.117069  4.775776e-16
NHLH1      1.606171e+03       -1.114806  0.277854 -4.345954  1.386717e-05
REEP1      1.841003e+05        2.661272  0.136281  9.695678  3.145426e-22

                   padj
MLYCD      1.112217e-01
RPL26      8.565510e-01
FASTKD5    1.740363e-01
ADCY10     4.418869e-01
UPK2       8.980152e-01
...                 ...
RPS15AP14  1.310247e-01
POMT2      6.563861e-01
NKX2-8     4.232882e-15
NHLH1      5.457192e-05
REEP1      4.242075e-21

[4990 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R5.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R5.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R5.csv
============================================================
[INFO] (117/160) sim_S40_G5000_CNweak_R6.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=6
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.89 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.66 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 185 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.20 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SYCP2L        5675.526225       -1.765078  0.400688 -4.789607  0.000002
RNA5SP187      234.313725        0.025707  0.514536  0.066601  0.946899
PRR13       475338.911600        0.186306  0.166753  0.992949  0.320735
SLC44A3      49680.728223       -0.075319  0.283375 -0.304467  0.760772
CCDC92      308951.162543       -0.318976  0.188924 -1.834670  0.066555
...                   ...             ...       ...       ...       ...
MTSS1       457133.196616       -0.321220  0.625366 -0.840874  0.400419
GRHL2       340434.784113       -0.308461  0.178542 -1.842864  0.065349
SHC2        258080.049314       -0.228153  0.453915 -0.672078  0.501534
ZNF829       47330.264652        0.701739  0.732837  1.572894  0.115743
RNU6-1330P     441.101687        0.064809  0.214539  0.319183  0.749588

                padj
SYCP2L      0.000009
RNA5SP187   0.975521
PRR13       0.531433
SLC44A3     0.873531
CCDC92      0.160561
...              ...
MTSS1       0.612412
GRHL2       0.158188
SHC2        0.698926
ZNF829      0.253599
RNU6-1330P  0.867075

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.88 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 181 outlier genes.

Fitting dispersions...
... done in 0.04 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 181)
Number of True values in replace_mask: 284
replacement_counts_trimmed shape: (80, 181)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.06 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SYCP2L        5675.526225       -2.157975  0.400606 -5.974890  2.302455e-09
RNA5SP187      234.313725        0.024825  0.511757  0.066597  9.469022e-01
PRR13       475338.911600        1.978576  0.119644  0.992949  3.207350e-01
SLC44A3      49680.728223        1.254184  0.291958 -0.304467  7.607724e-01
CCDC92      308951.162543        1.539415  0.147540 -1.834670  6.655465e-02
...                   ...             ...       ...       ...           ...
MTSS1       457133.196616        1.117798  0.275664 -1.952949  5.082564e-02
GRHL2       340434.784113        0.898390  0.144676 -6.112091  9.833425e-10
SHC2        258080.049314        1.460329  0.365292 -0.672077  5.015348e-01
ZNF829       47330.264652        1.750762  0.629634  0.545401  5.854778e-01
RNU6-1330P     441.101687        0.075031  0.214493  0.319110  7.496433e-01

                    padj
SYCP2L      1.244523e-08
RNA5SP187   9.933660e-01
PRR13       5.415049e-01
SLC44A3     8.881585e-01
CCDC92      1.591760e-01
...                  ...
MTSS1       1.255293e-01
GRHL2       5.487579e-09
SHC2        7.080649e-01
ZNF829      7.713358e-01
RNU6-1330P  8.818605e-01

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R6.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R6.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R6.csv
============================================================
[INFO] (118/160) sim_S40_G5000_CNweak_R7.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=7
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.90 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.71 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 188 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
... done in 1.02 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat         pvalue  \
LINC01908     110.367339       -0.850708  1.058764  -1.849067   6.444818e-02
PCSK6      186516.298520        0.010183  0.337401   0.011656   9.906998e-01
NRF1       263263.728230        1.832319  0.081127  22.791015  5.629503e-115
EFCAB11     37195.104182       -0.042154  0.260376  -0.182022   8.555657e-01
VANGL1     189471.585590       -0.088516  0.306779  -0.371741   7.100858e-01
...                  ...             ...       ...        ...            ...
RCN1       816219.665374        0.233951  0.753954   0.908198   3.637734e-01
UBE2D1     142322.081023       -0.630056  0.729378  -1.544805   1.223935e-01
ZNF512     193069.931998       -0.557053  0.318629  -2.019921   4.339157e-02
PRR22       15621.352073        0.052419  0.154827   0.303322   7.616441e-01
CACNA1G     29294.197686        0.873863  0.166649   5.372908   7.747696e-08

                    padj
LINC01908   1.513910e-01
PCSK6       9.950896e-01
NRF1       2.005310e-112
EFCAB11     9.249309e-01
VANGL1      8.405407e-01
...                  ...
RCN1        5.667410e-01
UBE2D1      2.577604e-01
ZNF512      1.085769e-01
PRR22       8.731174e-01
CACNA1G     4.361318e-07

[4987 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.06 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.35 seconds.

Fitting LFCs...
... done in 1.01 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 184 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 184)
Number of True values in replace_mask: 303
replacement_counts_trimmed shape: (78, 184)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.05 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC01908     110.367339       -0.821561  1.051275  -1.848917  6.446973e-02
PCSK6      186516.298520        1.561269  0.297872   0.011656  9.906998e-01
NRF1       263263.728230        3.547795  0.090637  18.011023  1.596514e-72
EFCAB11     37195.104182        1.106922  0.277627  -0.182021  8.555659e-01
VANGL1     189471.585590        1.458595  0.275213  -0.371741  7.100859e-01
...                  ...             ...       ...        ...           ...
RCN1       816219.665374        2.022954  0.208004   0.411007  6.810674e-01
UBE2D1     142322.081023        1.032910  0.587810  -1.544812  1.223918e-01
ZNF512     193069.931998        0.922386  0.298487  -2.934624  3.339523e-03
PRR22       15621.352073       -0.057977  0.151300   0.303319  7.616470e-01
CACNA1G     29294.197686        0.701341  0.174633   0.831388  4.057546e-01

                   padj
LINC01908  1.530274e-01
PCSK6      9.986673e-01
NRF1       3.184726e-70
EFCAB11    9.332256e-01
VANGL1     8.531014e-01
...                 ...
RCN1       8.380702e-01
UBE2D1     2.628630e-01
ZNF512     1.031859e-02
PRR22      8.857332e-01
CACNA1G    6.258887e-01

[4987 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R7.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R7.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R7.csv
============================================================
[INFO] (119/160) sim_S40_G5000_CNweak_R8.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=8
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.92 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.33 seconds.

Fitting LFCs...
... done in 0.67 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 173 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.39 seconds.

Fitting MAP LFCs...
... done in 1.21 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
ZNF542P     263235.258480        2.348853  0.177632  13.307871  2.083327e-40
RFX7        136618.263142        0.186064  0.139424   1.371561  1.702002e-01
GEMIN7-AS1   11486.719859       -1.948093  0.210073  -9.468312  2.844029e-21
MIR6774        173.100287       -0.469579  0.556113  -1.222090  2.216736e-01
RMDN1       204782.784665       -0.579955  0.197363  -3.177302  1.486520e-03
...                   ...             ...       ...        ...           ...
LCNL1         6621.325215        0.118230  0.251378   0.506549  6.124711e-01
ENDOD1      292641.240757       -0.145119  0.665745  -0.399046  6.898593e-01
ZNF335      196969.159318       -1.185935  0.463121  -3.054102  2.257356e-03
PGF          83509.593218        0.366350  0.396184   1.154391  2.483398e-01
PKNOX2       18157.972923       -0.032745  0.383895  -0.112464  9.104557e-01

                    padj
ZNF542P     8.522856e-39
RFX7        3.349641e-01
GEMIN7-AS1  4.394597e-20
MIR6774     4.060083e-01
RMDN1       5.431348e-03
...                  ...
LCNL1       7.853887e-01
ENDOD1      8.320657e-01
ZNF335      7.973434e-03
PGF         4.415617e-01
PKNOX2      9.572315e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.05 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.38 seconds.

Fitting LFCs...
... done in 0.94 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 173 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 173)
Number of True values in replace_mask: 283
replacement_counts_trimmed shape: (76, 173)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.44 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
ZNF542P     263235.258480        3.001318  0.128711  10.516160  7.278000e-26
RFX7        136618.263142        1.882292  0.135955   1.371558  1.702009e-01
GEMIN7-AS1   11486.719859       -2.176041  0.210838 -10.936270  7.731565e-28
MIR6774        173.100287       -0.465716  0.555370  -1.221991  2.217110e-01
RMDN1       204782.784665        6.077221  0.238494  14.209332  8.018685e-46
...                   ...             ...       ...        ...           ...
LCNL1         6621.325215        0.037820  0.248600   0.506544  6.124751e-01
ENDOD1      292641.240757        1.559007  0.435203  -0.399027  6.898732e-01
ZNF335      196969.159318        0.629272  0.373010  -4.851390  1.225995e-06
PGF          83509.593218        1.863067  0.338399   1.154396  2.483380e-01
PKNOX2       18157.972923        0.874383  0.429123  -0.112464  9.104558e-01

                    padj
ZNF542P     1.435751e-24
RFX7        3.392464e-01
GEMIN7-AS1  1.754011e-26
MIR6774     4.113605e-01
RMDN1       4.653635e-44
...                  ...
LCNL1       7.918983e-01
ENDOD1      8.389759e-01
ZNF335      5.562673e-06
PGF         4.466504e-01
PKNOX2      9.602655e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R8.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R8.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R8.csv
============================================================
[INFO] (120/160) sim_S40_G5000_CNweak_R9.pkl
[INFO] Running analysis for S=40, G=5000, CN=weak, R=9
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.85 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.70 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 184 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.23 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
VN1R81P      1.717935e+03       -1.215617  0.255823  -5.007998  5.499920e-07
MIR7844      2.135677e+03       -1.073159  0.325286  -3.626459  2.873340e-04
CFAP69       4.673373e+04       -2.243080  0.329485  -7.159578  8.092558e-13
BCAR3        2.292944e+05       -0.222909  0.248351  -1.059173  2.895209e-01
CEP57        2.313724e+05       -0.029999  0.130114  -0.268392  7.883976e-01
...                   ...             ...       ...        ...           ...
ARPC4-TTLL3  1.251435e+06        1.703442  0.167333  10.400173  2.474847e-25
SRGAP3-AS4   1.120495e+02       -1.121699  0.280909  -4.271478  1.941821e-05
GPR45        1.726446e+02       -0.080840  0.626220  -0.226384  8.209031e-01
SULT4A1      8.462615e+03       -0.006934  0.378474  -0.030454  9.757048e-01
GTSE1-DT     2.969099e+03        0.122198  0.109613   1.134413  2.566214e-01

                     padj
VN1R81P      2.872628e-06
MIR7844      1.111025e-03
CFAP69       6.650029e-12
BCAR3        4.947346e-01
CEP57        8.868158e-01
...                   ...
ARPC4-TTLL3  3.833707e-24
SRGAP3-AS4   8.632621e-05
GPR45        9.065756e-01
SULT4A1      9.901018e-01
GTSE1-DT     4.550399e-01

[4988 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.03 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.36 seconds.

Fitting LFCs...
... done in 0.88 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 188 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 188)
Number of True values in replace_mask: 283
replacement_counts_trimmed shape: (78, 188)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.06 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
VN1R81P      1.717935e+03       -1.356657  0.255688 -5.666104  1.460808e-08
MIR7844      2.135677e+03       -1.440111  0.325510 -4.718878  2.371494e-06
CFAP69       4.673373e+04       -0.260151  0.379918 -8.516321  1.647022e-17
BCAR3        2.292944e+05        1.411706  0.228707 -1.059173  2.895211e-01
CEP57        2.313724e+05        1.918918  0.125032 -0.268391  7.883987e-01
...                   ...             ...       ...       ...           ...
ARPC4-TTLL3  1.251435e+06        2.787373  0.095830  8.257687  1.485229e-16
SRGAP3-AS4   1.120495e+02       -1.401656  0.281747 -5.252832  1.497783e-07
GPR45        1.726446e+02       -0.078810  0.621904 -0.226373  8.209111e-01
SULT4A1      8.462615e+03       -0.096193  0.374397 -0.030454  9.757049e-01
GTSE1-DT     2.969099e+03        0.122469  0.109823  1.134260  2.566855e-01

                     padj
VN1R81P      7.511867e-08
MIR7844      1.004161e-05
CFAP69       1.663025e-16
BCAR3        4.966063e-01
CEP57        8.890210e-01
...                   ...
ARPC4-TTLL3  1.416505e-15
SRGAP3-AS4   7.034786e-07
GPR45        9.098053e-01
SULT4A1      9.910030e-01
GTSE1-DT     4.582325e-01

[4988 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S40_G5000_CNweak_R9.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S40_G5000_CNweak_R9.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S40_G5000_CNweak_R9.csv
============================================================
[INFO] (121/160) sim_S60_G5000_CNstrong_R1.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=1
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.02 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.49 seconds.

Fitting LFCs...
... done in 0.72 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 164 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.26 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat         pvalue  \
JMJD6       2.721365e+05        1.087301  0.135222   8.260286   1.453242e-16
PLA2G12AP1  4.265880e+03       -0.210486  0.128773  -1.675158   9.390328e-02
VEGFA       3.464812e+06        1.925296  0.350603   4.951576   7.361471e-07
RHO         9.631017e+02        2.247118  0.618410   4.148955   3.339965e-05
TK1         2.201087e+05       -0.433071  0.396776  -1.285984   1.984487e-01
...                  ...             ...       ...        ...            ...
SCN9A       1.336198e+04        0.277592  0.257959   1.168940   2.424278e-01
BCL2L2      5.428314e+05        0.349006  0.425368   0.985813   3.242250e-01
NADSYN1     6.567354e+05        0.994253  0.105162   9.709029   2.759547e-22
CUL7        1.159104e+06        2.712622  0.113945  23.849557  1.023411e-125
POGK        5.192075e+05       -0.448287  0.259169  -1.823207   6.827212e-02

                     padj
JMJD6        1.085798e-15
PLA2G12AP1   2.019264e-01
VEGFA        3.066870e-06
RHO          1.214113e-04
TK1          3.658875e-01
...                   ...
SCN9A        4.226186e-01
BCL2L2       5.156810e-01
NADSYN1      2.564785e-21
CUL7        1.824230e-123
POGK         1.546737e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.88 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 0.95 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 159 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 159)
Number of True values in replace_mask: 251
replacement_counts_trimmed shape: (102, 159)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
... done in 1.05 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
JMJD6       2.721365e+05        1.360181  0.111413  -1.134649  2.565224e-01
PLA2G12AP1  4.265880e+03       -0.190858  0.128869  -1.675081  9.391829e-02
VEGFA       3.464812e+06        2.725531  0.075398   4.143444  3.421291e-05
RHO         9.631017e+02        1.930105  0.616019   3.691013  2.233628e-04
TK1         2.201087e+05        1.789911  0.356723   0.812330  4.166025e-01
...                  ...             ...       ...        ...           ...
SCN9A       1.336198e+04        0.357614  0.262061   1.168936  2.424294e-01
BCL2L2      5.428314e+05        1.908189  0.173438   0.485906  6.270338e-01
NADSYN1     6.567354e+05        1.611878  0.076128  -0.915210  3.600815e-01
CUL7        1.159104e+06        3.572295  0.055147  20.542066  9.062365e-94
POGK        5.192075e+05        0.886138  0.148632  -5.725459  1.031546e-08

                    padj
JMJD6       4.393267e-01
PLA2G12AP1  2.006619e-01
VEGFA       1.180890e-04
RHO         7.118799e-04
TK1         6.129903e-01
...                  ...
SCN9A       4.244003e-01
BCL2L2      7.837529e-01
NADSYN1     5.565706e-01
CUL7        9.422971e-92
POGK        4.572330e-08

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R1.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R1.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R1.csv
============================================================
[INFO] (122/160) sim_S60_G5000_CNstrong_R10.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=10
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.92 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.44 seconds.

Fitting LFCs...
... done in 0.69 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 151 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.24 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
CCL18     32629.469615        0.039362  0.430406  0.110382  9.121066e-01
TMPRSS3  106106.675382       -1.126140  0.610490 -2.464315  1.372752e-02
NPC2     901585.820458        0.090447  0.163923  0.703102  4.819924e-01
GZMH       9183.559784        0.059090  0.336651  0.201115  8.406083e-01
OTOGL      3678.826719       -2.038687  0.315555 -6.751029  1.468000e-11
...                ...             ...       ...       ...           ...
CCDC196    1095.686314        0.042753  0.533425  0.111051  9.115762e-01
PBOV1       195.365388       -0.987619  0.162085 -6.248148  4.153475e-10
CDHR2      5377.649137        0.313176  0.686889  2.593874  9.490136e-03
FAM215A     255.741999       -0.185346  0.166433 -1.158935  2.464825e-01
POLD3    117414.946190       -0.943889  0.885189 -1.953092  5.080870e-02

                 padj
CCL18    9.627791e-01
TMPRSS3  3.762833e-02
NPC2     6.852250e-01
GZMH     9.235971e-01
OTOGL    8.619970e-11
...               ...
CCDC196  9.624226e-01
PBOV1    2.217406e-09
CDHR2    2.677179e-02
FAM215A  4.414599e-01
POLD3    1.235480e-01

[4997 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.18 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.50 seconds.

Fitting LFCs...
... done in 0.92 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 147 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 147)
Number of True values in replace_mask: 242
replacement_counts_trimmed shape: (102, 147)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.22 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
CCL18     32629.469615        1.303433  0.465928  0.110382  9.121066e-01
TMPRSS3  106106.675382        0.685844  0.514906 -3.152002  1.621551e-03
NPC2     901585.820458        1.893239  0.103287  0.703102  4.819925e-01
GZMH       9183.559784       -0.034088  0.334535  0.201115  8.406088e-01
OTOGL      3678.826719       -2.295570  0.315943 -7.693132  1.435765e-14
...                ...             ...       ...       ...           ...
CCDC196    1095.686314        0.051284  0.537867  0.111043  9.115825e-01
PBOV1       195.365388       -1.415177  0.162346 -8.855249  8.349702e-19
CDHR2       857.914157        0.660443  0.352632 -3.161503  1.569570e-03
FAM215A     255.741999       -0.183831  0.166464 -1.158413  2.466957e-01
POLD3    117414.946190        0.710342  0.583951 -2.612910  8.977492e-03

                 padj
CCL18    9.605473e-01
TMPRSS3  4.732997e-03
NPC2     6.815435e-01
GZMH     9.221784e-01
OTOGL    9.174578e-14
...               ...
CCDC196  9.601977e-01
PBOV1    6.686452e-18
CDHR2    4.586631e-03
FAM215A  4.340629e-01
POLD3    2.384930e-02

[4997 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R10.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R10.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R10.csv
============================================================
[INFO] (123/160) sim_S60_G5000_CNstrong_R11.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=11
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 1.01 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 152 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.40 seconds.

Fitting MAP LFCs...
... done in 1.18 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE       stat        pvalue  \
OSGEPL1-AS1    2323.774903        0.172163  0.132093   1.335564  1.816918e-01
CPLANE1      211902.871286        0.711938  0.144531   4.976865  6.462232e-07
NPEPL1       404235.559032       -0.197829  0.296919  -0.731390  4.645408e-01
ZNF467       314308.181470        1.975398  0.257103   7.927516  2.235719e-15
ABHD17A      334272.068285       -0.061013  0.186925  -0.271550  7.859679e-01
...                    ...             ...       ...        ...           ...
TGDS          63956.381646        0.148234  0.169249   0.875704  3.811911e-01
NPAP1           254.155992       -0.125951  0.361904  -0.413530  6.792186e-01
NOD1         296443.636483        0.889050  0.287565   3.322214  8.930607e-04
NT5C1B         5641.409952        1.590536  0.157583  10.230630  1.445763e-24
NHP2P2          745.744923        1.002123  0.127143   7.994460  1.301432e-15

                     padj
OSGEPL1-AS1  3.441457e-01
CPLANE1      2.665537e-06
NPEPL1       6.529215e-01
ZNF467       1.516097e-14
ABHD17A      8.849625e-01
...                   ...
TGDS         5.775729e-01
NPAP1        8.199333e-01
NOD1         2.833608e-03
NT5C1B       1.446052e-23
NHP2P2       8.885703e-15

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.48 seconds.

Fitting LFCs...
... done in 0.93 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 150 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 150)
Number of True values in replace_mask: 229
replacement_counts_trimmed shape: (93, 150)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.19 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat        pvalue  \
OSGEPL1-AS1    2323.774903        0.139746  0.131735  1.335458  1.817264e-01
CPLANE1      211902.871286        1.264002  0.125588 -1.999619  4.554138e-02
NPEPL1       404235.559032        0.959692  0.185996 -4.607296  4.079387e-06
ZNF467       314308.181470        2.845408  0.135877  6.471042  9.732939e-11
ABHD17A      334272.068285        1.601886  0.154055 -0.271550  7.859680e-01
...                    ...             ...       ...       ...           ...
TGDS          63956.381646        1.402314  0.173804  0.875702  3.811920e-01
NPAP1           254.155992       -0.122159  0.361957 -0.413494  6.792449e-01
NOD1         296443.636483        1.559633  0.180535 -0.451990  6.512765e-01
NT5C1B         5641.409952        1.278802  0.156759  8.417924  3.832132e-17
NHP2P2          745.744923       -0.035601  0.126412 -0.373996  7.084073e-01

                     padj
OSGEPL1-AS1  3.438198e-01
CPLANE1      1.074183e-01
NPEPL1       1.474310e-05
ZNF467       4.767134e-10
ABHD17A      8.861621e-01
...                   ...
TGDS         5.843148e-01
NPAP1        8.245205e-01
NOD1         8.065544e-01
NT5C1B       2.663812e-16
NHP2P2       8.422251e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R11.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R11.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R11.csv
============================================================
[INFO] (124/160) sim_S60_G5000_CNstrong_R12.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=12
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.30 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.53 seconds.

Fitting LFCs...
... done in 0.85 seconds.

Calculating cook's distance...
... done in 0.08 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 154 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.14 seconds.

Running Wald tests...
... done in 0.38 seconds.

Fitting MAP LFCs...
... done in 1.37 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
PCGF1     68687.818326       -0.536913  0.119007 -4.583531  0.000005  0.000018
NPAS3     11754.076136       -1.057382  0.255709 -4.419525  0.000010  0.000037
USP8     294502.671264       -0.031171  0.083276 -0.480390  0.630950  0.789589
YRDC     110710.207988        0.149771  0.161325  0.954159  0.340003  0.541941
OSR2     148051.665934       -0.035569  0.277549 -0.209562  0.834010  0.914256
...                ...             ...       ...       ...       ...       ...
SLC10A7   56355.358018        0.067620  0.179099  0.367104  0.713542  0.847085
MYOM1     55700.305144        0.329633  0.484465  0.894167  0.371233  0.571983
ZNF644   262022.918175       -0.238155  0.140504 -1.854232  0.063706  0.144863
FABP9       486.994567       -0.377334  0.270804 -1.533897  0.125055  0.256537
DCAF1    342042.571102        1.146689  0.596289  2.445115  0.014481  0.038224

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.45 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.73 seconds.

Fitting LFCs...
... done in 1.49 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

Replacing 155 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 155)
Number of True values in replace_mask: 238
replacement_counts_trimmed shape: (104, 155)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 0.96 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
PCGF1     68687.818326        0.771915  0.128824 -6.737875  1.607201e-11
NPAS3     11754.076136       -0.894035  0.268137 -5.461999  4.708020e-08
USP8     294502.671264        2.263879  0.090309 -0.480389  6.309507e-01
YRDC     110710.207988        1.612438  0.154789  0.954158  3.400037e-01
OSR2     148051.665934        2.204491  0.239630  2.829089  4.668067e-03
...                ...             ...       ...       ...           ...
SLC10A7   56355.358018        1.324388  0.185627  0.367103  7.135421e-01
MYOM1     55700.305144        1.781325  0.456635  0.894166  3.712332e-01
ZNF644   262022.918175        1.565296  0.122016 -1.854231  6.370616e-02
FABP9       486.994567       -1.496791  0.277818 -5.713102  1.109353e-08
DCAF1    342042.571102        2.703594  0.242589  2.445137  1.447969e-02

                 padj
PCGF1    8.369861e-11
NPAS3    1.958992e-07
USP8     7.927707e-01
YRDC     5.463152e-01
OSR2     1.271233e-02
...               ...
SLC10A7  8.514379e-01
MYOM1    5.735778e-01
ZNF644   1.420787e-01
FABP9    4.821045e-08
DCAF1    3.689438e-02

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R12.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R12.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R12.csv
============================================================
[INFO] (125/160) sim_S60_G5000_CNstrong_R13.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=13
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.08 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.86 seconds.

Fitting LFCs...
... done in 0.76 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 167 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.39 seconds.

Fitting MAP LFCs...
... done in 1.32 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
EPDR1       76321.701108       -0.749153  0.233149  -3.421143  6.235864e-04
INTS12     125593.113044        0.071806  0.087699   0.794210  4.270729e-01
LINC00943     520.605297       -0.104876  0.431902  -0.316220  7.518352e-01
PCDH9       39062.845711        0.252774  0.379374   0.833615  4.044979e-01
LRGUK       17075.707034        1.867772  0.301999   6.460049  1.046693e-10
...                  ...             ...       ...        ...           ...
MIR155HG     4929.440569       -0.497473  0.122489  -4.143194  3.425021e-05
TNFAIP3    223366.594290       -1.307296  0.154021  -8.724907  2.663995e-18
CRYBG3     200528.428946       -2.106131  0.114219 -18.546368  8.725244e-77
ATXN3      203800.035932       -0.205119  0.294670  -0.758241  4.483070e-01
NCR1          464.703239       -1.253592  0.110199 -11.484010  1.587439e-30

                   padj
EPDR1      2.049691e-03
INTS12     6.251775e-01
LINC00943  8.670203e-01
PCDH9      6.023949e-01
LRGUK      5.801636e-10
...                 ...
MIR155HG   1.277461e-04
TNFAIP3    2.227297e-17
CRYBG3     5.367641e-75
ATXN3      6.454327e-01
NCR1       2.253621e-29

[4983 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.25 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.71 seconds.

Fitting LFCs...
... done in 0.97 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 163 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 163)
Number of True values in replace_mask: 265
replacement_counts_trimmed shape: (105, 163)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.31 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat         pvalue  \
EPDR1       76321.701108        0.616599  0.234952  -5.365005   8.094689e-08
INTS12     125593.113044        1.988398  0.097528   0.794208   4.270745e-01
LINC00943     520.605297       -0.103873  0.433054  -0.316212   7.518417e-01
PCDH9       39062.845711        1.565430  0.384079   0.833614   4.044987e-01
LRGUK       17075.707034        2.523093  0.291137   5.588547   2.289770e-08
...                  ...             ...       ...        ...            ...
MIR155HG     4929.440569       -0.713201  0.122787  -6.180818   6.377028e-10
TNFAIP3    223366.594290        0.635645  0.149239 -10.807095   3.186000e-27
CRYBG3     200528.428946        0.238765  0.131156 -21.432976  6.583477e-102
ATXN3      203800.035932        1.438481  0.250241  -0.758240   4.483070e-01
NCR1          464.703239       -1.708843  0.110177 -15.582665   9.548921e-55

                   padj
EPDR1      3.378211e-07
INTS12     6.303649e-01
LINC00943  8.694424e-01
PCDH9      6.076627e-01
LRGUK      1.001749e-07
...                 ...
MIR155HG   3.121486e-09
TNFAIP3    3.616364e-26
CRYBG3     1.093515e-99
ATXN3      6.522376e-01
NCR1       3.236889e-53

[4983 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R13.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R13.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R13.csv
============================================================
[INFO] (126/160) sim_S60_G5000_CNstrong_R14.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=14
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.31 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.76 seconds.

Fitting LFCs...
... done in 1.01 seconds.

Calculating cook's distance...
... done in 0.08 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 138 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.46 seconds.

Fitting MAP LFCs...
... done in 2.25 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
MIA3       5.980199e+05       -0.091064  0.167497 -0.707804  4.790673e-01
CTNNB1     2.408793e+06        0.078430  0.146513  0.775981  4.377605e-01
DDX10      1.734768e+05       -0.188637  0.130745 -1.486515  1.371430e-01
RNU6-322P  3.983846e+02       -0.192343  0.315347 -0.696531  4.860961e-01
RN7SL130P  6.652284e+02        0.020642  0.305408  0.073385  9.414997e-01
...                 ...             ...       ...       ...           ...
GPR137     2.032172e+05       -0.454062  0.220334 -2.283223  2.241721e-02
DDX52      1.200183e+05       -1.461985  0.160128 -9.342150  9.439774e-21
TOR1AIP1   4.204761e+05       -0.066017  0.133247 -0.628779  5.294939e-01
ACTBP11    1.274588e+04       -0.247227  0.118354 -2.169076  3.007691e-02
RPS3AP49   9.341145e+03       -0.440148  0.314384 -1.593866  1.109660e-01

                   padj
MIA3       6.672038e-01
CTNNB1     6.315164e-01
DDX10      2.758344e-01
RNU6-322P  6.742623e-01
RN7SL130P  9.715076e-01
...                 ...
GPR137     5.787633e-02
DDX52      8.231747e-20
TOR1AIP1   7.082325e-01
ACTBP11    7.535089e-02
RPS3AP49   2.320748e-01

[4988 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.18 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.64 seconds.

Fitting LFCs...
... done in 1.07 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 138 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 138)
Number of True values in replace_mask: 209
replacement_counts_trimmed shape: (99, 138)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.17 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
MIA3       5.980199e+05        0.860833  0.103754  -7.467914  8.147637e-14
CTNNB1     2.408793e+06        1.999276  0.066714   0.775980  4.377605e-01
DDX10      1.734768e+05        1.439566  0.129889  -1.486513  1.371434e-01
RNU6-322P  3.983846e+02       -0.456324  0.320369  -1.575637  1.151094e-01
RN7SL130P  6.652284e+02        0.006143  0.306069   0.073381  9.415026e-01
...                 ...             ...       ...        ...           ...
GPR137     2.032172e+05        1.111198  0.173950  -4.036436  5.426925e-05
DDX52      1.200183e+05        0.358474  0.174171 -11.171509  5.621776e-29
TOR1AIP1   4.204761e+05        0.827717  0.104053  -8.365062  6.008334e-17
ACTBP11    1.274588e+04       -1.303992  0.118863 -11.157441  6.585996e-29
RPS3AP49   9.341145e+03       -0.500100  0.310987  -1.593861  1.109672e-01

                   padj
MIA3       4.602538e-13
CTNNB1     6.278266e-01
DDX10      2.716410e-01
RNU6-322P  2.342267e-01
RN7SL130P  9.720999e-01
...                 ...
GPR137     1.758902e-04
DDX52      7.135221e-28
TOR1AIP1   4.044477e-16
ACTBP11    8.295694e-28
RPS3AP49   2.274988e-01

[4988 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R14.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R14.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R14.csv
============================================================
[INFO] (127/160) sim_S60_G5000_CNstrong_R15.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=15
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.01 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.50 seconds.

Fitting LFCs...
... done in 0.72 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 164 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.25 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
BBIP1       302673.885483        0.108656  0.201993   0.659239  5.097423e-01
DMWD        364962.158870        1.184366  0.120774  10.006921  1.421062e-23
TMEM163      14327.143467       -0.060179  0.269929  -0.250973  8.018349e-01
RPTOR       331801.616742        0.939736  0.142561   6.600523  4.097093e-11
CRYGS        43722.374565        1.185194  0.163881   7.387951  1.491090e-13
...                   ...             ...       ...        ...           ...
VWA8        164427.433177       -0.150421  0.222421  -0.773658  4.391329e-01
FGB          32838.111053       -0.130840  0.388787  -0.419506  6.748462e-01
THAP6        56940.218904       -0.281903  0.369326  -0.922925  3.560462e-01
HNRNPA3P13     484.095399       -0.118040  0.576776  -0.323418  7.463786e-01
GUSBP5        4372.427388       -0.000537  0.177195  -0.007393  9.941012e-01

                    padj
BBIP1       7.131533e-01
DMWD        1.384703e-22
TMEM163     9.122060e-01
RPTOR       2.241272e-10
CRYGS       9.287202e-13
...                  ...
VWA8        6.487516e-01
FGB         8.339875e-01
THAP6       5.706118e-01
HNRNPA3P13  8.811365e-01
GUSBP5      9.982278e-01

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.01 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.44 seconds.

Fitting LFCs...
... done in 0.94 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 161 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 161)
Number of True values in replace_mask: 245
replacement_counts_trimmed shape: (101, 161)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.78 seconds.

Fitting MAP LFCs...
... done in 1.95 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
BBIP1       302673.885483        1.727043  0.165136  0.659239  5.097425e-01
DMWD        364962.158870        2.298684  0.093815  6.761692  1.363891e-11
TMEM163      14327.143467        0.028335  0.274108 -0.250972  8.018354e-01
RPTOR       331801.616742        1.603881  0.107062  0.218752  8.268434e-01
CRYGS        43722.374565        1.377542  0.160538  1.043354  2.967845e-01
...                   ...             ...       ...       ...           ...
VWA8        164427.433177        1.369075  0.210455 -0.773658  4.391331e-01
FGB          32838.111053        1.140768  0.417104 -0.419506  6.748463e-01
THAP6        56940.218904        0.971143  0.372389 -1.767452  7.715263e-02
HNRNPA3P13     484.095399       -0.120019  0.577781 -0.323385  7.464041e-01
GUSBP5        4372.427388       -0.048052  0.176210 -0.007393  9.941013e-01

                    padj
BBIP1       7.179856e-01
DMWD        6.804450e-11
TMEM163     9.138747e-01
RPTOR       9.264279e-01
CRYGS       5.051717e-01
...                  ...
VWA8        6.555461e-01
FGB         8.377229e-01
THAP6       1.736979e-01
HNRNPA3P13  8.815838e-01
GUSBP5      9.987466e-01

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R15.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R15.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R15.csv
============================================================
[INFO] (128/160) sim_S60_G5000_CNstrong_R16.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=16
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.91 seconds.

Fitting dispersion trend curve...
... done in 0.23 seconds.

Fitting MAP dispersions...
... done in 3.33 seconds.

Fitting LFCs...
... done in 1.85 seconds.

Calculating cook's distance...
... done in 0.10 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 150 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.12 seconds.

Fitting LFCs...
... done in 0.34 seconds.

Running Wald tests...
... done in 0.48 seconds.

Fitting MAP LFCs...
... done in 1.82 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat        pvalue  \
TMEM167A   469517.012062       -0.040449  0.128618 -0.406447  6.844140e-01
LINC02021    3279.399093       -1.024562  0.224332 -4.783291  1.724484e-06
FAAP100    188882.462813       -0.852569  0.118399 -7.360652  1.830137e-13
MYOM2       19988.944009        0.238006  0.321980  0.851529  3.944754e-01
FOXN3-AS1    9952.771056       -0.260088  0.233817 -1.211606  2.256633e-01
...                  ...             ...       ...       ...           ...
IPO8P1      14334.990286        0.070291  0.147681  0.484582  6.279726e-01
ATP6V1B1   167399.231319        0.817918  0.535802  1.961422  4.982981e-02
KCNH3        5160.160572       -1.119124  0.118569 -9.554178  1.245684e-21
KRTAP1-5      189.609985       -0.474260  0.134833 -3.600401  3.177265e-04
AGA        101246.621344        0.302242  0.130291  2.321138  2.027938e-02

                   padj
TMEM167A   8.297792e-01
LINC02021  7.006069e-06
FAAP100    1.181184e-12
MYOM2      6.018465e-01
FOXN3-AS1  4.119596e-01
...                 ...
IPO8P1     7.897543e-01
ATP6V1B1   1.194622e-01
KCNH3      1.161629e-20
KRTAP1-5   1.078325e-03
AGA        5.395938e-02

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.46 seconds.

Fitting dispersion trend curve...
... done in 0.14 seconds.

Fitting MAP dispersions...
... done in 2.02 seconds.

Fitting LFCs...
... done in 3.82 seconds.

Calculating cook's distance...
... done in 0.13 seconds.

Replacing 148 outlier genes.

replace_mask before filtering: (120, 148)
Number of True values in replace_mask: 238
replacement_counts_trimmed shape: (105, 148)

Fitting dispersions...
... done in 0.21 seconds.

Fitting MAP dispersions...
... done in 0.25 seconds.

Fitting LFCs...
... done in 0.16 seconds.

Running Wald tests...
... done in 0.57 seconds.

Fitting MAP LFCs...
... done in 1.91 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
TMEM167A   469517.012062        1.850646  0.100350  -0.406447  6.844141e-01
LINC02021    3279.399093       -1.426277  0.224580  -6.691707  2.205826e-11
FAAP100    188882.462813        2.246814  0.129030   0.012202  9.902648e-01
MYOM2       19988.944009        1.227789  0.348254   0.851528  3.944761e-01
FOXN3-AS1    9952.771056       -0.001461  0.240450  -1.211599  2.256660e-01
...                  ...             ...       ...        ...           ...
IPO8P1      14334.990286        0.874406  0.147308   6.348219  2.178224e-10
ATP6V1B1   167399.231319        2.165831  0.333979   1.410007  1.585375e-01
KCNH3        5160.160572       -1.469521  0.118621 -12.778196  2.170464e-37
KRTAP1-5      189.609985       -0.704549  0.135191  -5.309793  1.097495e-07
AGA        101246.621344        1.598126  0.135932   2.321134  2.027962e-02

                   padj
TMEM167A   8.320034e-01
LINC02021  1.104906e-10
FAAP100    9.958575e-01
MYOM2      6.051788e-01
FOXN3-AS1  4.096798e-01
...                 ...
IPO8P1     1.039919e-09
ATP6V1B1   3.126260e-01
KCNH3      3.981047e-36
KRTAP1-5   4.397915e-07
AGA        5.143620e-02

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R16.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R16.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R16.csv
============================================================
[INFO] (129/160) sim_S60_G5000_CNstrong_R17.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=17
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.27 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.69 seconds.

Fitting LFCs...
... done in 0.86 seconds.

Calculating cook's distance...
... done in 0.09 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 141 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.12 seconds.

Fitting LFCs...
... done in 0.16 seconds.

Running Wald tests...
... done in 0.39 seconds.

Fitting MAP LFCs...
... done in 1.71 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE       stat        pvalue  \
DNAJB14  2.331902e+05        0.089620  0.095346   0.819748  4.123598e-01
GAL3ST3  1.126431e+02       -0.595707  0.731156  -1.394014  1.633135e-01
KCTD3    6.075596e+05       -0.005060  0.192138  -0.010637  9.915130e-01
SFRP2    1.796895e+06       -0.311734  0.343270  -0.988132  3.230880e-01
WDR1     1.696746e+06        0.180697  0.104425   2.189572  2.855532e-02
...               ...             ...       ...        ...           ...
TDG      1.325007e+05       -0.152261  0.260048  -0.660469  5.089529e-01
DBN1     4.948722e+05       -0.673664  0.136083  -5.232932  1.668418e-07
SIGLEC1  2.084872e+05       -0.541843  0.659212  -1.325601  1.849721e-01
ENGASE   4.654552e+05        1.032718  0.097510  10.814494  2.939104e-27
OR7E2P   4.284478e+02       -0.006298  0.180220  -0.039113  9.688001e-01

                 padj
DNAJB14  6.168102e-01
GAL3ST3  3.230683e-01
KCTD3    9.965025e-01
SFRP2    5.240996e-01
WDR1     7.372115e-02
...               ...
TDG      7.029603e-01
DBN1     7.029884e-07
SIGLEC1  3.542637e-01
ENGASE   3.183286e-26
OR7E2P   9.868625e-01

[4993 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.64 seconds.

Fitting dispersion trend curve...
... done in 0.14 seconds.

Fitting MAP dispersions...
... done in 2.12 seconds.

Fitting LFCs...
... done in 2.08 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 150 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 150)
Number of True values in replace_mask: 225
replacement_counts_trimmed shape: (105, 150)

... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.18 seconds.

Running Wald tests...
... done in 0.39 seconds.

Fitting MAP LFCs...
... done in 1.39 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat        pvalue  \
DNAJB14  2.331902e+05        1.985097  0.100376  0.819747  4.123605e-01
GAL3ST3  1.126431e+02       -0.897829  0.806782 -1.885386  5.937768e-02
KCTD3    6.075596e+05        1.102107  0.107487 -4.986117  6.160497e-07
SFRP2    1.796895e+06        1.643696  0.117981 -0.988114  3.230967e-01
WDR1     1.696746e+06        2.365722  0.063813  2.189570  2.855541e-02
...               ...             ...       ...       ...           ...
TDG      1.325007e+05        1.339157  0.250833 -0.660469  5.089530e-01
DBN1     4.948722e+05        1.213726  0.106789 -7.370271  1.702817e-13
SIGLEC1  2.084872e+05        1.635088  0.502341 -0.132455  8.946243e-01
ENGASE   4.654552e+05        1.529422  0.083724 -1.330573  1.833297e-01
OR7E2P   4.284478e+02        0.005549  0.180234 -0.039104  9.688072e-01

                 padj
DNAJB14  6.188507e-01
GAL3ST3  1.385387e-01
KCTD3    2.353432e-06
SFRP2    5.251374e-01
WDR1     7.125296e-02
...               ...
TDG      7.062819e-01
DBN1     9.979070e-13
SIGLEC1  9.544219e-01
ENGASE   3.531773e-01
OR7E2P   9.862590e-01

[4993 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R17.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R17.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R17.csv
============================================================
[INFO] (130/160) sim_S60_G5000_CNstrong_R18.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=18
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.24 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.86 seconds.

Fitting LFCs...
... done in 0.88 seconds.

Calculating cook's distance...
... done in 0.08 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 155 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.14 seconds.

Fitting LFCs...
... done in 0.25 seconds.

Running Wald tests...
... done in 0.35 seconds.

Fitting MAP LFCs...
... done in 1.54 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC02766  8.314248e+02        0.147297  0.551049   0.385313  7.000057e-01
SLC25A48   1.606914e+04        0.109888  0.367210   0.345761  7.295223e-01
TYSND1     1.825804e+05        0.151076  0.137484   1.045209  2.959263e-01
RAD51D     1.006972e+05       -0.037444  0.152778  -0.350582  7.259019e-01
SIGLEC5    1.126013e+04       -0.266610  0.220920  -1.304746  1.919794e-01
...                 ...             ...       ...        ...           ...
ARLNC1     1.341335e+03       -0.482684  0.521149  -1.254743  2.095719e-01
CXCL9      2.179298e+05       -0.925410  0.584181  -2.174831  2.964282e-02
AP2A1      1.226998e+06        1.075841  0.303117   3.840323  1.228727e-04
RFC2       5.632038e+05        2.468239  0.125391  19.834918  1.487576e-87
QRICH1     5.045125e+05       -0.111391  0.261513  -0.349140  7.269842e-01

                   padj
LINC02766  8.414568e-01
SLC25A48   8.609708e-01
TYSND1     5.006672e-01
RAD51D     8.579153e-01
SIGLEC5    3.669740e-01
...                 ...
ARLNC1     3.905801e-01
CXCL9      7.494797e-02
AP2A1      4.267626e-04
RFC2       9.899324e-86
QRICH1     8.585845e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.24 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.68 seconds.

Fitting LFCs...
... done in 1.16 seconds.

Calculating cook's distance...
... done in 0.08 seconds.

Replacing 154 outlier genes.

replace_mask before filtering: (120, 154)
Number of True values in replace_mask: 218
replacement_counts_trimmed shape: (100, 154)

Fitting dispersions...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.15 seconds.

Fitting LFCs...
... done in 0.17 seconds.

Running Wald tests...
... done in 0.36 seconds.

Fitting MAP LFCs...
... done in 1.30 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC02766  8.314248e+02        0.157570  0.552302   0.385309  7.000086e-01
SLC25A48   1.606914e+04        1.011000  0.405612   0.345760  7.295228e-01
TYSND1     1.825804e+05        1.723118  0.128538   1.045208  2.959268e-01
RAD51D     1.006972e+05        1.399706  0.153386  -0.350582  7.259022e-01
SIGLEC5    1.126013e+04       -0.451505  0.228450  -3.202147  1.364073e-03
...                 ...             ...       ...        ...           ...
ARLNC1     1.341335e+03       -0.468059  0.521097  -1.254733  2.095756e-01
CXCL9      2.179298e+05        0.893135  0.410258  -2.977029  2.910560e-03
AP2A1      1.226998e+06        2.186270  0.087701   2.189233  2.857994e-02
RFC2       5.632038e+05        3.277503  0.075375  16.507508  3.239866e-61
QRICH1     5.045125e+05        1.671851  0.165121  -0.349140  7.269842e-01

                   padj
LINC02766  8.465575e-01
SLC25A48   8.646517e-01
TYSND1     4.974640e-01
RAD51D     8.619981e-01
SIGLEC5    3.969730e-03
...                 ...
ARLNC1     3.879792e-01
CXCL9      8.207123e-03
AP2A1      6.964964e-02
RFC2       1.188983e-59
QRICH1     8.626672e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R18.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R18.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R18.csv
============================================================
[INFO] (131/160) sim_S60_G5000_CNstrong_R19.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=19
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.31 seconds.

Fitting dispersion trend curve...
... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 1.68 seconds.

Fitting LFCs...
... done in 0.96 seconds.

Calculating cook's distance...
... done in 0.09 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 138 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.11 seconds.

Fitting LFCs...
... done in 0.21 seconds.

Running Wald tests...
... done in 0.48 seconds.

Fitting MAP LFCs...
... done in 2.63 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE       stat         pvalue  \
NOTCH1   536118.459128       -0.323931  0.208689  -1.665259   9.586103e-02
TMEM30A  686821.472848       -0.994729  0.115891  -8.489003   2.084180e-17
ZIC4      10226.420630        1.045939  0.589321   2.310304   2.087136e-02
ZBTB24   372196.737131        2.805731  0.132102  21.294744  1.269970e-100
SVIP     522376.881903        2.436580  0.185732  13.288616   2.695172e-40
...                ...             ...       ...        ...            ...
ZHX2     231621.854784       -0.315350  0.326939  -1.111958   2.661564e-01
HOXD3     39591.641649        0.233340  0.294578   0.843475   3.989630e-01
RARS2    194870.508144        0.310699  0.228878   1.393194   1.635611e-01
PRAL     334714.352001        0.044891  0.081034   0.399248   6.897104e-01
GRIK1     13465.376239        1.766380  0.220330   8.210310   2.206181e-16

                 padj
NOTCH1   2.097433e-01
TMEM30A  1.503802e-16
ZIC4     5.438971e-02
ZBTB24   1.409102e-98
SVIP     4.705242e-39
...               ...
ZHX2     4.580899e-01
HOXD3    6.047427e-01
RARS2    3.180143e-01
PRAL     8.314365e-01
GRIK1    1.521473e-15

[4993 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.03 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.23 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.71 seconds.

Fitting LFCs...
... done in 1.14 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 142 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 142)
Number of True values in replace_mask: 221
replacement_counts_trimmed shape: (96, 142)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.37 seconds.

Fitting MAP LFCs...
... done in 1.42 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE       stat        pvalue  \
NOTCH1   536118.459128        1.542876  0.143352  -1.665259  9.586107e-02
TMEM30A  686821.472848        1.077628  0.098050 -11.286455  1.530866e-29
ZIC4      10226.420630        1.394474  0.586838   0.542024  5.878017e-01
ZBTB24   372196.737131        3.555778  0.089757  18.672485  8.290400e-78
SVIP     522376.881903        3.226061  0.118838  11.453162  2.267203e-30
...                ...             ...       ...        ...           ...
ZHX2     231621.854784        0.956345  0.243619  -3.954258  7.677237e-05
HOXD3     39591.641649        1.477421  0.299526   0.843474  3.989634e-01
RARS2    194870.508144        1.757180  0.198744   1.398163  1.620640e-01
PRAL     334714.352001        2.385516  0.089311   0.399248  6.897108e-01
GRIK1     13465.376239        1.924759  0.228719   6.529381  6.604220e-11

                 padj
NOTCH1   2.081019e-01
TMEM30A  1.824252e-28
ZIC4     7.617289e-01
ZBTB24   5.446575e-76
SVIP     2.788213e-29
...               ...
ZHX2     2.498856e-04
HOXD3    6.038268e-01
RARS2    3.178262e-01
PRAL     8.312359e-01
GRIK1    3.210796e-10

[4993 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R19.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R19.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R19.csv
============================================================
[INFO] (132/160) sim_S60_G5000_CNstrong_R2.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=2
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.18 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.58 seconds.

Fitting LFCs...
... done in 0.74 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 166 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.46 seconds.

Fitting MAP LFCs...
... done in 1.33 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SPHKAP     3.781604e+03       -0.162923  0.618142 -1.313649  1.889644e-01
P2RX3      1.578137e+02        0.025053  0.615764  0.061667  9.508280e-01
SRSF5      2.014512e+06       -0.292650  0.197842 -1.654607  9.800423e-02
MFSD2A     5.722846e+04        0.185519  0.286676  0.693031  4.882898e-01
SMOC2      5.353197e+05        0.154642  0.260457  0.604187  5.457193e-01
...                 ...             ...       ...       ...           ...
RNU6-395P  1.913006e+03       -0.224842  0.387020 -0.711812  4.765815e-01
ZNF33A     8.188368e+05        1.940523  0.424863  4.926662  8.364637e-07
CHTF18     2.024770e+05        0.378845  0.249111  1.672945  9.433816e-02
ZC3H7B     6.069603e+05       -0.251760  0.310413 -0.971577  3.312608e-01
NOX4       4.756562e+04       -0.393653  0.154383 -2.674435  7.485519e-03

               padj
SPHKAP     0.350342
P2RX3      0.974588
SRSF5      0.207702
MFSD2A     0.675693
SMOC2      0.720742
...             ...
RNU6-395P  0.667214
ZNF33A     0.000004
CHTF18     0.201559
ZC3H7B     0.523369
NOX4       0.021191

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.12 seconds.

Fitting dispersion trend curve...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 1.75 seconds.

Fitting LFCs...
... done in 1.57 seconds.

Calculating cook's distance...
... done in 0.10 seconds.

Replacing 171 outlier genes.

replace_mask before filtering: (120, 171)
Number of True values in replace_mask: 254
replacement_counts_trimmed shape: (105, 171)

Fitting dispersions...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 0.15 seconds.

Fitting LFCs...
... done in 0.16 seconds.

Running Wald tests...
... done in 0.42 seconds.

Fitting MAP LFCs...
... done in 1.58 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SPHKAP     6.970849e+02       -0.360761  0.308223  0.466627  0.640766
P2RX3      1.578137e+02       -0.159043  0.618272 -0.422952  0.672330
SRSF5      2.014512e+06        1.658621  0.079110 -1.654607  0.098004
MFSD2A     5.722846e+04        1.563050  0.274721  0.693031  0.488290
SMOC2      5.353197e+05        1.824221  0.156956  0.604187  0.545719
...                 ...             ...       ...       ...       ...
RNU6-395P  1.913006e+03       -0.288298  0.385631 -0.711804  0.476586
ZNF33A     8.188368e+05        2.880362  0.130445  3.959204  0.000075
CHTF18     2.024770e+05        1.201489  0.190536 -2.353423  0.018601
ZC3H7B     6.069603e+05        1.579937  0.177658 -0.971578  0.331261
NOX4       4.756562e+04        1.119321  0.159383 -2.674428  0.007486

               padj
SPHKAP     0.792974
P2RX3      0.813175
SRSF5      0.206388
MFSD2A     0.680219
SMOC2      0.723807
...             ...
RNU6-395P  0.671995
ZNF33A     0.000245
CHTF18     0.046677
ZC3H7B     0.531615
NOX4       0.019896

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R2.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R2.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R2.csv
============================================================
[INFO] (133/160) sim_S60_G5000_CNstrong_R20.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=20
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.60 seconds.

Fitting dispersion trend curve...
... done in 0.15 seconds.

Fitting MAP dispersions...
... done in 2.17 seconds.

Fitting LFCs...
... done in 1.88 seconds.

Calculating cook's distance...
... done in 0.08 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 143 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.21 seconds.

Running Wald tests...
... done in 0.41 seconds.

Fitting MAP LFCs...
... done in 1.70 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                   baseMean  log2FoldChange     lfcSE       stat  \
PRICKLE2-AS2     160.894570       -0.026997  0.606845  -0.077762
HCCAT5            77.937513       -2.244434  0.924238  -3.240330
THY1          996994.522522       -0.088961  0.414336   0.036072
PPARD         217090.520638       -1.753828  0.099854 -17.677646
FAM180A        41154.196371        0.803006  0.270688   3.209073
...                     ...             ...       ...        ...
MYHAS           2535.739198       -0.472077  0.323507  -1.659982
SYCE1L         20121.817440       -0.033096  0.117767  -0.355224
SAR1B         369171.128235       -0.252091  0.145303  -1.898464
TXNL4B         52012.963535        0.140947  0.392305   0.429399
HSD17B6        33649.399558        1.102503  0.122677   9.063167

                    pvalue          padj
PRICKLE2-AS2  9.380171e-01  9.652985e-01
HCCAT5        1.193916e-03  3.679090e-03
THY1          9.712246e-01  9.840454e-01
PPARD         6.234579e-70  3.173910e-68
FAM180A       1.331637e-03  4.085816e-03
...                    ...           ...
MYHAS         9.691810e-02  2.083259e-01
SYCE1L        7.224219e-01  8.514441e-01
SAR1B         5.763505e-02  1.336158e-01
TXNL4B        6.676326e-01  8.119988e-01
HSD17B6       1.267167e-19  1.105226e-18

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.48 seconds.

Fitting dispersion trend curve...
... done in 0.14 seconds.

Fitting MAP dispersions...
... done in 1.78 seconds.

Fitting LFCs...
... done in 1.31 seconds.

Calculating cook's distance...
... done in 0.08 seconds.

Replacing 143 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 143)
Number of True values in replace_mask: 206
replacement_counts_trimmed shape: (97, 143)

... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 0.27 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.41 seconds.

Fitting MAP LFCs...
... done in 1.25 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                   baseMean  log2FoldChange     lfcSE       stat  \
PRICKLE2-AS2     160.894570       -0.026744  0.607093  -0.077760
HCCAT5            77.937513       -2.240055  0.923960  -3.239915
THY1          996994.522522        1.813471  0.180630   0.036072
PPARD         217090.520638        0.143275  0.116463 -21.822227
FAM180A        41154.196371        1.609108  0.269091   1.879063
...                     ...             ...       ...        ...
MYHAS           2535.739198       -0.526506  0.321126  -1.659963
SYCE1L         20121.817440       -0.151431  0.114826  -0.355220
SAR1B         369171.128235        1.611684  0.111775  -1.898463
TXNL4B         52012.963535        1.552489  0.382003   0.429399
HSD17B6        33649.399558        1.407958  0.129035   6.946118

                     pvalue           padj
PRICKLE2-AS2   9.380192e-01   9.684971e-01
HCCAT5         1.195652e-03   3.525479e-03
THY1           9.712249e-01   9.842456e-01
PPARD         1.427359e-105  2.373698e-103
FAM180A        6.023593e-02   1.370972e-01
...                     ...            ...
MYHAS          9.692192e-02   2.069078e-01
SYCE1L         7.224250e-01   8.579334e-01
SAR1B          5.763515e-02   1.320210e-01
TXNL4B         6.676327e-01   8.184770e-01
HSD17B6        3.754741e-12   2.063040e-11

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R20.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R20.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R20.csv
============================================================
[INFO] (134/160) sim_S60_G5000_CNstrong_R3.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=3
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.21 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.60 seconds.

Fitting LFCs...
... done in 0.90 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 167 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.38 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
SULT2B1   143717.855170        1.776965  0.483732   4.090506  4.304335e-05
MORN2      42751.073228       -1.098010  0.195907  -5.812782  6.144296e-09
PRR7-AS1    2914.594541        1.054306  0.242507   4.573726  4.791269e-06
FMO2      491678.950324       -0.279745  0.311893  -0.885706  3.757762e-01
NFYC      302206.458251        0.004490  0.087808  -0.038737  9.691002e-01
...                 ...             ...       ...        ...           ...
GAS2        5482.724453       -1.986463  0.149506 -13.418709  4.698278e-41
AGMAT       7340.003756        0.298089  0.626320   0.760256  4.471014e-01
LIPT1      35561.293108        0.146197  0.125368   1.130780  2.581478e-01
PGPEP1    102307.542791       -1.684718  0.227443  -7.668244  1.743667e-14
ADAMTS15  399467.313831       -0.028126  0.514204  -0.017835  9.857707e-01

                  padj
SULT2B1   1.558175e-04
MORN2     2.908666e-08
PRR7-AS1  1.861324e-05
FMO2      5.770146e-01
NFYC      9.876987e-01
...                ...
GAS2      8.850493e-40
AGMAT     6.453628e-01
LIPT1     4.512114e-01
PGPEP1    1.168374e-13
ADAMTS15  9.948580e-01

[4992 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.20 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.49 seconds.

Fitting LFCs...
... done in 1.01 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 166 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 166)
Number of True values in replace_mask: 269
replacement_counts_trimmed shape: (105, 166)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.61 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
SULT2B1   143717.855170        2.857526  0.299136   3.651532  2.606802e-04
MORN2      42751.073228        0.126871  0.211920  -7.150997  8.615011e-13
PRR7-AS1    2914.594541        0.916248  0.244948   3.721729  1.978635e-04
FMO2      491678.950324        1.004000  0.177570  -4.258881  2.054524e-05
NFYC      302206.458251        2.292465  0.085945  -0.038737  9.691003e-01
...                 ...             ...       ...        ...           ...
GAS2        5482.724453       -2.465601  0.149136 -16.370256  3.118990e-60
AGMAT       7340.003756        1.257085  0.753925   0.760256  4.471016e-01
LIPT1      35561.293108        0.705667  0.133202   1.130773  2.581506e-01
PGPEP1    102307.542791        0.351924  0.239668  -9.476223  2.636542e-21
ADAMTS15  399467.313831        1.780829  0.249154  -0.017835  9.857709e-01

                  padj
SULT2B1   8.130076e-04
MORN2     4.864947e-12
PRR7-AS1  6.235698e-04
FMO2      6.972254e-05
NFYC      9.872957e-01
...                ...
GAS2      1.255645e-58
AGMAT     6.544946e-01
LIPT1     4.530124e-01
PGPEP1    2.285003e-20
ADAMTS15  9.940551e-01

[4992 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R3.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R3.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R3.csv
============================================================
[INFO] (135/160) sim_S60_G5000_CNstrong_R4.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=4
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.13 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.92 seconds.

Fitting LFCs...
... done in 0.96 seconds.

Calculating cook's distance...
... done in 0.10 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 172 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 0.16 seconds.

Fitting LFCs...
... done in 0.20 seconds.

Running Wald tests...
... done in 0.42 seconds.

Fitting MAP LFCs...
... done in 1.51 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
TCP11        5267.366766        1.438762  0.501894   3.332139  8.618129e-04
RNA5SP216   21379.954313        1.857136  0.158607  11.835095  2.570531e-32
EML5        96026.679661       -0.032551  0.094347  -0.372911  7.092150e-01
TEX19        1247.352533        1.237185  0.757432   2.250295  2.443020e-02
PA2G4P5     37137.391230        1.253715  0.120415  10.495817  9.029282e-26
...                  ...             ...       ...        ...           ...
LINC02345    1827.121330        0.507299  0.562785   1.273452  2.028576e-01
DOCK1      536449.632899        0.029484  0.095408   0.095008  9.243082e-01
ANKRD39     78211.361724        0.061218  0.325671   0.180652  8.566411e-01
IFT81       91766.791812       -0.364828  0.158992  -2.410836  1.591600e-02
SCN3B       27697.653811        0.205852  0.183992   1.139518  2.544870e-01

                   padj
TCP11      2.697680e-03
RNA5SP216  3.450869e-31
EML5       8.463130e-01
TEX19      6.453408e-02
PA2G4P5    9.493102e-25
...                 ...
LINC02345  3.830118e-01
DOCK1      9.624677e-01
ANKRD39    9.292765e-01
IFT81      4.348166e-02
SCN3B      4.507372e-01

[4994 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.14 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.79 seconds.

Fitting LFCs...
... done in 1.13 seconds.

Calculating cook's distance...
... done in 0.08 seconds.

Replacing 169 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 169)
Number of True values in replace_mask: 255
replacement_counts_trimmed shape: (105, 169)

... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.41 seconds.

Fitting MAP LFCs...
... done in 1.40 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
TCP11        5267.366766        1.924262  0.507172   2.348661  1.884106e-02
RNA5SP216   21379.954313        2.443440  0.160939  10.258760  1.080856e-24
EML5        96026.679661        1.790448  0.103905  -0.372909  7.092161e-01
TEX19         147.060595        0.443343  0.221380  -5.674200  1.393383e-08
PA2G4P5     37137.391230        1.850257  0.125384   7.064431  1.612758e-12
...                  ...             ...       ...        ...           ...
LINC02345    1827.121330        0.445472  0.560693   1.273446  2.028599e-01
DOCK1      536449.632899        2.210951  0.082474   0.095008  9.243082e-01
ANKRD39     78211.361724        1.578586  0.290119   0.180651  8.566412e-01
IFT81       91766.791812        1.143828  0.163543  -2.410833  1.591614e-02
SCN3B       27697.653811        1.447073  0.188461   1.139514  2.544886e-01

                   padj
TCP11      4.790848e-02
RNA5SP216  1.060471e-23
EML5       8.466476e-01
TEX19      5.769948e-08
PA2G4P5    8.389704e-12
...                 ...
LINC02345  3.808277e-01
DOCK1      9.646803e-01
ANKRD39    9.280673e-01
IFT81      4.097176e-02
SCN3B      4.503601e-01

[4994 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R4.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R4.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R4.csv
============================================================
[INFO] (136/160) sim_S60_G5000_CNstrong_R5.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=5
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.04 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 4.79 seconds.

Fitting LFCs...
... done in 0.80 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 156 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.24 seconds.

Running Wald tests...
... done in 0.61 seconds.

Fitting MAP LFCs...
... done in 1.70 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
MLYCD      9.286432e+04       -0.244570  0.172232  -1.447229  1.478329e-01
RPL26      2.088280e+06        0.175283  0.151221   1.345178  1.785676e-01
FASTKD5    1.658927e+05        1.242665  0.176475   7.202300  5.920528e-13
ADCY10     3.094315e+03       -0.213896  0.298754  -0.798339  4.246735e-01
UPK2       5.288469e+03       -0.222304  0.234174  -1.038145  2.992027e-01
...                 ...             ...       ...        ...           ...
RPS15AP14  3.189674e+02       -0.065532  0.674382  -0.184756  8.534207e-01
POMT2      1.326408e+05       -0.494860  0.681525  -0.643509  5.198939e-01
NKX2-8     5.185931e+02       -0.474616  0.089484  -5.357920  8.418557e-08
NHLH1      1.867722e+03       -0.214451  0.219797  -1.028938  3.035090e-01
REEP1      1.652792e+05        1.926377  0.102831  18.777497  1.153935e-78

                   padj
MLYCD      2.880461e-01
RPL26      3.335848e-01
FASTKD5    3.479792e-12
ADCY10     6.254784e-01
UPK2       4.923667e-01
...                 ...
RPS15AP14  9.278405e-01
POMT2      7.088170e-01
NKX2-8     3.691441e-07
NHLH1      4.977812e-01
REEP1      5.875650e-77

[4990 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.26 seconds.

Fitting dispersion trend curve...
... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 2.32 seconds.

Fitting LFCs...
... done in 1.91 seconds.

Calculating cook's distance...
... done in 0.08 seconds.

Replacing 155 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 155)
Number of True values in replace_mask: 247
replacement_counts_trimmed shape: (106, 155)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.11 seconds.

Fitting LFCs...
... done in 0.19 seconds.

Running Wald tests...
... done in 0.58 seconds.

Fitting MAP LFCs...
... done in 1.29 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
MLYCD      9.286432e+04        1.279942  0.170352  -1.447229  1.478329e-01
RPL26      2.088280e+06        2.050694  0.070357   1.345181  1.785668e-01
FASTKD5    1.658927e+05        1.561962  0.150260   0.956413  3.388635e-01
ADCY10     3.094315e+03       -1.212740  0.309975  -4.308188  1.645977e-05
UPK2       5.288469e+03       -0.302780  0.231541  -1.034614  3.008492e-01
...                 ...             ...       ...        ...           ...
RPS15AP14  3.189674e+02       -0.066771  0.675632  -0.184748  8.534268e-01
POMT2      2.475617e+04        0.981889  0.315145  -2.419783  1.552976e-02
NKX2-8     5.185931e+02       -0.826030  0.089665  -9.257448  2.093772e-20
NHLH1      1.867722e+03       -1.446074  0.224314  -6.812940  9.562434e-12
REEP1      1.652792e+05        2.649016  0.101945  14.824149  1.022683e-49

                   padj
MLYCD      2.908858e-01
RPL26      3.357502e-01
FASTKD5    5.447580e-01
ADCY10     5.479270e-05
UPK2       4.984787e-01
...                 ...
RPS15AP14  9.296223e-01
POMT2      3.998634e-02
NKX2-8     1.561722e-19
NHLH1      4.800457e-11
REEP1      2.743651e-48

[4990 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R5.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R5.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R5.csv
============================================================
[INFO] (137/160) sim_S60_G5000_CNstrong_R6.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=6
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.19 seconds.

Fitting dispersion trend curve...
... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 1.56 seconds.

Fitting LFCs...
... done in 0.77 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 154 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.12 seconds.

Fitting LFCs...
... done in 0.23 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.33 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SYCP2L        4927.750915       -2.398992  0.316179 -7.848972  4.194627e-15
RNA5SP187      209.665381        0.099397  0.446278  0.285610  7.751769e-01
PRR13       503386.261668       -0.148145  0.136092 -1.329927  1.835422e-01
SLC44A3      49124.290572       -0.025320  0.251726 -0.141266  8.876599e-01
CCDC92      333153.426243       -0.022811  0.159403 -0.306718  7.590577e-01
...                   ...             ...       ...       ...           ...
MTSS1       348599.860246        0.744786  0.500974  1.865572  6.210125e-02
GRHL2       349474.169629        0.038243  0.153043  0.087088  9.306016e-01
SHC2        178339.796773       -0.293771  0.447717 -0.840671  4.005320e-01
ZNF829       76402.442425        0.703985  0.705597  1.587602  1.123764e-01
RNU6-1330P     397.190164       -0.636767  0.212091 -3.162130  1.566194e-03

                    padj
SYCP2L      2.839483e-14
RNA5SP187   8.859926e-01
PRR13       3.460665e-01
SLC44A3     9.448478e-01
CCDC92      8.782326e-01
...                  ...
MTSS1       1.439030e-01
GRHL2       9.676472e-01
SHC2        6.006175e-01
ZNF829      2.362604e-01
RNU6-1330P  4.874450e-03

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.56 seconds.

Fitting dispersion trend curve...
... done in 0.15 seconds.

Fitting MAP dispersions...
... done in 2.13 seconds.

Fitting LFCs...
... done in 1.37 seconds.

Calculating cook's distance...
... done in 0.10 seconds.

Replacing 153 outlier genes.

replace_mask before filtering: (120, 153)
Number of True values in replace_mask: 250
replacement_counts_trimmed shape: (104, 153)

Fitting dispersions...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 0.20 seconds.

Fitting LFCs...
... done in 0.14 seconds.

Running Wald tests...
... done in 0.45 seconds.

Fitting MAP LFCs...
... done in 1.50 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SYCP2L        4927.750915       -2.711777  0.317018 -8.931604  4.198753e-19
RNA5SP187      209.665381        0.098544  0.445727  0.285591  7.751917e-01
PRR13       503386.261668        1.775724  0.097675 -1.329927  1.835423e-01
SLC44A3      49124.290572        1.321449  0.255432 -0.141266  8.876600e-01
CCDC92      333153.426243        1.754607  0.115827 -0.306718  7.590578e-01
...                   ...             ...       ...       ...           ...
MTSS1       348599.860246        1.629237  0.209658 -0.429070  6.678720e-01
GRHL2       349474.169629        0.873170  0.119382 -7.138459  9.438331e-13
SHC2        178339.796773        1.354236  0.394488 -0.840671  4.005320e-01
ZNF829       76402.442425        1.736048  0.412177  0.122907  9.021804e-01
RNU6-1330P     397.190164       -0.619245  0.211879 -3.161528  1.569438e-03

                    padj
SYCP2L      3.232651e-18
RNA5SP187   8.849957e-01
PRR13       3.467220e-01
SLC44A3     9.466649e-01
CCDC92      8.770124e-01
...                  ...
MTSS1       8.219942e-01
GRHL2       5.157485e-12
SHC2        6.037022e-01
ZNF829      9.537991e-01
RNU6-1330P  4.589641e-03

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R6.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R6.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R6.csv
============================================================
[INFO] (138/160) sim_S60_G5000_CNstrong_R7.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=7
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.62 seconds.

Fitting dispersion trend curve...
... done in 0.16 seconds.

Fitting MAP dispersions...
... done in 1.91 seconds.

Fitting LFCs...
... done in 1.87 seconds.

Calculating cook's distance...
... done in 0.13 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 130 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 0.14 seconds.

Fitting LFCs...
... done in 0.15 seconds.

Running Wald tests...
... done in 0.41 seconds.

Fitting MAP LFCs...
... done in 1.66 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat         pvalue  \
LINC01908      73.643482       -0.213504  0.625082  -0.563370   5.731827e-01
PCSK6      183412.599446        0.064537  0.337176   0.259514   7.952388e-01
NRF1       273786.832707        1.834066  0.062930  29.629641  6.205400e-193
EFCAB11     37198.826334       -0.192299  0.189461  -1.083958   2.783834e-01
VANGL1     186969.697568       -0.237295  0.267279  -1.015612   3.098140e-01
...                  ...             ...       ...        ...            ...
RCN1       519265.864068        0.738766  0.842862   0.399920   6.892156e-01
UBE2D1     102746.287643       -0.376022  0.569128  -0.972787   3.306591e-01
ZNF512     173119.904013       -0.532488  0.278998  -2.160863   3.070595e-02
PRR22       17377.297875       -0.012124  0.105754  -0.126638   8.992268e-01
CACNA1G     35157.307710        1.377573  0.132927  10.475902   1.114703e-25

                    padj
LINC01908   7.494657e-01
PCSK6       8.932108e-01
NRF1       6.189266e-190
EFCAB11     4.688612e-01
VANGL1      5.069643e-01
...                  ...
RCN1        8.303990e-01
UBE2D1      5.295430e-01
ZNF512      7.718275e-02
PRR22       9.500809e-01
CACNA1G     1.148559e-24

[4987 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.30 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.95 seconds.

Fitting LFCs...
... done in 1.09 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 128 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 128)
Number of True values in replace_mask: 198
replacement_counts_trimmed shape: (98, 128)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.15 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat         pvalue  \
LINC01908      73.643482       -0.213688  0.624330  -0.563364   5.731871e-01
PCSK6      183412.599446        1.638562  0.286226   0.259515   7.952382e-01
NRF1       273786.832707        3.621575  0.077256  22.887199  6.231714e-116
EFCAB11     37198.826334        0.935502  0.202484  -1.083956   2.783845e-01
VANGL1     186969.697568        1.383510  0.237152  -1.015612   3.098141e-01
...                  ...             ...       ...        ...            ...
RCN1       258204.059589        2.130159  0.101104  -0.494036   6.212808e-01
UBE2D1     102746.287643        1.260566  0.495750  -0.972788   3.306588e-01
ZNF512     173119.904013        1.087094  0.219686  -3.550605   3.843470e-04
PRR22       17377.297875       -0.094739  0.104406  -0.126636   8.992285e-01
CACNA1G     35157.307710        1.155459  0.137548   0.950143   3.420396e-01

                    padj
LINC01908   7.516393e-01
PCSK6       8.962379e-01
NRF1       1.553878e-113
EFCAB11     4.696562e-01
VANGL1      5.081353e-01
...                  ...
RCN1        7.863776e-01
UBE2D1      5.315911e-01
ZNF512      1.189782e-03
PRR22       9.537173e-01
CACNA1G     5.454914e-01

[4987 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R7.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R7.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R7.csv
============================================================
[INFO] (139/160) sim_S60_G5000_CNstrong_R8.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=8
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.10 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.59 seconds.

Fitting LFCs...
... done in 0.84 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 153 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.38 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
ZNF542P     229866.835363        2.010194  0.152810  13.213808  7.303385e-40
RFX7        136605.445132        0.146845  0.121483   1.183550  2.365911e-01
GEMIN7-AS1   13706.735695       -2.046084  0.155117 -13.333378  1.480388e-40
MIR6774        216.006853        0.100064  0.418076   0.298974  7.649598e-01
RMDN1       210576.380740       -0.248430  0.145079  -1.813146  6.980923e-02
...                   ...             ...       ...        ...           ...
LCNL1         8118.340735        0.094945  0.204590   0.497684  6.187067e-01
ENDOD1      388571.348524       -0.258738  0.644891  -0.686304  4.925211e-01
ZNF335      261538.341067        0.057866  0.389518   0.128544  8.977187e-01
PGF          81619.011709       -0.093245  0.265367  -0.402356  6.874218e-01
PKNOX2       12249.701861        0.024089  0.313640   0.087912  9.299463e-01

                    padj
ZNF542P     1.538025e-38
RFX7        4.236907e-01
GEMIN7-AS1  3.198535e-39
MIR6774     8.866498e-01
RMDN1       1.578443e-01
...                  ...
LCNL1       7.846912e-01
ENDOD1      6.907771e-01
ZNF335      9.508731e-01
PGF         8.348501e-01
PKNOX2      9.647872e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.17 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.51 seconds.

Fitting LFCs...
... done in 0.98 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 154 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 154)
Number of True values in replace_mask: 255
replacement_counts_trimmed shape: (106, 154)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.81 seconds.

Fitting MAP LFCs...
... done in 0.96 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat         pvalue  \
ZNF542P     229866.835363        2.751179  0.113522  10.238876   1.327700e-24
RFX7        136605.445132        1.568239  0.126371   1.183549   2.365918e-01
GEMIN7-AS1   13706.735695       -2.325738  0.155999 -15.686116   1.882271e-55
MIR6774        216.006853        0.099383  0.417759   0.298953   7.649761e-01
RMDN1       210576.380740        7.145335  0.243147  21.811961  1.786542e-105
...                   ...             ...       ...        ...            ...
LCNL1         8118.340735        0.110692  0.205526   0.497680   6.187099e-01
ENDOD1      388571.348524        1.495321  0.353916  -0.686266   4.925453e-01
ZNF335      261538.341067        1.106364  0.278096  -2.573580   1.006524e-02
PGF          81619.011709        1.451955  0.242376  -0.402356   6.874220e-01
PKNOX2       12249.701861        0.073529  0.317491   0.087912   9.299465e-01

                     padj
ZNF542P      1.409905e-23
RFX7         4.258311e-01
GEMIN7-AS1   6.523898e-54
MIR6774      8.874932e-01
RMDN1       3.184512e-103
...                   ...
LCNL1        7.833026e-01
ENDOD1       6.896160e-01
ZNF335       2.721322e-02
PGF          8.331527e-01
PKNOX2       9.659920e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R8.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R8.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R8.csv
============================================================
[INFO] (140/160) sim_S60_G5000_CNstrong_R9.pkl
[INFO] Running analysis for S=60, G=5000, CN=strong, R=9
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.05 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.53 seconds.

Fitting LFCs...
... done in 0.79 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 155 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.53 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
VN1R81P      1.606700e+03       -0.897742  0.181334  -5.117310  3.099232e-07
MIR7844      2.016349e+03       -1.818952  0.298712  -6.376845  1.807736e-10
CFAP69       4.810426e+04       -2.663674  0.228675 -11.830159  2.726253e-32
BCAR3        1.962607e+05       -0.090121  0.204557  -0.546500  5.847222e-01
CEP57        2.161497e+05       -0.151442  0.117815  -1.366241  1.718634e-01
...                   ...             ...       ...        ...           ...
ARPC4-TTLL3  1.140151e+06        1.733263  0.123323  14.124174  2.695414e-45
SRGAP3-AS4   1.220978e+02       -1.461830  0.246792  -6.168020  6.915031e-10
GPR45        2.453039e+02        0.848836  0.671367   1.874287  6.089082e-02
SULT4A1      9.919463e+03        0.300859  0.296070   1.139261  2.545944e-01
GTSE1-DT     2.703005e+03        0.011354  0.103686   0.109684  9.126598e-01

                     padj
VN1R81P      1.259900e-06
MIR7844      9.117278e-10
CFAP69       3.655524e-31
BCAR3        7.563835e-01
CEP57        3.293333e-01
...                   ...
ARPC4-TTLL3  5.649044e-44
SRGAP3-AS4   3.391561e-09
GPR45        1.413982e-01
SULT4A1      4.428190e-01
GTSE1-DT     9.601952e-01

[4988 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.09 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.61 seconds.

Fitting LFCs...
... done in 1.33 seconds.

Calculating cook's distance...
... done in 0.08 seconds.

Replacing 153 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 153)
Number of True values in replace_mask: 237
replacement_counts_trimmed shape: (104, 153)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.37 seconds.

Fitting MAP LFCs...
... done in 1.13 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
VN1R81P      1.606700e+03       -1.191617  0.181115  -6.585358  4.537898e-11
MIR7844      2.016349e+03       -2.053210  0.299572  -7.364428  1.779086e-13
CFAP69       4.810426e+04       -0.484227  0.297448 -13.579903  5.269585e-42
BCAR3        1.962607e+05        1.460677  0.191288  -0.546500  5.847223e-01
CEP57        2.161497e+05        1.536397  0.120671  -1.366239  1.718638e-01
...                   ...             ...       ...        ...           ...
ARPC4-TTLL3  1.140151e+06        2.902837  0.059782  11.637351  2.661546e-31
SRGAP3-AS4   1.220978e+02       -1.676564  0.246955  -7.017747  2.254742e-12
GPR45        2.453039e+02        0.860130  0.672405   1.874223  6.089969e-02
SULT4A1      9.919463e+03        0.259597  0.294551   1.139257  2.545960e-01
GTSE1-DT     2.703005e+03        0.007261  0.103822   0.109672  9.126695e-01

                     padj
VN1R81P      2.195445e-10
MIR7844      9.849144e-13
CFAP69       9.994179e-41
BCAR3        7.577540e-01
CEP57        3.306043e-01
...                   ...
ARPC4-TTLL3  3.286087e-30
SRGAP3-AS4   1.171526e-11
GPR45        1.385801e-01
SULT4A1      4.459007e-01
GTSE1-DT     9.566313e-01

[4988 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNstrong_R9.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNstrong_R9.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNstrong_R9.csv
============================================================
[INFO] (141/160) sim_S60_G5000_CNweak_R1.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=1
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.15 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.50 seconds.

Fitting LFCs...
... done in 0.78 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 165 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.36 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat         pvalue  \
JMJD6       2.174799e+05        0.672970  0.137161   4.882076   1.049748e-06
PLA2G12AP1  4.262766e+03       -0.148611  0.129314  -1.180485   2.378073e-01
VEGFA       3.503865e+06        1.998870  0.350558   5.151357   2.586084e-07
RHO         9.778839e+02        2.314110  0.618377   4.254295   2.097086e-05
TK1         2.183793e+05       -0.388412  0.394410  -1.160674   2.457746e-01
...                  ...             ...       ...        ...            ...
SCN9A       1.341730e+04        0.348723  0.257525   1.473833   1.405264e-01
BCL2L2      5.332405e+05        0.378519  0.426946   1.069252   2.849559e-01
NADSYN1     5.549548e+05        0.670948  0.107716   6.260484   3.837843e-10
CUL7        1.159111e+06        2.753550  0.112304  24.489577  1.907571e-132
POGK        4.810154e+05       -0.590196  0.266038  -2.399345   1.642441e-02

                     padj
JMJD6        4.682118e-06
PLA2G12AP1   4.106907e-01
VEGFA        1.219957e-06
RHO          8.189796e-05
TK1          4.215127e-01
...                   ...
SCN9A        2.767828e-01
BCL2L2       4.706562e-01
NADSYN1      2.201687e-09
CUL7        3.966953e-130
POGK         4.419097e-02

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.97 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.53 seconds.

Fitting LFCs...
... done in 0.99 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 165 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 165)
Number of True values in replace_mask: 267
replacement_counts_trimmed shape: (109, 165)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.11 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat         pvalue  \
JMJD6       2.174799e+05        1.441067  0.119222  -0.671115   5.021472e-01
PLA2G12AP1  4.262766e+03       -0.131465  0.129425  -1.180429   2.378295e-01
VEGFA       3.503865e+06        2.778125  0.074900   4.347715   1.375632e-05
RHO         9.778839e+02        1.997197  0.616144   3.794789   1.477690e-04
TK1         2.183793e+05        1.827284  0.355940   0.939937   3.472498e-01
...                  ...             ...       ...        ...            ...
SCN9A       1.341730e+04        0.426546  0.261540   1.473827   1.405281e-01
BCL2L2      5.332405e+05        1.921010  0.175958   0.520263   6.028801e-01
NADSYN1     5.549548e+05        1.703001  0.083445  -0.459472   6.458951e-01
CUL7        1.159111e+06        3.628719  0.056657  21.234367  4.598454e-100
POGK        4.810154e+05        0.975320  0.153258  -5.382575   7.342791e-08

                    padj
JMJD6       6.952635e-01
PLA2G12AP1  4.194372e-01
VEGFA       4.950093e-05
RHO         4.826669e-04
TK1         5.512031e-01
...                  ...
SCN9A       2.807749e-01
BCL2L2      7.719279e-01
NADSYN1     8.025050e-01
CUL7        5.100196e-98
POGK        3.116315e-07

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R1.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R1.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R1.csv
============================================================
[INFO] (142/160) sim_S60_G5000_CNweak_R10.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=10
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.04 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.50 seconds.

Fitting LFCs...
... done in 0.73 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 157 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.29 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
CCL18     32545.490670        0.084943  0.429791  0.248944  8.034043e-01
TMPRSS3  104780.161236       -1.076692  0.605648 -2.401424  1.633140e-02
NPC2     901776.626296        0.148411  0.164183  1.075986  2.819334e-01
GZMH       9198.287318        0.102731  0.336740  0.354446  7.230047e-01
OTOGL      3620.521679       -1.979160  0.315401 -6.570984  4.998395e-11
...                ...             ...       ...       ...           ...
CCDC196    1238.695788        0.245467  0.471192  0.699799  4.840530e-01
PBOV1       206.333687       -0.784101  0.144400 -5.558960  2.713873e-08
CDHR2      2726.490847        0.932019  0.791135  1.950342  5.113534e-02
FAM215A     232.383037       -0.045297  0.185495 -0.256796  7.973361e-01
POLD3     70085.657833       -0.900483  0.846697 -1.929213  5.370443e-02

                 padj
CCL18    8.997336e-01
TMPRSS3  4.454585e-02
NPC2     4.740314e-01
GZMH     8.527864e-01
OTOGL    3.133874e-10
...               ...
CCDC196  6.842469e-01
PBOV1    1.411875e-07
CDHR2    1.227589e-01
FAM215A  8.965545e-01
POLD3    1.278457e-01

[4997 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.04 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.49 seconds.

Fitting LFCs...
... done in 0.97 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 156 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 156)
Number of True values in replace_mask: 234
replacement_counts_trimmed shape: (104, 156)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.10 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
CCL18     32545.490670        1.350971  0.465913  0.248944  8.034044e-01
TMPRSS3  104780.161236        0.701930  0.515593 -3.070826  2.134675e-03
NPC2     901776.626296        1.944489  0.103180  1.075986  2.819335e-01
GZMH       9198.287318        0.009417  0.334374  0.354445  7.230054e-01
OTOGL      3620.521679       -2.233820  0.315613 -7.516402  5.630407e-14
...                ...             ...       ...       ...           ...
CCDC196    1238.695788        0.210239  0.470692  0.699792  4.840574e-01
PBOV1       206.333687       -1.150945  0.144709 -8.079169  6.520979e-16
CDHR2      2726.490847        0.642448  0.735852  1.736818  8.241925e-02
FAM215A     232.383037       -0.045504  0.185603 -0.256695  7.974142e-01
POLD3     70085.657833        0.706062  0.635062 -2.308775  2.095606e-02

                 padj
CCL18    9.082833e-01
TMPRSS3  6.300632e-03
NPC2     4.829722e-01
GZMH     8.590718e-01
OTOGL    3.588666e-13
...               ...
CCDC196  6.968697e-01
PBOV1    4.635182e-15
CDHR2    1.839433e-01
FAM215A  9.047399e-01
POLD3    5.408958e-02

[4997 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R10.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R10.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R10.csv
============================================================
[INFO] (143/160) sim_S60_G5000_CNweak_R11.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=11
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.04 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.79 seconds.

Fitting LFCs...
... done in 1.69 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 157 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.49 seconds.

Fitting MAP LFCs...
... done in 1.80 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE       stat        pvalue  \
OSGEPL1-AS1    2326.445751        0.224351  0.132376   1.737422  8.231272e-02
CPLANE1      177858.709230        0.332786  0.144527   2.321562  2.025653e-02
NPEPL1       377183.717342       -0.329563  0.299230  -1.254718  2.095812e-01
ZNF467       317331.526374        2.029324  0.256864   8.145448  3.778804e-16
ABHD17A      333306.114815       -0.008714  0.186195   0.021637  9.827376e-01
...                    ...             ...       ...        ...           ...
TGDS          66432.679915        0.069421  0.175187   0.378963  7.047151e-01
NPAP1           241.708063       -0.186158  0.349209  -0.626197  5.311858e-01
NOD1         245923.889266        0.455289  0.281080   1.723232  8.484654e-02
NT5C1B         5467.118748        1.675301  0.151287  11.217689  3.338827e-29
NHP2P2          651.244547        0.483320  0.129401   3.811077  1.383629e-04

                     padj
OSGEPL1-AS1  1.833212e-01
CPLANE1      5.383404e-02
NPEPL1       3.864128e-01
ZNF467       2.866263e-15
ABHD17A      9.938892e-01
...                   ...
TGDS         8.414434e-01
NPAP1        7.155037e-01
NOD1         1.883759e-01
NT5C1B       4.084335e-28
NHP2P2       4.984885e-04

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.50 seconds.

Fitting dispersion trend curve...
... done in 0.23 seconds.

Fitting MAP dispersions...
... done in 1.89 seconds.

Fitting LFCs...
... done in 1.31 seconds.

Calculating cook's distance...
... done in 0.08 seconds.

Replacing 155 outlier genes.

replace_mask before filtering: (120, 155)
Number of True values in replace_mask: 243
replacement_counts_trimmed shape: (96, 155)

Fitting dispersions...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 0.21 seconds.

Fitting LFCs...
... done in 0.12 seconds.

Running Wald tests...
... done in 0.42 seconds.

Fitting MAP LFCs...
... done in 1.51 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat        pvalue  \
OSGEPL1-AS1    2326.445751        0.191401  0.131984  1.737285  8.233695e-02
CPLANE1      177858.709230        1.338167  0.132268 -1.628833  1.033483e-01
NPEPL1       377183.717342        1.071036  0.183575 -4.029395  5.592049e-05
ZNF467       317331.526374        2.890101  0.135253  6.692306  2.196803e-11
ABHD17A      333306.114815        1.645921  0.153516  0.021637  9.827376e-01
...                    ...             ...       ...       ...           ...
TGDS          66432.679915        1.389874  0.179435  0.378963  7.047156e-01
NPAP1           241.708063       -0.181336  0.349271 -0.626134  5.312267e-01
NOD1         245923.889266        1.545266  0.184456 -0.621828  5.340553e-01
NT5C1B         5467.118748        1.423614  0.151019  9.671588  3.981502e-22
NHP2P2          651.244547       -0.156803  0.129094 -1.294869  1.953653e-01

                     padj
OSGEPL1-AS1  1.815122e-01
CPLANE1      2.206207e-01
NPEPL1       1.869385e-04
ZNF467       1.138551e-10
ABHD17A      9.928832e-01
...                   ...
TGDS         8.418467e-01
NPAP1        7.200849e-01
NOD1         7.219583e-01
NT5C1B       3.639501e-21
NHP2P2       3.703260e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R11.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R11.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R11.csv
============================================================
[INFO] (144/160) sim_S60_G5000_CNweak_R12.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=12
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.45 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 2.05 seconds.

Fitting LFCs...
... done in 1.14 seconds.

Calculating cook's distance...
... done in 0.10 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 155 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 0.31 seconds.

Fitting LFCs...
... done in 0.30 seconds.

Running Wald tests...
... done in 0.39 seconds.

Fitting MAP LFCs...
... done in 1.42 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
PCGF1     68386.320921       -0.477798  0.118910 -4.084697  0.000044  0.000166
NPAS3     11697.690633       -1.011366  0.255981 -4.238964  0.000022  0.000088
USP8     294541.965726        0.033191  0.082848  0.239421  0.810779  0.897825
YRDC     110687.772926        0.202695  0.161058  1.297628  0.194415  0.360437
OSR2     148097.499382        0.015403  0.277295 -0.009321  0.992563  0.994831
...                ...             ...       ...       ...       ...       ...
SLC10A7   56483.328288        0.121746  0.179783  0.680216  0.496368  0.682198
MYOM1     55754.547711        0.369270  0.486211  1.009523  0.312724  0.510554
ZNF644   261459.285871       -0.183901  0.140436 -1.460279  0.144213  0.286532
FABP9       477.736758       -0.364539  0.290171 -1.409710  0.158625  0.309860
DCAF1    400932.202157        0.675332  0.563222  1.597618  0.110128  0.229983

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.21 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.63 seconds.

Fitting LFCs...
... done in 1.02 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 153 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 153)
Number of True values in replace_mask: 252
replacement_counts_trimmed shape: (106, 153)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.36 seconds.

Fitting MAP LFCs...
... done in 1.58 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat        pvalue  \
PCGF1     68386.320921        0.826833  0.128801 -6.246123  4.207646e-10
NPAS3     11697.690633       -0.852895  0.268150 -5.282038  1.277544e-07
USP8     294541.965726        2.327160  0.090276  0.236262  8.132291e-01
YRDC     110687.772926        1.659452  0.154482  1.297628  1.944153e-01
OSR2     148097.499382        2.250422  0.239303  3.026993  2.469997e-03
...                ...             ...       ...       ...           ...
SLC10A7   56483.328288        1.376299  0.186138  0.680215  4.963684e-01
MYOM1     55754.547711        1.824935  0.455585  1.009528  3.127215e-01
ZNF644   261459.285871        1.613949  0.121942 -1.460278  1.442137e-01
FABP9       477.736758       -1.154582  0.298595 -4.134643  3.555069e-05
DCAF1    400932.202157        2.356215  0.229365  1.597581  1.101362e-01

                 padj
PCGF1    2.101296e-09
NPAS3    5.466267e-07
USP8     9.036080e-01
YRDC     3.636813e-01
OSR2     7.045634e-03
...               ...
SLC10A7  6.894158e-01
MYOM1    5.140868e-01
ZNF644   2.892972e-01
FABP9    1.213980e-04
DCAF1    2.328261e-01

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R12.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R12.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R12.csv
============================================================
[INFO] (145/160) sim_S60_G5000_CNweak_R13.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=13
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.13 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.55 seconds.

Fitting LFCs...
... done in 0.75 seconds.

Calculating cook's distance...
... done in 0.08 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 149 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.25 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
EPDR1       75512.655103       -0.696626  0.231779  -3.206029  1.345806e-03
INTS12     125639.616951        0.137031  0.088254   1.523199  1.277089e-01
LINC00943     522.211194       -0.056801  0.430751  -0.174948  8.611204e-01
PCDH9       39010.501438        0.292832  0.379933   0.971070  3.315133e-01
LRGUK       17292.212009        1.935876  0.302003   6.682563  2.347994e-11
...                  ...             ...       ...        ...           ...
MIR155HG     5263.051849       -0.498971  0.119932  -4.243058  2.204942e-05
TNFAIP3    220731.025865       -1.160742  0.148129  -8.061804  7.517682e-16
CRYBG3     203692.173303       -2.065096  0.109533 -19.077758  3.864822e-81
ATXN3      204217.657535       -0.043208  0.316416  -0.097385  9.224210e-01
NCR1          503.669246       -1.032983  0.111315  -9.387745  6.129875e-21

                   padj
EPDR1      4.452957e-03
INTS12     2.569131e-01
LINC00943  9.281772e-01
PCDH9      5.255905e-01
LRGUK      1.490453e-10
...                 ...
MIR155HG   8.768738e-05
TNFAIP3    6.212373e-15
CRYBG3     2.638138e-79
ATXN3      9.603894e-01
NCR1       6.390202e-20

[4983 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.15 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.53 seconds.

Fitting LFCs...
... done in 1.01 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 152 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 152)
Number of True values in replace_mask: 241
replacement_counts_trimmed shape: (98, 152)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.17 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat         pvalue  \
EPDR1       75512.655103        0.650955  0.233846  -5.155287   2.532429e-07
INTS12     125639.616951        2.050931  0.097838   1.523194   1.277102e-01
LINC00943     522.211194       -0.055346  0.432501  -0.174944   8.611238e-01
PCDH9       39010.501438        1.607030  0.383175   0.971070   3.315136e-01
LRGUK       17292.212009        2.581396  0.290435   5.808794   6.292449e-09
...                  ...             ...       ...        ...            ...
MIR155HG     5263.051849       -0.751422  0.120255  -6.623432   3.509533e-11
TNFAIP3    220731.025865        0.730989  0.143519  -9.872748   5.464658e-23
CRYBG3     203692.173303        0.265486  0.129391 -22.023577  1.712026e-107
ATXN3      204217.657535        1.583408  0.265586  -0.097385   9.224210e-01
NCR1          503.669246       -1.506891  0.111393 -13.614679   3.275825e-42

                    padj
EPDR1       1.035200e-06
INTS12      2.578525e-01
LINC00943   9.299913e-01
PCDH9       5.346059e-01
LRGUK       2.876630e-08
...                  ...
MIR155HG    1.891122e-10
TNFAIP3     5.568587e-22
CRYBG3     3.046794e-105
ATXN3       9.601888e-01
NCR1        7.487814e-41

[4983 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R13.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R13.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R13.csv
============================================================
[INFO] (146/160) sim_S60_G5000_CNweak_R14.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=14
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.11 seconds.

Fitting dispersion trend curve...
... done in 0.22 seconds.

Fitting MAP dispersions...
... done in 1.57 seconds.

Fitting LFCs...
... done in 1.08 seconds.

Calculating cook's distance...
... done in 0.09 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 156 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.36 seconds.

Fitting MAP LFCs...
... done in 1.78 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
MIA3       5.519146e+05       -0.272897  0.168550 -1.792519  7.304990e-02
CTNNB1     2.413440e+06        0.132738  0.146564  1.158328  2.467304e-01
DDX10      1.738178e+05       -0.136333  0.131805 -1.035040  3.006500e-01
RNU6-322P  3.983295e+02       -0.144470  0.314444 -0.527617  5.977653e-01
RN7SL130P  6.648922e+02        0.065998  0.304940  0.242967  8.080309e-01
...                 ...             ...       ...       ...           ...
GPR137     2.105422e+05       -0.751705  0.215921 -3.772923  1.613464e-04
DDX52      1.198433e+05       -1.586602  0.166773 -9.850370  6.829230e-23
TOR1AIP1   3.648629e+05       -0.517233  0.146080 -3.732751  1.894001e-04
ACTBP11    1.186513e+04       -0.619908  0.101185 -6.215213  5.125510e-10
RPS3AP49   9.438919e+03       -0.429081  0.314427 -1.559703  1.188302e-01

                   padj
MIA3       1.634692e-01
CTNNB1     4.270268e-01
DDX10      4.902394e-01
RNU6-322P  7.601297e-01
RN7SL130P  8.905121e-01
...                 ...
GPR137     5.752651e-04
DDX52      7.067261e-22
TOR1AIP1   6.681242e-04
ACTBP11    2.872589e-09
RPS3AP49   2.444226e-01

[4988 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.03 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.02 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.72 seconds.

Fitting LFCs...
... done in 1.05 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 154 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 154)
Number of True values in replace_mask: 241
replacement_counts_trimmed shape: (97, 154)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.35 seconds.

Fitting MAP LFCs...
... done in 1.09 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
MIA3       5.519146e+05        1.022021  0.105630  -6.490652  8.546580e-11
CTNNB1     2.413440e+06        2.047973  0.066661   1.158327  2.467304e-01
DDX10      1.738178e+05        1.496044  0.130423  -1.035039  3.006506e-01
RNU6-322P  3.983295e+02       -0.406249  0.319352  -1.405648  1.598288e-01
RN7SL130P  6.648922e+02        0.049856  0.305642   0.242955  8.080399e-01
...                 ...             ...       ...        ...           ...
GPR137     2.105422e+05        0.962909  0.175123  -5.689508  1.274060e-08
DDX52      1.198433e+05        0.398473  0.183167 -11.310981  1.157878e-29
TOR1AIP1   3.648629e+05        0.835828  0.117580  -8.763188  1.898042e-18
ACTBP11    1.186513e+04       -1.211269  0.103317 -13.265355  3.676742e-40
RPS3AP49   9.438919e+03       -0.491873  0.311163  -1.559696  1.188317e-01

                   padj
MIA3       4.237608e-10
CTNNB1     4.297107e-01
DDX10      4.939542e-01
RNU6-322P  3.091221e-01
RN7SL130P  8.909158e-01
...                 ...
GPR137     5.445597e-08
DDX52      1.556737e-28
TOR1AIP1   1.472384e-17
ACTBP11    7.424934e-39
RPS3AP49   2.441239e-01

[4988 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R14.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R14.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R14.csv
============================================================
[INFO] (147/160) sim_S60_G5000_CNweak_R15.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=15
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.99 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.58 seconds.

Fitting LFCs...
... done in 0.78 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 167 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.31 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
BBIP1       302345.346954        0.161241  0.201779   0.939974  3.472307e-01
DMWD        367185.036519        1.239161  0.120740  10.460199  1.315792e-25
TMEM163      14301.825969       -0.009777  0.269583  -0.046686  9.627635e-01
RPTOR       293119.248250        0.697044  0.144512   4.895334  9.813912e-07
CRYGS        37320.333590        0.896917  0.164276   5.576555  2.453278e-08
...                   ...             ...       ...        ...           ...
VWA8        177693.558122       -0.328501  0.229809  -1.609112  1.075919e-01
FGB          25995.379373       -0.178414  0.385229  -0.571862  5.674157e-01
THAP6        73908.555491       -0.863081  0.370138  -2.731710  6.300658e-03
HNRNPA3P13     821.468661        0.015511  0.565930   0.036707  9.707189e-01
GUSBP5        3974.428685        0.195033  0.161597   1.248636  2.117983e-01

                    padj
BBIP1       5.412026e-01
DMWD        1.570451e-24
TMEM163     9.809176e-01
RPTOR       4.287356e-06
CRYGS       1.230091e-07
...                  ...
VWA8        2.219000e-01
FGB         7.421669e-01
THAP6       1.797672e-02
HNRNPA3P13  9.856335e-01
GUSBP5      3.802310e-01

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.09 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.49 seconds.

Fitting LFCs...
... done in 1.01 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 165 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 165)
Number of True values in replace_mask: 239
replacement_counts_trimmed shape: (102, 165)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.09 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
BBIP1       302345.346954        1.772176  0.164690  0.939974  3.472309e-01
DMWD        367185.036519        2.345027  0.093754  7.214374  5.418283e-13
TMEM163      14301.825969        0.086483  0.274327 -0.046686  9.627636e-01
RPTOR       293119.248250        1.677648  0.112439  0.592305  5.536467e-01
CRYGS        37320.333590        1.417311  0.163788  1.358862  1.741903e-01
...                   ...             ...       ...       ...           ...
VWA8        177693.558122        1.281938  0.214979 -1.609111  1.075920e-01
FGB          25995.379373        0.986738  0.421787 -0.571862  5.674153e-01
THAP6        73908.555491        0.724753  0.358134 -3.760779  1.693852e-04
HNRNPA3P13     821.468661       -0.036557  0.568495  0.036699  9.707250e-01
GUSBP5        3974.428685        0.214660  0.161635  1.248597  2.118124e-01

                    padj
BBIP1       5.497730e-01
DMWD        3.099979e-12
TMEM163     9.814744e-01
RPTOR       7.393179e-01
CRYGS       3.316844e-01
...                  ...
VWA8        2.247808e-01
FGB         7.500310e-01
THAP6       5.278342e-04
HNRNPA3P13  9.860349e-01
GUSBP5      3.880764e-01

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R15.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R15.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R15.csv
============================================================
[INFO] (148/160) sim_S60_G5000_CNweak_R16.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=16
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.51 seconds.

Fitting LFCs...
... done in 1.19 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 155 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.09 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
TMEM167A   470020.397125        0.007225  0.128259  -0.017748  9.858397e-01
LINC02021    3261.604822       -0.969374  0.224016  -4.543686  5.527905e-06
FAAP100    188207.083313       -0.800387  0.118214  -6.925577  4.342013e-12
MYOM2       20073.031020        0.286719  0.322595   1.034859  3.007347e-01
FOXN3-AS1    9931.511735       -0.213952  0.232852  -1.005252  3.147757e-01
...                  ...             ...       ...        ...           ...
IPO8P1      14333.801099        0.127883  0.150149   0.885300  3.759948e-01
ATP6V1B1   259808.701320        2.144392  0.570460   4.228829  2.349112e-05
KCNH3        6175.388727       -1.379594  0.116465 -11.970998  5.041878e-33
KRTAP1-5      200.633608       -0.348979  0.159352  -2.267222  2.337665e-02
AGA        104554.704628       -0.039100  0.114406  -0.431956  6.657733e-01

                   padj
TMEM167A   9.917848e-01
LINC02021  2.365242e-05
FAAP100    2.854058e-11
MYOM2      4.933218e-01
FOXN3-AS1  5.095444e-01
...                 ...
IPO8P1     5.746833e-01
ATP6V1B1   9.330986e-05
KCNH3      8.010806e-32
KRTAP1-5   6.014756e-02
AGA        8.107976e-01

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.01 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.49 seconds.

Fitting LFCs...
... done in 0.95 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 154 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 154)
Number of True values in replace_mask: 265
replacement_counts_trimmed shape: (105, 154)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
... done in 1.06 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
TMEM167A   470020.397125        1.897389  0.100403  -0.017748  9.858397e-01
LINC02021    3261.604822       -1.372610  0.224351  -6.457749  1.062717e-10
FAAP100    188207.083313        2.302167  0.129324   0.457480  6.473264e-01
MYOM2       20073.031020        1.282428  0.348139   1.034858  3.007354e-01
FOXN3-AS1    9931.511735        0.046912  0.239867  -1.005246  3.147785e-01
...                  ...             ...       ...        ...           ...
IPO8P1      14333.801099        0.979051  0.151238   6.651691  2.897437e-11
ATP6V1B1   259808.701320        3.014208  0.285019   3.410403  6.486691e-04
KCNH3        6175.388727       -1.709692  0.116604 -15.220295  2.593591e-52
KRTAP1-5      200.633608       -0.599592  0.160059  -3.857673  1.144717e-04
AGA        104554.704628        1.594419  0.118748  -0.431955  6.657740e-01

                   padj
TMEM167A   9.934440e-01
LINC02021  5.339270e-10
FAAP100    8.048303e-01
MYOM2      5.012781e-01
FOXN3-AS1  5.162492e-01
...                 ...
IPO8P1     1.499514e-10
ATP6V1B1   1.972096e-03
KCNH3      7.938299e-51
KRTAP1-5   3.732675e-04
AGA        8.191237e-01

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R16.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R16.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R16.csv
============================================================
[INFO] (149/160) sim_S60_G5000_CNweak_R17.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=17
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.46 seconds.

Fitting LFCs...
... done in 0.72 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 160 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.20 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat        pvalue  \
DNAJB14  2.333134e+05        0.143740  0.095348  1.388302  1.650450e-01
GAL3ST3  1.118200e+02       -0.536868  0.715310 -1.306389  1.914203e-01
KCTD3    5.431910e+05       -0.246329  0.194350 -1.423712  1.545300e-01
SFRP2    1.799410e+06       -0.261190  0.342017 -0.815464  4.148069e-01
WDR1     1.700130e+06        0.243646  0.104102  2.719401  6.540033e-03
...               ...             ...       ...       ...           ...
TDG      1.450513e+05       -0.055511  0.279405 -0.284753  7.758334e-01
DBN1     5.363904e+05       -0.401024  0.121239 -3.166219  1.544344e-03
SIGLEC1  1.447382e+05       -0.534757  0.670530 -1.367697  1.714070e-01
ENGASE   3.930764e+05        0.686936  0.107064  6.421735  1.347295e-10
OR7E2P   3.573410e+02       -0.085286  0.184597 -0.486239  6.267978e-01

                 padj
DNAJB14  3.214001e-01
GAL3ST3  3.597146e-01
KCTD3    3.053465e-01
SFRP2    6.131234e-01
WDR1     1.886446e-02
...               ...
TDG      8.841164e-01
DBN1     4.825351e-03
SIGLEC1  3.302411e-01
ENGASE   7.688051e-10
OR7E2P   7.788654e-01

[4993 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.91 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 157 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 157)
Number of True values in replace_mask: 261
replacement_counts_trimmed shape: (102, 157)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.49 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 0.87 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat        pvalue  \
DNAJB14  2.333134e+05        2.036674  0.100599  1.388300  1.650457e-01
GAL3ST3  1.118200e+02       -0.797585  0.785604 -1.795329  7.260138e-02
KCTD3    5.431910e+05        1.103579  0.146317 -4.645425  3.393775e-06
SFRP2    1.799410e+06        1.680229  0.117393 -0.815480  4.147976e-01
WDR1     1.700130e+06        2.415012  0.063907  2.692498  7.091899e-03
...               ...             ...       ...       ...           ...
TDG      1.450513e+05        1.441468  0.260394 -0.285050  7.756055e-01
DBN1     5.363904e+05        1.391214  0.098207 -5.593681  2.223054e-08
SIGLEC1  1.447382e+05        1.519065  0.589444 -0.205026  8.375520e-01
ENGASE   3.930764e+05        1.612800  0.093671 -0.717007  4.733699e-01
OR7E2P   3.573410e+02       -0.077615  0.184636 -0.486113  6.268872e-01

                 padj
DNAJB14  3.230392e-01
GAL3ST3  1.641751e-01
KCTD3    1.249640e-05
SFRP2    6.176809e-01
WDR1     1.962852e-02
...               ...
TDG      8.851259e-01
DBN1     9.610137e-08
SIGLEC1  9.172838e-01
ENGASE   6.687990e-01
OR7E2P   7.815874e-01

[4993 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R17.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R17.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R17.csv
============================================================
[INFO] (150/160) sim_S60_G5000_CNweak_R18.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=18
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.97 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.70 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 158 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.17 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat         pvalue  \
LINC02766  8.247166e+02        0.179898  0.550681   0.477727   6.328443e-01
SLC25A48   1.611558e+04        0.158461  0.367484   0.505661   6.130943e-01
TYSND1     1.829953e+05        0.209893  0.138147   1.467646   1.422003e-01
RAD51D     1.005715e+05        0.018337  0.152449   0.023603   9.811689e-01
SIGLEC5    1.121263e+04       -0.214692  0.220032  -1.060922   2.887252e-01
...                 ...             ...       ...        ...            ...
ARLNC1     2.007710e+03        0.156521  0.516641   0.421860   6.731275e-01
CXCL9      2.196546e+05       -1.713022  0.585977  -3.511566   4.454754e-04
AP2A1      1.163543e+06        1.703821  0.308408   5.825900   5.680563e-09
RFC2       6.441489e+05        2.619854  0.110924  23.634841  1.690147e-123
QRICH1     4.825015e+05       -0.092920  0.248682  -0.342928   7.316524e-01

                    padj
LINC02766   7.884904e-01
SLC25A48    7.752119e-01
TYSND1      2.813008e-01
RAD51D      9.906818e-01
SIGLEC5     4.768456e-01
...                  ...
ARLNC1      8.133366e-01
CXCL9       1.497217e-03
AP2A1       2.904886e-08
RFC2       2.556219e-121
QRICH1      8.532282e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.11 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 0.95 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 153 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 153)
Number of True values in replace_mask: 222
replacement_counts_trimmed shape: (99, 153)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.02 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
LINC02766  8.247166e+02        0.193660  0.552472   0.477722  6.328484e-01
SLC25A48   1.611558e+04        1.066208  0.406647   0.505661  6.130946e-01
TYSND1     1.829953e+05        1.776623  0.128748   1.467629  1.422050e-01
RAD51D     1.005715e+05        1.449318  0.153087   0.023603  9.811691e-01
SIGLEC5    1.121263e+04       -0.399196  0.227497  -2.956458  3.111948e-03
...                 ...             ...       ...        ...           ...
ARLNC1     2.007710e+03        0.020432  0.515709   0.421860  6.731275e-01
CXCL9      2.196546e+05        0.760445  0.422747  -3.951396  7.769668e-05
AP2A1      1.163543e+06        2.667597  0.087529   4.416952  1.001025e-05
RFC2       6.441489e+05        3.401350  0.070626  19.571802  2.689979e-85
QRICH1     4.825015e+05        1.684922  0.162069  -0.342927  7.316535e-01

                   padj
LINC02766  8.008829e-01
SLC25A48   7.887991e-01
TYSND1     2.806426e-01
RAD51D     9.914836e-01
SIGLEC5    8.745345e-03
...                 ...
ARLNC1     8.244367e-01
CXCL9      2.539516e-04
AP2A1      3.528329e-05
RFC2       2.533148e-83
QRICH1     8.639256e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R18.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R18.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R18.csv
============================================================
[INFO] (151/160) sim_S60_G5000_CNweak_R19.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=19
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.05 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.45 seconds.

Fitting LFCs...
... done in 0.70 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 172 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.70 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE       stat        pvalue  \
NOTCH1   534057.946801       -0.260204  0.208332  -1.346991  1.779833e-01
TMEM30A  680646.167207       -0.929777  0.115381  -8.018874  1.067189e-15
ZIC4       5504.554437        0.651230  0.566530   1.330097  1.834863e-01
ZBTB24   394685.671631        2.849128  0.151774  18.847423  3.085116e-79
SVIP     529327.830970        2.649684  0.182806  14.649854  1.350047e-48
...                ...             ...       ...        ...           ...
ZHX2     228361.482828       -0.811560  0.316579  -2.822444  4.765920e-03
HOXD3     39041.303054        0.095823  0.296456   0.356666  7.213421e-01
RARS2    199301.362817       -0.088822  0.235958  -0.469578  6.386564e-01
PRAL     333473.360273       -0.075307  0.088696  -1.007430  3.137280e-01
GRIK1     13756.090106        1.920655  0.225151   8.722780  2.714537e-18

                 padj
NOTCH1   3.328234e-01
TMEM30A  8.024809e-15
ZIC4     3.405752e-01
ZBTB24   1.974870e-77
SVIP     3.272224e-47
...               ...
ZHX2     1.381895e-02
HOXD3    8.490478e-01
RARS2    7.904838e-01
PRAL     5.035826e-01
GRIK1    2.255188e-17

[4993 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.89 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.43 seconds.

Fitting LFCs...
... done in 0.95 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 164 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 164)
Number of True values in replace_mask: 276
replacement_counts_trimmed shape: (111, 164)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.06 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE       stat        pvalue  \
NOTCH1   534057.946801        1.592522  0.142939  -1.346990  1.779834e-01
TMEM30A  680646.167207        1.133334  0.097955 -10.826676  2.573263e-27
ZIC4       1347.933337        0.025269  0.182016  -2.675235  7.467683e-03
ZBTB24   394685.671631        3.550214  0.091807  16.366113  3.338691e-60
SVIP     529327.830970        3.376856  0.116812  12.655027  1.049395e-36
...                ...             ...       ...        ...           ...
ZHX2     228361.482828        0.905950  0.233580  -4.815434  1.468800e-06
HOXD3     39041.303054        1.379747  0.305051   0.356666  7.213419e-01
RARS2    199301.362817        1.489603  0.209511  -0.469578  6.386565e-01
PRAL     333473.360273        2.279970  0.086001  -1.007429  3.137285e-01
GRIK1     13756.090106        2.293570  0.228335   6.854672  7.147635e-12

                 padj
NOTCH1   3.400960e-01
TMEM30A  2.960439e-26
ZIC4     2.013291e-02
ZBTB24   1.355291e-58
SVIP     1.806768e-35
...               ...
ZHX2     5.360905e-06
HOXD3    8.561004e-01
RARS2    8.000030e-01
PRAL     5.175572e-01
GRIK1    3.717515e-11

[4993 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R19.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R19.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R19.csv
============================================================
[INFO] (152/160) sim_S60_G5000_CNweak_R2.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=2
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 0.71 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 163 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.18 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SPHKAP     3.787531e+03       -0.127243  0.614770 -1.203511  2.287786e-01
P2RX3      1.580693e+02        0.055762  0.616069  0.146123  8.838242e-01
SRSF5      2.006394e+06       -0.236990  0.197227 -1.364779  1.723224e-01
MFSD2A     5.733825e+04        0.239163  0.287266  0.896143  3.701762e-01
SMOC2      5.352090e+05        0.196460  0.260537  0.777581  4.368163e-01
...                 ...             ...       ...       ...           ...
RNU6-395P  1.852753e+03       -0.295500  0.407551 -0.905329  3.652910e-01
ZNF33A     8.422692e+05        2.294041  0.393994  6.111315  9.881379e-10
CHTF18     1.703909e+05       -0.010472  0.257455 -0.117378  9.065602e-01
ZC3H7B     7.135332e+05       -0.050979  0.297621 -0.215740  8.291905e-01
NOX4       4.822360e+04       -0.063846  0.135571 -0.502165  6.155512e-01

                   padj
SPHKAP     3.996733e-01
P2RX3      9.458337e-01
SRSF5      3.204400e-01
MFSD2A     5.623926e-01
SMOC2      6.255970e-01
...                 ...
RNU6-395P  5.573731e-01
ZNF33A     5.688346e-09
CHTF18     9.582045e-01
ZC3H7B     9.175037e-01
NOX4       7.762042e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.02 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.92 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 159 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 159)
Number of True values in replace_mask: 261
replacement_counts_trimmed shape: (103, 159)

... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.10 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SPHKAP     1.334378e+03       -0.302735  0.340158 -7.139681  9.354760e-13
P2RX3      1.580693e+02       -0.126460  0.615815 -0.339111  7.345258e-01
SRSF5      2.006394e+06        1.702241  0.078847 -1.364779  1.723224e-01
MFSD2A     5.733825e+04        1.609917  0.274126  0.896143  3.701765e-01
SMOC2      5.352090e+05        1.857957  0.156512  0.777584  4.368141e-01
...                 ...             ...       ...       ...           ...
RNU6-395P  1.852753e+03       -0.337373  0.406912 -0.905321  3.652955e-01
ZNF33A     8.422692e+05        3.169246  0.117529  5.239460  1.610474e-07
CHTF18     1.703909e+05        1.185858  0.204926 -2.581930  9.824944e-03
ZC3H7B     7.135332e+05        1.735816  0.156443 -0.215740  8.291905e-01
NOX4       4.822360e+04        1.316599  0.142946 -0.502164  6.155525e-01

                   padj
SPHKAP     5.354313e-12
P2RX3      8.625925e-01
SRSF5      3.261514e-01
MFSD2A     5.735649e-01
SMOC2      6.351433e-01
...                 ...
RNU6-395P  5.683260e-01
ZNF33A     6.435451e-07
CHTF18     2.615269e-02
ZC3H7B     9.201646e-01
NOX4       7.843305e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R2.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R2.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R2.csv
============================================================
[INFO] (153/160) sim_S60_G5000_CNweak_R20.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=20
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.89 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.38 seconds.

Fitting LFCs...
... done in 0.96 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 147 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
... done in 1.27 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                   baseMean  log2FoldChange     lfcSE       stat  \
PRICKLE2-AS2     160.473831       -0.004847  0.603462  -0.018907
HCCAT5            77.366785       -2.171029  0.929749  -3.171159
THY1          993567.631010       -0.055058  0.412749   0.166732
PPARD         214732.026959       -1.690844  0.100662 -16.909361
FAM180A        41363.754421        0.855624  0.271216   3.415933
...                     ...             ...       ...        ...
MYHAS           2826.356808        0.052547  0.312658   0.188774
SYCE1L         18566.254256       -0.014868  0.128372  -0.148319
SAR1B         374358.635675       -0.212661  0.141007  -1.630728
TXNL4B         51727.846649        0.237810  0.399107   0.724978
HSD17B6        33183.949628        1.125963  0.118416   9.567548

                    pvalue          padj
PRICKLE2-AS2  9.849155e-01  9.932775e-01
HCCAT5        1.518319e-03  4.725448e-03
THY1          8.675810e-01  9.366721e-01
PPARD         3.838469e-64  1.541882e-62
FAM180A       6.356395e-04  2.060562e-03
...                    ...           ...
MYHAS         8.502703e-01  9.271687e-01
SYCE1L        8.820908e-01  9.445699e-01
SAR1B         1.029476e-01  2.172613e-01
TXNL4B        4.684658e-01  6.539384e-01
HSD17B6       1.094714e-21  1.144974e-20

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.02 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.93 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 147 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 147)
Number of True values in replace_mask: 229
replacement_counts_trimmed shape: (101, 147)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.05 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                   baseMean  log2FoldChange     lfcSE       stat  \
PRICKLE2-AS2     160.473831       -0.004537  0.604110  -0.018939
HCCAT5            77.366785       -2.167740  0.929573  -3.170782
THY1          993567.631010        1.849674  0.179903   0.166735
PPARD         214732.026959        0.232811  0.116998 -21.011122
FAM180A        41363.754421        1.654763  0.268741   2.077770
...                     ...             ...       ...        ...
MYHAS           2826.356808        0.086997  0.316825   0.188771
SYCE1L         18566.254256       -0.063198  0.127477  -0.148317
SAR1B         374358.635675        1.666962  0.110245  -1.630724
TXNL4B         51727.846649        1.645315  0.386014   0.724978
HSD17B6        33183.949628        1.328920  0.124239   7.156785

                    pvalue          padj
PRICKLE2-AS2  9.848895e-01  9.938539e-01
HCCAT5        1.520290e-03  4.466860e-03
THY1          8.675790e-01  9.407414e-01
PPARD         5.189371e-98  7.191604e-96
FAM180A       3.773058e-02  9.067334e-02
...                    ...           ...
MYHAS         8.502719e-01  9.328769e-01
SYCE1L        8.820923e-01  9.487096e-01
SAR1B         1.029486e-01  2.193042e-01
TXNL4B        4.684658e-01  6.700619e-01
HSD17B6       8.259100e-13  4.922897e-12

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R20.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R20.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R20.csv
============================================================
[INFO] (154/160) sim_S60_G5000_CNweak_R3.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=3
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.90 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.41 seconds.

Fitting LFCs...
... done in 0.71 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 168 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.30 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
SULT2B1   145345.084507        1.823652  0.483941   4.185429  2.846277e-05
MORN2      42449.043409       -1.027747  0.195802  -5.455747  4.876733e-08
PRR7-AS1    2947.705235        1.122396  0.242819   4.855953  1.198089e-06
FMO2      425076.293145       -0.623513  0.318965  -2.192145  2.836906e-02
NFYC      301299.395239        0.055075  0.086804   0.569682  5.688933e-01
...                 ...             ...       ...        ...           ...
GAS2        5573.920497       -2.040840  0.149940 -13.742033  5.685647e-43
AGMAT       7270.412809       -0.018275  0.629560  -0.060674  9.516192e-01
LIPT1      32511.442507        0.130500  0.116747   1.144052  2.526021e-01
PGPEP1    115146.689203       -2.014434  0.204578 -10.069558  7.531568e-24
ADAMTS15  445510.158535       -0.086662  0.517047  -0.131293  8.955433e-01

                  padj
SULT2B1   1.093812e-04
MORN2     2.432033e-07
PRR7-AS1  5.283444e-06
FMO2      7.145223e-02
NFYC      7.370660e-01
...                ...
GAS2      1.163227e-41
AGMAT     9.751874e-01
LIPT1     4.339131e-01
PGPEP1    8.245085e-23
ADAMTS15  9.464844e-01

[4992 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.43 seconds.

Fitting LFCs...
... done in 1.34 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

Replacing 158 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 158)
Number of True values in replace_mask: 275
replacement_counts_trimmed shape: (108, 158)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.27 seconds.

Fitting MAP LFCs...
... done in 0.94 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
SULT2B1   145345.084507        2.892297  0.297731   3.742940  1.818798e-04
MORN2      42449.043409        0.183272  0.211526  -6.790418  1.118091e-11
PRR7-AS1    2947.705235        0.900178  0.242080   3.998568  6.372685e-05
FMO2      425076.293145        1.037172  0.183385  -4.364792  1.272440e-05
NFYC      301299.395239        2.350600  0.087280   0.569681  5.688939e-01
...                 ...             ...       ...        ...           ...
GAS2        5573.920497       -2.506884  0.149248 -16.494172  4.040605e-61
AGMAT       7270.412809       -0.025557  0.640308  -0.060677  9.516161e-01
LIPT1      32511.442507        0.300998  0.119473   1.144044  2.526055e-01
PGPEP1    115146.689203        0.323259  0.224632 -11.535657  8.721855e-31
ADAMTS15  445510.158535        1.753512  0.243173  -0.131294  8.955425e-01

                  padj
SULT2B1   5.831367e-04
MORN2     6.034065e-11
PRR7-AS1  2.132201e-04
FMO2      4.476406e-05
NFYC      7.481344e-01
...                ...
GAS2      1.667000e-59
AGMAT     9.761891e-01
LIPT1     4.497171e-01
PGPEP1    1.176743e-29
ADAMTS15  9.494345e-01

[4992 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R3.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R3.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R3.csv
============================================================
[INFO] (155/160) sim_S60_G5000_CNweak_R4.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=4
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.41 seconds.

Fitting LFCs...
... done in 0.67 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 159 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.16 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
TCP11        5365.419279        1.509283  0.503154   3.478031  5.051116e-04
RNA5SP216   21744.548659        1.931313  0.159033  12.266866  1.364318e-34
EML5        96084.644151        0.031000  0.094034   0.327570  7.432369e-01
TEX19         687.767186        0.037557  0.610181   0.556062  5.781687e-01
PA2G4P5     38274.316232        1.316830  0.124408  10.722816  7.954365e-27
...                  ...             ...       ...        ...           ...
LINC02345    1754.502345        0.066594  0.502503   0.180644  8.566472e-01
DOCK1      539108.849841        0.228203  0.099859   2.276066  2.284208e-02
ANKRD39     75432.481570        0.363754  0.346180   1.220836  2.221479e-01
IFT81       87876.119091        0.078074  0.149526   0.493774  6.214656e-01
SCN3B       25796.124409        0.138407  0.188729   0.744237  4.567332e-01

                   padj
TCP11      1.695247e-03
RNA5SP216  2.096432e-33
EML5       8.615889e-01
TEX19      7.485768e-01
PA2G4P5    9.391040e-26
...                 ...
LINC02345  9.276010e-01
DOCK1      5.904418e-02
ANKRD39    3.938256e-01
IFT81      7.770653e-01
SCN3B      6.544981e-01

[4994 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.01 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 0.89 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 158 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 158)
Number of True values in replace_mask: 262
replacement_counts_trimmed shape: (104, 158)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 0.99 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat        pvalue  \
TCP11        5365.419279        1.991750  0.506314   2.496467  1.254372e-02
RNA5SP216   21744.548659        2.511093  0.161135  10.690541  1.127119e-26
EML5        96084.644151        1.849300  0.104009   0.327569  7.432378e-01
TEX19         201.486497       -0.484342  0.314357  -5.275801  1.321772e-07
PA2G4P5     38274.316232        1.917827  0.128505   7.258491  3.914335e-13
...                  ...             ...       ...        ...           ...
LINC02345    1754.502345        0.074236  0.503708   0.180644  8.566473e-01
DOCK1      539108.849841        2.365763  0.080103   2.276064  2.284216e-02
ANKRD39     75432.481570        1.826222  0.299071   1.220836  2.221481e-01
IFT81       87876.119091        1.438590  0.153856   0.493774  6.214661e-01
SCN3B       25796.124409        1.374554  0.195560   0.744234  4.567348e-01

                   padj
TCP11      3.255892e-02
RNA5SP216  1.253638e-25
EML5       8.676320e-01
TEX19      5.379730e-07
PA2G4P5    2.231529e-12
...                 ...
LINC02345  9.326568e-01
DOCK1      5.706541e-02
ANKRD39    3.984961e-01
IFT81      7.839358e-01
SCN3B      6.624843e-01

[4994 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R4.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R4.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R4.csv
============================================================
[INFO] (156/160) sim_S60_G5000_CNweak_R5.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=5
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 0.72 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 157 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.16 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
MLYCD      9.257980e+04       -0.186350  0.171656  -1.100676  2.710377e-01
RPL26      2.091329e+06        0.234256  0.151266   1.747652  8.052435e-02
FASTKD5    1.373099e+05        0.890892  0.178063   5.128104  2.926743e-07
ADCY10     2.812090e+03       -0.434924  0.301997  -1.615173  1.062732e-01
UPK2       5.280165e+03       -0.169966  0.234554  -0.798239  4.247319e-01
...                 ...             ...       ...        ...           ...
RPS15AP14  3.400028e+02       -0.270507  0.647782  -0.719787  4.716564e-01
POMT2      1.488611e+05       -0.226653  0.664537  -0.603978  5.458585e-01
NKX2-8     5.078969e+02       -0.546134  0.085925  -6.402729  1.526236e-10
NHLH1      1.845621e+03       -0.540865  0.236754  -2.441023  1.464574e-02
REEP1      1.831192e+05        2.136455  0.101891  20.982198  9.538120e-98

                   padj
MLYCD      4.504235e-01
RPL26      1.711203e-01
FASTKD5    1.339858e-06
ADCY10     2.168042e-01
UPK2       6.114866e-01
...                 ...
RPS15AP14  6.537136e-01
POMT2      7.121135e-01
NKX2-8     8.855717e-10
NHLH1      3.800428e-02
REEP1      6.610447e-96

[4990 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.84 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 1.00 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 161 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 161)
Number of True values in replace_mask: 253
replacement_counts_trimmed shape: (97, 161)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.05 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE       stat        pvalue  \
MLYCD      9.257980e+04        1.329902  0.169873  -1.100675  2.710382e-01
RPL26      2.091329e+06        2.102663  0.070280   1.747651  8.052456e-02
FASTKD5    1.373099e+05        1.624562  0.156305   1.263389  2.064494e-01
ADCY10     2.812090e+03       -1.145480  0.309726  -4.088025  4.350619e-05
UPK2       5.280165e+03       -0.254698  0.231159  -0.798231  4.247366e-01
...                 ...             ...       ...        ...           ...
RPS15AP14  3.400028e+02       -0.279277  0.650623  -0.719776  4.716631e-01
POMT2      1.488611e+05        1.393617  0.564579  -0.603950  5.458769e-01
NKX2-8     5.078969e+02       -0.897232  0.086041 -10.522510  6.803637e-26
NHLH1      1.845621e+03       -1.404160  0.239854  -6.257688  3.907269e-10
REEP1      1.831192e+05        2.857859  0.100124  17.096169  1.584852e-65

                   padj
MLYCD      4.618037e-01
RPL26      1.749982e-01
FASTKD5    3.770799e-01
ADCY10     1.439628e-04
UPK2       6.272375e-01
...                 ...
RPS15AP14  6.695871e-01
POMT2      7.267678e-01
NKX2-8     7.147400e-25
NHLH1      1.855116e-09
REEP1      7.061083e-64

[4990 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R5.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R5.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R5.csv
============================================================
[INFO] (157/160) sim_S60_G5000_CNweak_R6.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=6
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.47 seconds.

Fitting LFCs...
... done in 0.73 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 148 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.14 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SYCP2L        4858.227916       -2.343445  0.316365 -7.673499  1.673670e-14
RNA5SP187      207.998810        0.132815  0.445870  0.385022  7.002213e-01
PRR13       502572.575421       -0.089226  0.136618 -0.879057  3.793703e-01
SLC44A3      49076.160686        0.020519  0.251740  0.059554  9.525105e-01
CCDC92      332699.024779        0.030789  0.159569  0.040356  9.678091e-01
...                   ...             ...       ...       ...           ...
MTSS1       338334.385206       -0.645028  0.501071 -1.708170  8.760479e-02
GRHL2       295125.206796       -0.197801  0.168432 -1.363050  1.728666e-01
SHC2        236988.643649        0.779042  0.445185  2.108251  3.500926e-02
ZNF829       27953.249553       -0.367806  0.604928 -0.954295  3.399344e-01
RNU6-1330P     400.403422        0.327171  0.194242  1.767139  7.720493e-02

                    padj
SYCP2L      1.204898e-13
RNA5SP187   8.321591e-01
PRR13       5.745836e-01
SLC44A3     9.785986e-01
CCDC92      9.843832e-01
...                  ...
MTSS1       1.861297e-01
GRHL2       3.214430e-01
SHC2        8.557628e-02
ZNF829      5.336478e-01
RNU6-1330P  1.678324e-01

[4989 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.05 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.41 seconds.

Fitting LFCs...
... done in 0.96 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 148 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 148)
Number of True values in replace_mask: 260
replacement_counts_trimmed shape: (104, 148)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.07 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat        pvalue  \
SYCP2L        4858.227916       -2.660817  0.316992 -8.757496  1.996352e-18
RNA5SP187      207.998810        0.133190  0.446610  0.384996  7.002402e-01
PRR13       502572.575421        1.828423  0.097627 -0.879057  3.793705e-01
SLC44A3      49076.160686        1.362608  0.255183  0.059554  9.525105e-01
CCDC92      332699.024779        1.800873  0.115705  0.040356  9.678091e-01
...                   ...             ...       ...       ...           ...
MTSS1       338334.385206        0.998821  0.309164 -3.063715  2.186071e-03
GRHL2       295125.206796        1.001332  0.132670 -5.893085  3.790513e-09
SHC2        236988.643649        2.279769  0.306797  2.108251  3.500927e-02
ZNF829       27953.249553        0.570417  0.611358 -1.985576  4.708046e-02
RNU6-1330P     400.403422        0.326161  0.194429  1.766765  7.726766e-02

                    padj
SYCP2L      1.479911e-17
RNA5SP187   8.365657e-01
PRR13       5.814683e-01
SLC44A3     9.792036e-01
CCDC92      9.851866e-01
...                  ...
MTSS1       6.315176e-03
GRHL2       1.719170e-08
SHC2        8.393141e-02
ZNF829      1.092994e-01
RNU6-1330P  1.677495e-01

[4989 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R6.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R6.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R6.csv
============================================================
[INFO] (158/160) sim_S60_G5000_CNweak_R7.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=7
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 0.99 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 143 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.19 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat         pvalue  \
LINC01908      73.256499       -0.184641  0.618206  -0.500288   6.168725e-01
PCSK6      183569.217705        0.115222  0.336971   0.446105   6.555212e-01
NRF1       277055.947566        1.895662  0.063351  30.368214  1.444425e-202
EFCAB11     37141.880776       -0.138895  0.189215  -0.787763   4.308354e-01
VANGL1     186956.968819       -0.177589  0.266919  -0.773632   4.391486e-01
...                  ...             ...       ...        ...            ...
RCN1       524261.188561        0.832853  0.865725   0.477573   6.329541e-01
UBE2D1     102059.218363       -0.332563  0.562398  -0.878956   3.794251e-01
ZNF512     172329.797990       -0.470872  0.278172  -1.931008   5.348201e-02
PRR22       17364.779373        0.046377  0.105363   0.436347   6.625853e-01
CACNA1G     27770.226111        0.933082  0.132218   7.141100   9.258710e-13

                    padj
LINC01908   7.826344e-01
PCSK6       8.102219e-01
NRF1       1.800837e-199
EFCAB11     6.343508e-01
VANGL1      6.428042e-01
...                  ...
RCN1        7.950988e-01
UBE2D1      5.827512e-01
ZNF512      1.234791e-01
PRR22       8.162829e-01
CACNA1G     5.859542e-12

[4987 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.01 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 0.90 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 146 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 146)
Number of True values in replace_mask: 210
replacement_counts_trimmed shape: (97, 146)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.07 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE       stat         pvalue  \
LINC01908      73.256499       -0.187568  0.620207  -0.500280   6.168778e-01
PCSK6      183569.217705        1.685385  0.285153   0.446191   6.554590e-01
NRF1       277055.947566        3.658619  0.077520  23.664913  8.288976e-124
EFCAB11     37141.880776        0.985669  0.202426  -0.787761   4.308365e-01
VANGL1     186956.968819        1.431253  0.236674  -0.773632   4.391487e-01
...                  ...             ...       ...        ...            ...
RCN1       103408.591546        2.171743  0.083926  -7.715724   1.202976e-14
UBE2D1     102059.218363        1.292886  0.494676  -0.878956   3.794252e-01
ZNF512     172329.797990        1.126728  0.218875  -3.319926   9.004145e-04
PRR22       17364.779373       -0.047924  0.103755   0.436339   6.625906e-01
CACNA1G     27770.226111        0.675787  0.138289   1.406512   1.595721e-01

                    padj
LINC01908   7.943580e-01
PCSK6       8.218316e-01
NRF1       2.755808e-121
EFCAB11     6.489083e-01
VANGL1      6.562884e-01
...                  ...
RCN1        7.681489e-14
UBE2D1      5.959664e-01
ZNF512      2.701785e-03
PRR22       8.277403e-01
CACNA1G     3.155376e-01

[4987 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R7.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R7.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R7.csv
============================================================
[INFO] (159/160) sim_S60_G5000_CNweak_R8.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=8
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 0.72 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 163 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.20 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
ZNF542P     233258.644856        2.064301  0.152739  13.573645  5.739532e-42
RFX7        137167.974869        0.198787  0.121290   1.625235  1.041125e-01
GEMIN7-AS1   13607.020772       -1.984648  0.155980 -12.870252  6.618606e-38
MIR6774        216.868871        0.149168  0.418685   0.448110  6.540740e-01
RMDN1       210592.533449       -0.196203  0.144213  -1.452509  1.463602e-01
...                   ...             ...       ...        ...           ...
LCNL1         7003.382910        0.138360  0.207537   0.704047  4.814038e-01
ENDOD1      299987.245884        0.312635  0.660068   0.697203  4.856761e-01
ZNF335      213070.785076        0.233949  0.394320   0.684206  4.938453e-01
PGF          76182.440193        0.158643  0.267203   0.636090  5.247178e-01
PKNOX2       12453.647807       -0.541606  0.309223  -1.956448  5.041238e-02

                    padj
ZNF542P     1.267522e-40
RFX7        2.186977e-01
GEMIN7-AS1  1.260819e-36
MIR6774     7.940850e-01
RMDN1       2.886148e-01
...                  ...
LCNL1       6.646435e-01
ENDOD1      6.683235e-01
ZNF335      6.744835e-01
PGF         6.987370e-01
PKNOX2      1.177941e-01

[4991 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.01 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 1.27 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

Replacing 163 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 163)
Number of True values in replace_mask: 273
replacement_counts_trimmed shape: (103, 163)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 0.92 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat         pvalue  \
ZNF542P     233258.644856        2.798781  0.113253  10.601405   2.935354e-26
RFX7        137167.974869        1.616272  0.126269   1.625232   1.041131e-01
GEMIN7-AS1   13607.020772       -2.263890  0.156867 -15.218857   2.651243e-52
MIR6774        216.868871        0.148907  0.418910   0.448078   6.540968e-01
RMDN1       210592.533449        7.227563  0.247468  22.300996  3.613674e-110
...                   ...             ...       ...        ...            ...
LCNL1         7003.382910        0.089112  0.206201   0.704039   4.814084e-01
ENDOD1      299987.245884        2.083798  0.350405   0.697165   4.856995e-01
ZNF335      213070.785076        1.411215  0.276311  -1.120299   2.625863e-01
PGF          76182.440193        1.625832  0.244469   0.636090   5.247180e-01
PKNOX2       12453.647807       -0.550138  0.308818  -1.956443   5.041302e-02

                     padj
ZNF542P      3.479894e-25
RFX7         2.235923e-01
GEMIN7-AS1   9.125760e-51
MIR6774      7.991579e-01
RMDN1       8.198112e-108
...                   ...
LCNL1        6.735939e-01
ENDOD1       6.773194e-01
ZNF335       4.547426e-01
PGF          7.074197e-01
PKNOX2       1.187967e-01

[4991 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R8.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R8.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R8.csv
============================================================
[INFO] (160/160) sim_S60_G5000_CNweak_R9.pkl
[INFO] Running analysis for S=60, G=5000, CN=weak, R=9
[INFO] Running PyDESeq2 (CN-naive)

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.70 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 158 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.21 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
VN1R81P      1.596829e+03       -0.835361  0.181503  -4.767232  1.867744e-06
MIR7844      1.992146e+03       -1.756483  0.298640  -6.174767  6.626108e-10
CFAP69       4.729812e+04       -2.599888  0.228568 -11.559391  6.617681e-31
BCAR3        1.957117e+05       -0.036202  0.203942  -0.270201  7.870054e-01
CEP57        2.158584e+05       -0.088792  0.117855  -0.825570  4.090481e-01
...                   ...             ...       ...        ...           ...
ARPC4-TTLL3  1.110465e+06        1.659779  0.139380  12.107045  9.692389e-34
SRGAP3-AS4   1.144677e+02       -0.990016  0.223518  -4.641952  3.451333e-06
GPR45        2.351822e+02       -1.115421  0.589425  -2.478521  1.319282e-02
SULT4A1      8.350744e+03        0.445842  0.330161   1.541151  1.232801e-01
GTSE1-DT     2.686052e+03        0.091835  0.108199   0.866987  3.859493e-01

                     padj
VN1R81P      7.868504e-06
MIR7844      3.538654e-09
CFAP69       8.897303e-30
BCAR3        8.927735e-01
CEP57        6.106949e-01
...                   ...
ARPC4-TTLL3  1.421930e-32
SRGAP3-AS4   1.416893e-05
GPR45        3.562848e-02
SULT4A1      2.487546e-01
GTSE1-DT     5.873403e-01

[4988 rows x 6 columns]
[INFO] Running DeConveil (CN-aware)

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_8324/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.01 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 0.90 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 150 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 150)
Number of True values in replace_mask: 243
replacement_counts_trimmed shape: (97, 150)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.05 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE       stat        pvalue  \
VN1R81P      1.596829e+03       -1.129091  0.181341  -6.233069  4.573854e-10
MIR7844      1.992146e+03       -1.991544  0.299405  -7.162657  7.912793e-13
CFAP69       4.729812e+04       -0.454007  0.294500 -13.305311  2.155954e-40
BCAR3        1.957117e+05        1.505826  0.190689  -0.270201  7.870055e-01
CEP57        2.158584e+05        1.596479  0.120739  -0.825569  4.090486e-01
...                   ...             ...       ...        ...           ...
ARPC4-TTLL3  1.110465e+06        2.773561  0.082359   9.897944  4.249215e-23
SRGAP3-AS4   1.144677e+02       -1.224161  0.224027  -5.676310  1.376312e-08
GPR45        2.351822e+02       -1.117716  0.589004  -2.478390  1.319767e-02
SULT4A1      8.350744e+03        0.375796  0.325844   1.541145  1.232814e-01
GTSE1-DT     2.686052e+03        0.107934  0.108259   0.866898  3.859979e-01

                     padj
VN1R81P      2.156369e-09
MIR7844      4.346807e-12
CFAP69       3.982926e-39
BCAR3        8.947674e-01
CEP57        6.188457e-01
...                   ...
ARPC4-TTLL3  3.896156e-22
SRGAP3-AS4   5.897806e-08
GPR45        3.442991e-02
SULT4A1      2.521229e-01
GTSE1-DT     5.949807e-01

[4988 rows x 6 columns]
[INFO] Applying stageR

R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.


R callback write-console: The returned adjusted p-values are based on a stage-wise testing approach and are only valid for the provided target OFDR level of 5%. If a different target OFDR level is of interest,the entire adjustment should be re-run.

[SAVED] sim_results/sim_res_fit/sim2/res_CNnaive_S60_G5000_CNweak_R9.csv
[SAVED] sim_results/sim_res_fit/sim2/res_CNaware_S60_G5000_CNweak_R9.csv
[SAVED] sim_results/sim_res_fit/sim2/truth_S60_G5000_CNweak_R9.csv
[DONE] All simulations processed

#### Null simulation to show type-I error calibration

In [41]:
def collect_null_pvals(
    rna_counts,
    metadata,
    cn_tumor,
    cn_normal,
    n_genes=5000,
    sample_sizes=(10, 20, 40, 60),
    n_reps=20,
    seed_base=2000,
):
    all_p = []

    for S in sample_sizes:
        for rep in range(n_reps):
            seed = seed_base + rep
            sim = cn_aware_rna_simulator(
            counts=rna_counts,
            metadata=metadata,
            cn_tumor=cn_tumor,
            cn_normal=cn_normal,
            n_genes=n_genes,
            design="~ 1",
            n_normal_sim=S,
            n_tumor_sim=S,
            seed=seed,
            null_mode="pure_null",  
            inject_del=False,     # usually disable extra structure in null
            )
            counts_df = sim["counts"].T
            cn_df     = sim["CN"].T
            meta      = sim["metadata"]
            meta["condition"] = meta["condition"].replace({"normal": "A", "tumor": "B"})

            # PyDESeq2 (CN-naive)
            res_naive = run_pydeseq2(counts_df, meta)
            p_naive = res_naive["pvalue"].astype(float).values

            # DeConveil (CN-aware)
            res_aware = run_deconveil(counts_df, meta, cn_df)
            p_aware = res_aware["pvalue"].astype(float).values

            all_p.append(pd.DataFrame({
                "p_naive": p_naive,
                "p_aware": p_aware,
                "sample_size": S,
                "rep": rep,
            }))

    return pd.concat(all_p, ignore_index=True)

In [43]:
all_p = collect_null_pvals(rna_counts, metadata, cn_tumor, cn_normal)

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 577 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4994 genes.
Using None as control genes, passed at DeseqDataSet initialization

Fitting size factors...
... done in 0.00 seconds.

Fitting dispersions...
... done in 1.09 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 1.21 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 267 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.24 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.53 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
RTKN       227682.004884        0.025787  0.120375  1.835457  0.066438
RPL31P2      2854.599577        0.003642  0.100382  0.468735  0.639259
MIR6746      1107.543069       -0.002397  0.088767 -0.529412  0.596520
CYTH2      577205.361977        0.016486  0.102059  1.118404  0.263395
RNF112      25607.049404       -0.001581  0.092849 -0.260533  0.794453
...                  ...             ...       ...       ...       ...
MYL1         1454.668783        0.001077  0.102238  0.269102  0.787851
PPIAP16       385.760544        0.016385  0.114559  1.698999  0.089319
LINC02084    1364.721882        0.002065  0.091499  0.123027  0.902086
MIR202HG      533.817869       -0.031959  0.098524 -1.774575  0.075968
LRIG3      165343.742422        0.001999  0.099760  0.304053  0.761088

               padj
RTKN       0.729078
RPL31P2    0.983220
MIR6746    0.980999
CYTH2      0.922569
RNF112     0.988007
...             ...
MYL1       0.987475
PPIAP16    0.763174
LINC02084  0.996541
MIR202HG   0.739554
LRIG3      0.985284

[4994 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.99 seconds.

Fitting dispersion trend curve...
... done in 1.22 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.81 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 267 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 267)
Number of True values in replace_mask: 442
replacement_counts_trimmed shape: (20, 267)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.24 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.58 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
RTKN       227682.004884    2.058787e+00  0.392323  1.835456  0.066438
RPL31P2      2854.599577    8.487382e-07  0.001519  0.468726  0.639266
MIR6746      1107.543069   -6.955130e-07  0.001330 -0.529402  0.596527
CYTH2      577205.361977    2.124507e+00  0.218876  1.118403  0.263395
RNF112      25607.049404   -3.300748e-07  0.001398 -0.260532  0.794453
...                  ...             ...       ...       ...       ...
MYL1         1454.668783    1.422654e-07  0.001533  0.269099  0.787853
PPIAP16       385.760544    3.349106e-06  0.001691  1.698584  0.089398
LINC02084    1364.721882    1.331850e-07  0.001451  0.123003  0.902105
MIR202HG      533.817869   -6.886554e-06  0.001340 -1.773639  0.076123
LRIG3      165343.742422    1.568365e+00  0.702691  0.304052  0.761088

               padj
RTKN       0.822417
RPL31P2    0.999996
MIR6746    0.999996
CYTH2      0.999996
RNF112     0.999996
...             ...
MYL1       0.999996
PPIAP16    0.854643
LINC02084  0.999996
MIR202HG   0.827599
LRIG3      0.999996

[4994 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 546 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.84 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.12 seconds.

Fitting LFCs...
... done in 0.78 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 241 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.19 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.44 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat    pvalue  \
C5            58889.007400        0.003857  0.096527  0.348361  0.727569
ENPEP         67904.100147        0.013043  0.110399  1.176388  0.239440
MIR1469         237.967775        0.005781  0.108044  0.888947  0.374032
ENTPD5       312535.860039       -0.025961  0.094764 -1.642202  0.100548
TMEM243      110033.910865       -0.023847  0.096723  0.167239  0.867182
...                    ...             ...       ...       ...       ...
CCNJL         33765.936635        0.000413  0.094598 -0.072470  0.942228
ZRANB2       592966.586064        0.002050  0.094991 -0.007629  0.993913
RAPGEF4-AS1     255.148202        0.001430  0.100322  2.481332  0.013089
HCN3          30168.804313        0.029459  0.138759  2.666685  0.007660
ANGPTL1      131938.109568        0.015708  0.100255  1.063963  0.287345

                 padj
C5           0.987535
ENPEP        0.916286
MIR1469      0.947531
ENTPD5       0.837622
TMEM243      0.997129
...               ...
CCNJL        0.997358
ZRANB2       0.999904
RAPGEF4-AS1  0.498590
HCN3         0.415490
ANGPTL1      0.930550

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.45 seconds.

Fitting dispersion trend curve...
... done in 0.19 seconds.

Fitting MAP dispersions...
... done in 1.79 seconds.

Fitting LFCs...
... done in 1.64 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 241 outlier genes.

Fitting dispersions...

replace_mask before filtering: (20, 241)
Number of True values in replace_mask: 405
replacement_counts_trimmed shape: (20, 241)

... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.12 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.20 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.86 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat    pvalue  \
C5            58889.007400        1.293842  0.461688  0.348361  0.727569
ENPEP         67904.100147        1.840818  0.537186  1.176387  0.239440
MIR1469         237.967775        0.000001  0.001627  0.888794  0.374114
ENTPD5       312535.860039        1.425110  0.300176 -1.642201  0.100548
TMEM243      110033.910865        1.886994  0.253537  0.167239  0.867182
...                    ...             ...       ...       ...       ...
CCNJL         33765.936635        1.000474  1.264652 -0.072460  0.942236
ZRANB2       592966.586064        1.716342  0.332666 -0.007629  0.993913
RAPGEF4-AS1     116.986400        0.000068  0.001466 -0.021066  0.983193
HCN3          30168.804313        2.028466  0.507580  2.666676  0.007661
ANGPTL1      131938.109568        1.683905  0.322037  1.063962  0.287346

                 padj
C5           0.999984
ENPEP        0.987412
MIR1469      0.999984
ENTPD5       0.918039
TMEM243      0.999984
...               ...
CCNJL        0.999984
ZRANB2       0.999984
RAPGEF4-AS1  0.999984
HCN3         0.509681
ANGPTL1      0.999984

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 603 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.34 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.65 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 218 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.12 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.48 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
GBP5     122315.517993        0.005981  0.097348  1.640407  0.100921  0.834199
CXCL3      7351.618047       -0.001133  0.072299 -0.348023  0.727823  0.984183
ARID1B   555052.141945        0.000402  0.070907 -0.004107  0.996723  0.999117
DYNLRB2    6764.183989        0.007850  0.098838  1.864183  0.062296  0.738180
SLIT1     40340.657950        0.000313  0.076412  0.046169  0.963176  0.995755
...                ...             ...       ...       ...       ...       ...
MIR4656     161.877059        0.003583  0.083126  0.787044  0.431256  0.953548
GRXCR2      164.054548       -0.001630  0.073520 -0.188412  0.850554  0.991650
ELK4     343710.756937        0.004308  0.075885  0.152477  0.878811  0.992830
CLEC4D     1391.457767        0.002229  0.078230  0.399069  0.689843  0.980005
CC2D1A   302161.961388       -0.000779  0.074896  0.184075  0.853954  0.992830

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.05 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.29 seconds.

Fitting LFCs...
... done in 0.77 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 218 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 218)
Number of True values in replace_mask: 388
replacement_counts_trimmed shape: (20, 218)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.39 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
GBP5     122315.517993    2.237386e+00  0.658728  1.640407  0.100921  0.919338
CXCL3      7351.618047    1.471229e-06  0.001374 -0.348022  0.727824  0.999998
ARID1B   555052.141945    2.557517e+00  0.198929 -0.004107  0.996723  0.999998
DYNLRB2    6764.183989    2.808783e-06  0.001864  1.864168  0.062298  0.831197
SLIT1     40340.657950    1.083815e+00  1.727015  0.046168  0.963176  0.999998
...                ...             ...       ...       ...       ...       ...
MIR4656     161.877059    1.261583e-06  0.001584  0.786794  0.431402  0.999998
GRXCR2      164.054548   -6.015651e-07  0.001429 -0.188195  0.850724  0.999998
ELK4     343710.756937    1.781122e+00  0.278400  0.152477  0.878811  0.999998
CLEC4D     1391.457767    8.155877e-07  0.001498  0.399048  0.689858  0.999998
CC2D1A   302161.961388    1.765013e+00  0.279780  0.184075  0.853955  0.999998

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 560 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.

Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.18 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.44 seconds.

Fitting LFCs...
... done in 0.55 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 225 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.22 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.90 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
RASL11B    22013.957467        0.009233  0.118018  1.624292  0.104313
CD101       7995.999509        0.008352  0.102349  1.061250  0.288576
PTGES3L     6809.269257        0.003600  0.094401  0.417649  0.676204
NCOA1     352915.182812        0.000025  0.087154 -0.303343  0.761628
SRP19     193558.625332        0.013188  0.086945  0.445479  0.655974
...                 ...             ...       ...       ...       ...
CHCHD4P4     140.370538       -0.003410  0.073075 -1.377021  0.168506
TCFL5      85281.023864       -0.004445  0.087742 -0.452772  0.650713
ZNF384    344925.674692        0.026406  0.108706  1.864076  0.062311
FBXO27     69918.216051       -0.003061  0.071572 -1.442600  0.149133
ZSCAN10      183.514350       -0.003280  0.088354 -0.283248  0.776987

              padj
RASL11B   0.756744
CD101     0.907786
PTGES3L   0.977458
NCOA1     0.988577
SRP19     0.977458
...            ...
CHCHD4P4  0.842915
TCFL5     0.977458
ZNF384    0.719854
FBXO27    0.822787
ZSCAN10   0.989211

[4993 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.12 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.25 seconds.

Fitting LFCs...
... done in 0.78 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 225 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 225)
Number of True values in replace_mask: 399
replacement_counts_trimmed shape: (20, 225)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.17 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.48 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
RASL11B    22013.957467    1.816374e+00  0.803381  1.624289  0.104314
CD101       7995.999509    1.684604e-06  0.001608  1.061240  0.288581
PTGES3L     6809.269257    8.418401e-07  0.001497  0.417644  0.676208
NCOA1     352915.182812    1.685538e+00  0.263606 -0.303343  0.761628
SRP19     193558.625332    2.187179e+00  0.226236  0.445477  0.655975
...                 ...             ...       ...       ...       ...
CHCHD4P4     140.370538   -8.294338e-07  0.001138 -1.376888  0.168547
TCFL5      85281.023864    1.242232e+00  0.698919 -0.452772  0.650713
ZNF384    344925.674692    2.174888e+00  0.247152  1.864075  0.062311
FBXO27     69918.216051   -9.626854e-01  0.974918 -1.442586  0.149137
ZSCAN10      183.514350   -8.214115e-07  0.001420 -0.283006  0.777172

              padj
RASL11B   0.836964
CD101     0.969803
PTGES3L   0.999990
NCOA1     0.999990
SRP19     0.999990
...            ...
CHCHD4P4  0.914147
TCFL5     0.999990
ZNF384    0.807084
FBXO27    0.900413
ZSCAN10   0.999990

[4993 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 587 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.20 seconds.

Fitting LFCs...
... done in 0.59 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 241 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 1.43 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SPOCK2    89712.135627        0.000173  0.083824  0.015790  0.987402  0.999080
NR4A3    150743.974234       -0.004549  0.076250 -0.842346  0.399594  0.982188
NPR1     683483.989579        0.005170  0.116240  1.484651  0.137636  0.877972
ABHD17C   84927.423827        0.007758  0.087540  0.324119  0.745848  0.988492
PHYHIP    53329.109174       -0.000751  0.078011 -0.507403  0.611872  0.988492
...                ...             ...       ...       ...       ...       ...
NAALAD2   45993.476424       -0.002456  0.088405  0.225475  0.821610  0.991552
SNORA9     2177.690851       -0.012774  0.079367 -0.819940  0.412250  0.982208
NT5DC1   190595.797351        0.026274  0.100621  2.197511  0.027984  0.561263
CEP57L1   46819.872082        0.004417  0.084072  0.395016  0.692831  0.988492
ARPC4    848568.104206        0.001382  0.083707  0.418923  0.675273  0.988492

[4989 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.22 seconds.

Fitting LFCs...
... done in 0.97 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 240 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 240)
Number of True values in replace_mask: 405
replacement_counts_trimmed shape: (20, 240)

... done in 0.08 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.22 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.40 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SPOCK2    89712.135627        1.421590  0.482793  0.015790  0.987402  0.999999
NR4A3    150743.974234        0.905416  3.446967 -0.842346  0.399594  0.999999
NPR1     683483.989579        2.712294  0.432603  1.484650  0.137636  0.972873
ABHD17C   84927.423827        1.544767  0.519791  0.324118  0.745849  0.999999
PHYHIP    53329.109174        0.718119  0.796033 -0.507402  0.611872  0.999999
...                ...             ...       ...       ...       ...       ...
NAALAD2   45993.476424        1.280456  1.534906  0.225474  0.821610  0.999999
SNORA9     2177.690851       -0.000004  0.001401 -0.819775  0.412344  0.999999
NT5DC1   190595.797351        2.307498  0.252286  2.197508  0.027984  0.671337
CEP57L1   46819.872082        0.833051  0.377684  0.395014  0.692832  0.999999
ARPC4    848568.104206        2.102810  0.200673  0.418923  0.675273  0.999999

[4989 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 577 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.15 seconds.

Fitting dispersion trend curve...
... done in 0.16 seconds.

Fitting MAP dispersions...
... done in 1.57 seconds.

Fitting LFCs...
... done in 0.99 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 205 outlier genes.

Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.11 seconds.

Fitting LFCs...
... done in 0.14 seconds.

Running Wald tests...
... done in 0.44 seconds.

Fitting MAP LFCs...
... done in 2.00 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
ENHO        1.908242e+04        0.008826  0.145087  1.459802  0.144344
RPSAP36     1.310023e+03        0.004910  0.135859  0.965086  0.334502
KRT8        5.687166e+06       -0.009114  0.087461 -1.888060  0.059018
MAP2K4      2.040784e+05        0.009668  0.106193  0.012739  0.989836
MARCKSL1P1  5.341519e+02        0.007029  0.151561  1.399141  0.161771
...                  ...             ...       ...       ...       ...
FAM83A-AS1  1.103935e+03       -0.016381  0.099988 -0.723466  0.469394
MIR2110     9.902034e+02        0.026271  0.131193  1.855221  0.063565
ALOX12      8.487284e+03        0.002514  0.107414  0.188587  0.850416
OR52N4      3.000245e+03        0.002544  0.116708  0.412582  0.679913
ACSBG2      3.658874e+03       -0.000047  0.108162 -0.017398  0.986119

                padj
ENHO        0.827630
RPSAP36     0.941943
KRT8        0.752080
MAP2K4      0.999991
MARCKSL1P1  0.857103
...              ...
FAM83A-AS1  0.966755
MIR2110     0.754959
ALOX12      0.994534
OR52N4      0.980050
ACSBG2      0.999991

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.42 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.84 seconds.

Fitting LFCs...
... done in 1.35 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 205 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...

replace_mask before filtering: (20, 205)
Number of True values in replace_mask: 356
replacement_counts_trimmed shape: (20, 205)

... done in 0.05 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 2.29 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
ENHO        1.908242e+04    1.947759e-06  0.001926  1.459800  0.144345
RPSAP36     1.310023e+03    8.593971e-07  0.001807  0.965073  0.334508
KRT8        5.687166e+06    1.067930e+00  0.242772 -1.888060  0.059018
MAP2K4      2.040784e+05    1.663376e+00  0.332853  0.012739  0.989836
MARCKSL1P1  5.341519e+02    1.217716e-06  0.002013  1.399086  0.161787
...                  ...             ...       ...       ...       ...
FAM83A-AS1  1.103935e+03   -2.928395e-06  0.001401 -0.723249  0.469527
MIR2110     9.902034e+02    4.342584e-06  0.001681  1.855001  0.063596
ALOX12      8.487284e+03    5.920835e-07  0.001464  0.188585  0.850418
OR52N4      3.000245e+03    3.904602e-07  0.001556  0.412579  0.679915
ACSBG2      3.658874e+03    1.359826e-08  0.001438 -0.017398  0.986119

                padj
ENHO        0.885631
RPSAP36     0.997023
KRT8        0.814240
MAP2K4      0.999991
MARCKSL1P1  0.911981
...              ...
FAM83A-AS1  0.999991
MIR2110     0.816944
ALOX12      0.999991
OR52N4      0.999991
ACSBG2      0.999991

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 601 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.92 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.22 seconds.

Fitting LFCs...
... done in 0.63 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 259 outlier genes.

Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.27 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.70 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CHMP6    125674.421870       -0.003088  0.085876 -0.333483  0.738770  0.985579
PTMAP10     209.780462        0.001894  0.097212  0.462171  0.643958  0.985520
DRAXIN     9603.213942       -0.001418  0.084719  0.944548  0.344890  0.969205
CYP2T1P  176085.352163        0.003210  0.119889  1.535689  0.124615  0.868862
SH3RF1   270553.991645       -0.015765  0.085629 -1.031917  0.302111  0.967212
...                ...             ...       ...       ...       ...       ...
BET1      90271.159420       -0.001553  0.086760 -0.222903  0.823611  0.986732
AGBL2      6367.458160        0.008225  0.096136  0.950443  0.341887  0.969205
XPC      241916.261995        0.001449  0.097389  0.396543  0.691705  0.985579
PXT1        686.845302        0.013763  0.114052  1.977557  0.047979  0.732173
GAL3ST1    2086.877741       -0.009446  0.079293 -1.487097  0.136989  0.888084

[4991 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.91 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.34 seconds.

Fitting LFCs...
... done in 0.84 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 259 outlier genes.

Fitting dispersions...
... done in 0.04 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

replace_mask before filtering: (20, 259)
Number of True values in replace_mask: 432
replacement_counts_trimmed shape: (20, 259)

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.76 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CHMP6    125674.421870    1.368762e+00  0.403065 -0.333483  0.738770  1.000000
PTMAP10     209.780462    4.869996e-07  0.001572  0.462126  0.643991  1.000000
DRAXIN     4332.069178   -2.438276e-01  0.011313 -0.001855  0.998520  1.000000
CYP2T1P  176085.352163    2.466277e+00  0.705474  1.535689  0.124615  0.961526
SH3RF1   270553.991645    1.476182e+00  0.289369 -1.031916  0.302111  1.000000
...                ...             ...       ...       ...       ...       ...
BET1      90271.159420    1.328218e+00  0.537714 -0.222903  0.823611  1.000000
AGBL2      6367.458160    2.114396e-06  0.001565  0.950428  0.341895  1.000000
XPC      241916.261995    1.812589e+00  0.895742  0.401957  0.687715  1.000000
PXT1        686.845302    3.421714e-06  0.001811  1.977344  0.048003  0.834567
GAL3ST1    2086.877741   -2.839915e-06  0.001263 -1.487056  0.137000  0.982261

[4991 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 606 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.

Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.03 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.30 seconds.

Fitting LFCs...
... done in 0.58 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 257 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.24 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.41 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
PCDHB7       29459.864363       -0.016733  0.070445 -2.460661  0.013868
SAMD13        8657.090150       -1.130924  0.717729 -2.921034  0.003489
RNU6-100P      140.956549        0.002608  0.086859  0.668777  0.503638
ZC3HAV1     312562.947591        0.005243  0.079425  0.556779  0.577679
OR2C1          372.392548       -0.000057  0.078346 -0.027589  0.977990
...                   ...             ...       ...       ...       ...
RNU6-1330P     613.251363       -0.000786  0.075749 -0.246714  0.805130
RPL17P43     14619.093177       -0.003916  0.066827 -1.282872  0.199537
PCDHA5       55636.383069        0.002130  0.082830  0.552266  0.580766
GABRA1         150.039160        0.012580  0.081155  1.049193  0.294089
FXR2        226801.505207       -0.002408  0.082580  0.585662  0.558103

                padj
PCDHB7      0.516527
SAMD13      0.330497
RNU6-100P   0.988631
ZC3HAV1     0.988631
OR2C1       0.998799
...              ...
RNU6-1330P  0.994702
RPL17P43    0.915347
PCDHA5      0.988631
GABRA1      0.934093
FXR2        0.988631

[4991 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.08 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.23 seconds.

Fitting LFCs...
... done in 0.74 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 257 outlier genes.

Fitting dispersions...
... done in 0.04 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...

replace_mask before filtering: (20, 257)
Number of True values in replace_mask: 433
replacement_counts_trimmed shape: (20, 257)

... done in 0.05 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.34 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
PCDHB7       29459.864363   -8.767778e-01  0.847014 -2.460646  0.013869
SAMD13        8657.090150   -5.305183e-01  0.660916 -2.921007  0.003489
RNU6-100P      140.956549    8.736161e-07  0.001595  0.668627  0.503733
ZC3HAV1     312562.947591    1.919231e+00  0.275152  0.556778  0.577679
OR2C1          372.392548   -1.682896e-08  0.001436 -0.027588  0.977991
...                   ...             ...       ...       ...       ...
RNU6-1330P     613.251363   -2.613586e-07  0.001389 -0.246705  0.805137
RPL17P43     14619.093177   -1.315386e-06  0.001219 -1.282870  0.199538
PCDHA5       55636.383069    1.502796e+00  0.598130  0.552265  0.580767
GABRA1         150.039160    4.311737e-06  0.001510  1.047059  0.295072
FXR2        226801.505207    1.725362e+00  0.453315  0.585659  0.558104

                padj
PCDHB7      0.620635
SAMD13      0.425976
RNU6-100P   0.999993
ZC3HAV1     0.999993
OR2C1       0.999993
...              ...
RNU6-1330P  0.999993
RPL17P43    0.991707
PCDHA5      0.999993
GABRA1      0.999993
FXR2        0.999993

[4991 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 603 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.05 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.31 seconds.

Fitting LFCs...
... done in 0.91 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 249 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.14 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.66 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
KRT8P37     6143.461219        0.001839  0.098935  0.625904  0.531378
ERFL        2971.981503        0.013978  0.112736  2.237478  0.025255
AQP4        3236.549121        0.004084  0.101332  1.010980  0.312026
RASGRP2   118326.305370        0.001761  0.089258  0.499278  0.617584
ELOB      582954.699722       -0.011742  0.077378 -1.445667  0.148271
...                 ...             ...       ...       ...       ...
HEXD      182603.077346        0.000306  0.081543 -0.211111  0.832800
UNC13C      1231.018689        0.009549  0.087326  0.849212  0.395763
GPX1      829632.441296        0.008415  0.086365  0.107319  0.914536
PEF1      530234.698247        0.003973  0.082737 -0.153305  0.878158
RPS10P28     566.280863       -0.000451  0.082445 -0.153983  0.877623

              padj
KRT8P37   0.996004
ERFL      0.588657
AQP4      0.971526
RASGRP2   0.997282
ELOB      0.905236
...            ...
HEXD      0.997282
UNC13C    0.990776
GPX1      0.998082
PEF1      0.997282
RPS10P28  0.997282

[4988 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.25 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.27 seconds.

Fitting LFCs...
... done in 0.84 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 249 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 249)
Number of True values in replace_mask: 416
replacement_counts_trimmed shape: (20, 249)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.21 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.82 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
KRT8P37     6143.461219    4.096275e-07  0.001682  0.625904  0.531378
ERFL        2971.981503    3.940819e-06  0.001874  2.237414  0.025259
AQP4        3236.549121    1.071951e-06  0.001724  1.010972  0.312030
RASGRP2   118326.305370    1.516404e+00  0.640575  0.499277  0.617584
ELOB      582954.699722    1.363930e+00  0.390196 -1.445661  0.148272
...                 ...             ...       ...       ...       ...
HEXD      182603.077346    1.560244e+00  0.324100 -0.211109  0.832802
UNC13C      1231.018689    2.731260e-06  0.001514  0.849066  0.395845
GPX1      829632.441296    1.812511e+00  0.308741  0.107318  0.914536
PEF1      530234.698247    1.676928e+00  0.311675 -0.153304  0.878159
RPS10P28     566.280863   -1.626537e-07  0.001401 -0.153980  0.877626

              padj
KRT8P37   0.999995
ERFL      0.728285
AQP4      0.999995
RASGRP2   0.999995
ELOB      0.999995
...            ...
HEXD      0.999995
UNC13C    0.999995
GPX1      0.999995
PEF1      0.999995
RPS10P28  0.999995

[4988 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 605 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.08 seconds.

Fitting dispersion trend curve...
... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 1.22 seconds.

Fitting LFCs...
... done in 0.73 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 238 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.57 seconds.

Fitting MAP LFCs...
... done in 1.29 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
CRLF1      135635.122835        0.001455  0.108779  0.201796  0.840076
ARFGAP3    286091.196400        0.002105  0.096691 -0.755538  0.449926
KLB         38235.130649       -0.000077  0.104099 -0.124472  0.900942
EIF2AK3    220868.036495       -0.021826  0.102502 -0.986107  0.324081
APOH          878.888911        0.003111  0.306990  2.269510  0.023237
...                  ...             ...       ...       ...       ...
DERL1      619806.940139        0.001764  0.126059  0.559460  0.575848
GAD1         7909.443117       -0.003059  0.097853 -0.547825  0.583812
MRPL37P1      154.072690        0.007008  0.109696  0.585208  0.558408
RAB11FIP4  220213.500554        0.019891  0.104579  0.914654  0.360373
RPS15AP14     323.824373        0.007476  0.104177  0.438165  0.661267

               padj
CRLF1      0.987701
ARFGAP3    0.966583
KLB        0.989085
EIF2AK3    0.937865
APOH       0.556199
...             ...
DERL1      0.975056
GAD1       0.975056
MRPL37P1   0.972534
RAB11FIP4  0.949801
RPS15AP14  0.979043

[4988 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.97 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.29 seconds.

Fitting LFCs...
... done in 0.82 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 238 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 238)
Number of True values in replace_mask: 382
replacement_counts_trimmed shape: (20, 238)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.50 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
CRLF1      135635.122835    1.454783e+00  0.773711  0.201796  0.840076
ARFGAP3    286091.196400    1.565472e+00  0.281895 -0.755538  0.449926
KLB         38235.130649    8.834528e-01  1.530131 -0.124472  0.900942
EIF2AK3    220868.036495    1.425220e+00  0.312101 -0.986106  0.324081
APOH           40.872365    3.881789e+00  0.086562  0.026029  0.979234
...                  ...             ...       ...       ...       ...
DERL1      619806.940139    2.284274e+00  0.511373  0.545292  0.585553
GAD1         7909.443117   -5.702971e-07  0.001326 -0.547824  0.583813
MRPL37P1      154.072690    1.300398e-06  0.001516  0.584869  0.558636
RAB11FIP4  220213.500554    2.069262e+00  0.248242  0.914653  0.360374
RPS15AP14     323.824373    1.446876e-06  0.001479  0.437909  0.661452

               padj
CRLF1      0.999982
ARFGAP3    0.999982
KLB        0.999982
EIF2AK3    0.999982
APOH       0.999982
...             ...
DERL1      0.999982
GAD1       0.999982
MRPL37P1   0.999982
RAB11FIP4  0.999982
RPS15AP14  0.999982

[4988 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 575 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.08 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.27 seconds.

Fitting LFCs...
... done in 0.62 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 237 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.23 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.50 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
KLF7-IT1  1.768003e+03        0.015296  0.172365  2.090657  0.036559  0.584941
ATXN2     2.832312e+05        0.010072  0.103575  0.416095  0.677340  0.982660
PPDPF     1.553361e+06        0.005547  0.137338  1.043013  0.296942  0.903622
GDAP1     6.516757e+04       -0.004303  0.109702 -0.404732  0.685675  0.982827
FNBP1P1   5.804945e+03       -0.012105  0.106608 -0.984619  0.324811  0.916255
...                ...             ...       ...       ...       ...       ...
RGL1      2.175839e+05       -0.004533  0.110093 -0.372960  0.709178  0.983919
MESTP3    2.184752e+03       -0.032571  0.109475 -1.123267  0.261324  0.879358
IL22RA2   1.859347e+03       -0.006975  0.086232 -2.264337  0.023553  0.532030
SZT2-AS1  9.858602e+03        0.004870  0.152999  0.999370  0.317615  0.910469
MAX       4.032279e+05       -0.041197  0.121611 -1.058613  0.289776  0.900743

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.43 seconds.

Fitting dispersion trend curve...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 1.13 seconds.

Fitting LFCs...
... done in 0.95 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 237 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 237)
Number of True values in replace_mask: 392
replacement_counts_trimmed shape: (20, 237)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.19 seconds.

Fitting MAP LFCs...
... done in 1.47 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
KLF7-IT1  1.768003e+03    2.327833e-06  0.002130  2.090608  0.036563  0.691377
ATXN2     2.832312e+05    2.367882e+00  0.213774  0.416095  0.677341  0.999999
PPDPF     1.553361e+06    2.345601e+00  0.270147  1.043013  0.296942  0.971732
GDAP1     6.516757e+04    1.121103e+00  0.832783 -0.404731  0.685675  0.999999
FNBP1P1   5.804945e+03   -1.914387e-06  0.001329 -0.984607  0.324817  0.982183
...                ...             ...       ...       ...       ...       ...
RGL1      2.175839e+05    1.316053e+00  0.501621 -0.372960  0.709178  0.999999
MESTP3    2.184752e+03   -4.954622e-06  0.001385 -1.123063  0.261411  0.948288
IL22RA2   1.859347e+03   -1.117406e-06  0.001067 -2.264306  0.023555  0.650523
SZT2-AS1  9.858602e+03    6.429210e-07  0.001911  0.999368  0.317616  0.976339
MAX       4.032279e+05    1.136777e+00  0.742659 -1.058613  0.289776  0.968979

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 584 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.01 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.28 seconds.

Fitting LFCs...
... done in 0.63 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 226 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.25 seconds.

Fitting MAP LFCs...
... done in 1.39 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
PLD3       1.050219e+06        0.009840  0.110025  0.638207  0.523339
EBF1       2.649746e+05        0.023436  0.138523  1.956865  0.050363
ALKBH6     4.858036e+04       -0.019100  0.101218 -1.130146  0.258415
CRYZL1     1.159079e+05        0.008160  0.094859  0.122555  0.902460
GEMIN5     1.662765e+05       -0.096386  0.191455 -1.422610  0.154849
...                 ...             ...       ...       ...       ...
LPGAT1     1.656386e+06        0.001213  0.112573  0.201983  0.839930
ITGB8      8.146241e+04        0.009564  0.119957  0.499242  0.617609
RAB11FIP5  2.475290e+05       -0.021428  0.100350 -1.074964  0.282391
PRDM2      3.113290e+05        0.016060  0.106553 -0.098109  0.921846
HYI        3.140038e+05        0.001315  0.110219  0.200795  0.840859

               padj
PLD3       0.960202
EBF1       0.692724
ALKBH6     0.924094
CRYZL1     0.995695
GEMIN5     0.858585
...             ...
LPGAT1     0.992202
ITGB8      0.979075
RAB11FIP5  0.932873
PRDM2      0.995695
HYI        0.992202

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.13 seconds.

Fitting MAP dispersions...
... done in 1.31 seconds.

Fitting LFCs...
... done in 1.06 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 226 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...

replace_mask before filtering: (20, 226)
Number of True values in replace_mask: 390
replacement_counts_trimmed shape: (20, 226)

... done in 0.06 seconds.

Running Wald tests...
... done in 0.17 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.53 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
PLD3       1.050219e+06        2.009182  0.237465  0.638207  0.523339
EBF1       2.649746e+05        2.331109  0.429257  1.956864  0.050363
ALKBH6     4.858036e+04        1.078130  0.399935 -1.079385  0.280416
CRYZL1     1.159079e+05        2.166419  0.235162  0.122554  0.902460
GEMIN5     1.662765e+05        1.785534  0.247601 -1.422614  0.154848
...                 ...             ...       ...       ...       ...
LPGAT1     1.656386e+06        1.976448  0.290666  0.201979  0.839933
ITGB8      8.146241e+04        1.787296  1.024913  0.499241  0.617609
RAB11FIP5  2.475290e+05        1.773381  0.258775 -1.074963  0.282391
PRDM2      3.113290e+05        1.765597  0.307041 -0.098109  0.921846
HYI        3.140038e+05        1.739095  0.662498  0.200795  0.840859

               padj
PLD3       0.999986
EBF1       0.810245
ALKBH6     0.999986
CRYZL1     0.999986
GEMIN5     0.935113
...             ...
LPGAT1     0.999986
ITGB8      0.999986
RAB11FIP5  0.999986
PRDM2      0.999986
HYI        0.999986

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 588 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.02 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.27 seconds.

Fitting LFCs...
... done in 0.61 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 233 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.21 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.59 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
MAP4K3-DT  3.128291e+04       -0.001169  0.053213 -0.335757  0.737054
HDAC2-AS2  1.931345e+03        0.002450  0.057074  0.649134  0.516252
UFM1       4.104531e+05        0.002745  0.055251  0.374266  0.708206
FOXO3B     3.777229e+04       -0.000458  0.053833 -0.161714  0.871531
FBXO48     1.976408e+04        0.002910  0.053534  0.382613  0.702007
...                 ...             ...       ...       ...       ...
SHQ1       1.079541e+05       -0.005154  0.052084 -0.749690  0.453441
SLC25A38   1.662446e+05       -0.001657  0.044246 -1.501932  0.133115
SARS2      6.122193e+03        0.000645  0.070121  0.303274  0.761681
SSX2IP     1.048685e+05        0.013898  0.066277  2.528282  0.011462
MAP4       2.098683e+06        0.003114  0.058990  0.898150  0.369106

               padj
MAP4K3-DT  0.993367
HDAC2-AS2  0.993367
UFM1       0.993367
FOXO3B     0.993367
FBXO48     0.993367
...             ...
SHQ1       0.993367
SLC25A38   0.912501
SARS2      0.993367
SSX2IP     0.517348
MAP4       0.993367

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.08 seconds.

Fitting dispersion trend curve...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 1.69 seconds.

Fitting LFCs...
... done in 0.75 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 233 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 233)
Number of True values in replace_mask: 398
replacement_counts_trimmed shape: (20, 233)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.73 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
MAP4K3-DT  3.128291e+04       -0.669264  0.572292 -0.335756  0.737055
HDAC2-AS2  1.931345e+03        0.000002  0.001512  0.649092  0.516279
UFM1       4.104531e+05        1.890526  0.248917  0.374266  0.708206
FOXO3B     3.777229e+04        0.914039  0.675892 -0.161713  0.871532
FBXO48     1.976408e+04        0.000005  0.001461  0.382603  0.702014
...                 ...             ...       ...       ...       ...
SHQ1       1.079541e+05        1.205388  0.511505 -0.749690  0.453442
SLC25A38   1.662446e+05       -0.000008  0.001162 -1.521279  0.128190
SARS2      2.993084e+03        1.179114  0.011584 -0.006863  0.994524
SSX2IP     1.048685e+05        2.119943  0.267568  2.528274  0.011462
MAP4       2.098683e+06        2.055958  0.169886  0.898163  0.369099

               padj
MAP4K3-DT  0.999987
HDAC2-AS2  0.999987
UFM1       0.999987
FOXO3B     0.999987
FBXO48     0.999987
...             ...
SHQ1       0.999987
SLC25A38   0.999987
SARS2      0.999987
SSX2IP     0.644000
MAP4       0.999987

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 586 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4996 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.26 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.19 seconds.

Fitting LFCs...
... done in 0.60 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 233 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.19 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.63 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SDHB       2.962558e+05       -0.028503  0.081824 -2.132167  0.032993
LPL        2.545121e+06       -0.020619  0.067419 -2.036275  0.041723
RPS2       2.262048e+06       -0.003219  0.086383  1.983237  0.047341
LINC00881  4.492657e+02       -0.000106  0.075305 -0.067764  0.945974
LRP5       5.665668e+05        0.004547  0.077870  0.389603  0.696830
...                 ...             ...       ...       ...       ...
EMC8       1.704017e+05        0.015475  0.102845  2.098048  0.035901
USP15      2.825581e+05        0.005669  0.089227  1.260873  0.207355
MS4A6A     2.222917e+05       -0.006917  0.072099 -0.923059  0.355976
DDI2       5.347499e+05       -0.002619  0.073191 -0.389572  0.696853
ZEB2-AS1   6.495401e+03       -0.001779  0.061769 -2.340931  0.019236

               padj
SDHB       0.594124
LPL        0.647351
RPS2       0.659962
LINC00881  0.998355
LRP5       0.993766
...             ...
EMC8       0.610071
USP15      0.911180
MS4A6A     0.952071
DDI2       0.993766
ZEB2-AS1   0.520423

[4996 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.08 seconds.

Fitting dispersion trend curve...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 1.54 seconds.

Fitting LFCs...
... done in 0.77 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 233 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 233)
Number of True values in replace_mask: 393
replacement_counts_trimmed shape: (20, 233)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.17 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.32 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SDHB       2.962558e+05    1.653151e+00  0.265242 -2.132165  0.032993
LPL        2.545121e+06    1.011739e+00  0.386891 -2.036275  0.041723
RPS2       2.262048e+06    2.424382e+00  0.161703  1.983237  0.047341
LINC00881  4.492657e+02   -8.164954e-09  0.001420 -0.067762  0.945975
LRP5       5.665668e+05    1.852256e+00  0.303111  0.389603  0.696830
...                 ...             ...       ...       ...       ...
EMC8       1.704017e+05    2.354147e+00  0.506666  2.098048  0.035901
USP15      2.825581e+05    2.140837e+00  0.462952  1.260868  0.207356
MS4A6A     2.222917e+05    1.508933e+00  0.325282 -0.923059  0.355977
DDI2       5.347499e+05    1.597771e+00  0.420964 -0.389572  0.696853
ZEB2-AS1   8.458171e+02   -1.703751e+00  0.020947  0.019185  0.984693

               padj
SDHB       0.705515
LPL        0.757185
RPS2       0.765786
LINC00881  0.999995
LRP5       0.999995
...             ...
EMC8       0.720326
USP15      0.990714
MS4A6A     0.999995
DDI2       0.999995
ZEB2-AS1   0.999995

[4996 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 543 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.21 seconds.

Fitting dispersion trend curve...
... done in 0.15 seconds.

Fitting MAP dispersions...
... done in 1.34 seconds.

Fitting LFCs...
... done in 0.70 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 227 outlier genes.

Fitting dispersions...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.11 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.23 seconds.

Fitting MAP LFCs...
... done in 1.44 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SYT2        7867.087272       -0.002846  0.090318 -0.429699  0.667415
PFKFB2    124841.373088       -0.005475  0.089901 -0.596867  0.550596
NMRAL1    229553.504738       -0.004070  0.088239 -0.798634  0.424503
CDKN2A     50896.608544       -0.001933  0.088114  0.535578  0.592250
C12orf43   78648.315477        0.012812  0.087943  0.581806  0.560697
...                 ...             ...       ...       ...       ...
ATXN1     264906.463695       -0.002622  0.099950  0.387290  0.698542
SEC11B     15242.386335        0.011184  0.079285  0.415629  0.677682
ATP8A1    106641.834729       -0.008501  0.094595  0.176821  0.859649
PRSS22     64461.797030        0.002180  0.093090  0.171300  0.863988
EMC1-AS1   11382.575550       -0.001163  0.092184 -0.111177  0.911476

              padj
SYT2      0.982514
PFKFB2    0.965576
NMRAL1    0.950050
CDKN2A    0.975247
C12orf43  0.965792
...            ...
ATXN1     0.986318
SEC11B    0.982514
ATP8A1    0.990706
PRSS22    0.990706
EMC1-AS1  0.994039

[4988 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.13 seconds.

Fitting dispersion trend curve...
... done in 0.37 seconds.

Fitting MAP dispersions...
... done in 1.79 seconds.

Fitting LFCs...
... done in 1.25 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 227 outlier genes.

Fitting dispersions...

replace_mask before filtering: (20, 227)
Number of True values in replace_mask: 382
replacement_counts_trimmed shape: (20, 227)

... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.21 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.95 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SYT2        7867.087272   -3.742789e-07  0.001376 -0.429697  0.667416
PFKFB2    124841.373088    1.330351e+00  0.461181 -0.596866  0.550597
NMRAL1    229553.504738    1.243128e+00  0.522804 -0.798633  0.424503
CDKN2A     19247.659701   -4.581914e-01  0.006038 -0.000438  0.999650
C12orf43   78648.315477    2.612920e-01  0.283926  0.581802  0.560700
...                 ...             ...       ...       ...       ...
ATXN1     264906.463695    1.768621e+00  0.572269  0.387290  0.698542
SEC11B     15242.386335    3.263271e-06  0.001457  0.415598  0.677704
ATP8A1    106641.834729    1.447377e+00  0.375022  0.176820  0.859649
PRSS22     64461.797030    1.514918e+00  0.349752  0.178742  0.858140
EMC1-AS1   11382.575550   -1.494008e-06  0.001432 -0.111176  0.911477

              padj
SYT2      0.999998
PFKFB2    0.999998
NMRAL1    0.999998
CDKN2A    0.999998
C12orf43  0.999998
...            ...
ATXN1     0.999998
SEC11B    0.999998
ATP8A1    0.999998
PRSS22    0.999998
EMC1-AS1  0.999998

[4988 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 617 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.90 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.30 seconds.

Fitting LFCs...
... done in 0.94 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 207 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.33 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CCDC183   3.344215e+04        0.001613  0.071350  0.431881  0.665828  0.992491
OLFM5P    1.286027e+03        0.002589  0.080435  0.973243  0.330433  0.987492
CLEC14A   2.473913e+05        0.006092  0.071699  0.363076  0.716548  0.992989
PLPPR1    2.067335e+03       -0.000856  0.063063 -0.434870  0.663657  0.992491
GALM      9.686211e+04       -0.004441  0.066255 -0.344296  0.730623  0.993608
...                ...             ...       ...       ...       ...       ...
POGK      4.513344e+05        0.001818  0.068712  0.177286  0.859284  0.997156
C12orf71  6.285966e+02       -0.002278  0.065805 -0.331696  0.740119  0.994872
CDKAL1    1.442608e+05       -0.004642  0.068845  0.022142  0.982335  0.999398
ATP11A    2.375873e+05       -0.005632  0.070375  0.383551  0.701311  0.992989
COL4A1    3.231771e+06        0.001856  0.072364  0.570850  0.568101  0.989884

[4991 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.91 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.19 seconds.

Fitting LFCs...
... done in 0.87 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 207 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 207)
Number of True values in replace_mask: 352
replacement_counts_trimmed shape: (20, 207)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
... done in 1.72 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CCDC183   3.344215e+04    1.217462e+00  0.792846  0.431881  0.665828  0.999992
OLFM5P    1.286027e+03    1.101594e-06  0.001704  0.973221  0.330443  0.999992
CLEC14A   2.473913e+05    1.731149e+00  0.530694  0.365579  0.714679  0.999992
PLPPR1    2.067335e+03   -4.602370e-07  0.001334 -0.434867  0.663659  0.999992
GALM      9.686211e+04    1.283036e+00  0.401695 -0.344296  0.730624  0.999992
...                ...             ...       ...       ...       ...       ...
POGK      4.513344e+05    1.728010e+00  0.357963  0.177286  0.859284  0.999992
C12orf71  6.285966e+02   -9.882990e-07  0.001416 -0.331600  0.740191  0.999992
CDKAL1    1.442608e+05    1.386292e+00  0.906507  0.022142  0.982335  0.999992
ATP11A    2.375873e+05    1.631874e+00  0.414415  0.383551  0.701311  0.999992
COL4A1    3.231771e+06    2.052152e+00  0.160151  0.570850  0.568101  0.999992

[4991 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 573 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.83 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.18 seconds.

Fitting LFCs...
... done in 0.58 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 230 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.20 seconds.

Fitting MAP LFCs...
... done in 1.32 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
ACP2      233744.192360        0.024583  0.102247  1.222780  0.221413
RBM42     342585.764116        0.005636  0.087538 -0.229270  0.818659
FOSB      273094.347327       -0.001926  0.083440 -0.519196  0.603624
TPRG1L    353853.916397        0.001125  0.083180  0.018406  0.985315
LY86       19862.491155       -0.001088  0.088315 -0.178705  0.858169
...                 ...             ...       ...       ...       ...
NHSL1      85968.462481        0.025872  0.108493  1.814643  0.069579
TRMT13     93371.711819       -0.001583  0.084016 -0.444443  0.656722
SERPINA9    1425.965346        0.000505  0.093356  0.135664  0.892087
VPS26B    274438.349464        0.028116  0.089896  0.954524  0.339818
TNIP1     830756.285294        0.021496  0.099851  1.473317  0.140666

              padj
ACP2      0.910129
RBM42     0.994006
FOSB      0.983065
TPRG1L    0.999432
LY86      0.994006
...            ...
NHSL1     0.776889
TRMT13    0.987865
SERPINA9  0.997671
VPS26B    0.942829
TNIP1     0.862847

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.73 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.16 seconds.

Fitting LFCs...
... done in 0.82 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 230 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 230)
Number of True values in replace_mask: 403
replacement_counts_trimmed shape: (20, 230)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.18 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.37 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
ACP2      233744.192360    1.964368e+00  0.290909  1.222779  0.221413
RBM42     342585.764116    1.758931e+00  0.287490 -0.229270  0.818659
FOSB      273094.347327    1.225316e+00  1.070418 -0.519196  0.603624
TPRG1L    353853.916397    2.398684e+00  0.221109  0.018406  0.985315
LY86       19862.491155    6.707081e-07  0.001415 -0.178705  0.858170
...                 ...             ...       ...       ...       ...
NHSL1      85968.462481    1.785076e+00  0.355520  1.814639  0.069579
TRMT13     93371.711819    1.098816e+00  2.392760 -0.444443  0.656722
SERPINA9    1425.965346    1.291829e-07  0.001487  0.135663  0.892088
VPS26B    274438.349464    3.250629e+00  0.220870  0.954522  0.339819
TNIP1     830756.285294    2.338076e+00  0.195143  1.473317  0.140666

              padj
ACP2      0.981787
RBM42     0.999999
FOSB      0.999999
TPRG1L    0.999999
LY86      0.999999
...            ...
NHSL1     0.866211
TRMT13    0.999999
SERPINA9  0.999999
VPS26B    0.999999
TNIP1     0.935458

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 561 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.58 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.27 seconds.

Fitting LFCs...
... done in 0.73 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 248 outlier genes.

Fitting dispersions...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
... done in 1.57 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SLC22A2  2.626987e+02        0.000637  0.072963  0.452647  0.650803  0.988421
TENT5B   1.511908e+05       -0.001901  0.057979 -0.955398  0.339377  0.950178
LCMT1    1.908267e+05       -0.011062  0.067077  0.226188  0.821055  0.998158
ERICH5   5.317971e+03        0.001435  0.101112  1.247792  0.212107  0.937120
SNORD89  4.087404e+03       -0.002332  0.061776 -0.397105  0.691290  0.994273
...               ...             ...       ...       ...       ...       ...
CNBP     1.682560e+06       -0.005634  0.055910 -1.617722  0.105723  0.815367
SARS2    1.022317e+05       -0.001531  0.058927 -0.588269  0.556352  0.985111
NUDT21   4.869719e+05       -0.000370  0.060759 -0.367764  0.713049  0.996863
ARAP2    8.582521e+04        0.002912  0.063124  0.360841  0.718218  0.998158
ZNF564   5.703372e+04        0.006777  0.069061  0.484890  0.627754  0.986275

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.11 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.53 seconds.

Fitting LFCs...
... done in 1.13 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 248 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 248)
Number of True values in replace_mask: 420
replacement_counts_trimmed shape: (20, 248)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.17 seconds.

Fitting MAP LFCs...
... done in 1.15 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SLC22A2  2.626987e+02    3.226052e-07  0.001644  0.452631  0.650815  0.999997
TENT5B   1.511908e+05    9.630689e-01  0.976908 -0.955397  0.339377  0.999997
LCMT1    1.908267e+05    1.688528e+00  0.330560  0.226188  0.821055  0.999997
ERICH5   5.317971e+03    8.063147e-07  0.002277  1.247787  0.212109  0.999997
SNORD89  4.087404e+03   -1.345552e-06  0.001410 -0.397089  0.691302  0.999997
...               ...             ...       ...       ...       ...       ...
CNBP     1.682560e+06    1.345462e+00  0.267883 -1.617722  0.105723  0.914196
SARS2    1.022317e+05    1.161196e+00  1.086187 -0.588269  0.556352  0.999997
NUDT21   4.869719e+05    1.519321e+00  0.553133 -0.367768  0.713046  0.999997
ARAP2    8.582521e+04    1.868552e+00  0.266481  0.360840  0.718219  0.999997
ZNF564   5.703372e+04    1.541075e+00  0.728646  0.484890  0.627754  0.999997

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 573 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.44 seconds.

Fitting LFCs...
... done in 0.64 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 237 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.52 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat    pvalue  \
BNIP3P1       61803.794743        0.002322  0.085588  0.282412  0.777628
TRIL         135877.234773        0.007818  0.093897  0.926501  0.354186
SNORD116-21     236.195951        0.001639  0.093242  0.471368  0.637378
KAT2B        154352.719817        0.016321  0.098190  1.619953  0.105242
RRM1         462472.299471        0.016614  0.088825  0.040155  0.967970
...                    ...             ...       ...       ...       ...
MADD         279832.988968        0.011202  0.086274 -0.045628  0.963606
WDR83OS      463169.747915       -0.001416  0.079900 -0.390555  0.696127
GHITM        943261.450267        0.008327  0.089645  0.528012  0.597491
CUTC         133941.473788        0.015774  0.073097  0.609373  0.542278
PMP2           5899.671175        0.002783  0.083652  0.253308  0.800030

                 padj
BNIP3P1      0.992234
TRIL         0.949469
SNORD116-21  0.978140
KAT2B        0.831277
RRM1         0.998028
...               ...
MADD         0.998028
WDR83OS      0.988645
GHITM        0.968107
CUTC         0.966812
PMP2         0.992234

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.03 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.49 seconds.

Fitting LFCs...
... done in 0.95 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 237 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 237)
Number of True values in replace_mask: 415
replacement_counts_trimmed shape: (20, 237)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.19 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 3.19 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat    pvalue  \
BNIP3P1       61803.794743    1.314882e+00  0.483901  0.282411  0.777628
TRIL         135877.234773    1.723196e+00  0.544283  0.926500  0.354186
SNORD116-21     236.195951    4.649692e-07  0.001584  0.471331  0.637404
KAT2B        154352.719817    2.020069e+00  0.347162  1.619952  0.105243
RRM1         462472.299471    1.675752e+00  0.362647  0.040154  0.967970
...                    ...             ...       ...       ...       ...
MADD         279832.988968    1.489292e+00  1.043750 -0.045629  0.963606
WDR83OS      463169.747915    1.454510e+00  0.653599 -0.390555  0.696127
GHITM        943261.450267    1.964154e+00  0.268014  0.528011  0.597492
CUTC         133941.473788    2.387894e-01  0.149593  0.609367  0.542281
PMP2           5899.671175    8.943562e-07  0.001464  0.253300  0.800036

                 padj
BNIP3P1      0.999996
TRIL         0.999996
SNORD116-21  0.999996
KAT2B        0.911968
RRM1         0.999996
...               ...
MADD         0.999996
WDR83OS      0.999996
GHITM        0.999996
CUTC         0.999996
PMP2         0.999996

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 548 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.16 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.69 seconds.

Fitting LFCs...
... done in 0.68 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 218 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.19 seconds.

Fitting MAP LFCs...
... done in 1.39 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
HMMR-AS1     3383.564525        0.001571  0.099270  0.538154  0.590471
ZNRF2P2      4311.328335        0.008639  0.091478  0.919788  0.357683
CCT6B       23492.798740        0.005964  0.093241  0.819880  0.412285
CCDC201       125.742000        0.001416  0.105518 -0.606990  0.543858
HDGFL1        388.446321        0.001277  0.116300  2.303265  0.021264
...                  ...             ...       ...       ...       ...
CCDC162P    22387.968508        0.005447  0.093445  1.080684  0.279838
LINC00240    4564.962591        0.000870  0.091952  0.452288  0.651062
DDX27      675404.516378        0.000669  0.094151  0.492462  0.622393
DEGS1      714908.192284        0.002512  0.081322 -0.695345  0.486839
RPS3AP37      157.508416       -0.008490  0.077636 -1.357230  0.174708

               padj
HMMR-AS1   0.968867
ZNRF2P2    0.939011
CCT6B      0.947601
CCDC201    0.962312
HDGFL1     0.609091
...             ...
CCDC162P   0.925146
LINC00240  0.976193
DDX27      0.973768
DEGS1      0.959077
RPS3AP37   0.875811

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.00 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.86 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.17 seconds.

Fitting LFCs...
... done in 0.72 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 218 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (20, 218)
Number of True values in replace_mask: 358
replacement_counts_trimmed shape: (20, 218)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.17 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.28 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
HMMR-AS1     3383.564525    3.986368e-07  0.001655  0.538152  0.590472
ZNRF2P2      4311.328335    2.462532e-06  0.001543  0.919762  0.357697
CCT6B       23492.798740    1.596926e-06  0.001565  0.819877  0.412286
CCDC201        68.345386    9.844023e-01  0.070079  0.004785  0.996182
HDGFL1         64.519396    1.413310e+00  0.066577 -0.065431  0.947831
...                  ...             ...       ...       ...       ...
CCDC162P    22387.968508    1.101078e-06  0.001580  1.080679  0.279840
LINC00240    3464.722166    3.441501e-01  0.012597 -0.002184  0.998257
DDX27      675404.516378    2.028261e+00  0.450442  0.492462  0.622393
DEGS1      714908.192284    1.686512e+00  0.311062 -0.695345  0.486839
RPS3AP37      157.508416   -2.155244e-06  0.001282 -1.356687  0.174881

               padj
HMMR-AS1   0.999998
ZNRF2P2    0.999998
CCT6B      0.999998
CCDC201    0.999998
HDGFL1     0.999998
...             ...
CCDC162P   0.994250
LINC00240  0.999998
DDX27      0.999998
DEGS1      0.999998
RPS3AP37   0.950050

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 577 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4994 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.15 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.46 seconds.

Fitting LFCs...
... done in 0.95 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 412 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.16 seconds.

Fitting MAP dispersions...
... done in 0.22 seconds.

Fitting LFCs...
... done in 0.14 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.69 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
RTKN       235445.185422       -0.011072  0.057901 -1.427129  0.153543
RPL31P2      4459.113100        0.002045  0.061238  0.425485  0.670483
MIR6746      1530.763234       -0.004077  0.050837 -1.757047  0.078910
CYTH2      582228.212571       -0.001213  0.057282 -0.115759  0.907844
RNF112      17638.831744        0.003258  0.068229  1.097841  0.272274
...                  ...             ...       ...       ...       ...
MYL1         2066.875228       -0.002453  0.049331 -1.530959  0.125780
PPIAP16       365.572137       -0.005950  0.055274 -1.415619  0.156887
LINC02084    1193.894046        0.009231  0.061294  1.021295  0.307115
MIR202HG      589.869170       -0.015146  0.059074 -1.279599  0.200686
LRIG3      212485.849290        0.010503  0.079120  2.631100  0.008511

               padj
RTKN       0.829970
RPL31P2    0.969294
MIR6746    0.737209
CYTH2      0.994225
RNF112     0.903291
...             ...
MYL1       0.800179
PPIAP16    0.831729
LINC02084  0.918918
MIR202HG   0.852319
LRIG3      0.404794

[4994 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.28 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.32 seconds.

Fitting LFCs...
... done in 0.77 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 412 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 412)
Number of True values in replace_mask: 895
replacement_counts_trimmed shape: (40, 412)

... done in 0.11 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.37 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
RTKN       235445.185422        1.205426  0.320074 -1.427128  0.153543
RPL31P2      4459.113100        0.000001  0.001485  0.425479  0.670488
MIR6746      1530.763234       -0.000002  0.001211 -1.757022  0.078914
CYTH2      582228.212571        1.935920  0.161285 -0.115759  0.907844
RNF112      17638.831744        1.348663  0.709921  1.097839  0.272275
...                  ...             ...       ...       ...       ...
MYL1         2066.875228       -0.000001  0.001180 -1.530951  0.125781
PPIAP16       365.572137       -0.000004  0.001315 -1.415403  0.156950
LINC02084    1193.894046        0.000005  0.001495  1.021076  0.307218
MIR202HG      589.869170       -0.000009  0.001398 -1.278659  0.201017
LRIG3      212485.849290        2.380515  0.349301  2.631100  0.008511

               padj
RTKN       0.948487
RPL31P2    1.000000
MIR6746    0.873016
CYTH2      1.000000
RNF112     1.000000
...             ...
MYL1       0.924276
PPIAP16    0.948487
LINC02084  1.000000
MIR202HG   0.965524
LRIG3      0.566713

[4994 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 546 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.16 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.38 seconds.

Fitting LFCs...
... done in 0.69 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 390 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.13 seconds.

Fitting LFCs...
... done in 0.27 seconds.

Running Wald tests...
... done in 0.67 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.87 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat    pvalue  \
C5            48645.463766       -0.001292  0.033629 -0.067924  0.945846
ENPEP        132816.508085        0.001444  0.035007  0.465088  0.641868
MIR1469         177.340202        0.000311  0.034949  0.320304  0.748738
ENTPD5       246590.139578       -0.005481  0.032710 -1.576873  0.114825
TMEM243       93817.039987       -0.006008  0.033043 -1.833140  0.066782
...                    ...             ...       ...       ...       ...
CCNJL          7178.315908       -0.000255  0.031553 -0.198332  0.842785
ZRANB2       613790.664256        0.001156  0.034939  0.856305  0.391829
RAPGEF4-AS1     267.358137        0.000119  0.034318  0.132742  0.894397
HCN3          38021.631148        0.001719  0.035509  0.928553  0.353121
ANGPTL1      147897.019125        0.000473  0.033671  0.165251  0.868746

                 padj
C5           0.996452
ENPEP        0.986371
MIR1469      0.986371
ENTPD5       0.873967
TMEM243      0.826901
...               ...
CCNJL        0.991013
ZRANB2       0.953399
RAPGEF4-AS1  0.996452
HCN3         0.952891
ANGPTL1      0.995254

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.56 seconds.

Fitting LFCs...
... done in 0.92 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 390 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 390)
Number of True values in replace_mask: 861
replacement_counts_trimmed shape: (40, 390)

... done in 0.11 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.51 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat    pvalue  \
C5            48645.463766    1.184403e+00  0.384335 -0.067924  0.945846
ENPEP        132816.508085    1.513118e+00  0.408298  0.465088  0.641868
MIR1469         177.340202    5.714059e-07  0.001493  0.320254  0.748775
ENTPD5       246590.139578    1.394557e+00  0.224738 -1.576872  0.114825
TMEM243       93817.039987    1.216562e+00  0.206462 -1.833135  0.066783
...                    ...             ...       ...       ...       ...
CCNJL          3798.155276   -4.854745e-01  0.005851  0.004698  0.996252
ZRANB2       613790.664256    1.874432e+00  0.196367  0.856305  0.391829
RAPGEF4-AS1     267.358137    2.182645e-07  0.001466  0.132731  0.894406
HCN3          38021.631148    1.257842e+00  0.331716  0.928550  0.353122
ANGPTL1      147897.019125    1.530808e+00  0.226447  0.165251  0.868746

                 padj
C5           0.999988
ENPEP        0.999988
MIR1469      0.999988
ENTPD5       0.999988
TMEM243      0.985932
...               ...
CCNJL        0.999988
ZRANB2       0.999988
RAPGEF4-AS1  0.999988
HCN3         0.999988
ANGPTL1      0.999988

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 603 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.36 seconds.

Fitting dispersion trend curve...
... done in 0.74 seconds.

Fitting MAP dispersions...
... done in 2.45 seconds.

Fitting LFCs...
... done in 1.12 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 401 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.16 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 2.55 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
GBP5     104486.497552       -0.002275  0.049860 -0.937595  0.348452  0.959859
CXCL3      6941.705761       -0.001147  0.051059 -0.532532  0.594358  0.977692
ARID1B   509920.606073       -0.015084  0.055230 -0.784301  0.432864  0.964912
DYNLRB2    5294.475101       -0.003087  0.050235 -1.004708  0.315037  0.951264
SLIT1     22387.499069       -0.000147  0.053524 -0.076518  0.939007  0.997527
...                ...             ...       ...       ...       ...       ...
MIR4656     175.036377       -0.007833  0.050413 -1.805849  0.070942  0.797087
GRXCR2      157.070089       -0.000077  0.052555 -0.016405  0.986911  0.999030
ELK4     346979.297378       -0.001394  0.053776  0.034957  0.972114  0.997573
CLEC4D     1042.095275        0.001598  0.054922  0.390533  0.696143  0.988163
CC2D1A   331519.052537       -0.002528  0.051064 -0.335096  0.737553  0.988163

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.03 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.46 seconds.

Fitting LFCs...
... done in 0.89 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 401 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 401)
Number of True values in replace_mask: 868
replacement_counts_trimmed shape: (40, 401)

... done in 0.11 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.48 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
GBP5     104486.497552    9.738576e-01  0.708940 -0.937595  0.348453  0.999982
CXCL3      6941.705761    1.196974e-07  0.001363 -0.534830  0.592767  0.999982
ARID1B   509920.606073    2.416843e+00  0.146667 -0.784300  0.432864  0.999982
DYNLRB2    5294.475101   -1.174423e-06  0.001338 -1.004700  0.315042  0.999982
SLIT1     22387.499069   -4.801213e-08  0.001430 -0.076518  0.939007  0.999982
...                ...             ...       ...       ...       ...       ...
MIR4656     175.036377   -5.512319e-06  0.001314 -1.804915  0.071088  0.927862
GRXCR2      157.070089   -7.064149e-08  0.001442 -0.016384  0.986928  0.999982
ELK4     346979.297378    1.676322e+00  0.282413  0.034957  0.972114  0.999982
CLEC4D     1042.095275    1.183183e-06  0.001479  0.390504  0.696164  0.999982
CC2D1A   331519.052537    2.020179e+00  0.169947 -0.335095  0.737553  0.999982

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 560 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.88 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.26 seconds.

Fitting LFCs...
... done in 0.53 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 378 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.11 seconds.

Fitting LFCs...
... done in 0.18 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.76 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
RASL11B    31029.762959        0.000167  0.037316  0.130861  0.895886
CD101      11390.274766       -0.000470  0.035614 -0.385600  0.699793
PTGES3L     7364.024612       -0.002379  0.034800 -1.152889  0.248956
NCOA1     460283.650479       -0.002156  0.036020 -0.410489  0.681447
SRP19     172522.747656       -0.000998  0.035703 -0.287220  0.773944
...                 ...             ...       ...       ...       ...
CHCHD4P4     282.792046       -0.000311  0.034201 -0.477602  0.632933
TCFL5      78808.670482       -0.000228  0.038169  0.394166  0.693459
ZNF384    339019.095102        0.004553  0.041575  1.838544  0.065982
FBXO27     44132.724501        0.000468  0.043335 -0.125267  0.900312
ZSCAN10      192.410935       -0.004208  0.034821 -1.679213  0.093111

              padj
RASL11B   0.999399
CD101     0.999399
PTGES3L   0.950093
NCOA1     0.999399
SRP19     0.999399
...            ...
CHCHD4P4  0.999399
TCFL5     0.999399
ZNF384    0.827763
FBXO27    0.999399
ZSCAN10   0.857725

[4993 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.12 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.50 seconds.

Fitting LFCs...
... done in 1.06 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 378 outlier genes.

Fitting dispersions...

replace_mask before filtering: (40, 378)
Number of True values in replace_mask: 797
replacement_counts_trimmed shape: (40, 378)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.19 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.35 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.67 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
RASL11B    31029.762959    1.115075e+00  0.632810  0.130860  0.895886
CD101      11390.274766   -7.069410e-07  0.001393 -0.385598  0.699794
PTGES3L     7364.024612   -5.695512e-06  0.001357 -1.152875  0.248962
NCOA1     460283.650479    1.841142e+00  0.174322 -0.410489  0.681447
SRP19     172522.747656    2.036377e+00  0.166966 -0.287220  0.773944
...                 ...             ...       ...       ...       ...
CHCHD4P4     282.792046   -4.416466e-07  0.001336 -0.477582  0.632948
TCFL5      78808.670482    1.604906e+00  0.447832  0.394165  0.693460
ZNF384    339019.095102    1.990537e+00  0.242993  1.838543  0.065982
FBXO27     19947.676771    7.324097e-01  0.002823  0.000147  0.999882
ZSCAN10      192.410935   -6.373614e-06  0.001343 -1.678026  0.093342

              padj
RASL11B   0.999999
CD101     0.999999
PTGES3L   0.999999
NCOA1     0.999999
SRP19     0.999999
...            ...
CHCHD4P4  0.999999
TCFL5     0.999999
ZNF384    0.977482
FBXO27    0.999999
ZSCAN10   0.977482

[4993 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 587 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.98 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.41 seconds.

Fitting LFCs...
... done in 0.85 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 394 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 0.14 seconds.

Fitting LFCs...
... done in 0.20 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.36 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SPOCK2   140824.275831        0.010873  0.062398  2.060807  0.039321  0.701867
NR4A3     86772.909719       -0.000620  0.047361 -1.054233  0.291776  0.980059
NPR1     470573.294673       -0.002285  0.055832  0.730903  0.464838  0.992103
ABHD17C  104860.197835       -0.000899  0.050699 -0.312738  0.754479  0.993953
PHYHIP    74414.144626       -0.007292  0.046618 -1.831506  0.067025  0.758464
...                ...             ...       ...       ...       ...       ...
NAALAD2   24243.263791        0.001225  0.054534  0.482119  0.629722  0.993953
SNORA9     1977.555944       -0.004525  0.048194 -0.488972  0.624861  0.993953
NT5DC1   201656.335515       -0.002387  0.050157 -0.377117  0.706086  0.993953
CEP57L1   43247.396721       -0.012886  0.052136 -1.825071  0.067990  0.758464
ARPC4    858877.406121       -0.007647  0.050093 -1.225739  0.220297  0.951111

[4989 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.02 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.85 seconds.

Fitting LFCs...
... done in 1.13 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 394 outlier genes.

Fitting dispersions...

replace_mask before filtering: (40, 394)
Number of True values in replace_mask: 870
replacement_counts_trimmed shape: (40, 394)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.11 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.38 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.87 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SPOCK2   140824.275831        2.077746  0.274297  2.060806  0.039322  0.904361
NR4A3     86772.909719        1.139014  0.596237 -1.054233  0.291776  0.999997
NPR1     470573.294673        1.966331  0.304234  0.730903  0.464838  0.999997
ABHD17C  104860.197835        1.474597  0.402041 -0.312738  0.754479  0.999997
PHYHIP    74414.144626        0.857507  0.713896 -1.831512  0.067024  0.928413
...                ...             ...       ...       ...       ...       ...
NAALAD2   24243.263791        1.157910  0.661701  0.482118  0.629722  0.999997
SNORA9     1977.555944       -0.000004  0.001428 -0.488814  0.624973  0.999997
NT5DC1   201656.335515        1.567025  0.212936 -0.377117  0.706087  0.999997
CEP57L1   43247.396721       -0.525531  0.248826 -1.825061  0.067992  0.928413
ARPC4    858877.406121        1.994960  0.155635 -1.225739  0.220297  0.999997

[4989 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 577 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.11 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.44 seconds.

Fitting LFCs...
... done in 0.71 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 393 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.21 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.77 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
ENHO        2.798735e+04        0.004490  0.064781  1.796855  0.072359
RPSAP36     8.552973e+02        0.000424  0.054027  0.195956  0.844645
KRT8        5.057735e+06        0.000420  0.052900  0.021136  0.983137
MAP2K4      1.769543e+05       -0.010855  0.051531 -1.565388  0.117492
MARCKSL1P1  3.759253e+02       -0.000776  0.049548 -0.479479  0.631598
...                  ...             ...       ...       ...       ...
FAM83A-AS1  9.477711e+02       -0.003191  0.048904 -0.333775  0.738549
MIR2110     7.882239e+02        0.008449  0.058835  1.706417  0.087930
ALOX12      1.190052e+04       -0.004839  0.049670 -1.207800  0.227124
OR52N4      1.540697e+03       -0.001467  0.049709 -0.635619  0.525025
ACSBG2      1.974971e+03        0.000292  0.054279  0.171340  0.863956

                padj
ENHO        0.813545
RPSAP36     0.999705
KRT8        0.999705
MAP2K4      0.885625
MARCKSL1P1  0.998155
...              ...
FAM83A-AS1  0.999705
MIR2110     0.846341
ALOX12      0.929822
OR52N4      0.985195
ACSBG2      0.999705

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.24 seconds.

Fitting dispersion trend curve...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 1.38 seconds.

Fitting LFCs...
... done in 0.83 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 393 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 393)
Number of True values in replace_mask: 846
replacement_counts_trimmed shape: (40, 393)

... done in 0.10 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.35 seconds.

Fitting MAP LFCs...
... done in 2.00 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
ENHO        2.798735e+04    1.861423e+00  0.567568  1.796854  0.072359
RPSAP36     8.552973e+02    2.278312e-07  0.001477  0.195951  0.844648
KRT8        5.057735e+06    1.843840e+00  0.118095  0.021136  0.983137
MAP2K4      1.769543e+05    1.566762e+00  0.187711 -1.565385  0.117493
MARCKSL1P1  3.759253e+02   -5.782168e-07  0.001352 -0.479462  0.631610
...                  ...             ...       ...       ...       ...
FAM83A-AS1  9.477711e+02   -2.941848e-06  0.001432 -0.333569  0.738705
MIR2110     7.882239e+02    6.017191e-06  0.001579  1.706147  0.087981
ALOX12      1.190052e+04   -4.683378e-07  0.001349 -1.207792  0.227127
OR52N4      1.540697e+03   -1.107309e-06  0.001357 -0.635608  0.525032
ACSBG2      1.974971e+03    4.197379e-07  0.001482  0.171339  0.863957

                padj
ENHO        0.967060
RPSAP36     0.999996
KRT8        0.999996
MAP2K4      0.999996
MARCKSL1P1  0.999996
...              ...
FAM83A-AS1  0.999996
MIR2110     0.995110
ALOX12      0.999996
OR52N4      0.999996
ACSBG2      0.999996

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 601 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.99 seconds.

Fitting dispersion trend curve...
... done in 0.23 seconds.

Fitting MAP dispersions...
... done in 1.50 seconds.

Fitting LFCs...
... done in 0.81 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 426 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.21 seconds.

Fitting LFCs...
... done in 0.18 seconds.

Running Wald tests...
... done in 0.43 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.98 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CHMP6    129501.325779       -0.005542  0.053876 -0.450922  0.652046  0.984174
PTMAP10     213.659311       -0.002746  0.050702 -1.029299  0.303339  0.953980
DRAXIN     8175.544999        0.000139  0.055564  0.044195  0.964749  0.997852
CYP2T1P   69374.867510        0.001453  0.060349  0.656948  0.511214  0.971157
SH3RF1   273076.586299       -0.007018  0.052942 -1.204427  0.228424  0.913720
...                ...             ...       ...       ...       ...       ...
BET1     144389.597684       -0.007283  0.052350 -1.344904  0.178656  0.887616
AGBL2      7761.107684        0.003785  0.058012  0.844190  0.398563  0.965090
XPC      383097.877507       -0.001335  0.051340 -0.630291  0.528504  0.977462
PXT1       1179.136571        0.004018  0.059851  1.058272  0.289932  0.947453
GAL3ST1    2415.936738        0.002270  0.058313  0.649436  0.516057  0.972306

[4991 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.49 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.38 seconds.

Fitting LFCs...
... done in 0.89 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 426 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 426)
Number of True values in replace_mask: 925
replacement_counts_trimmed shape: (40, 426)

... done in 0.11 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.49 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CHMP6    129501.325779    1.393359e+00  0.240298 -0.450921  0.652046  0.999999
PTMAP10     213.659311   -1.847937e-06  0.001318 -1.029146  0.303411  0.999999
DRAXIN     8175.544999    3.022565e-08  0.001450  0.044194  0.964749  0.999999
CYP2T1P   69374.867510    1.774410e+00  0.627666  0.656948  0.511215  0.999999
SH3RF1   273076.586299    1.589857e+00  0.222521 -1.204427  0.228425  0.999999
...                ...             ...       ...       ...       ...       ...
BET1     144389.597684    1.324504e+00  0.314459 -1.344903  0.178657  0.999999
AGBL2      7761.107684    1.535222e-06  0.001520  0.844181  0.398568  0.999999
XPC      383097.877507    1.405278e+00  0.528738 -0.630287  0.528507  0.999999
PXT1       1179.136571    2.680957e-06  0.001562  1.058217  0.289956  0.999999
GAL3ST1    2415.936738    1.398442e-06  0.001525  0.649424  0.516064  0.999999

[4991 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 606 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.14 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.50 seconds.

Fitting LFCs...
... done in 1.00 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 430 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.14 seconds.

Fitting LFCs...
... done in 0.23 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 2.03 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
PCDHB7       18416.647230       -0.000243  0.028443 -0.219969  0.825896
SAMD13        9553.602863        0.001527  0.032727  1.518089  0.128992
RNU6-100P      129.096555       -0.000633  0.024389 -1.420210  0.155547
ZC3HAV1     282488.925718       -0.000093  0.028701  0.018633  0.985134
OR2C1          433.362085       -0.000071  0.028584 -0.104900  0.916455
...                   ...             ...       ...       ...       ...
RNU6-1330P     314.866806        0.998836  0.580702  2.991531  0.002776
RPL17P43     11435.364944        0.000204  0.030220  0.341432  0.732778
PCDHA5       67656.100853       -0.000370  0.028070 -0.499807  0.617211
GABRA1         122.395369       -0.000002  0.028399 -0.001701  0.998642
FXR2        217307.459449       -0.008043  0.029584 -1.956213  0.050440

                padj
PCDHB7      0.995922
SAMD13      0.902675
RNU6-100P   0.906931
ZC3HAV1     0.999644
OR2C1       0.995922
...              ...
RNU6-1330P  0.399977
RPL17P43    0.993697
PCDHA5      0.985604
GABRA1      0.999644
FXR2        0.774923

[4991 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.94 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.76 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 430 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 430)
Number of True values in replace_mask: 923
replacement_counts_trimmed shape: (40, 430)

... done in 0.09 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.28 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
PCDHB7       18416.647230    1.560727e-06  0.001423 -0.219968  0.825896
SAMD13        9553.602863    3.699796e-06  0.001631  1.518080  0.128994
RNU6-100P      129.096555   -1.576028e-06  0.001216 -1.420040  0.155596
ZC3HAV1     282488.925718    1.803940e+00  0.203135  0.018633  0.985134
OR2C1          433.362085   -1.920805e-07  0.001428 -0.104893  0.916461
...                   ...             ...       ...       ...       ...
RNU6-1330P     314.866806    1.008504e+00  0.579267  2.991070  0.002780
RPL17P43     11435.364944   -9.428240e-08  0.001509  0.341432  0.732779
PCDHA5       67656.100853    1.215161e+00  0.327619 -0.499806  0.617212
GABRA1         122.395369   -4.674918e-09  0.001440 -0.001696  0.998647
FXR2        217307.459449    1.369546e+00  0.251204 -1.956212  0.050440

                padj
PCDHB7      0.999992
SAMD13      0.999992
RNU6-100P   0.999992
ZC3HAV1     0.999992
OR2C1       0.999992
...              ...
RNU6-1330P  0.664521
RPL17P43    0.999992
PCDHA5      0.999992
GABRA1      0.999992
FXR2        0.972189

[4991 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 603 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.

Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.71 seconds.

Fitting dispersion trend curve...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.66 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 430 outlier genes.

Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.21 seconds.

Running Wald tests...
... done in 0.63 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.44 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
KRT8P37     3466.730123       -0.003868  0.059654 -1.515536  0.129637
ERFL        3397.789791        0.000335  0.069807  0.036311  0.971035
AQP4        3431.372569        0.004069  0.079397  0.948305  0.342974
RASGRP2   128097.840140       -0.001309  0.071771  0.195240  0.845205
ELOB      622927.488238        0.010760  0.079331  1.278910  0.200929
...                 ...             ...       ...       ...       ...
HEXD      202455.709904       -0.005712  0.068139 -0.282652  0.777444
UNC13C      1250.221166        0.006194  0.069840  0.533621  0.593604
GPX1      929768.360342       -0.016405  0.074046 -0.451471  0.651650
PEF1      383766.646227        0.000571  0.069303  0.182821  0.854939
RPS10P28     563.580158        0.004033  0.084787  1.173793  0.240478

              padj
KRT8P37   0.849722
ERFL      0.998447
AQP4      0.931764
RASGRP2   0.989287
ELOB      0.889359
...            ...
HEXD      0.988223
UNC13C    0.978372
GPX1      0.981387
PEF1      0.989315
RPS10P28  0.911469

[4988 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.02 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 2.50 seconds.

Fitting LFCs...
... done in 2.27 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 430 outlier genes.

replace_mask before filtering: (40, 430)
Number of True values in replace_mask: 948
replacement_counts_trimmed shape: (40, 430)

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.12 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.54 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
KRT8P37     3466.730123   -1.931154e-06  0.001197 -1.515530  0.129638
ERFL        3397.789791   -4.182679e-07  0.001445  0.036309  0.971036
AQP4        3431.372569    1.681762e-06  0.001606  0.948297  0.342978
RASGRP2   128097.840140    1.437373e+00  0.416904  0.195240  0.845205
ELOB      622927.488238    2.058840e+00  0.222125  1.290013  0.197046
...                 ...             ...       ...       ...       ...
HEXD      202455.709904    1.596057e+00  0.218190 -0.282652  0.777444
UNC13C      1250.221166    2.715019e-06  0.001472  0.533530  0.593667
GPX1      929768.360342    1.725399e+00  0.191167 -0.451477  0.651646
PEF1      383766.646227    1.829358e+00  0.181750  0.182821  0.854939
RPS10P28     563.580158    1.673629e-06  0.001711  1.173751  0.240495

              padj
KRT8P37   0.996680
ERFL      0.999999
AQP4      0.999999
RASGRP2   0.999999
ELOB      0.999999
...            ...
HEXD      0.999999
UNC13C    0.999999
GPX1      0.999999
PEF1      0.999999
RPS10P28  0.999999

[4988 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 605 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.

Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.07 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 0.60 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 401 outlier genes.

Fitting dispersions...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 0.17 seconds.

Fitting LFCs...
... done in 0.20 seconds.

Running Wald tests...
... done in 0.37 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.94 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
CRLF1      1.171895e+05        0.001903  0.063170  0.150149  0.880647
ARFGAP3    3.385239e+05       -0.037203  0.084814 -1.482650  0.138167
KLB        5.365379e+04       -0.005035  0.055562 -1.161870  0.245288
EIF2AK3    1.927714e+05       -0.007017  0.059717 -0.837678  0.402212
APOH       9.199172e+02        4.272649  1.446013  4.611357  0.000004
...                 ...             ...       ...       ...       ...
DERL1      1.107831e+06        0.012115  0.094463  1.514401  0.129924
GAD1       7.735816e+03        0.001352  0.064874  0.376518  0.706532
MRPL37P1   1.537741e+02        0.001847  0.063531  0.380397  0.703651
RAB11FIP4  1.929027e+05        0.001914  0.060599  0.196584  0.844153
RPS15AP14  3.271926e+02        0.008321  0.067030  1.276470  0.201789

               padj
CRLF1      0.999832
ARFGAP3    0.801251
KLB        0.894670
EIF2AK3    0.944476
APOH       0.004989
...             ...
DERL1      0.801251
GAD1       0.988174
MRPL37P1   0.988174
RAB11FIP4  0.999439
RPS15AP14  0.863787

[4988 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.36 seconds.

Fitting dispersion trend curve...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 1.45 seconds.

Fitting LFCs...
... done in 0.77 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 401 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 401)
Number of True values in replace_mask: 832
replacement_counts_trimmed shape: (40, 401)

... done in 0.09 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.38 seconds.

Fitting MAP LFCs...
... done in 1.32 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
CRLF1      1.171895e+05    1.668956e+00  0.431594  0.150149  0.880647
ARFGAP3    3.385239e+05    2.196537e+00  0.157940 -1.482648  0.138168
KLB        5.365379e+04    7.285119e-01  1.173167 -1.161870  0.245288
EIF2AK3    1.927714e+05    1.545557e+00  0.228505 -0.837677  0.402212
APOH       4.241092e+01    5.228493e+00  0.055911  0.037091  0.970413
...                 ...             ...       ...       ...       ...
DERL1      1.107831e+06    2.876445e+00  0.254224  1.514396  0.129925
GAD1       7.735816e+03    3.736161e-08  0.001504  0.376517  0.706533
MRPL37P1   1.537741e+02    9.897605e-07  0.001482  0.380247  0.703762
RAB11FIP4  1.929027e+05    1.682679e+00  0.219190  0.196583  0.844154
RPS15AP14  3.271926e+02    4.449991e-06  0.001546  1.276037  0.201942

               padj
CRLF1      0.999996
ARFGAP3    0.910423
KLB        0.994170
EIF2AK3    0.999996
APOH       0.999996
...             ...
DERL1      0.910423
GAD1       0.999996
MRPL37P1   0.999996
RAB11FIP4  0.999996
RPS15AP14  0.971024

[4988 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 575 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.09 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.34 seconds.

Fitting LFCs...
... done in 0.62 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 383 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.17 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.50 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
KLF7-IT1    3204.951441        0.001529  0.059921  0.545422  0.585463
ATXN2     297602.096359       -0.016078  0.056621 -1.430773  0.152495
PPDPF     910768.734293       -0.000748  0.052484 -0.738929  0.459950
GDAP1      94297.668790       -0.002035  0.055552 -0.242862  0.808112
FNBP1P1     6237.308044        0.000380  0.056325  0.076778  0.938800
...                 ...             ...       ...       ...       ...
RGL1      276653.540015        0.001421  0.058759  0.737846  0.460608
MESTP3      2132.188838       -0.003082  0.052609 -0.332477  0.739529
IL22RA2      848.261615        0.000437  0.060489  0.612784  0.540019
SZT2-AS1   40167.591257       -0.000263  0.053278 -0.397034  0.691342
MAX       427222.719472       -0.002479  0.060116  0.531071  0.595370

              padj
KLF7-IT1  0.969787
ATXN2     0.873941
PPDPF     0.953892
GDAP1     0.996009
FNBP1P1   0.996688
...            ...
RGL1      0.953892
MESTP3    0.991429
IL22RA2   0.966907
SZT2-AS1  0.984807
MAX       0.969787

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.02 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.33 seconds.

Fitting LFCs...
... done in 0.96 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 383 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 383)
Number of True values in replace_mask: 843
replacement_counts_trimmed shape: (40, 383)

... done in 0.09 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.40 seconds.

Fitting MAP LFCs...
... done in 1.31 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
KLF7-IT1    3204.951441        0.000001  0.001528  0.545417  0.585467
ATXN2     297602.096359        2.057840  0.162684 -1.430770  0.152496
PPDPF     910768.734293        1.518218  0.304146 -0.738929  0.459950
GDAP1      94297.668790        1.424014  0.361665 -0.242862  0.808113
FNBP1P1     6237.308044       -0.000002  0.001449  0.076777  0.938801
...                 ...             ...       ...       ...       ...
RGL1      276653.540015        1.739835  0.288746  0.737853  0.460604
MESTP3      2132.188838       -0.000002  0.001431 -0.332401  0.739587
IL22RA2      364.577156        0.311746  0.015213  0.001045  0.999167
SZT2-AS1   40167.591257        0.719512  0.829209 -0.397024  0.691350
MAX       427222.719472        1.897225  0.354187  0.531071  0.595370

              padj
KLF7-IT1  0.999996
ATXN2     0.999996
PPDPF     0.999996
GDAP1     0.999996
FNBP1P1   0.999996
...            ...
RGL1      0.999996
MESTP3    0.999996
IL22RA2   0.999996
SZT2-AS1  0.999996
MAX       0.999996

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 584 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.53 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.58 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 421 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.20 seconds.

Fitting LFCs...
... done in 0.20 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.55 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
PLD3       1.254141e+06        0.010637  0.065966  1.416905  0.156511
EBF1       2.721090e+05        0.006859  0.068080  1.432162  0.152097
ALKBH6     6.153604e+04        0.001837  0.058218  0.231250  0.817121
CRYZL1     1.392408e+05       -0.002326  0.055852 -0.233284  0.815541
GEMIN5     1.771040e+05       -0.011651  0.058343 -0.619163  0.535809
...                 ...             ...       ...       ...       ...
LPGAT1     7.308503e+05       -0.002326  0.052849 -1.004202  0.315281
ITGB8      1.995355e+05       -0.001649  0.050926 -1.066217  0.286326
RAB11FIP5  2.624898e+05       -0.001499  0.056145 -0.298560  0.765276
PRDM2      3.217395e+05       -0.005035  0.057890 -0.491933  0.622766
HYI        2.299316e+05        0.002401  0.057173 -0.349666  0.726589

               padj
PLD3       0.866448
EBF1       0.866448
ALKBH6     0.994203
CRYZL1     0.994203
GEMIN5     0.974275
...             ...
LPGAT1     0.919409
ITGB8      0.902997
RAB11FIP5  0.994075
PRDM2      0.977505
HYI        0.986663

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.22 seconds.

Fitting dispersion trend curve...
... done in 0.14 seconds.

Fitting MAP dispersions...
... done in 1.76 seconds.

Fitting LFCs...
... done in 1.40 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 421 outlier genes.

Fitting dispersions...

replace_mask before filtering: (40, 421)
Number of True values in replace_mask: 956
replacement_counts_trimmed shape: (40, 421)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.11 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.73 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.85 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
PLD3       1.254141e+06        2.089750  0.150576  1.416905  0.156511
EBF1       2.721090e+05        2.045404  0.336066  1.432162  0.152098
ALKBH6     6.153604e+04        1.471998  0.233531  0.231249  0.817121
CRYZL1     1.392408e+05        1.572311  0.184024 -0.233283  0.815542
GEMIN5     1.771040e+05        1.684295  0.183912 -0.619162  0.535810
...                 ...             ...       ...       ...       ...
LPGAT1     7.308503e+05        1.392518  0.302964 -1.004190  0.315287
ITGB8      1.995355e+05        1.054698  1.140386 -1.066216  0.286326
RAB11FIP5  2.624898e+05        1.923137  0.171488 -0.298560  0.765276
PRDM2      3.217395e+05        1.521972  0.291276 -0.487242  0.626087
HYI        2.299316e+05        1.428325  0.603032 -0.349666  0.726589

               padj
PLD3       0.977953
EBF1       0.977953
ALKBH6     1.000000
CRYZL1     1.000000
GEMIN5     1.000000
...             ...
LPGAT1     1.000000
ITGB8      1.000000
RAB11FIP5  1.000000
PRDM2      1.000000
HYI        1.000000

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 588 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.36 seconds.

Fitting dispersion trend curve...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 1.74 seconds.

Fitting LFCs...
... done in 0.70 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 387 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.15 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.36 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
MAP4K3-DT  3.147962e+04        0.007644  0.063898  1.031648  0.302237
HDAC2-AS2  2.227424e+03        0.002579  0.062546  0.484273  0.628192
UFM1       4.042588e+05        0.031048  0.076305  0.489440  0.624530
FOXO3B     4.107182e+04       -0.005847  0.058497 -0.665170  0.505942
FBXO48     1.909768e+04       -0.017109  0.062563 -1.452904  0.146250
...                 ...             ...       ...       ...       ...
SHQ1       9.076613e+04       -0.000432  0.060366 -0.098487  0.921546
SLC25A38   2.617573e+05        0.001498  0.066032  0.558333  0.576617
SARS2      1.202219e+04       -0.000799  0.056761 -0.546294  0.584864
SSX2IP     1.125171e+05        0.004620  0.062220  0.412960  0.679636
MAP4       1.763650e+06        0.015813  0.068405  0.366867  0.713718

               padj
MAP4K3-DT  0.946883
HDAC2-AS2  0.976805
UFM1       0.976805
FOXO3B     0.966640
FBXO48     0.880075
...             ...
SHQ1       0.996466
SLC25A38   0.975753
SARS2      0.976805
SSX2IP     0.976805
MAP4       0.979726

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.89 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.47 seconds.

Fitting LFCs...
... done in 0.74 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 387 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 387)
Number of True values in replace_mask: 836
replacement_counts_trimmed shape: (40, 387)

... done in 0.12 seconds.

Fitting LFCs...
... done in 0.12 seconds.

Running Wald tests...
... done in 0.44 seconds.

Fitting MAP LFCs...
... done in 1.35 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
MAP4K3-DT  3.147962e+04       -0.000003  0.001514  1.031643  0.302239
HDAC2-AS2  2.227424e+03        0.000002  0.001487  0.484256  0.628204
UFM1       4.042588e+05        2.515796  0.153551  0.489440  0.624530
FOXO3B     4.107182e+04       -0.208497  1.579678 -0.665166  0.505944
FBXO48     1.909768e+04       -0.204652  0.539431 -1.491214  0.135905
...                 ...             ...       ...       ...       ...
SHQ1       9.076613e+04        1.476551  0.363890 -0.098487  0.921546
SLC25A38   2.617573e+05        1.882574  0.510186  0.558333  0.576617
SARS2      4.306565e+03       -0.528046  0.004188 -0.001143  0.999088
SSX2IP     1.125171e+05        1.621562  0.290776  0.412960  0.679636
MAP4       1.763650e+06        1.922364  0.147641  0.364620  0.715395

               padj
MAP4K3-DT  0.999999
HDAC2-AS2  0.999999
UFM1       0.999999
FOXO3B     0.999999
FBXO48     0.994049
...             ...
SHQ1       0.999999
SLC25A38   0.999999
SARS2      0.999999
SSX2IP     0.999999
MAP4       0.999999

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 586 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4996 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.62 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 403 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.16 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.52 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SDHB       3.069631e+05        0.001949  0.047981  1.357157  0.174731
LPL        3.761141e+06        0.001834  0.051334  0.533021  0.594019
RPS2       2.565840e+06        0.003398  0.048443  0.667230  0.504625
LINC00881  1.242547e+02        0.002237  0.063142  2.510277  0.012064
LRP5       6.260066e+05        0.002550  0.052430  1.224909  0.220610
...                 ...             ...       ...       ...       ...
EMC8       1.121099e+05        0.009254  0.056428  1.934861  0.053007
USP15      2.641577e+05        0.009041  0.055424  1.097860  0.272266
MS4A6A     2.038488e+05       -0.013951  0.053011  0.141771  0.887261
DDI2       3.216308e+05        0.015597  0.052916 -0.601228  0.547688
ZEB2-AS1   3.075382e+03        0.000433  0.050002  1.147158  0.251316

               padj
SDHB       0.919872
LPL        0.984529
RPS2       0.966853
LINC00881  0.517387
LRP5       0.938195
...             ...
EMC8       0.737440
USP15      0.943478
MS4A6A     0.990162
DDI2       0.970383
ZEB2-AS1   0.943173

[4996 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.03 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.43 seconds.

Fitting LFCs...
... done in 0.81 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 403 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 403)
Number of True values in replace_mask: 886
replacement_counts_trimmed shape: (40, 403)

... done in 0.09 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.38 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SDHB       3.069631e+05        2.214457  0.162768  1.357155  0.174732
LPL        3.761141e+06        2.077471  0.157459  0.533021  0.594019
RPS2       2.565840e+06        2.054095  0.112708  0.667230  0.504625
LINC00881  6.019379e+01        1.346228  0.043130 -0.017401  0.986117
LRP5       6.260066e+05        2.074416  0.238768  1.224907  0.220610
...                 ...             ...       ...       ...       ...
EMC8       1.121099e+05        2.007307  0.295767  1.934860  0.053008
USP15      2.641577e+05        1.992543  0.374503  1.097860  0.272266
MS4A6A     2.038488e+05        1.697746  0.220043  0.141771  0.887261
DDI2       3.216308e+05        1.507782  0.332599 -0.601228  0.547688
ZEB2-AS1   1.206558e+03        0.293362  0.010244  0.000655  0.999477

               padj
SDHB       0.999993
LPL        0.999993
RPS2       0.999993
LINC00881  0.999993
LRP5       0.999993
...             ...
EMC8       0.921196
USP15      0.999993
MS4A6A     0.999993
DDI2       0.999993
ZEB2-AS1   0.999993

[4996 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 543 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.92 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.80 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 394 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.28 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.34 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SYT2        8798.306149       -0.000482  0.051839 -0.159350  0.873393
PFKFB2    133919.754561        0.001335  0.052540 -0.016481  0.986850
NMRAL1    176751.265760        0.004964  0.055547  0.604150  0.545744
CDKN2A    118399.422887        0.002901  0.062540  1.338742  0.180655
C12orf43   96536.853730        0.013681  0.053519  1.111053  0.266545
...                 ...             ...       ...       ...       ...
ATXN1     257684.923957       -0.003377  0.055585  0.555815  0.578337
SEC11B     15831.791733       -0.010505  0.050863 -1.105925  0.268759
ATP8A1     98000.347246        0.006897  0.056823  1.502154  0.133057
PRSS22     84336.855762        0.004482  0.056611  1.121700  0.261990
EMC1-AS1   11298.815547       -0.000200  0.052264 -0.052542  0.958096

              padj
SYT2      0.992584
PFKFB2    0.998890
NMRAL1    0.959113
CDKN2A    0.866129
C12orf43  0.907016
...            ...
ATXN1     0.962919
SEC11B    0.907016
ATP8A1    0.850097
PRSS22    0.907016
EMC1-AS1  0.996937

[4988 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.90 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.25 seconds.

Fitting LFCs...
... done in 0.77 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 394 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 394)
Number of True values in replace_mask: 834
replacement_counts_trimmed shape: (40, 394)

... done in 0.09 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.44 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.52 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SYT2        8798.306149    2.279187e-07  0.001425 -0.159349  0.873394
PFKFB2    133919.754561    1.412933e+00  0.508654 -0.016481  0.986850
NMRAL1    176751.265760    1.665030e+00  0.377696  0.604150  0.545744
CDKN2A    118399.422887    2.163190e+00  0.452444  1.338741  0.180655
C12orf43   96536.853730    8.507776e-01  0.140348  1.111044  0.266549
...                 ...             ...       ...       ...       ...
ATXN1     257684.923957    1.788172e+00  0.377826  0.555815  0.578337
SEC11B     15831.791733   -3.943686e-06  0.001406 -1.105888  0.268775
ATP8A1     98000.347246    1.705270e+00  0.263974  1.502152  0.133058
PRSS22     84336.855762    1.721542e+00  0.327315  1.121703  0.261989
EMC1-AS1   11298.815547   -2.788437e-06  0.001437 -0.052542  0.958097

              padj
SYT2      0.999988
PFKFB2    0.999988
NMRAL1    0.999988
CDKN2A    0.975330
C12orf43  0.999988
...            ...
ATXN1     0.999988
SEC11B    0.999988
ATP8A1    0.965026
PRSS22    0.999988
EMC1-AS1  0.999988

[4988 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 617 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.90 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 2.03 seconds.

Fitting LFCs...
... done in 1.14 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 398 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.40 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.53 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CCDC183   3.513038e+04       -0.002206  0.050282 -0.554474  0.579255  0.974649
OLFM5P    9.794942e+02        0.003240  0.058981  1.226053  0.220179  0.882787
CLEC14A   3.501234e+05       -0.002043  0.048749 -0.885933  0.375654  0.953892
PLPPR1    3.875993e+03        0.000964  0.055558  0.484983  0.627688  0.983599
GALM      9.845228e+04        0.005439  0.054940  0.925615  0.354646  0.940035
...                ...             ...       ...       ...       ...       ...
POGK      5.508656e+05        0.001783  0.051618 -0.079742  0.936443  0.997708
C12orf71  6.695601e+02        0.000731  0.050532  0.101044  0.919515  0.997708
CDKAL1    6.513311e+04        0.002068  0.060105 -0.833780  0.404405  0.953892
ATP11A    2.608749e+05       -0.000003  0.052609  0.307283  0.758628  0.993794
COL4A1    3.303356e+06       -0.001987  0.051854 -0.072864  0.941914  0.997708

[4991 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.97 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.29 seconds.

Fitting LFCs...
... done in 0.90 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 398 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 398)
Number of True values in replace_mask: 859
replacement_counts_trimmed shape: (40, 398)

... done in 0.10 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.82 seconds.

Fitting MAP LFCs...
... done in 1.89 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CCDC183   3.513038e+04    9.080000e-01  0.436669 -0.554473  0.579255  0.999998
OLFM5P    9.794942e+02    2.438952e-06  0.001628  1.226005  0.220197  0.989169
CLEC14A   3.501234e+05    1.426929e+00  0.367515 -0.885938  0.375651  0.999998
PLPPR1    3.875993e+03    7.663393e-07  0.001536  0.484981  0.627690  0.999998
GALM      9.845228e+04    1.659418e+00  0.286493  0.925614  0.354646  0.999998
...                ...             ...       ...       ...       ...       ...
POGK      5.508656e+05    1.713364e+00  0.232902 -0.079742  0.936443  0.999998
C12orf71  6.695601e+02    4.559920e-07  0.001447  0.101002  0.919549  0.999998
CDKAL1    3.784309e+04    8.153085e-01  0.002144 -0.000688  0.999451  0.999998
ATP11A    2.608749e+05    1.622173e+00  0.284160  0.307283  0.758628  0.999998
COL4A1    3.303356e+06    1.846120e+00  0.116101 -0.072864  0.941914  0.999998

[4991 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 573 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.52 seconds.

Fitting LFCs...
... done in 0.88 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 368 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.22 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 2.13 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
ACP2      273990.720889       -0.003214  0.036395 -0.493122  0.621927
RBM42     409015.853351       -0.001480  0.035868 -0.671257  0.502057
FOSB      280751.202372       -0.000461  0.034730 -0.622688  0.533490
TPRG1L    377726.498142        0.008141  0.038894  1.234659  0.216957
LY86       22327.513788       -0.005747  0.038118 -0.100426  0.920006
...                 ...             ...       ...       ...       ...
NHSL1      94062.289738        0.000373  0.038204  0.802960  0.421998
TRMT13    125236.882427       -0.000085  0.037192  0.020042  0.984010
SERPINA9    1798.845278       -0.000714  0.032382 -1.011741  0.311662
VPS26B    342821.530040        0.011668  0.042454  0.739946  0.459333
TNIP1     890170.520486       -0.004548  0.035891 -1.223315  0.221211

              padj
ACP2      0.972559
RBM42     0.957836
FOSB      0.964051
TPRG1L    0.915415
LY86      0.997139
...            ...
NHSL1     0.944003
TRMT13    0.998619
SERPINA9  0.938552
VPS26B    0.955428
TNIP1     0.915415

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.87 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 0.99 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 368 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 368)
Number of True values in replace_mask: 802
replacement_counts_trimmed shape: (40, 368)

... done in 0.10 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 2.24 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
ACP2      273990.720889    1.650730e+00  0.199761 -0.493121  0.621927
RBM42     409015.853351    1.710551e+00  0.180760 -0.671257  0.502057
FOSB      280751.202372    1.378179e+00  0.519940 -0.622688  0.533489
TPRG1L    377726.498142    2.861191e+00  0.151073  1.234659  0.216958
LY86       22327.513788   -3.920900e-07  0.001433 -0.100426  0.920006
...                 ...             ...       ...       ...       ...
NHSL1      94062.289738    1.535846e+00  0.265082  0.802959  0.421998
TRMT13    125236.882427    1.423836e+00  0.666504  0.020042  0.984010
SERPINA9    1798.845278   -1.077000e-06  0.001257 -1.011734  0.311665
VPS26B    342821.530040    2.149160e+00  0.157346  0.739945  0.459333
TNIP1     890170.520486    1.792051e+00  0.140464 -1.223314  0.221211

              padj
ACP2      0.999989
RBM42     0.999989
FOSB      0.999989
TPRG1L    0.999989
LY86      0.999989
...            ...
NHSL1     0.999989
TRMT13    0.999989
SERPINA9  0.999989
VPS26B    0.999989
TNIP1     0.999989

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 561 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.94 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.38 seconds.

Fitting LFCs...
... done in 0.64 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 385 outlier genes.

Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.10 seconds.

Fitting LFCs...
... done in 0.20 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.63 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SLC22A2  1.752603e+02       -0.000370  0.029009 -0.787472  0.431006  0.955788
TENT5B   1.064292e+05       -0.002815  0.030343 -1.379509  0.167738  0.915254
LCMT1    2.055354e+05       -0.001263  0.031855 -0.713803  0.475349  0.958377
ERICH5   3.439945e+03        0.000761  0.040550  1.207694  0.227165  0.921086
SNORD89  2.867560e+03       -0.000509  0.032332 -0.292858  0.769631  0.981312
...               ...             ...       ...       ...       ...       ...
CNBP     1.644436e+06        0.003143  0.038563  1.658506  0.097215  0.855906
SARS2    1.487719e+05       -0.000751  0.030425 -0.740735  0.458854  0.957275
NUDT21   4.795795e+05        0.002983  0.032888 -0.119689  0.904729  0.996050
ARAP2    7.657583e+04        0.000464  0.032316  0.169320  0.865545  0.995758
ZNF564   7.484422e+04        0.001246  0.035097  0.605902  0.544580  0.965819

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.98 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 1.05 seconds.

Calculating cook's distance...
... done in 0.01 seconds.

Replacing 385 outlier genes.

Fitting dispersions...

replace_mask before filtering: (40, 385)
Number of True values in replace_mask: 837
replacement_counts_trimmed shape: (40, 385)

... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 0.13 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.45 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SLC22A2  1.752603e+02   -6.959110e-07  0.001268 -0.787433  0.431028  0.999996
TENT5B   1.064292e+05    1.208306e+00  0.411285 -1.379509  0.167738  0.999996
LCMT1    2.055354e+05    1.575706e+00  0.231991 -0.713802  0.475349  0.999996
ERICH5   3.439945e+03    1.428241e-06  0.001773  1.207689  0.227167  0.999996
SNORD89  2.867560e+03   -9.280526e-07  0.001420 -0.292848  0.769638  0.999996
...               ...             ...       ...       ...       ...       ...
CNBP     1.644436e+06    2.289519e+00  0.155498  1.652061  0.098522  0.996785
SARS2    1.487719e+05    1.359633e+00  0.545764 -0.736969  0.461141  0.999996
NUDT21   4.795795e+05    1.675575e+00  0.413039 -0.120183  0.904338  0.999996
ARAP2    7.657583e+04   -9.983807e-02  0.144743  0.169319  0.865545  0.999996
ZNF564   7.484422e+04    1.703937e+00  0.492278  0.605902  0.544580  0.999996

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 573 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.92 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.30 seconds.

Fitting LFCs...
... done in 0.57 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 397 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.13 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.41 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat    pvalue  \
BNIP3P1       67760.075755        0.003011  0.040109  1.044440  0.296282
TRIL         171703.700188        0.000896  0.040050  0.504398  0.613982
SNORD116-21     304.635411        0.000384  0.039826  0.324915  0.745246
KAT2B        149316.072291        0.000597  0.038484  0.196677  0.844080
RRM1         386166.088042        0.000771  0.038937  0.326583  0.743983
...                    ...             ...       ...       ...       ...
MADD         399961.866803        0.000981  0.044683  0.941554  0.346421
WDR83OS      447137.316266       -0.000800  0.035606 -0.784624  0.432674
GHITM        626700.161443       -0.002537  0.035322 -1.341179  0.179862
CUTC         112608.146013       -0.001030  0.036202  0.573240  0.566482
PMP2           5514.178098        0.003516  0.041666  1.424190  0.154391

                 padj
BNIP3P1      0.969784
TRIL         0.987715
SNORD116-21  0.987715
KAT2B        0.990788
RRM1         0.987715
...               ...
MADD         0.969784
WDR83OS      0.987715
GHITM        0.959378
CUTC         0.987715
PMP2         0.952614

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.03 seconds.

Fitting dispersion trend curve...
... done in 0.20 seconds.

Fitting MAP dispersions...
... done in 1.32 seconds.

Fitting LFCs...
... done in 0.74 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 397 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 397)
Number of True values in replace_mask: 852
replacement_counts_trimmed shape: (40, 397)

... done in 0.10 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.34 seconds.

Fitting MAP LFCs...
... done in 1.52 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat    pvalue  \
BNIP3P1       67760.075755    1.403859e+00  0.263698  1.044438  0.296283
TRIL         171703.700188    1.650705e+00  0.423119  0.504397  0.613982
SNORD116-21     304.635411    5.541565e-07  0.001497  0.324889  0.745265
KAT2B        149316.072291    1.630446e+00  0.258548  0.196677  0.844080
RRM1         386166.088042    1.748581e+00  0.259433  0.326583  0.743983
...                    ...             ...       ...       ...       ...
MADD         399961.866803    2.239883e+00  0.337093  0.941564  0.346416
WDR83OS      447137.316266    1.444255e+00  0.399828 -0.784624  0.432674
GHITM        626700.161443    1.459088e+00  0.264676 -1.341181  0.179862
CUTC         112608.146013   -1.193964e-01  0.190568  0.573235  0.566486
PMP2           5514.178098    6.285345e-06  0.001560  1.424161  0.154400

                 padj
BNIP3P1      0.999997
TRIL         0.999997
SNORD116-21  0.999997
KAT2B        0.999997
RRM1         0.999997
...               ...
MADD         0.999997
WDR83OS      0.999997
GHITM        0.999997
CUTC         0.999997
PMP2         0.999997

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 548 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.83 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.25 seconds.

Fitting LFCs...
... done in 0.57 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 387 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.12 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.40 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
HMMR-AS1     1845.426833       -0.000427  0.046392  0.829511  0.406815
ZNRF2P2      3434.926359        0.000293  0.047956  0.049541  0.960489
CCT6B       24791.073105       -0.001305  0.046998 -0.352996  0.724091
CCDC201       282.060544        0.001201  0.078127  2.326596  0.019987
HDGFL1        149.099383        0.001768  0.102928  2.456065  0.014047
...                  ...             ...       ...       ...       ...
CCDC162P    18432.172629       -0.002832  0.048418  0.098635  0.921428
LINC00240    9739.632168       -0.000737  0.043938 -0.785927  0.431910
DDX27      335375.784298        0.000985  0.049224  0.184192  0.853863
DEGS1      537923.806674       -0.005689  0.047106 -0.732256  0.464013
RPS3AP37      128.071040       -0.005311  0.042159 -2.265096  0.023507

               padj
HMMR-AS1   0.959958
ZNRF2P2    0.995176
CCT6B      0.972264
CCDC201    0.573414
HDGFL1     0.506631
...             ...
CCDC162P   0.992954
LINC00240  0.959958
DDX27      0.986374
DEGS1      0.959958
RPS3AP37   0.623428

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.03 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.26 seconds.

Fitting LFCs...
... done in 0.71 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 387 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (40, 387)
Number of True values in replace_mask: 820
replacement_counts_trimmed shape: (40, 387)

... done in 0.09 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.24 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
HMMR-AS1     1133.594080   -3.360837e-01  0.011589 -0.007419  0.994081
ZNRF2P2      3434.926359   -1.076897e-07  0.001447  0.049539  0.960490
CCT6B       24791.073105   -4.736085e-01  0.411105 -0.352995  0.724092
CCDC201        29.779178    2.064197e+00  0.050274 -0.023672  0.981114
HDGFL1        149.099383    1.571127e-06  0.003069  2.455796  0.014057
...                  ...             ...       ...       ...       ...
CCDC162P    18432.172629    4.076374e-07  0.001451  0.098635  0.921428
LINC00240    9739.632168   -8.801377e-07  0.001312 -0.785926  0.431911
DDX27      335375.784298    1.733375e+00  0.410888  0.184191  0.853863
DEGS1      537923.806674    1.623756e+00  0.224388 -0.732255  0.464013
RPS3AP37      128.071040   -4.713321e-06  0.001238 -2.264233  0.023560

               padj
HMMR-AS1   0.999996
ZNRF2P2    0.999996
CCT6B      0.999996
CCDC201    0.999996
HDGFL1     0.711334
...             ...
CCDC162P   0.999996
LINC00240  0.999996
DDX27      0.999996
DEGS1      0.999996
RPS3AP37   0.840075

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 577 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4994 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.33 seconds.

Fitting LFCs...
... done in 0.60 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 160 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.74 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
RTKN       251026.882872        0.003427  0.021569  1.584772  0.113018
RPL31P2      4102.482701        0.000048  0.019499  0.058329  0.953487
MIR6746      1691.729992       -0.000220  0.018601 -0.572982  0.566657
CYTH2      598451.130715        0.003933  0.021472  2.315871  0.020565
RNF112      15943.352846       -0.000811  0.018905 -0.512539  0.608274
...                  ...             ...       ...       ...       ...
MYL1         3843.188036       -0.000150  0.018449 -0.518447  0.604146
PPIAP16       328.570343       -0.000564  0.018550 -0.946171  0.344061
LINC02084    1451.041103        0.000812  0.019674  0.813188  0.416110
MIR202HG      637.318659       -0.001904  0.018935 -1.447291  0.147815
LRIG3      230424.747774        0.742235  0.356112  3.084048  0.002042

               padj
RTKN       0.901718
RPL31P2    0.994319
MIR6746    0.987399
CYTH2      0.813212
RNF112     0.987399
...             ...
MYL1       0.987399
PPIAP16    0.970321
LINC02084  0.974016
MIR202HG   0.913059
LRIG3      0.507727

[4994 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.98 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.33 seconds.

Fitting LFCs...
... done in 0.76 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 160 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 160)
Number of True values in replace_mask: 255
replacement_counts_trimmed shape: (79, 160)

... done in 0.08 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.25 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
RTKN       251026.882872    1.771246e+00  0.188835  1.584772  0.113018
RPL31P2      4102.482701    3.245976e-05  0.001448  0.058328  0.953487
MIR6746      1691.729992   -1.211547e-06  0.001378 -0.572975  0.566662
CYTH2      598451.130715    2.413774e+00  0.092721  2.315863  0.020566
RNF112      15943.352846   -5.951239e-01  0.505246 -0.512538  0.608275
...                  ...             ...       ...       ...       ...
MYL1         3843.188036   -7.895066e-07  0.001366 -0.518445  0.604148
PPIAP16       328.570343   -3.110025e-06  0.001374 -0.946029  0.344134
LINC02084    1451.041103    5.319924e-06  0.001470  0.813025  0.416204
MIR202HG      637.318659   -1.020914e-05  0.001393 -1.446768  0.147962
LRIG3      230424.747774    2.283981e+00  0.244963  3.084048  0.002042

               padj
RTKN       0.888285
RPL31P2    0.994116
MIR6746    0.986462
CYTH2      0.732550
RNF112     0.986462
...             ...
MYL1       0.986462
PPIAP16    0.980416
LINC02084  0.986083
MIR202HG   0.904164
LRIG3      0.351655

[4994 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 546 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.94 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.31 seconds.

Fitting LFCs...
... done in 0.90 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 156 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.42 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat    pvalue  \
C5            54204.472688        0.003514  0.035615  1.419395  0.155784
ENPEP        123847.029988        0.000156  0.033544  0.098486  0.921547
MIR1469         276.255518       -0.000988  0.031370 -0.840229  0.400780
ENTPD5       300244.487752        0.002547  0.033260  0.047325  0.962254
TMEM243       96183.939416       -0.003297  0.032617 -0.524532  0.599908
...                    ...             ...       ...       ...       ...
CCNJL         31984.931610       -0.001717  0.034863  0.240759  0.809742
ZRANB2       592145.203136        0.007448  0.035933  0.535028  0.592631
RAPGEF4-AS1     200.836413        0.000561  0.034908  0.496252  0.619717
HCN3          41598.390433       -0.004601  0.033708 -0.082458  0.934282
ANGPTL1      141161.486988        0.006140  0.035569  1.659472  0.097021

                 padj
C5           0.920143
ENPEP        0.994403
MIR1469      0.954568
ENTPD5       0.997836
TMEM243      0.976097
...               ...
CCNJL        0.992245
ZRANB2       0.974424
RAPGEF4-AS1  0.978957
HCN3         0.994403
ANGPTL1      0.886639

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.94 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.33 seconds.

Fitting LFCs...
... done in 0.76 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 156 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 156)
Number of True values in replace_mask: 258
replacement_counts_trimmed shape: (78, 156)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.09 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat    pvalue  \
C5            54204.472688        1.500930  0.232784  1.419392  0.155785
ENPEP        123847.029988        1.476579  0.359325  0.098486  0.921547
MIR1469         276.255518       -0.001573  0.039589 -0.840160  0.400819
ENTPD5       300244.487752        1.781058  0.144999  0.047325  0.962254
TMEM243       96183.939416        1.527279  0.147269 -0.524531  0.599909
...                    ...             ...       ...       ...       ...
CCNJL         31984.931610        1.237326  1.243803  0.240776  0.809729
ZRANB2       592145.203136        1.960829  0.112547  0.535027  0.592631
RAPGEF4-AS1     200.836413        0.000949  0.044020  0.496203  0.619751
HCN3          41598.390433        1.307319  0.182664 -0.082458  0.934283
ANGPTL1      141161.486988        1.651396  0.153032  1.659469  0.097021

                 padj
C5           0.906671
ENPEP        0.993660
MIR1469      0.957391
ENTPD5       0.997807
TMEM243      0.977470
...               ...
CCNJL        0.988371
ZRANB2       0.976978
RAPGEF4-AS1  0.977470
HCN3         0.993660
ANGPTL1      0.856560

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 603 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.92 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.43 seconds.

Fitting LFCs...
... done in 0.67 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 157 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.72 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
GBP5     129070.504387        0.000326  0.017729  1.189091  0.234404  0.953457
CXCL3      9199.087100        0.000049  0.016138  0.152660  0.878666  0.992583
ARID1B   546628.015180       -0.004079  0.017261  0.074803  0.940372  0.996626
DYNLRB2    6355.499114       -0.000562  0.015271 -0.792916  0.427827  0.978414
SLIT1     21419.014163        0.000171  0.018586  1.552728  0.120488  0.909125
...                ...             ...       ...       ...       ...       ...
MIR4656     156.395586        0.000505  0.016853  1.102928  0.270059  0.962704
GRXCR2      169.425160        0.001427  0.016786  1.682114  0.092547  0.909125
ELK4     449553.528845       -0.004689  0.016866 -1.835394  0.066447  0.903817
CLEC4D     1388.805324        0.001230  0.018108  2.463126  0.013773  0.755254
CC2D1A   347462.807599       -0.008644  0.023189 -1.973056  0.048489  0.897835

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.91 seconds.

Fitting dispersion trend curve...
... done in 0.11 seconds.

Fitting MAP dispersions...
... done in 1.34 seconds.

Fitting LFCs...
... done in 0.80 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 157 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 157)
Number of True values in replace_mask: 264
replacement_counts_trimmed shape: (78, 157)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.22 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
GBP5     129070.504387        1.844579  0.406025  1.189093  0.234403  0.939809
CXCL3      9199.087100       -0.001445  0.033170  0.152660  0.878667  1.000000
ARID1B   546628.015180        3.042425  0.101716  0.074802  0.940372  1.000000
DYNLRB2    6355.499114       -0.001057  0.031253 -0.792911  0.427830  0.983217
SLIT1     21419.014163        1.641110  0.533915  1.552726  0.120489  0.880081
...                ...             ...       ...       ...       ...       ...
MIR4656     156.395586        0.002168  0.034558  1.102458  0.270262  0.952783
GRXCR2      169.425160        0.006069  0.035051  1.679953  0.092966  0.865399
ELK4     449553.528845        1.461172  0.186261 -1.835394  0.066447  0.830175
CLEC4D     1388.805324        0.005244  0.037932  2.462983  0.013779  0.541381
CC2D1A   347462.807599        2.181079  0.108319 -1.973053  0.048490  0.799851

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 560 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.97 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.38 seconds.

Fitting LFCs...
... done in 0.58 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 145 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.56 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
RASL11B    28555.680234        0.000003  0.005781  0.048424  0.961379
CD101      12067.837368       -0.000020  0.005666 -0.348733  0.727290
PTGES3L     5831.985187       -0.000067  0.005520 -1.157631  0.247015
NCOA1     472028.881579        0.000684  0.006022  1.151019  0.249725
SRP19     189657.775376        0.000896  0.006078  0.817606  0.413582
...                 ...             ...       ...       ...       ...
CHCHD4P4     321.150586        0.000016  0.006224  0.633493  0.526412
TCFL5     120121.630154        0.000030  0.005975  0.601875  0.547257
ZNF384    368149.071111        0.000059  0.006118  1.444484  0.148603
FBXO27     69014.786554        0.000262  0.006385  0.675691  0.499237
ZSCAN10      229.014700       -0.000079  0.005545 -1.056911  0.290552

              padj
RASL11B   0.997723
CD101     0.997723
PTGES3L   0.984549
NCOA1     0.988054
SRP19     0.997723
...            ...
CHCHD4P4  0.997723
TCFL5     0.997723
ZNF384    0.953335
FBXO27    0.997723
ZSCAN10   0.995290

[4993 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.29 seconds.

Fitting dispersion trend curve...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 1.23 seconds.

Fitting LFCs...
... done in 0.78 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 145 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 145)
Number of True values in replace_mask: 229
replacement_counts_trimmed shape: (76, 145)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.22 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
RASL11B    28555.680234        1.134881  0.442666  0.048424  0.961379
CD101      12067.837368       -0.006887  0.038071 -0.348731  0.727291
PTGES3L     5831.985187       -0.002845  0.035368 -1.157612  0.247023
NCOA1     472028.881579        2.271774  0.104312  1.151018  0.249725
SRP19     189657.775376        1.925712  0.126964  0.817605  0.413583
...                 ...             ...       ...       ...       ...
CHCHD4P4     321.150586        0.000665  0.039948  0.633470  0.526427
TCFL5     120121.630154        1.547827  0.320035  0.601874  0.547258
ZNF384    368149.071111        1.867081  0.177284  1.444484  0.148603
FBXO27     69014.786554        1.827275  0.668334  0.675679  0.499244
ZSCAN10      229.014700       -0.003236  0.035597 -1.056445  0.290765

              padj
RASL11B   0.997521
CD101     0.997521
PTGES3L   0.952747
NCOA1     0.956914
SRP19     0.987389
...            ...
CHCHD4P4  0.996954
TCFL5     0.997521
ZNF384    0.914226
FBXO27    0.996954
ZSCAN10   0.966933

[4993 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 587 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.92 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.61 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 165 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.50 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SPOCK2   138216.235315       -0.001469  0.024538 -1.424845  0.154202  0.916000
NR4A3     90613.469479        0.000345  0.026465  0.291042  0.771019  0.985949
NPR1     544979.345102        0.002061  0.024881 -0.863455  0.387887  0.960614
ABHD17C  119295.687095        0.001295  0.028822  1.497449  0.134277  0.916000
PHYHIP    69646.160289       -0.000041  0.028327  0.891500  0.372661  0.960614
...                ...             ...       ...       ...       ...       ...
NAALAD2   32571.096077       -0.000229  0.025443 -0.313524  0.753882  0.985360
SNORA9     1944.990059        0.000844  0.024785  0.203842  0.838477  0.991271
NT5DC1   214710.706528       -0.002567  0.025958 -0.136174  0.891683  0.997669
CEP57L1   49656.001192       -0.001245  0.025451 -0.618489  0.536253  0.966180
ARPC4    875225.392936       -0.005474  0.026184 -1.889950  0.058765  0.849770

[4989 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.15 seconds.

Fitting dispersion trend curve...
... done in 0.18 seconds.

Fitting MAP dispersions...
... done in 1.52 seconds.

Fitting LFCs...
... done in 1.12 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 165 outlier genes.

Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 165)
Number of True values in replace_mask: 258
replacement_counts_trimmed shape: (77, 165)

... done in 0.08 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 0.97 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SPOCK2   138216.235315        1.386718  0.230675 -1.424842  0.154203  0.889409
NR4A3     90613.469479        1.600404  0.284677  0.291042  0.771019  0.983435
NPR1     544979.345102        1.548657  0.226976 -0.863456  0.387887  0.961816
ABHD17C  119295.687095        1.794297  0.322388  1.497448  0.134277  0.882714
PHYHIP    69646.160289        1.800820  0.430289  0.891500  0.372661  0.958578
...                ...             ...       ...       ...       ...       ...
NAALAD2   32571.096077        1.083356  0.526525 -0.313524  0.753883  0.983300
SNORA9     1944.990059        0.001877  0.039147  0.203753  0.838546  0.990883
NT5DC1   214710.706528        1.616321  0.145258 -0.136174  0.891683  0.997035
CEP57L1   49656.001192        1.313150  0.181308 -0.618487  0.536254  0.962268
ARPC4    875225.392936        2.221508  0.095962 -1.889949  0.058765  0.775602

[4989 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 577 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.91 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.28 seconds.

Fitting LFCs...
... done in 0.59 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 140 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.42 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
ENHO        3.059486e+04        0.000648  0.033995  0.641031  0.521503
RPSAP36     9.662907e+02        0.000026  0.031953  0.018269  0.985424
KRT8        4.385058e+06        0.001000  0.037598  1.541763  0.123131
MAP2K4      1.821890e+05       -0.007093  0.032577 -1.105765  0.268828
MARCKSL1P1  3.392792e+02        0.000995  0.036446  1.155788  0.247768
...                  ...             ...       ...       ...       ...
FAM83A-AS1  8.853299e+02       -0.005823  0.031623 -1.415998  0.156776
MIR2110     8.119196e+02        0.002100  0.032995  0.909842  0.362906
ALOX12      1.379375e+04        0.000726  0.031922  0.284457  0.776060
OR52N4      1.707711e+03        0.000321  0.032689  0.297485  0.766096
ACSBG2      2.407987e+03       -0.001757  0.027753 -1.903692  0.056950

                padj
ENHO        0.973764
RPSAP36     0.999524
KRT8        0.917501
MAP2K4      0.960436
MARCKSL1P1  0.960436
...              ...
FAM83A-AS1  0.931912
MIR2110     0.960436
ALOX12      0.995671
OR52N4      0.995671
ACSBG2      0.830987

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.31 seconds.

Fitting LFCs...
... done in 0.75 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 140 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 140)
Number of True values in replace_mask: 208
replacement_counts_trimmed shape: (73, 140)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.38 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
ENHO        3.059486e+04        1.441917  0.566745  0.641030  0.521503
RPSAP36     9.662907e+02        0.000047  0.043078  0.018269  0.985424
KRT8        4.385058e+06        2.340241  0.098084  1.541789  0.123125
MAP2K4      1.821890e+05        1.731328  0.131993 -1.105764  0.268829
MARCKSL1P1  3.392792e+02        0.001815  0.049216  1.155736  0.247789
...                  ...             ...       ...       ...       ...
FAM83A-AS1  8.853299e+02       -0.011069  0.043522 -1.415511  0.156919
MIR2110     8.119196e+02        0.003758  0.044373  0.909730  0.362965
ALOX12      1.379375e+04       -0.000113  0.042680  0.284454  0.776062
OR52N4      1.707711e+03        0.000619  0.044076  0.297481  0.766099
ACSBG2      2.407987e+03       -0.003163  0.037596 -1.903676  0.056952

                padj
ENHO        0.966062
RPSAP36     0.999525
KRT8        0.866774
MAP2K4      0.942156
MARCKSL1P1  0.942156
...              ...
FAM83A-AS1  0.889576
MIR2110     0.946893
ALOX12      0.993747
OR52N4      0.993747
ACSBG2      0.741058

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 601 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.90 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.31 seconds.

Fitting LFCs...
... done in 0.58 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 164 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.10 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.45 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CHMP6    140892.431231        0.000972  0.016308  1.495806  0.134704  0.898041
PTMAP10     159.598538       -0.000099  0.015153 -0.348784  0.727251  0.981173
DRAXIN     9303.230928       -0.000165  0.014810 -0.652588  0.514022  0.980945
CYP2T1P  103884.054948       -0.000031  0.015325 -0.165835  0.868287  0.994053
SH3RF1   237704.091384       -0.000042  0.015509  0.067341  0.946310  0.994356
...                ...             ...       ...       ...       ...       ...
BET1     138611.049031       -0.000179  0.015342 -0.297718  0.765918  0.982509
AGBL2      7057.134971       -0.000223  0.015275 -0.405116  0.685392  0.981173
XPC      282613.504805        0.001855  0.014848 -0.703706  0.481616  0.980945
PXT1        809.688402        0.000435  0.016792  1.231195  0.218250  0.923780
GAL3ST1    3506.903435       -0.000728  0.014151 -1.360219  0.173761  0.914719

[4991 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.29 seconds.

Fitting LFCs...
... done in 0.77 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 164 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 164)
Number of True values in replace_mask: 272
replacement_counts_trimmed shape: (77, 164)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.20 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CHMP6    140892.431231        1.730897  0.168205  1.495804  0.134705  0.865765
PTMAP10     159.598538       -0.000579  0.036520 -0.348724  0.727297  0.984323
DRAXIN     9303.230928       -0.000438  0.035709 -0.652587  0.514023  0.978302
CYP2T1P  103884.054948        1.551329  0.375795 -0.165835  0.868287  0.993285
SH3RF1   237704.091384        1.715878  0.152059  0.067341  0.946310  0.993385
...                ...             ...       ...       ...       ...       ...
BET1     138611.049031        1.517904  0.182914 -0.297718  0.765918  0.986057
AGBL2      7057.134971       -0.001457  0.036572 -0.405110  0.685397  0.984323
XPC      282613.504805        1.525865  0.316508 -0.703706  0.481616  0.978302
PXT1        809.688402        0.002534  0.040560  1.231129  0.218274  0.905581
GAL3ST1    3506.903435       -0.002076  0.034177 -1.360209  0.173764  0.893900

[4991 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 606 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.91 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.30 seconds.

Fitting LFCs...
... done in 0.79 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 173 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.65 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
PCDHB7       26210.375328        0.000028  0.004106  1.320299  0.186735
SAMD13       10118.447922       -0.000011  0.003830  0.059706  0.952390
RNU6-100P      198.885491       -0.000019  0.003493 -1.234355  0.217070
ZC3HAV1     283289.290988       -0.000085  0.003832  0.119608  0.904794
OR2C1          359.973231        0.000021  0.004393  1.447315  0.147809
...                   ...             ...       ...       ...       ...
RNU6-1330P     492.407243       -0.000016  0.003635 -0.818353  0.413156
RPL17P43     10065.295006        0.000042  0.004195  0.951578  0.341311
PCDHA5       64310.056435        0.000027  0.003816 -0.009511  0.992411
GABRA1         127.822750       -0.000023  0.003780 -0.436365  0.662572
FXR2        232002.212979       -0.000043  0.003565 -2.309050  0.020941

                padj
PCDHB7      0.946422
SAMD13      0.997748
RNU6-100P   0.946422
ZC3HAV1     0.997748
OR2C1       0.946422
...              ...
RNU6-1330P  0.974560
RPL17P43    0.967450
PCDHA5      0.999721
GABRA1      0.986679
FXR2        0.877831

[4991 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.98 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.34 seconds.

Fitting LFCs...
... done in 0.79 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 173 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 173)
Number of True values in replace_mask: 288
replacement_counts_trimmed shape: (80, 173)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.11 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.31 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
PCDHB7       26210.375328    1.341914e+00  0.318926  1.320296  0.186736
SAMD13       10118.447922    2.436707e-07  0.001448  0.059705  0.952390
RNU6-100P      198.885491   -2.741405e-06  0.001320 -1.234208  0.217125
ZC3HAV1     283289.290988    1.752533e+00  0.141345  0.119608  0.904794
OR2C1          359.973231    2.979304e-06  0.001660  1.447231  0.147832
...                   ...             ...       ...       ...       ...
RNU6-1330P     492.407243   -2.332144e-06  0.001374 -0.818291  0.413191
RPL17P43     10065.295006   -1.603575e-07  0.001585  0.951577  0.341312
PCDHA5       64310.056435    1.331464e+00  0.241730 -0.009511  0.992411
GABRA1         127.822750   -3.293542e-06  0.001429 -0.435492  0.663205
FXR2        232002.212979    1.421784e+00  0.161986 -2.309049  0.020941

                padj
PCDHB7      0.999348
SAMD13      0.999984
RNU6-100P   0.999348
ZC3HAV1     0.999984
OR2C1       0.999348
...              ...
RNU6-1330P  0.999984
RPL17P43    0.999984
PCDHA5      0.999984
GABRA1      0.999984
FXR2        0.999348

[4991 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 603 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.94 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.31 seconds.

Fitting LFCs...
... done in 0.92 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 166 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.36 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
KRT8P37   3.809578e+03        0.000522  0.029189  0.900113  0.368060  0.995891
ERFL      3.417681e+03       -0.000963  0.024859 -1.388861  0.164875  0.939094
AQP4      4.799470e+03        0.000827  0.029709  1.224190  0.220881  0.953376
RASGRP2   1.142606e+05       -0.000185  0.025882 -0.267654  0.788966  0.995891
ELOB      6.780655e+05        0.000136  0.026040 -0.181343  0.856098  0.995891
...                ...             ...       ...       ...       ...       ...
HEXD      1.800468e+05       -0.002069  0.025526 -1.070141  0.284556  0.992922
UNC13C    1.379856e+03        0.002630  0.027405  1.259959  0.207684  0.951242
GPX1      1.092671e+06        0.002977  0.028821  1.832712  0.066845  0.867805
PEF1      4.344172e+05        0.004695  0.028373  1.541152  0.123280  0.908658
RPS10P28  4.912249e+02        0.000099  0.026644  0.130444  0.896215  0.996386

[4988 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.45 seconds.

Fitting LFCs...
... done in 0.76 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 166 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 166)
Number of True values in replace_mask: 279
replacement_counts_trimmed shape: (77, 166)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.09 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
KRT8P37   3.809578e+03        0.001398  0.045182  0.900111  0.368061  0.997232
ERFL      3.417681e+03       -0.003870  0.038696 -1.388828  0.164885  0.912115
AQP4      4.799470e+03        0.002004  0.046006  1.224185  0.220882  0.938006
RASGRP2   1.142606e+05        1.536806  0.294692 -0.267653  0.788966  0.997232
ELOB      6.780655e+05        1.718685  0.173645 -0.181343  0.856098  0.997232
...                ...             ...       ...       ...       ...       ...
HEXD      1.800468e+05        1.497518  0.166684 -1.070140  0.284556  0.980393
UNC13C    1.379856e+03        0.006532  0.042553  1.259795  0.207743  0.932803
GPX1      1.092671e+06        2.063652  0.115948  1.832712  0.066845  0.824461
PEF1      4.344172e+05        2.022698  0.121656  1.541151  0.123280  0.871655
RPS10P28  4.912249e+02        0.000136  0.041185  0.130439  0.896219  0.997727

[4988 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 605 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.90 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.29 seconds.

Fitting LFCs...
... done in 0.59 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 141 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.46 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
CRLF1      113117.489792        0.000153  0.016706  0.133143  0.894080
ARFGAP3    297739.796679       -0.001804  0.016174 -1.636138  0.101811
KLB         54448.582900       -0.000116  0.015933 -0.449903  0.652781
EIF2AK3    235497.651029        0.013329  0.045948  1.782642  0.074645
APOH          734.267216       -0.000201  0.013662 -1.539711  0.123631
...                  ...             ...       ...       ...       ...
DERL1      714039.675726       -0.000434  0.016653  0.028545  0.977227
GAD1         7871.460172       -0.000274  0.015672 -0.818600  0.413015
MRPL37P1      172.893489        0.000370  0.017174  0.740730  0.458857
RAB11FIP4  190753.351692       -0.000267  0.015691 -2.112657  0.034630
RPS15AP14     314.539221       -0.000289  0.016313 -0.408540  0.682877

               padj
CRLF1      0.998800
ARFGAP3    0.938977
KLB        0.981685
EIF2AK3    0.891819
APOH       0.961518
...             ...
DERL1      0.999433
GAD1       0.964064
MRPL37P1   0.973003
RAB11FIP4  0.817665
RPS15AP14  0.981685

[4988 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.46 seconds.

Fitting dispersion trend curve...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 1.16 seconds.

Fitting LFCs...
... done in 0.75 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 141 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 141)
Number of True values in replace_mask: 236
replacement_counts_trimmed shape: (72, 141)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.05 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
CRLF1      113117.489792        1.425595  0.353160  0.133143  0.894080
ARFGAP3    297739.796679        1.829697  0.118699 -1.636137  0.101811
KLB         54448.582900        1.247106  0.542470 -0.449902  0.652781
EIF2AK3    235497.651029        1.884149  0.142855  1.782641  0.074645
APOH          734.267216       -0.001037  0.031062 -1.539710  0.123631
...                  ...             ...       ...       ...       ...
DERL1      714039.675726        1.813186  0.223077  0.028573  0.977205
GAD1         7871.460172       -0.000782  0.035528 -0.818597  0.413016
MRPL37P1      172.893489        0.001916  0.038818  0.740451  0.459026
RAB11FIP4  190753.351692        1.327415  0.150258 -2.112655  0.034630
RPS15AP14     314.539221       -0.001480  0.036592 -0.408368  0.683003

               padj
CRLF1      0.998956
ARFGAP3    0.856184
KLB        0.977947
EIF2AK3    0.793936
APOH       0.883681
...             ...
DERL1      0.999433
GAD1       0.949848
MRPL37P1   0.963795
RAB11FIP4  0.671739
RPS15AP14  0.977947

[4988 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 575 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.92 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.30 seconds.

Fitting LFCs...
... done in 0.59 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 155 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.53 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
KLF7-IT1  2.770410e+03       -0.000094  0.024839 -0.174000  0.861865  0.996388
ATXN2     2.816887e+05       -0.001909  0.024441 -0.388346  0.697760  0.996388
PPDPF     1.109337e+06        0.000596  0.026470  0.764525  0.444555  0.988465
GDAP1     1.075173e+05       -0.002791  0.024186 -1.174347  0.240256  0.962260
FNBP1P1   5.800889e+03        0.000169  0.025287  0.131388  0.895468  0.996388
...                ...             ...       ...       ...       ...       ...
RGL1      2.736506e+05       -0.000089  0.024983 -0.139339  0.889182  0.996388
MESTP3    2.025781e+03        0.003778  0.026030  1.306120  0.191512  0.950572
IL22RA2   3.846579e+03        0.000267  0.028146 -0.591592  0.554124  0.996388
SZT2-AS1  2.155969e+04       -0.000046  0.024619 -0.202521  0.839509  0.996388
MAX       4.271772e+05        0.002322  0.025968  0.189038  0.850063  0.996388

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.99 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.27 seconds.

Fitting LFCs...
... done in 1.10 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 155 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 155)
Number of True values in replace_mask: 253
replacement_counts_trimmed shape: (77, 155)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 0.98 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
KLF7-IT1  2.770410e+03       -0.000165  0.038397 -0.173999  0.861866  0.995669
ATXN2     2.816887e+05        2.512875  0.112537 -0.388346  0.697760  0.995669
PPDPF     1.109337e+06        1.966735  0.145278  0.764525  0.444554  0.983486
GDAP1     1.075173e+05        1.360571  0.274332 -1.174347  0.240256  0.940682
FNBP1P1   5.800889e+03        0.000415  0.038872  0.131386  0.895470  0.995669
...                ...             ...       ...       ...       ...       ...
RGL1      2.736506e+05        1.589631  0.199136 -0.139339  0.889182  0.995669
MESTP3    2.025781e+03        0.011056  0.041735  1.305861  0.191600  0.923362
IL22RA2   1.356707e+03        0.320708  0.283492  0.966740  0.333674  0.972388
SZT2-AS1  2.155969e+04       -0.001703  0.038207 -0.202521  0.839509  0.995669
MAX       4.271772e+05        1.789985  0.288535  0.189282  0.849872  0.995669

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 584 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.91 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.26 seconds.

Fitting LFCs...
... done in 0.57 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 164 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.09 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
... done in 1.57 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
PLD3       1.090985e+06       -0.000277  0.021279  0.056473  0.954965
EBF1       2.803519e+05        0.000542  0.022669  0.962703  0.335697
ALKBH6     6.916107e+04        0.001948  0.022135  1.139329  0.254566
CRYZL1     1.330233e+05        0.000926  0.020875 -0.193359  0.846677
GEMIN5     1.886413e+05        0.000678  0.021017  0.197004  0.843825
...                 ...             ...       ...       ...       ...
LPGAT1     4.678083e+05       -0.000353  0.019522 -0.831249  0.405833
ITGB8      2.024434e+05        0.000911  0.026770  2.134993  0.032762
RAB11FIP5  3.178147e+05        0.000853  0.021250  0.412475  0.679992
PRDM2      3.885495e+05       -0.011455  0.031365 -0.778272  0.436408
HYI        2.122155e+05        0.001478  0.023976  1.296554  0.194785

               padj
PLD3       0.997254
EBF1       0.963715
ALKBH6     0.955917
CRYZL1     0.996072
GEMIN5     0.995471
...             ...
LPGAT1     0.974271
ITGB8      0.875587
RAB11FIP5  0.994248
PRDM2      0.982742
HYI        0.948916

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.31 seconds.

Fitting LFCs...
... done in 0.76 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 164 outlier genes.

Fitting dispersions...

replace_mask before filtering: (80, 164)
Number of True values in replace_mask: 271
replacement_counts_trimmed shape: (78, 164)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.08 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
... done in 1.37 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
PLD3       1.090985e+06        1.830657  0.120488  0.056472  0.954966
EBF1       2.803519e+05        1.861135  0.256236  0.962702  0.335697
ALKBH6     6.916107e+04        1.334900  0.178321  1.139301  0.254578
CRYZL1     1.330233e+05        1.872846  0.121134 -0.193352  0.846683
GEMIN5     1.886413e+05        2.128964  0.115883  0.196996  0.843831
...                 ...             ...       ...       ...       ...
LPGAT1     4.678083e+05        1.487989  0.292123 -0.831256  0.405829
ITGB8      2.024434e+05        2.347738  0.373190  2.135005  0.032761
RAB11FIP5  3.178147e+05        2.058085  0.112878  0.412462  0.680001
PRDM2      3.885495e+05        1.542520  0.191000 -0.778272  0.436409
HYI        2.122155e+05        1.995258  0.340268  1.296559  0.194783

               padj
PLD3       0.996522
EBF1       0.963765
ALKBH6     0.952733
CRYZL1     0.991181
GEMIN5     0.990879
...             ...
LPGAT1     0.973348
ITGB8      0.778842
RAB11FIP5  0.987474
PRDM2      0.983170
HYI        0.940652

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 588 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.99 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.41 seconds.

Fitting LFCs...
... done in 0.58 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 134 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.46 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
MAP4K3-DT  3.283421e+04       -0.000322  0.017242 -0.357732  0.720544
HDAC2-AS2  2.362733e+03        0.001320  0.018400  1.132682  0.257348
UFM1       4.185219e+05       -0.002714  0.017679 -0.750448  0.452985
FOXO3B     5.001942e+04       -0.000615  0.017131 -0.566557  0.571015
FBXO48     2.113757e+04       -0.001254  0.017104 -1.015217  0.310002
...                 ...             ...       ...       ...       ...
SHQ1       1.052743e+05        0.000198  0.017125 -0.463863  0.642746
SLC25A38   2.156572e+05        0.000545  0.022117  2.372775  0.017655
SARS2      1.681812e+05       -0.000169  0.015716 -0.796537  0.425720
SSX2IP     1.217637e+05       -0.004435  0.018505 -1.044976  0.296034
MAP4       1.899049e+06        0.000246  0.017636  0.288813  0.772725

               padj
MAP4K3-DT  0.988573
HDAC2-AS2  0.973242
UFM1       0.988573
FOXO3B     0.988573
FBXO48     0.977501
...             ...
SHQ1       0.988573
SLC25A38   0.785219
SARS2      0.986550
SSX2IP     0.977501
MAP4       0.996753

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.31 seconds.

Fitting LFCs...
... done in 0.73 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 134 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 134)
Number of True values in replace_mask: 209
replacement_counts_trimmed shape: (73, 134)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.13 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
MAP4K3-DT  3.283421e+04        1.237250  0.216223 -0.357731  0.720545
HDAC2-AS2  2.362733e+03        0.003306  0.037679  1.132633  0.257369
UFM1       4.185219e+05        2.080558  0.114136 -0.750448  0.452985
FOXO3B     5.001942e+04        1.085278  0.234462 -0.566556  0.571016
FBXO48     2.113757e+04       -0.104118  0.257995 -1.015205  0.310008
...                 ...             ...       ...       ...       ...
SHQ1       1.052743e+05        1.456751  0.235004 -0.463863  0.642746
SLC25A38   2.156572e+05        2.380347  0.340677  2.372774  0.017655
SARS2      1.681812e+05        1.268353  0.687772 -0.796505  0.425739
SSX2IP     1.217637e+05        1.382114  0.202535 -1.044976  0.296034
MAP4       1.899049e+06        1.903341  0.091989  0.288813  0.772725

               padj
MAP4K3-DT  0.984390
HDAC2-AS2  0.944000
UFM1       0.977707
FOXO3B     0.981852
FBXO48     0.956663
...             ...
SHQ1       0.983152
SLC25A38   0.572299
SARS2      0.969856
SSX2IP     0.956663
MAP4       0.993200

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 586 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4996 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.84 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.36 seconds.

Fitting LFCs...
... done in 0.57 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 157 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.49 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SDHB       3.294373e+05        0.000487  0.014074  0.947902  0.343179
LPL        2.467276e+06        0.000957  0.015695  1.015082  0.310067
RPS2       2.948818e+06        0.000441  0.014216  0.779929  0.435433
LINC00881  3.026852e+02        0.000159  0.018519  1.554034  0.120176
LRP5       5.726135e+05       -0.000629  0.013916  0.075575  0.939757
...                 ...             ...       ...       ...       ...
EMC8       1.376535e+05       -0.001484  0.013889 -0.297904  0.765776
USP15      4.042428e+05        0.000147  0.013788 -0.065182  0.948029
MS4A6A     2.185206e+05        0.000583  0.014007  0.571112  0.567924
DDI2       4.612383e+05       -0.000512  0.013895  0.043446  0.965346
ZEB2-AS1   5.346976e+03        0.000049  0.014710  0.405415  0.685172

               padj
SDHB       0.987852
LPL        0.983475
RPS2       0.997383
LINC00881  0.930452
LRP5       0.999501
...             ...
EMC8       0.998807
USP15      0.999501
MS4A6A     0.998807
DDI2       0.999501
ZEB2-AS1   0.998807

[4996 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.33 seconds.

Fitting LFCs...
... done in 0.74 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 157 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 157)
Number of True values in replace_mask: 263
replacement_counts_trimmed shape: (77, 157)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.09 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SDHB       3.294373e+05        2.147003  0.115060  0.947901  0.343180
LPL        2.467276e+06        2.191577  0.146887  1.015082  0.310067
RPS2       2.948818e+06        2.018071  0.074682  0.779929  0.435433
LINC00881  3.026852e+02        0.001180  0.050389  1.554029  0.120177
LRP5       5.726135e+05        1.752278  0.161616  0.075575  0.939757
...                 ...             ...       ...       ...       ...
EMC8       1.376535e+05        1.549533  0.213575 -0.297904  0.765777
USP15      4.042428e+05        1.687656  0.213364 -0.065182  0.948029
MS4A6A     2.185206e+05        1.697403  0.143361  0.571111  0.567924
DDI2       4.612383e+05        1.724877  0.197861  0.043446  0.965346
ZEB2-AS1   5.346976e+03        0.000349  0.039991  0.405416  0.685172

               padj
SDHB       0.979404
LPL        0.973689
RPS2       0.991679
LINC00881  0.880293
LRP5       0.999089
...             ...
EMC8       0.998326
USP15      0.999089
MS4A6A     0.998326
DDI2       0.999089
ZEB2-AS1   0.998326

[4996 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 543 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.02 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.36 seconds.

Fitting LFCs...
... done in 0.90 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 135 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.36 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SYT2        7948.085803       -0.000335  0.036709 -0.135384  0.892308
PFKFB2    131140.990948        0.001406  0.038357  0.648665  0.516555
NMRAL1    285904.587066       -0.002394  0.036077 -0.660459  0.508959
CDKN2A     86158.136910       -0.004361  0.034722 -1.381647  0.167080
C12orf43   96637.587342        0.011783  0.037575  0.189689  0.849553
...                 ...             ...       ...       ...       ...
ATXN1     248972.107487       -0.000658  0.036341 -0.308071  0.758028
SEC11B     16893.078780        0.000382  0.034581  0.157545  0.874815
ATP8A1    133407.435012       -0.002969  0.036406 -0.472504  0.636567
PRSS22     65509.109668        0.007561  0.041641  1.934541  0.053047
EMC1-AS1   14080.554057        0.001500  0.038091  0.604982  0.545191

              padj
SYT2      0.990836
PFKFB2    0.981016
NMRAL1    0.981016
CDKN2A    0.914793
C12orf43  0.986315
...            ...
ATXN1     0.982543
SEC11B    0.986734
ATP8A1    0.981090
PRSS22    0.793747
EMC1-AS1  0.981016

[4988 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.31 seconds.

Fitting LFCs...
... done in 0.74 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 135 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 135)
Number of True values in replace_mask: 221
replacement_counts_trimmed shape: (74, 135)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.05 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SYT2        7948.085803        0.002060  0.047831 -0.135383  0.892309
PFKFB2    131140.990948        1.552000  0.288745  0.648665  0.516555
NMRAL1    285904.587066        1.672960  0.155187 -0.660458  0.508960
CDKN2A     86158.136910        1.222046  0.376778 -1.381647  0.167080
C12orf43   96637.587342       -0.633924  0.075047  0.189687  0.849554
...                 ...             ...       ...       ...       ...
ATXN1     248972.107487        1.549840  0.313366 -0.308071  0.758028
SEC11B     16893.078780       -0.022506  0.054307  0.157539  0.874820
ATP8A1    133407.435012        1.482366  0.184721 -0.472504  0.636567
PRSS22     65509.109668        1.602952  0.209010  1.934538  0.053047
EMC1-AS1   14080.554057       -0.002747  0.049605  0.604979  0.545193

              padj
SYT2      0.989764
PFKFB2    0.977080
NMRAL1    0.976237
CDKN2A    0.890483
C12orf43  0.985861
...            ...
ATXN1     0.982445
SEC11B    0.986291
ATP8A1    0.980094
PRSS22    0.732815
EMC1-AS1  0.977080

[4988 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 617 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.32 seconds.

Fitting LFCs...
... done in 0.58 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 147 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.68 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CCDC183   3.364931e+04       -0.003002  0.026409 -0.985883  0.324191  0.974463
OLFM5P    9.703392e+02       -0.002301  0.024700 -2.098091  0.035897  0.853596
CLEC14A   3.295211e+05        0.000660  0.028354  0.670412  0.502595  0.975849
PLPPR1    1.470861e+03       -0.000180  0.026401 -0.301662  0.762909  0.992414
GALM      1.015963e+05        0.002008  0.027913  0.901190  0.367488  0.974463
...                ...             ...       ...       ...       ...       ...
POGK      6.097229e+05       -0.001432  0.028629  0.816270  0.414346  0.975849
C12orf71  5.821743e+02        0.001666  0.027313  0.647954  0.517014  0.975849
CDKAL1    6.766520e+04       -0.000398  0.026613 -0.253101  0.800190  0.992414
ATP11A    2.595928e+05       -0.004644  0.027575 -0.637101  0.524059  0.975849
COL4A1    3.128031e+06        0.555828  0.360099  1.109834  0.267070  0.973303

[4991 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.29 seconds.

Fitting LFCs...
... done in 0.75 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 147 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 147)
Number of True values in replace_mask: 244
replacement_counts_trimmed shape: (75, 147)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.04 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CCDC183   3.364931e+04        0.885393  0.318837 -0.985882  0.324191  0.963166
OLFM5P    9.703392e+02       -0.005138  0.036460 -2.097989  0.035906  0.726236
CLEC14A   3.295211e+05        1.818987  0.242567  0.670412  0.502595  0.974467
PLPPR1    1.470861e+03       -0.000336  0.038484 -0.301660  0.762912  0.992812
GALM      1.015963e+05        1.542564  0.181126  0.901188  0.367488  0.965816
...                ...             ...       ...       ...       ...       ...
POGK      6.097229e+05        1.917661  0.182439  0.816269  0.414346  0.968144
C12orf71  5.821743e+02        0.003623  0.039281  0.647684  0.517189  0.974784
CDKAL1    6.766520e+04        1.396278  0.494173 -0.253101  0.800190  0.992812
ATP11A    2.595928e+05        1.472146  0.208318 -0.637101  0.524059  0.974784
COL4A1    3.128031e+06        2.040088  0.079239  1.113131  0.265652  0.959385

[4991 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 573 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.91 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.30 seconds.

Fitting LFCs...
... done in 0.57 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 136 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.45 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
ACP2      304718.990818       -0.000144  0.014014 -0.182377  0.855287
RBM42     389049.940399        0.000515  0.014267  0.326138  0.744320
FOSB      362570.993364       -0.000509  0.016351  1.394900  0.163046
TPRG1L    385866.227910       -0.000405  0.013935 -0.442426  0.658181
LY86       29697.950544        0.639950  0.325691  3.077237  0.002089
...                 ...             ...       ...       ...       ...
NHSL1      94012.124530        0.000076  0.014469  0.667395  0.504520
TRMT13     88746.782400        0.000484  0.012957 -1.534109  0.125003
SERPINA9    2241.315931        0.000103  0.015114  0.593831  0.552625
VPS26B    346795.921764        0.000916  0.014233  0.533484  0.593698
TNIP1     815300.506152       -0.000646  0.013879 -0.760218  0.447124

              padj
ACP2      0.993428
RBM42     0.986921
FOSB      0.974835
TPRG1L    0.982018
LY86      0.532850
...            ...
NHSL1     0.974835
TRMT13    0.950043
SERPINA9  0.974835
VPS26B    0.974835
TNIP1     0.974835

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.97 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.27 seconds.

Fitting LFCs...
... done in 0.94 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 136 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 136)
Number of True values in replace_mask: 227
replacement_counts_trimmed shape: (74, 136)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.11 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
ACP2      304718.990818        1.739511  0.134112 -0.182377  0.855287
RBM42     389049.940399        1.843699  0.128889  0.326138  0.744320
FOSB      362570.993364        2.164554  0.310147  1.394900  0.163046
TPRG1L    385866.227910        2.077071  0.115602 -0.442425  0.658182
LY86       29697.950544        1.813151  0.299828  3.077231  0.002089
...                 ...             ...       ...       ...       ...
NHSL1      94012.124530        1.538368  0.203245  0.667394  0.504521
TRMT13     88746.782400        1.200147  0.343956 -1.534109  0.125003
SERPINA9    2241.315931        0.000509  0.034280  0.593827  0.552628
VPS26B    346795.921764        2.421707  0.106025  0.533486  0.593697
TNIP1     815300.506152        2.020240  0.108196 -0.760210  0.447129

              padj
ACP2      0.993213
RBM42     0.988198
FOSB      0.950317
TPRG1L    0.981444
LY86      0.221825
...            ...
NHSL1     0.973605
TRMT13    0.923283
SERPINA9  0.973605
VPS26B    0.973605
TNIP1     0.973605

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 561 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.91 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.31 seconds.

Fitting LFCs...
... done in 0.61 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 156 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.09 seconds.

Fitting LFCs...
... done in 0.11 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.48 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SLC22A2  2.020601e+02       -0.000036  0.028368 -0.083327  0.933591  0.996789
TENT5B   1.212980e+05        0.000173  0.028719  0.068839  0.945117  0.996789
LCMT1    1.924601e+05        0.001065  0.029599  0.987973  0.323166  0.964464
ERICH5   5.664272e+03        0.000023  0.028801  0.029515  0.976454  0.997759
SNORD89  2.772123e+03       -0.000457  0.028240 -0.249788  0.802751  0.991172
...               ...             ...       ...       ...       ...       ...
CNBP     1.470353e+06       -0.000586  0.027689 -0.611600  0.540803  0.991017
SARS2    9.178560e+04       -0.000850  0.026573 -0.964322  0.334885  0.964464
NUDT21   6.110890e+05       -0.002594  0.024722 -2.491870  0.012707  0.665139
ARAP2    8.135103e+04       -0.004145  0.027607 -1.028450  0.303738  0.964190
ZNF564   5.942247e+04        0.000002  0.027878 -0.387464  0.698413  0.991017

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 1.33 seconds.

Fitting LFCs...
... done in 0.76 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 157 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 157)
Number of True values in replace_mask: 251
replacement_counts_trimmed shape: (78, 157)

... done in 0.08 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.63 seconds.

Fitting MAP LFCs...
... done in 0.99 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SLC22A2  2.020601e+02       -0.000060  0.036311 -0.083325  0.933593  0.996582
TENT5B   1.212980e+05        1.409618  0.305540  0.068839  0.945117  0.996582
LCMT1    1.924601e+05        1.795784  0.170092  0.987972  0.323166  0.971778
ERICH5   5.664272e+03       -0.000002  0.036854  0.029517  0.976452  0.997556
SNORD89  2.772123e+03       -0.001014  0.036008 -0.249779  0.802758  0.989055
...               ...             ...       ...       ...       ...       ...
CNBP     1.470353e+06        1.706909  0.131255 -0.611600  0.540803  0.987665
SARS2    9.178560e+04        1.273062  0.455912 -0.964321  0.334885  0.971778
NUDT21   6.110890e+05        1.196981  0.283306 -2.491871  0.012707  0.538597
ARAP2    8.135103e+04       -0.488117  0.083259 -1.028441  0.303742  0.966842
ZNF564   5.942247e+04        1.331666  0.418581 -0.387464  0.698413  0.987665

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 573 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.27 seconds.

Fitting LFCs...
... done in 0.59 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 146 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.37 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
BNIP3P1      7.307108e+04        0.002381  0.037670  1.700091  0.089114
TRIL         1.496494e+05       -0.000008  0.035300 -0.077774  0.938007
SNORD116-21  3.710412e+02       -0.001418  0.032278 -1.222967  0.221342
KAT2B        1.540564e+05        0.002702  0.035141 -0.221986  0.824325
RRM1         4.379961e+05        0.000958  0.035458  0.297473  0.766105
...                   ...             ...       ...       ...       ...
MADD         3.335012e+05       -0.000474  0.033420 -0.640934  0.521565
WDR83OS      6.144413e+05        0.001871  0.038823  0.999469  0.317568
GHITM        1.035236e+06        0.003139  0.036005  0.136674  0.891288
CUTC         1.178050e+05        0.015280  0.040920  1.667912  0.095333
PMP2         5.395173e+03       -0.003232  0.034485 -0.788797  0.430231

                 padj
BNIP3P1      0.898978
TRIL         0.993381
SNORD116-21  0.930551
KAT2B        0.985398
RRM1         0.983215
...               ...
MADD         0.972348
WDR83OS      0.930551
GHITM        0.989085
CUTC         0.898978
PMP2         0.956034

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.28 seconds.

Fitting LFCs...
... done in 0.82 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 146 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 146)
Number of True values in replace_mask: 247
replacement_counts_trimmed shape: (69, 146)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.04 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
BNIP3P1      7.307108e+04        1.622874  0.209542  1.700089  0.089114
TRIL         1.496494e+05        1.455374  0.287283 -0.077774  0.938008
SNORD116-21  3.710412e+02       -0.002214  0.040355 -1.222907  0.221365
KAT2B        1.540564e+05        1.576686  0.181227 -0.221986  0.824325
RRM1         4.379961e+05        1.875902  0.126682  0.297473  0.766105
...                   ...             ...       ...       ...       ...
MADD         3.335012e+05        1.554340  0.309089 -0.640934  0.521566
WDR83OS      6.144413e+05        2.038278  0.223167  0.999468  0.317568
GHITM        1.035236e+06        1.830768  0.134474  0.136674  0.891288
CUTC         1.178050e+05       -0.322686  0.080994  1.667901  0.095335
PMP2         5.395173e+03       -0.012977  0.047218 -0.788765  0.430249

                 padj
BNIP3P1      0.840409
TRIL         0.992751
SNORD116-21  0.904916
KAT2B        0.982205
RRM1         0.979913
...               ...
MADD         0.965305
WDR83OS      0.913871
GHITM        0.987344
CUTC         0.840409
PMP2         0.945027

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 548 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.82 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.30 seconds.

Fitting LFCs...
... done in 0.60 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 150 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.50 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
HMMR-AS1     1875.728121       -0.000008  0.036196 -0.011112  0.991134
ZNRF2P2      3579.552847       -0.000139  0.035776 -0.049950  0.960162
CCT6B       24234.958604        0.000505  0.036314  0.201374  0.840406
CCDC201       264.309055       -0.000946  0.029435 -1.639901  0.101026
HDGFL1        267.069367       -0.000915  0.029343 -1.634702  0.102112
...                  ...             ...       ...       ...       ...
CCDC162P    18652.913661        0.000489  0.037190  0.734028  0.462932
LINC00240   10611.116609       -0.000329  0.035039 -0.322520  0.747059
DDX27      298017.020557       -0.001122  0.035236 -0.396768  0.691538
DEGS1      494214.354991       -0.001892  0.035069 -0.711241  0.476935
RPS3AP37      133.985148        0.001796  0.036888  0.630370  0.528452

               padj
HMMR-AS1   0.998794
ZNRF2P2    0.998617
CCT6B      0.989181
CCDC201    0.864284
HDGFL1     0.864284
...             ...
CCDC162P   0.962959
LINC00240  0.980367
DDX27      0.976115
DEGS1      0.962959
RPS3AP37   0.975552

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.01 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.30 seconds.

Fitting LFCs...
... done in 0.74 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 150 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (80, 150)
Number of True values in replace_mask: 251
replacement_counts_trimmed shape: (76, 150)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
... done in 1.05 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
HMMR-AS1     1875.728121        0.000886  0.053790 -0.011112  0.991134
ZNRF2P2      3579.552847       -0.000471  0.052502 -0.049949  0.960163
CCT6B       24234.958604        0.950176  0.296114  0.201374  0.840406
CCDC201       264.309055       -0.002100  0.043889 -1.639852  0.101036
HDGFL1        267.069367       -0.002067  0.043752 -1.634664  0.102119
...                  ...             ...       ...       ...       ...
CCDC162P    18652.913661        0.189131  0.360201  0.734025  0.462933
LINC00240   10611.116609        0.000199  0.052110 -0.322520  0.747059
DDX27      298017.020557        1.564583  0.306336 -0.396768  0.691538
DEGS1      494214.354991        1.603088  0.163080 -0.711241  0.476935
RPS3AP37      133.985148        0.003852  0.054284  0.629930  0.528741

               padj
HMMR-AS1   0.998793
ZNRF2P2    0.998362
CCT6B      0.986223
CCDC201    0.830126
HDGFL1     0.830126
...             ...
CCDC162P   0.958445
LINC00240  0.976640
DDX27      0.972137
DEGS1      0.958445
RPS3AP37   0.970193

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 577 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4994 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.92 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.89 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 122 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.53 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
RTKN       259076.452457        0.000039  0.008819  0.342449  0.732013
RPL31P2      3922.562946        0.000050  0.008854  0.332279  0.739679
MIR6746      1596.213741        0.000039  0.008981  0.404160  0.686095
CYTH2      508505.257677        0.000262  0.008488 -1.412089  0.157924
RNF112      16281.325379        0.000177  0.009488  1.442858  0.149060
...                  ...             ...       ...       ...       ...
MYL1         3836.887744        0.000041  0.009198  0.557385  0.577264
PPIAP16       392.057733        0.000146  0.009074  0.917043  0.359120
LINC02084    1417.646611       -0.000174  0.008626 -0.489157  0.624731
MIR202HG      624.356180       -0.000224  0.008557 -0.935159  0.349706
LRIG3      172144.874753        0.000780  0.008954  0.293375  0.769235

               padj
RTKN       0.989259
RPL31P2    0.989259
MIR6746    0.989259
CYTH2      0.989259
RNF112     0.989259
...             ...
MYL1       0.989259
PPIAP16    0.989259
LINC02084  0.989259
MIR202HG   0.989259
LRIG3      0.989259

[4994 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.36 seconds.

Fitting LFCs...
... done in 0.79 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 122 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (120, 122)
Number of True values in replace_mask: 205
replacement_counts_trimmed shape: (95, 122)

... done in 0.05 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.30 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
RTKN       259076.452457        1.636983  0.166706  0.342449  0.732013
RPL31P2      3922.562946       -0.000178  0.017841  0.332275  0.739682
MIR6746      1596.213741        0.000110  0.018113  0.404155  0.686099
CYTH2      508505.257677        1.841195  0.100134 -1.412089  0.157924
RNF112      16281.325379        1.234445  0.336962  1.442855  0.149061
...                  ...             ...       ...       ...       ...
MYL1         3836.887744        0.000109  0.018555  0.557383  0.577266
PPIAP16       392.057733        0.000633  0.018300  0.916908  0.359191
LINC02084    1417.646611       -0.000714  0.017271 -0.489058  0.624801
MIR202HG      624.356180       -0.001381  0.017261 -0.934776  0.349904
LRIG3      172144.874753        1.591491  0.241381  0.293375  0.769235

               padj
RTKN       0.985303
RPL31P2    0.985303
MIR6746    0.985303
CYTH2      0.947769
RNF112     0.940437
...             ...
MYL1       0.980886
PPIAP16    0.976546
LINC02084  0.983218
MIR202HG   0.976546
LRIG3      0.985303

[4994 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 546 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.91 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.60 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 133 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.57 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat    pvalue  \
C5            55109.348163       -0.000607  0.023082 -0.397183  0.691232
ENPEP        105298.427427        0.000272  0.024084  0.668248  0.503975
MIR1469         219.577304       -0.000410  0.022644 -0.578554  0.562890
ENTPD5       267153.473184        0.000573  0.023575  0.455375  0.648839
TMEM243      103936.165267        0.002093  0.023559  0.797877  0.424942
...                    ...             ...       ...       ...       ...
CCNJL         25345.857128       -0.000043  0.023274 -0.100177  0.920204
ZRANB2       609480.609522       -0.000447  0.023184 -0.120958  0.903724
RAPGEF4-AS1     334.606144        0.000370  0.024363  0.519964  0.603089
HCN3          45232.710300        0.000253  0.023291  0.131271  0.895561
ANGPTL1      134187.997280        0.001903  0.023332  0.669914  0.502913

                 padj
C5           0.993094
ENPEP        0.990274
MIR1469      0.990274
ENTPD5       0.991865
TMEM243      0.990274
...               ...
CCNJL        0.993094
ZRANB2       0.993094
RAPGEF4-AS1  0.991865
HCN3         0.993094
ANGPTL1      0.990274

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.94 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.45 seconds.

Fitting LFCs...
... done in 0.93 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 133 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (120, 133)
Number of True values in replace_mask: 227
replacement_counts_trimmed shape: (106, 133)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.14 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                  baseMean  log2FoldChange     lfcSE      stat    pvalue  \
C5            55109.348163        1.225452  0.201438 -0.397183  0.691233
ENPEP        105298.427427        1.660043  0.201359  0.668247  0.503976
MIR1469         219.577304       -0.001202  0.038350 -0.578497  0.562929
ENTPD5       267153.473184        1.774894  0.122006  0.455375  0.648840
TMEM243      103936.165267        1.649482  0.113996  0.797875  0.424943
...                    ...             ...       ...       ...       ...
CCNJL         25345.857128        1.023019  0.800478 -0.100340  0.920075
ZRANB2       609480.609522        1.864800  0.090129 -0.121688  0.903146
RAPGEF4-AS1     334.606144        0.001089  0.041226  0.519930  0.603112
HCN3          45232.710300        1.373086  0.148039  0.131271  0.895561
ANGPTL1      134187.997280        1.696165  0.107496  0.669912  0.502914

                 padj
C5           0.989531
ENPEP        0.976955
MIR1469      0.978516
ENTPD5       0.982239
TMEM243      0.971619
...               ...
CCNJL        0.990759
ZRANB2       0.990759
RAPGEF4-AS1  0.982239
HCN3         0.990759
ANGPTL1      0.976955

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 603 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.60 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 127 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.48 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
GBP5     129843.704686        0.000615  0.026497 -0.202109  0.839831  0.993285
CXCL3      7767.901926       -0.000973  0.025183 -1.051866  0.292861  0.954284
ARID1B   541150.740041        0.007712  0.029717  1.616350  0.106019  0.909464
DYNLRB2    7030.501198        0.001632  0.028643  1.251919  0.210600  0.948589
SLIT1     20148.754117        0.000531  0.027855  0.548123  0.583608  0.990807
...                ...             ...       ...       ...       ...       ...
MIR4656     164.709344       -0.001908  0.025625 -1.278614  0.201033  0.948589
GRXCR2      178.498313        0.000927  0.026399  0.308911  0.757389  0.993285
ELK4     364101.528172        0.003168  0.028415  1.468879  0.141866  0.910917
CLEC4D     1142.561803        0.000646  0.026848  0.316494  0.751628  0.993285
CC2D1A   331665.955608       -0.009107  0.030097 -0.650449  0.515402  0.982798

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.99 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.53 seconds.

Fitting LFCs...
... done in 0.96 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 127 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 127)
Number of True values in replace_mask: 213
replacement_counts_trimmed shape: (99, 127)

... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.11 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
GBP5     129843.704686        1.440582  0.334297 -0.202050  0.839878  0.992766
CXCL3      7767.901926       -0.002900  0.034729 -1.051863  0.292862  0.939125
ARID1B   541150.740041        2.333063  0.081841  1.616349  0.106019  0.850500
DYNLRB2    7030.501198        0.002340  0.039090  1.251911  0.210602  0.914076
SLIT1     20148.754117        1.167463  0.426930  0.548122  0.583608  0.981554
...                ...             ...       ...       ...       ...       ...
MIR4656     164.709344       -0.003522  0.035171 -1.278169  0.201190  0.914076
GRXCR2      178.498313        0.001707  0.035455  0.308505  0.757698  0.991140
ELK4     364101.528172        1.850356  0.143701  1.468878  0.141866  0.855085
CLEC4D     1142.561803        0.001202  0.036452  0.316465  0.751650  0.991140
CC2D1A   331665.955608        2.014199  0.095488 -0.644271  0.519400  0.972600

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 560 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4993 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 0.58 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 150 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.53 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
RASL11B    29222.993241       -0.000116  0.009597 -0.622822  0.533401
CD101       9392.064395       -0.000118  0.009611 -0.742871  0.457560
PTGES3L     6439.195323        0.000099  0.010030  0.347361  0.728320
NCOA1     432726.727099        0.000093  0.009918  0.383917  0.701040
SRP19     176492.253259       -0.001027  0.010333  1.731579  0.083349
...                 ...             ...       ...       ...       ...
CHCHD4P4     229.671249        0.000054  0.010403  0.555526  0.578535
TCFL5     115777.998572        0.000516  0.010113  0.414860  0.678245
ZNF384    378011.604707       -0.000019  0.009648 -0.827460  0.407976
FBXO27     41919.068998       -0.002819  0.010573 -0.564444  0.572452
ZSCAN10      181.306640       -0.000235  0.009540 -1.017403  0.308962

              padj
RASL11B   0.972610
CD101     0.972610
PTGES3L   0.983439
NCOA1     0.981466
SRP19     0.962398
...            ...
CHCHD4P4  0.972610
TCFL5     0.981466
ZNF384    0.972610
FBXO27    0.972610
ZSCAN10   0.972610

[4993 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.10 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.41 seconds.

Fitting LFCs...
... done in 1.11 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

Replacing 150 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (120, 150)
Number of True values in replace_mask: 231
replacement_counts_trimmed shape: (102, 150)

... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.01 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
RASL11B    29222.993241        0.992603  0.316534 -0.622821  0.533402
CD101       9392.064395       -0.003745  0.029612 -0.742866  0.457563
PTGES3L     6439.195323        0.000586  0.030201  0.347358  0.728322
NCOA1     432726.727099        2.136330  0.085126  0.383916  0.701040
SRP19     176492.253259        1.971261  0.105915  1.731576  0.083349
...                 ...             ...       ...       ...       ...
CHCHD4P4     229.671249        0.000536  0.031492  0.555495  0.578556
TCFL5     115777.998572        1.469817  0.250052  0.414859  0.678245
ZNF384    378011.604707        1.581831  0.142425 -0.827460  0.407976
FBXO27     41919.068998        1.094178  0.695415 -0.566560  0.571013
ZSCAN10      181.306640       -0.002118  0.028884 -1.017001  0.309153

              padj
RASL11B   0.960410
CD101     0.959775
PTGES3L   0.977332
NCOA1     0.973968
SRP19     0.855243
...            ...
CHCHD4P4  0.960410
TCFL5     0.973800
ZNF384    0.959445
FBXO27    0.960410
ZSCAN10   0.946184

[4993 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 587 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4989 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 0.60 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 110 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.05 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.74 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SPOCK2   142933.617276    6.904167e-05  0.007663  0.010191  0.991869  0.999666
NR4A3     96806.607953   -9.333988e-05  0.007224 -1.081645  0.279410  0.965552
NPR1     616202.701459   -3.479768e-04  0.006955 -1.904782  0.056808  0.941585
ABHD17C  109171.760530    1.569529e-07  0.007445 -0.593128  0.553095  0.993278
PHYHIP    64846.444315    6.562961e-04  0.008673  1.614248  0.106474  0.962523
...                ...             ...       ...       ...       ...       ...
NAALAD2   39147.001974    2.999548e-05  0.007830  0.341231  0.732930  0.999666
SNORA9     2007.435337    1.104237e-03  0.007919  0.821938  0.411112  0.990322
NT5DC1   203970.932044    3.417202e-04  0.007813  0.976570  0.328782  0.979965
CEP57L1   53185.168215   -5.536608e-05  0.007633 -0.106396  0.915268  0.999666
ARPC4    822967.799493    2.742681e-03  0.009525  1.969873  0.048853  0.941585

[4989 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.36 seconds.

Fitting LFCs...
... done in 0.78 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 110 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (120, 110)
Number of True values in replace_mask: 164
replacement_counts_trimmed shape: (92, 110)

... done in 0.05 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.31 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SPOCK2   142933.617276        1.425279  0.210633  0.010191  0.991869  0.999666
NR4A3     96806.607953        1.355885  0.286300 -1.081645  0.279410  0.943360
NPR1     616202.701459        1.422750  0.192449 -1.904782  0.056808  0.821499
ABHD17C  109171.760530        1.274733  0.283427 -0.593128  0.553095  0.986883
PHYHIP    64846.444315        1.891101  0.317871  1.614250  0.106473  0.908336
...                ...             ...       ...       ...       ...       ...
NAALAD2   39147.001974        1.393922  0.363393  0.341231  0.732930  0.999666
SNORA9     2007.435337        0.001538  0.015904  0.821625  0.411291  0.977682
NT5DC1   203970.932044        1.954728  0.103026  0.976568  0.328783  0.960059
CEP57L1   53185.168215        1.332500  0.133070 -0.106396  0.915268  0.999666
ARPC4    822967.799493        2.438643  0.070253  1.969872  0.048853  0.821499

[4989 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 577 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.01 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.46 seconds.

Fitting LFCs...
... done in 0.68 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 123 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.52 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
ENHO        3.626287e+04        0.000480  0.016976  0.843217  0.399107
RPSAP36     9.131117e+02        0.000435  0.017930  1.408493  0.158985
KRT8        3.571477e+06       -0.000349  0.016057  0.009280  0.992596
MAP2K4      1.837636e+05        0.001928  0.016542  1.281968  0.199854
MARCKSL1P1  3.748202e+02        0.000569  0.019634  2.128782  0.033272
...                  ...             ...       ...       ...       ...
FAM83A-AS1  8.898722e+02        0.000383  0.015877  0.270703  0.786620
MIR2110     8.237193e+02       -0.000680  0.015625 -0.891438  0.372694
ALOX12      1.256686e+04       -0.000566  0.015529 -0.920211  0.357462
OR52N4      1.838206e+03       -0.000070  0.015747 -0.289924  0.771874
ACSBG2      2.237820e+03        0.000181  0.017050  0.679866  0.496589

                padj
ENHO        0.980022
RPSAP36     0.980022
KRT8        0.999007
MAP2K4      0.980022
MARCKSL1P1  0.872181
...              ...
FAM83A-AS1  0.981329
MIR2110     0.980022
ALOX12      0.980022
OR52N4      0.981329
ACSBG2      0.980022

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.98 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.41 seconds.

Fitting LFCs...
... done in 0.78 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 123 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (120, 123)
Number of True values in replace_mask: 207
replacement_counts_trimmed shape: (99, 123)

... done in 0.05 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.13 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
ENHO        3.626287e+04        1.503331  0.366010  0.843216  0.399108
RPSAP36     9.131117e+02        0.001555  0.033631  1.408462  0.158994
KRT8        3.571477e+06        1.848960  0.084391  0.009280  0.992596
MAP2K4      1.837636e+05        1.937656  0.104382  1.281966  0.199855
MARCKSL1P1  3.748202e+02        0.001968  0.036894  2.128686  0.033280
...                  ...             ...       ...       ...       ...
FAM83A-AS1  8.898722e+02        0.001397  0.028723  0.270580  0.786714
MIR2110     8.237193e+02       -0.002548  0.029216 -0.891313  0.372761
ALOX12      1.256686e+04       -0.400877  0.255647 -0.920206  0.357465
OR52N4      1.838206e+03       -0.000346  0.029463 -0.289496  0.772202
ACSBG2      2.237820e+03        0.000631  0.031931  0.679862  0.496592

                padj
ENHO        0.973859
RPSAP36     0.930144
KRT8        0.998806
MAP2K4      0.939534
MARCKSL1P1  0.656011
...              ...
FAM83A-AS1  0.976487
MIR2110     0.973859
ALOX12      0.973859
OR52N4      0.975674
ACSBG2      0.973859

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 601 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.10 seconds.

Fitting MAP dispersions...
... done in 1.48 seconds.

Fitting LFCs...
... done in 0.79 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 129 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.53 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CHMP6    140037.268004       -0.000274  0.014137 -0.180439  0.856808  0.996952
PTMAP10     202.141093        0.000184  0.014695  0.563913  0.572813  0.986648
DRAXIN     6694.587731        0.000047  0.014392  0.166336  0.867893  0.996952
CYP2T1P  119022.122529        0.000301  0.015677  1.152175  0.249249  0.986614
SH3RF1   238015.456338       -0.001709  0.014276 -0.641052  0.521489  0.986648
...                ...             ...       ...       ...       ...       ...
BET1     136176.767154        0.000110  0.014268  0.155250  0.876624  0.996952
AGBL2      7428.748121        0.000629  0.014667  1.044839  0.296097  0.986614
XPC      354244.298107       -0.001575  0.015515  0.766593  0.443324  0.986614
PXT1        908.390887        0.000607  0.015177  1.340785  0.179990  0.969817
GAL3ST1    4156.353081       -0.000022  0.014048 -0.250124  0.802492  0.996006

[4991 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.97 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.39 seconds.

Fitting LFCs...
... done in 0.80 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 129 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 129)
Number of True values in replace_mask: 216
replacement_counts_trimmed shape: (99, 129)

... done in 0.07 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.35 seconds.

Fitting MAP LFCs...
... done in 1.17 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CHMP6    140037.268004        1.562816  0.153416 -0.180439  0.856808  0.995206
PTMAP10     202.141093        0.000490  0.023965  0.563819  0.572877  0.979420
DRAXIN     6694.587731        0.000157  0.023479  0.166335  0.867893  0.995206
CYP2T1P  119022.122529        1.817467  0.387218  1.152175  0.249249  0.971377
SH3RF1   238015.456338        1.645533  0.120645 -0.641051  0.521489  0.976989
...                ...             ...       ...       ...       ...       ...
BET1     136176.767154        1.584635  0.153930  0.155250  0.876625  0.995206
AGBL2      7428.748121        0.001071  0.023795  1.044821  0.296106  0.975844
XPC      354244.298107        1.933755  0.286207  0.766593  0.443324  0.975844
PXT1        908.390887        0.001553  0.024806  1.340709  0.180015  0.927191
GAL3ST1    4156.353081       -0.000114  0.022910 -0.250122  0.802493  0.993401

[4991 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 606 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.36 seconds.

Fitting LFCs...
... done in 0.63 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 120 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.60 seconds.

Fitting MAP LFCs...
... done in 1.47 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
PCDHB7       22684.049942       -0.000197  0.009904 -1.079468  0.280379
SAMD13        8785.328743        0.000298  0.010885  1.070944  0.284195
RNU6-100P      188.950863        0.000069  0.010896  0.620121  0.535178
ZC3HAV1     291429.746771        0.000220  0.010414  0.530079  0.596057
OR2C1          461.170870        0.000146  0.011392  1.198398  0.230762
...                   ...             ...       ...       ...       ...
RNU6-1330P     440.202050        0.000127  0.010878  0.831533  0.405672
RPL17P43     12785.406610        0.000255  0.011843  1.896809  0.057853
PCDHA5       68734.282877        0.000032  0.010317  0.011468  0.990850
GABRA1         134.335346       -0.000145  0.010218 -0.266814  0.789612
FXR2        276952.568855        0.000303  0.010435  0.349970  0.726361

                padj
PCDHB7      0.953443
SAMD13      0.953443
RNU6-100P   0.975016
ZC3HAV1     0.977429
OR2C1       0.953443
...              ...
RNU6-1330P  0.959449
RPL17P43    0.912043
PCDHA5      0.999188
GABRA1      0.984523
FXR2        0.978552

[4991 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.98 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.36 seconds.

Fitting LFCs...
... done in 0.85 seconds.

Calculating cook's distance...
... done in 0.07 seconds.

Replacing 120 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (120, 120)
Number of True values in replace_mask: 205
replacement_counts_trimmed shape: (99, 120)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.17 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
PCDHB7       22684.049942       -0.003873  0.023156 -1.079465  0.280381
SAMD13        8785.328743        0.001030  0.024462  1.070938  0.284197
RNU6-100P      188.950863        0.000331  0.024508  0.620074  0.535209
ZC3HAV1     291429.746771        1.826257  0.113617  0.530079  0.596057
OR2C1          461.170870        0.000731  0.025639  1.198352  0.230780
...                   ...             ...       ...       ...       ...
RNU6-1330P     440.202050        0.000627  0.024460  0.831482  0.405702
RPL17P43     12785.406610        1.690280  0.381977  1.896806  0.057853
PCDHA5       68734.282877        1.400304  0.200236  0.011468  0.990850
GABRA1         134.335346       -0.000734  0.022530 -0.266130  0.790139
FXR2        276952.568855        1.649252  0.158249  0.349970  0.726361

                padj
PCDHB7      0.933441
SAMD13      0.933441
RNU6-100P   0.966203
ZC3HAV1     0.972953
OR2C1       0.933441
...              ...
RNU6-1330P  0.946253
RPL17P43    0.800488
PCDHA5      0.999188
GABRA1      0.983087
FXR2        0.976467

[4991 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 603 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.44 seconds.

Fitting LFCs...
... done in 0.62 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 130 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.57 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
KRT8P37   3.706078e+03        0.000217  0.013150  1.604831  0.108531  0.935518
ERFL      2.789603e+03       -0.000099  0.011170 -0.323086  0.746630  0.996156
AQP4      4.224918e+03       -0.000119  0.010775 -0.798377  0.424652  0.996156
RASGRP2   1.028330e+05        0.000399  0.012080  1.525278  0.127190  0.935518
ELOB      6.687475e+05       -0.002318  0.011632 -0.894007  0.371318  0.996156
...                ...             ...       ...       ...       ...       ...
HEXD      1.952184e+05        0.000204  0.011336  0.312341  0.754781  0.996156
UNC13C    1.384049e+03       -0.000738  0.011054 -1.308824  0.190594  0.971165
GPX1      1.043857e+06        0.348201  0.236337  2.714826  0.006631  0.839893
PEF1      3.915575e+05        0.001302  0.011854  1.236245  0.216368  0.983810
RPS10P28  5.502415e+02        0.000058  0.011506  0.255352  0.798451  0.996156

[4988 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.13 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.43 seconds.

Fitting LFCs...
... done in 0.80 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 130 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (120, 130)
Number of True values in replace_mask: 216
replacement_counts_trimmed shape: (102, 130)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.16 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
KRT8P37   3.706078e+03        0.000782  0.027724  1.604824  0.108532  0.868146
ERFL      2.789603e+03       -0.000447  0.023451 -0.323077  0.746637  0.995125
AQP4      4.224918e+03       -0.000366  0.022698 -0.798373  0.424654  0.981152
RASGRP2   1.028330e+05        1.779820  0.196615  1.525277  0.127190  0.882027
ELOB      6.687475e+05        1.641248  0.134966 -0.896161  0.370167  0.980265
...                ...             ...       ...       ...       ...       ...
HEXD      1.952184e+05        1.621616  0.119748  0.312341  0.754781  0.995125
UNC13C    1.384049e+03       -0.003948  0.023722 -1.308582  0.190676  0.928370
GPX1      1.043857e+06        2.149406  0.097578  2.714826  0.006631  0.453092
PEF1      3.915575e+05        1.927360  0.103792  1.236244  0.216368  0.945046
RPS10P28  5.502415e+02        0.000175  0.024228  0.255342  0.798459  0.995125

[4988 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 605 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.60 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 135 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.49 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
CRLF1      128800.313833        0.000538  0.023654  0.669400  0.503240
ARFGAP3    352345.596414        0.003691  0.023951  1.741295  0.081632
KLB         54253.109355        0.000269  0.020308 -2.069135  0.038533
EIF2AK3    230716.494087       -0.000622  0.022696  0.276121  0.782455
APOH         2367.105049        0.000361  0.029720  1.343584  0.179083
...                  ...             ...       ...       ...       ...
DERL1      656549.203240        0.002488  0.030647  2.211370  0.027010
GAD1         8806.334590        0.000205  0.024650  0.880630  0.378518
MRPL37P1      187.485042       -0.001122  0.022006 -0.995908  0.319295
RAB11FIP4  196332.144929       -0.001713  0.022011 -1.422279  0.154945
RPS15AP14     340.756863       -0.000202  0.022599 -0.140672  0.888129

               padj
CRLF1      0.984403
ARFGAP3    0.874151
KLB        0.809618
EIF2AK3    0.994832
APOH       0.920953
...             ...
DERL1      0.760379
GAD1       0.982297
MRPL37P1   0.974871
RAB11FIP4  0.908897
RPS15AP14  0.994832

[4988 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.98 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.38 seconds.

Fitting LFCs...
... done in 1.12 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

Replacing 135 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (120, 135)
Number of True values in replace_mask: 198
replacement_counts_trimmed shape: (100, 135)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.03 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
CRLF1      128800.313833        1.592015  0.272603  0.669400  0.503240
ARFGAP3    352345.596414        1.963401  0.104743  1.741294  0.081632
KLB         54253.109355        0.913011  0.420782 -2.069134  0.038533
EIF2AK3    230716.494087        1.708492  0.121014  0.276121  0.782455
APOH         2367.105049        0.000930  0.046002  1.343573  0.179087
...                  ...             ...       ...       ...       ...
DERL1      656549.203240        2.628769  0.181117  2.211409  0.027008
GAD1         8806.334590        0.001269  0.038152  0.880629  0.378519
MRPL37P1      187.485042       -0.002678  0.034025 -0.995582  0.319453
RAB11FIP4  196332.144929        1.744729  0.105716 -1.422277  0.154946
RPS15AP14     340.756863       -0.000426  0.034601 -0.140630  0.888162

               padj
CRLF1      0.975452
ARFGAP3    0.805564
KLB        0.664953
EIF2AK3    0.993599
APOH       0.884174
...             ...
DERL1      0.604097
GAD1       0.969237
MRPL37P1   0.957561
RAB11FIP4  0.864628
RPS15AP14  0.994442

[4988 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 575 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.94 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.45 seconds.

Fitting LFCs...
... done in 0.64 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 124 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.40 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
KLF7-IT1  2.605073e+03       -0.000363  0.030602 -0.355174  0.722460  0.985535
ATXN2     2.846637e+05        0.003076  0.029854  0.572660  0.566875  0.985535
PPDPF     1.309215e+06       -0.001947  0.030229 -0.991660  0.321363  0.965815
GDAP1     1.171138e+05        0.001238  0.032026  0.571571  0.567613  0.985535
FNBP1P1   5.519729e+03        0.001903  0.032338  0.821352  0.411446  0.985535
...                ...             ...       ...       ...       ...       ...
RGL1      2.488851e+05        0.000244  0.031269  0.112448  0.910468  0.993219
MESTP3    1.990710e+03        0.004522  0.031635  0.994252  0.320100  0.965815
IL22RA2   3.525929e+03        0.000094  0.031886  0.110322  0.912154  0.993219
SZT2-AS1  2.682870e+04       -0.000766  0.029268 -0.855537  0.392254  0.985535
MAX       3.510264e+05        0.000227  0.031568  0.100798  0.919711  0.993219

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.35 seconds.

Fitting LFCs...
... done in 0.79 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 124 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (120, 124)
Number of True values in replace_mask: 208
replacement_counts_trimmed shape: (100, 124)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.45 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
KLF7-IT1  2.605073e+03       -0.000543  0.037061 -0.355172  0.722461  0.983326
ATXN2     2.846637e+05        2.292907  0.092904  0.572659  0.566876  0.983326
PPDPF     1.309215e+06        1.662128  0.106586 -0.991660  0.321363  0.946000
GDAP1     1.171138e+05        1.665084  0.190163  0.571571  0.567612  0.983326
FNBP1P1   5.519729e+03        0.003200  0.039169  0.821342  0.411452  0.983230
...                ...             ...       ...       ...       ...       ...
RGL1      2.488851e+05        1.586960  0.172188  0.112448  0.910468  0.991303
MESTP3    1.990710e+03        0.006944  0.038198  0.994109  0.320170  0.946000
IL22RA2   3.525929e+03        0.000137  0.038624  0.110322  0.912154  0.991303
SZT2-AS1  2.682870e+04        0.757146  1.085156 -0.855532  0.392256  0.971045
MAX       3.510264e+05        1.716070  0.210614  0.100798  0.919711  0.991303

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 584 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.41 seconds.

Fitting LFCs...
... done in 0.62 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 141 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.46 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
PLD3       1.205600e+06        0.292508  0.255854  2.481107  0.013098
EBF1       2.766501e+05        0.001644  0.031182  0.026412  0.978929
ALKBH6     6.964600e+04        0.007382  0.033961  1.842589  0.065389
CRYZL1     1.292617e+05       -0.012790  0.035274 -1.249031  0.211654
GEMIN5     1.824993e+05        0.002129  0.029042 -0.650776  0.515191
...                 ...             ...       ...       ...       ...
LPGAT1     5.020060e+05       -0.000703  0.027078 -1.649689  0.099007
ITGB8      1.299213e+05       -0.000193  0.030262 -0.389837  0.696657
RAB11FIP5  2.952546e+05        0.007446  0.032821  1.015811  0.309719
PRDM2      3.910286e+05        0.001157  0.030537 -0.321576  0.747774
HYI        2.631592e+05       -0.000249  0.030141 -0.468485  0.639438

               padj
PLD3       0.689461
EBF1       0.998009
ALKBH6     0.843968
CRYZL1     0.899815
GEMIN5     0.955861
...             ...
LPGAT1     0.877810
ITGB8      0.969413
RAB11FIP5  0.926512
PRDM2      0.969996
HYI        0.968040

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.97 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 0.80 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 141 outlier genes.

Fitting dispersions...

replace_mask before filtering: (120, 141)
Number of True values in replace_mask: 231
replacement_counts_trimmed shape: (101, 141)

... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
... done in 1.29 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
PLD3       1.205600e+06        2.121394  0.092210  2.481112  0.013097
EBF1       2.766501e+05        1.656751  0.223917  0.026412  0.978929
ALKBH6     6.964600e+04        1.668169  0.127974  1.842590  0.065389
CRYZL1     1.292617e+05        2.118710  0.094956 -1.249033  0.211653
GEMIN5     1.824993e+05        1.957900  0.096178 -0.650778  0.515190
...                 ...             ...       ...       ...       ...
LPGAT1     5.020060e+05        1.310343  0.258567 -1.649696  0.099005
ITGB8      1.299213e+05        1.387709  0.383155 -0.389837  0.696657
RAB11FIP5  2.952546e+05        2.072426  0.094087  1.015814  0.309718
PRDM2      3.910286e+05        1.635546  0.151915 -0.321574  0.747776
HYI        2.631592e+05        1.546507  0.289560 -0.468484  0.639438

               padj
PLD3       0.487131
EBF1       0.998009
ALKBH6     0.743764
CRYZL1     0.860401
GEMIN5     0.949847
...             ...
LPGAT1     0.792041
ITGB8      0.966734
RAB11FIP5  0.899085
PRDM2      0.968768
HYI        0.963988

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 588 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.80 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 104 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.05 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.31 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.45 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
MAP4K3-DT  3.435234e+04        0.000747  0.027340  0.220756  0.825282
HDAC2-AS2  2.343022e+03       -0.000382  0.026498 -0.941849  0.346270
UFM1       4.039446e+05        0.004493  0.027856  0.875697  0.381195
FOXO3B     4.959957e+04        0.001755  0.027247 -0.100307  0.920100
FBXO48     2.163846e+04       -0.001434  0.026484 -0.546648  0.584620
...                 ...             ...       ...       ...       ...
SHQ1       1.163726e+05       -0.000911  0.028278  0.796574  0.425699
SLC25A38   1.794826e+05        0.001060  0.028636  0.590795  0.554658
SARS2      5.726241e+04        0.000548  0.031347  2.063017  0.039111
SSX2IP     1.049329e+05        0.005195  0.030864  2.219609  0.026445
MAP4       1.743544e+06       -0.184640  0.390183 -1.649103  0.099126

               padj
MAP4K3-DT  0.999785
HDAC2-AS2  0.975947
UFM1       0.981019
FOXO3B     0.999785
FBXO48     0.992524
...             ...
SHQ1       0.981019
SLC25A38   0.992524
SARS2      0.840394
SSX2IP     0.821454
MAP4       0.888736

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.01 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.47 seconds.

Fitting LFCs...
... done in 0.94 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 104 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (120, 104)
Number of True values in replace_mask: 159
replacement_counts_trimmed shape: (87, 104)

... done in 0.05 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.28 seconds.

Fitting MAP LFCs...
... done in 1.07 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
MAP4K3-DT  3.435234e+04        1.333680  0.166787  0.220756  0.825283
HDAC2-AS2  2.343022e+03       -0.002409  0.029973 -0.941808  0.346291
UFM1       4.039446e+05        2.207494  0.090819  0.875696  0.381195
FOXO3B     4.959957e+04        1.132163  0.175700 -0.100307  0.920101
FBXO48     2.163846e+04       -0.129519  0.149930 -0.546640  0.584626
...                 ...             ...       ...       ...       ...
SHQ1       1.163726e+05        1.703090  0.189557  0.796573  0.425699
SLC25A38   1.794826e+05        1.712902  0.299682  0.590795  0.554658
SARS2      2.354325e+04        1.961664  0.320031  3.171905  0.001514
SSX2IP     1.049329e+05        1.795543  0.166503  2.219606  0.026445
MAP4       1.743544e+06        1.730716  0.081408 -1.649103  0.099126

               padj
MAP4K3-DT  0.999585
HDAC2-AS2  0.961725
UFM1       0.970521
FOXO3B     0.999585
FBXO48     0.990194
...             ...
SHQ1       0.970521
SLC25A38   0.988073
SARS2      0.268186
SSX2IP     0.709047
MAP4       0.839213

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 586 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4996 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.98 seconds.

Fitting dispersion trend curve...
... done in 0.17 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 0.98 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 139 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.07 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.33 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SDHB       3.346967e+05        0.001173  0.021334  1.065175  0.286797
LPL        2.620922e+06        0.000213  0.022158  0.406099  0.684670
RPS2       2.667922e+06       -0.000200  0.021134 -0.106688  0.915036
LINC00881  2.802212e+02       -0.000648  0.018582 -1.709938  0.087277
LRP5       6.482278e+05        0.002861  0.021353 -0.642740  0.520393
...                 ...             ...       ...       ...       ...
EMC8       1.385739e+05       -0.000564  0.021738  0.415964  0.677436
USP15      3.773847e+05       -0.002042  0.020518 -1.231558  0.218114
MS4A6A     2.097486e+05        0.001379  0.021406  0.594222  0.552364
DDI2       4.868911e+05        0.000579  0.020485 -1.031895  0.302121
ZEB2-AS1   7.677984e+03        0.000422  0.024756  1.181168  0.237536

               padj
SDHB       0.969611
LPL        0.978898
RPS2       0.993921
LINC00881  0.943184
LRP5       0.976697
...             ...
EMC8       0.977068
USP15      0.967121
MS4A6A     0.976697
DDI2       0.969611
ZEB2-AS1   0.969611

[4996 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.98 seconds.

Fitting dispersion trend curve...
... done in 0.12 seconds.

Fitting MAP dispersions...
... done in 1.48 seconds.

Fitting LFCs...
... done in 0.79 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 139 outlier genes.

Fitting dispersions...
... done in 0.07 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (120, 139)
Number of True values in replace_mask: 217
replacement_counts_trimmed shape: (103, 139)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.32 seconds.

Fitting MAP LFCs...
... done in 1.12 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SDHB       3.346967e+05        2.170769  0.096054  1.053606  0.292063
LPL        2.620922e+06        1.952464  0.119709  0.406099  0.684670
RPS2       2.667922e+06        1.968303  0.065855 -0.106688  0.915036
LINC00881  2.802212e+02       -0.002032  0.032904 -1.709869  0.087290
LRP5       6.482278e+05        1.715739  0.133938 -0.642741  0.520392
...                 ...             ...       ...       ...       ...
EMC8       1.385739e+05        1.537830  0.235680  0.415964  0.677436
USP15      3.773847e+05        1.542220  0.187317 -1.231557  0.218115
MS4A6A     2.097486e+05        1.693467  0.119644  0.594221  0.552364
DDI2       4.868911e+05        1.619084  0.160368 -1.031904  0.302117
ZEB2-AS1   7.677984e+03        0.001306  0.043726  1.181172  0.237535

               padj
SDHB       0.936898
LPL        0.972159
RPS2       0.992253
LINC00881  0.831104
LRP5       0.964606
...             ...
EMC8       0.969813
USP15      0.914304
MS4A6A     0.967963
DDI2       0.937613
ZEB2-AS1   0.926690

[4996 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 543 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4988 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.93 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.43 seconds.

Fitting LFCs...
... done in 0.60 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 127 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.39 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SYT2        7316.476054       -0.000035  0.025453 -0.326787  0.743829
PFKFB2    157365.665587        0.006893  0.028611  0.060061  0.952107
NMRAL1    273675.099988        0.001769  0.027677  1.609305  0.107550
CDKN2A     85802.513927       -0.000799  0.024494 -0.942661  0.345855
C12orf43   96909.047696       -0.008688  0.027998 -1.524220  0.127454
...                 ...             ...       ...       ...       ...
ATXN1     258103.962982       -0.000424  0.025930  0.057723  0.953970
SEC11B     15584.910012       -0.005778  0.025447 -0.916024  0.359654
ATP8A1    126184.805832        0.000099  0.025777  0.482734  0.629285
PRSS22     69359.434210        0.003365  0.026027 -0.297071  0.766412
EMC1-AS1   13088.940079       -0.001790  0.025006 -1.084268  0.278246

              padj
SYT2      0.998397
PFKFB2    0.998397
NMRAL1    0.899889
CDKN2A    0.968893
C12orf43  0.899889
...            ...
ATXN1     0.998397
SEC11B    0.979233
ATP8A1    0.998397
PRSS22    0.998397
EMC1-AS1  0.948379

[4988 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.86 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.41 seconds.

Fitting LFCs...
... done in 0.78 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 127 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (120, 127)
Number of True values in replace_mask: 185
replacement_counts_trimmed shape: (97, 127)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.13 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
SYT2        7316.476054       -0.001712  0.034785 -0.326785  0.743831
PFKFB2    157365.665587        1.477494  0.209836  0.060061  0.952107
NMRAL1    273675.099988        1.851703  0.176030  1.609305  0.107550
CDKN2A     85802.513927        1.109104  0.394999 -0.942660  0.345855
C12orf43   96909.047696        0.709917  0.087087 -1.524212  0.127456
...                 ...             ...       ...       ...       ...
ATXN1     258103.962982        1.655293  0.221996  0.057723  0.953970
SEC11B     15584.910012       -0.066799  0.085163 -0.915978  0.359678
ATP8A1    126184.805832        1.551103  0.139790  0.482733  0.629285
PRSS22     69359.434210        1.266425  0.166660 -0.297070  0.766413
EMC1-AS1   13088.940079       -0.469091  0.234397 -1.084261  0.278249

              padj
SYT2      0.998149
PFKFB2    0.998509
NMRAL1    0.830933
CDKN2A    0.946116
C12orf43  0.848379
...            ...
ATXN1     0.998509
SEC11B    0.956840
ATP8A1    0.998149
PRSS22    0.998149
EMC1-AS1  0.915892

[4988 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 617 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4991 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.94 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.41 seconds.

Fitting LFCs...
... done in 0.61 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 134 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.08 seconds.

Running Wald tests...
... done in 0.33 seconds.

Fitting MAP LFCs...
... done in 1.64 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CCDC183   3.399724e+04        0.000912  0.023477  0.387354  0.698494  0.991101
OLFM5P    8.732958e+02       -0.001163  0.021695 -1.363887  0.172603  0.954313
CLEC14A   2.959431e+05        0.001822  0.024570  1.287065  0.198071  0.954313
PLPPR1    2.129124e+03        0.000664  0.026391  1.293086  0.195981  0.954313
GALM      1.077551e+05       -0.002860  0.022293 -1.922550  0.054537  0.924710
...                ...             ...       ...       ...       ...       ...
POGK      4.734999e+05       -0.001454  0.022242 -1.203782  0.228674  0.954313
C12orf71  5.967782e+02       -0.001170  0.022599 -0.505433  0.613255  0.991101
CDKAL1    9.184269e+04        0.001161  0.026797  1.832496  0.066878  0.924710
ATP11A    2.278389e+05       -0.001502  0.022038 -1.362358  0.173085  0.954313
COL4A1    3.170280e+06       -0.000445  0.023083 -0.027498  0.978063  0.999881

[4991 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 1.00 seconds.

Fitting dispersion trend curve...
... done in 0.09 seconds.

Fitting MAP dispersions...
... done in 1.43 seconds.

Fitting LFCs...
... done in 1.20 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

Replacing 134 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (120, 134)
Number of True values in replace_mask: 218
replacement_counts_trimmed shape: (100, 134)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.00 seconds.

Log2 fold change & Wald test p-value: condition B vs A
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
CCDC183   3.399724e+04        1.204733  0.239740  0.386145  0.699390  0.986312
OLFM5P    8.732958e+02       -0.002105  0.029607 -1.363834  0.172620  0.898575
CLEC14A   2.959431e+05        1.847085  0.177149  1.287065  0.198072  0.922822
PLPPR1    2.129124e+03        0.001445  0.036005  1.293078  0.195984  0.922822
GALM      1.077551e+05        1.294106  0.169695 -1.922548  0.054537  0.784174
...                ...             ...       ...       ...       ...       ...
POGK      4.734999e+05        1.596199  0.151710 -1.203787  0.228672  0.923652
C12orf71  5.967782e+02       -0.001985  0.030366 -0.505220  0.613404  0.985186
CDKAL1    9.184269e+04        1.911623  0.372572  1.832496  0.066878  0.795535
ATP11A    2.278389e+05        1.397325  0.207535 -1.362350  0.173087  0.898575
COL4A1    3.170280e+06        1.865165  0.068598 -0.027498  0.978063  0.999881

[4991 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 573 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.35 seconds.

Fitting LFCs...
... done in 0.64 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 112 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.42 seconds.

Fitting MAP LFCs...
... done in 1.75 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
ACP2      283121.152373        0.000069  0.001436 -0.442554  0.658088
RBM42     395605.061428        0.000005  0.001464  0.565168  0.571960
FOSB      498117.692558       -0.000105  0.001519  0.596873  0.550592
TPRG1L    404024.063330       -0.000067  0.001467  0.909029  0.363335
LY86       26697.826807       -0.000010  0.001401 -0.814654  0.415271
...                 ...             ...       ...       ...       ...
NHSL1      93307.237715       -0.000024  0.001425 -0.431552  0.666067
TRMT13    109972.574442       -0.000048  0.001419 -0.318183  0.750346
SERPINA9    1949.866913        0.000001  0.001525  0.598590  0.549446
VPS26B    332200.731101        0.000175  0.001532  2.466285  0.013652
TNIP1     889437.537373        0.000048  0.001457  0.412860  0.679709

              padj
ACP2      0.990973
RBM42     0.990973
FOSB      0.990973
TPRG1L    0.970026
LY86      0.970026
...            ...
NHSL1     0.990973
TRMT13    0.990973
SERPINA9  0.990973
VPS26B    0.843353
TNIP1     0.990973

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.98 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.78 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 112 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (120, 112)
Number of True values in replace_mask: 183
replacement_counts_trimmed shape: (93, 112)

... done in 0.05 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.19 seconds.

Log2 fold change & Wald test p-value: condition B vs A
               baseMean  log2FoldChange     lfcSE      stat    pvalue  \
ACP2      283121.152373        1.990235  0.099101 -0.442554  0.658088
RBM42     395605.061428        1.908353  0.107545  0.565168  0.571960
FOSB      498117.692558        1.903000  0.219429  0.596873  0.550592
TPRG1L    404024.063330        2.505314  0.084579  0.909029  0.363335
LY86       26697.826807        0.826261  0.238938 -0.814651  0.415272
...                 ...             ...       ...       ...       ...
NHSL1      93307.237715        1.428319  0.173021 -0.431551  0.666068
TRMT13    109972.574442        1.355428  0.328721 -0.318183  0.750346
SERPINA9    1949.866913        0.000044  0.011023  0.598586  0.549449
VPS26B    332200.731101        2.560150  0.088367  2.466281  0.013652
TNIP1     889437.537373        2.148405  0.084351  0.412860  0.679710

              padj
ACP2      0.990415
RBM42     0.990415
FOSB      0.987399
TPRG1L    0.956359
LY86      0.960043
...            ...
NHSL1     0.990415
TRMT13    0.990415
SERPINA9  0.986951
VPS26B    0.596165
TNIP1     0.990415

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 561 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.81 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.50 seconds.

Fitting LFCs...
... done in 0.62 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 128 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
... done in 1.53 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SLC22A2  3.129296e+02       -0.000039  0.010748 -0.373686  0.708638  0.991311
TENT5B   1.298763e+05        0.000469  0.011881  1.049350  0.294017  0.980450
LCMT1    1.843727e+05       -0.000034  0.011240  0.070697  0.943639  0.997759
ERICH5   4.650447e+03       -0.000097  0.010230 -1.097342  0.272492  0.968426
SNORD89  3.193903e+03       -0.000316  0.011355  0.371987  0.709902  0.991311
...               ...             ...       ...       ...       ...       ...
CNBP     1.754467e+06        0.000560  0.011488  0.363965  0.715884  0.991311
SARS2    5.575508e+04       -0.000070  0.010697 -0.591204  0.554384  0.982466
NUDT21   4.634821e+05        0.000107  0.011648  0.494195  0.621169  0.991311
ARAP2    8.061377e+04       -0.001283  0.011245 -0.347977  0.727858  0.991311
ZNF564   7.617761e+04       -0.000068  0.011112 -0.190413  0.848985  0.997759

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.35 seconds.

Fitting LFCs...
... done in 0.81 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 128 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (120, 128)
Number of True values in replace_mask: 204
replacement_counts_trimmed shape: (93, 128)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))
... done in 1.11 seconds.

Log2 fold change & Wald test p-value: condition B vs A
             baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
SLC22A2  3.129296e+02       -0.000096  0.018747 -0.373679  0.708643  0.987439
TENT5B   1.298763e+05        1.645569  0.254641  1.048092  0.294596  0.951001
LCMT1    1.843727e+05        1.642923  0.136267  0.070697  0.943639  0.996484
ERICH5   4.650447e+03       -0.000128  0.017839 -1.097171  0.272567  0.937430
SNORD89  3.193903e+03        0.000368  0.019695  0.371972  0.709913  0.987439
...               ...             ...       ...       ...       ...       ...
CNBP     1.754467e+06        1.881420  0.097117  0.363965  0.715884  0.987439
SARS2    5.575508e+04        1.237507  0.519621 -0.591204  0.554384  0.973555
NUDT21   4.634821e+05        1.848870  0.223548  0.494195  0.621169  0.985985
ARAP2    8.061377e+04       -0.535601  0.062886 -0.347973  0.727860  0.987439
ZNF564   7.617761e+04        1.483671  0.317134 -0.190413  0.848985  0.996484

[4992 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 573 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4990 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 1.08 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.40 seconds.

Fitting LFCs...
... done in 0.91 seconds.

Calculating cook's distance...
... done in 0.05 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 131 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
/opt/anaconda3/lib/python3.11/site-packages/pydeseq2/utils.py:1088: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset))
... done in 1.54 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
BNIP3P1      7.490605e+04   -4.078983e-04  0.008097 -0.629221  0.529204
TRIL         1.399989e+05    9.648245e-04  0.008439  0.129771  0.896748
SNORD116-21  2.951714e+02    5.228740e-06  0.008256  0.053975  0.956955
KAT2B        1.402343e+05   -4.553459e-05  0.008262  0.239046  0.811070
RRM1         4.126207e+05   -2.953328e-04  0.007929 -1.098205  0.272115
...                   ...             ...       ...       ...       ...
MADD         5.363042e+05   -3.330679e-05  0.009152  1.153743  0.248606
WDR83OS      5.087582e+05    4.836362e-07  0.008637  0.780517  0.435087
GHITM        1.040560e+06    4.717820e-04  0.008400  0.505377  0.613294
CUTC         1.258784e+05    1.411037e-03  0.008603  1.000501  0.317068
PMP2         6.134939e+03    4.012578e-05  0.008269  0.213422  0.830998

                 padj
BNIP3P1      0.990881
TRIL         0.998117
SNORD116-21  0.998117
KAT2B        0.998117
RRM1         0.955019
...               ...
MADD         0.955019
WDR83OS      0.987163
GHITM        0.990881
CUTC         0.972431
PMP2         0.998117

[4990 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.96 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.37 seconds.

Fitting LFCs...
... done in 0.80 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 131 outlier genes.

Fitting dispersions...
... done in 0.06 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (120, 131)
Number of True values in replace_mask: 211
replacement_counts_trimmed shape: (99, 131)

... done in 0.06 seconds.

Fitting LFCs...
... done in 0.06 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.15 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                 baseMean  log2FoldChange     lfcSE      stat    pvalue  \
BNIP3P1      7.490605e+04        1.272956  0.176450 -0.629220  0.529205
TRIL         1.399989e+05        1.455313  0.228071  0.129771  0.896748
SNORD116-21  2.951714e+02        0.000038  0.024280  0.053971  0.956958
KAT2B        1.402343e+05        1.542430  0.136990  0.239046  0.811070
RRM1         4.126207e+05        1.537495  0.154503 -1.098205  0.272115
...                   ...             ...       ...       ...       ...
MADD         5.363042e+05        2.098296  0.241527  1.153743  0.248606
WDR83OS      5.087582e+05        1.898460  0.189485  0.780517  0.435087
GHITM        1.040560e+06        1.850613  0.099342  0.505377  0.613294
CUTC         1.258784e+05        0.156453  0.073238  1.015111  0.310053
PMP2         6.134939e+03        0.000379  0.024142  0.213418  0.831001

                 padj
BNIP3P1      0.981166
TRIL         0.997506
SNORD116-21  0.997506
KAT2B        0.997506
RRM1         0.917884
...               ...
MADD         0.915529
WDR83OS      0.963506
GHITM        0.984735
CUTC         0.941084
PMP2         0.997506

[4990 rows x 6 columns]

R callback write-console: estimating size factors

R callback write-console: estimating dispersions

R callback write-console: gene-wise dispersion estimates

R callback write-console: mean-dispersion relationship

R callback write-console: final dispersion estimates

R callback write-console: fitting model and testing

R callback write-console: -- replacing outliers and refitting for 548 genes
-- DESeq argument 'minReplicatesForReplace' = 7
-- original counts are preserved in counts(dds)

R callback write-console: estimating dispersions

R callback write-console: fitting model and testing

R callback write-console: In aggiunta:
R callback write-console: Messaggio di avvertimento:

R callback write-console: In (function (object, test = c("Wald", "LRT"), fitType = c("parametric",  :
R callback write-console:

R callback write-console:  the design is ~ 1 (just an intercept). is this intended?

[Simulator] Using 4992 genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.41 seconds.

Fitting LFCs...
... done in 0.60 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Replacing 114 outlier genes.

/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
/opt/anaconda3/lib/python3.11/site-packages/anndata/_core/anndata.py:1792: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")
Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...
... done in 0.06 seconds.

Fitting LFCs...
... done in 0.07 seconds.

Running Wald tests...
... done in 0.29 seconds.

Fitting MAP LFCs...
... done in 1.95 seconds.

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
HMMR-AS1     2158.345037    7.568244e-07  0.001482  0.329051  0.742117
ZNRF2P2      3509.094133    2.503943e-07  0.001495  0.888246  0.374409
CCT6B       21917.614866    3.668886e-05  0.001452  0.170868  0.864327
CCDC201       266.154361    7.027726e-07  0.001586  0.580028  0.561896
HDGFL1         67.405046    1.153087e-06  0.001621 -0.410564  0.681392
...                  ...             ...       ...       ...       ...
CCDC162P    20119.137205   -1.696144e-05  0.001448  0.135846  0.891943
LINC00240    7115.401971   -1.633926e-06  0.001353 -0.774219  0.438801
DDX27      343287.251007    1.108268e-05  0.001583  1.220883  0.222130
DEGS1      556872.472264   -6.664890e-04  0.001915 -1.123782  0.261105
RPS3AP37      142.746428    4.839464e-06  0.001492  0.947182  0.343546

               padj
HMMR-AS1   0.995873
ZNRF2P2    0.970407
CCT6B      0.997683
CCDC201    0.982486
HDGFL1     0.988843
...             ...
CCDC162P   0.997683
LINC00240  0.975584
DDX27      0.956723
DEGS1      0.961024
RPS3AP37   0.962808

[4992 rows x 6 columns]

/var/folders/mh/vvy722dj18x7xj41n2qbdzs80000gn/T/ipykernel_3408/637833339.py:81: DeprecationWarning: design_factors are deprecated and will soon be removedPlease consider providing a formulaic formula using the design argument instead
  dds = deconveil_fit(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at deconveil_fit initialization

Fitting dispersions...
... done in 0.95 seconds.

Fitting dispersion trend curve...
... done in 0.08 seconds.

Fitting MAP dispersions...
... done in 1.42 seconds.

Fitting LFCs...
... done in 0.79 seconds.

Calculating cook's distance...
... done in 0.06 seconds.

Replacing 114 outlier genes.

Fitting dispersions...
... done in 0.05 seconds.

Fitting MAP dispersions...

replace_mask before filtering: (120, 114)
Number of True values in replace_mask: 186
replacement_counts_trimmed shape: (95, 114)

... done in 0.05 seconds.

Fitting LFCs...
... done in 0.05 seconds.

Running Wald tests...
... done in 0.30 seconds.

Fitting MAP LFCs...
/Users/katsiarynadavydzenka/Documents/PhD_AI/DeConveil/deconveil/utils_fit.py:422: RuntimeWarning: overflow encountered in exp
  counts - (counts + size) / (1 + size * np.exp(-xbeta - offset - cnv))

Log2 fold change & Wald test p-value: condition B vs A
                baseMean  log2FoldChange     lfcSE      stat    pvalue  \
HMMR-AS1     2158.345037        0.000054  0.011703  0.329049  0.742119
ZNRF2P2      3509.094133        0.000314  0.011803  0.888229  0.374418
CCT6B       21917.614866        0.354819  0.211203  0.170867  0.864328
CCDC201       266.154361        0.000044  0.012526  0.580018  0.561903
HDGFL1         21.300028        0.000260  0.012806 -3.347050  0.000817
...                  ...             ...       ...       ...       ...
CCDC162P    20119.137205        0.000113  0.011412  0.135845  0.891944
LINC00240    7115.401971        0.000058  0.010684 -0.774217  0.438802
DDX27      343287.251007        2.005680  0.249857  1.220883  0.222130
DEGS1      556872.472264        1.621036  0.123905 -1.123782  0.261105
RPS3AP37      142.746428        0.000308  0.011777  0.946636  0.343824

               padj
HMMR-AS1   0.989756
ZNRF2P2    0.953096
CCT6B      0.995050
CCDC201    0.972665
HDGFL1     0.151011
...             ...
CCDC162P   0.995050
LINC00240  0.963562
DDX27      0.925005
DEGS1      0.933146
RPS3AP37   0.941508

[4992 rows x 6 columns]

... done in 1.28 seconds.

In [45]:
all_p.to_csv("sim_results/sim_null/null_pval_all_v3.csv", index=True)